### ISSUE TITLE
Incorrect text position after scale + translate

### ISSUE THREAD

**Issue by dscheg** [RazrFalcon/resvg#102]
Using the latest rendersvg tool

```svg
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <!--text id="text1" transform="translate(100, 200)">Test</text-->
    <text id="text2" transform="scale(2) translate(0, 100)">Test</text>
</svg>
```

**Expected:** allmost all text is visible at the bottom of the image
**Result:** text partially out of the bottom line

Uncommenting the first line fixes the problem for some reason

**Comment by RazrFalcon** [comment]
Transform sets a text baseline. So it renders correctly. Can you provide an image of what result do you expect?

**Comment by dscheg** [comment]
Expected:
![image](https://user-images.githubusercontent.com/1962268/50605381-fdcdd180-0ee3-11e9-8498-dd01e88d9bd4.png)

Got:
![image](https://user-images.githubusercontent.com/1962268/50605347-e68ee400-0ee3-11e9-8658-b3849bb94155.png)

After uncommenting:
![image](https://user-images.githubusercontent.com/1962268/50605326-d70f9b00-0ee3-11e9-8681-db11bdf431d2.png)

**Comment by RazrFalcon** [comment]
>the latest rendersvg tool

v0.4.0 or git master?

What backend and OS do you use?

Do you have Times New Roman font installed?

**Comment by dscheg** [comment]
git master
cargo +stable-x86_64-pc-windows-gnu run --release --features="cairo-backend"
Times New Roman font installed

**Comment by RazrFalcon** [comment]
It's ok on linux with cairo. Will test on windows.

**Comment by RazrFalcon** [comment]
Can confirm. `pango` returns an invalid font ascent. Not sure if it's a `resvg` bug.
