### ISSUE TITLE
Build the KDE thumbnailer without installing the resvg lib first

### ISSUE THREAD

**Issue by flying-sheep** [RazrFalcon/resvg#111]
The following line is commented out. I can neither figure out how to make this work:

https://github.com/RazrFalcon/resvg/blob/8245a683cd2fb3229556571c720dc63b047a263b/tools/kde-dolphin-thumbnailer/CMakeLists.txt#L24

**Comment by RazrFalcon** [comment]
The problem is that I can't build a plugin with a statically linked `resvg`. Not sure why. Have to investigate this. That's why it's commented out.

By default, cmake will take `resvg` from `/usr/lib`.

**Comment by flying-sheep** [comment]
… and using `-DCMAKE_CXX_FLAGS="-L../../../target/release"`, also the not-yet-installed version, which is enough for me.
