### ISSUE TITLE
usvg supported features

### ISSUE THREAD

**Issue by JanWerder** [RazrFalcon/resvg#115]
As a new user, it's not clear to me, what elements usvg simplifies.
Maybe you could add a list to the readme?

**Comment by RazrFalcon** [comment]
Almost all of them. I'm planning to add a list of such features.

**Comment by RazrFalcon** [comment]
This hard to enumerate. Basically, usvg creates a brand new SVG tree. There are literary no elements and/or attributes that will be preserved.
