### ISSUE TITLE
Arabic text does not align right correctly

### ISSUE THREAD

**Issue by jonoomph** [RazrFalcon/resvg#116]
When rendering Arabic text (aligned to the right), each row of text is not aligned. Each row is offset.
[ArabicExample.zip](https://github.com/RazrFalcon/resvg/files/2862998/ArabicExample.zip)

Attached is an Arabic SVG file which demonstrates the issue, and a test render made with resvg. It's also possible I'm just doing something wrong, so I apologize if that is the case.

This was rendered with the Qt back-end, on Ubuntu 16.04, and uses a version of resvg compiled from source. Please let me know if I can provide any more details.

**Comment by jonoomph** [comment]
I also tried multiple fonts, and all misaligned with Arabic.

**Comment by jonoomph** [comment]
On second glance, this might also be related to a filter on the text elements, which appear to affect the bounding box around the text. Just a guess.

**Comment by RazrFalcon** [comment]
It works fine on my machine. (c)

I have Qt 5.11.3. I will try to reproduce it on Ubuntu. It might me Qt/fontconfig/freetype bug.

**Comment by RazrFalcon** [comment]
Was able to reproduce on Ubuntu 16.04.

By the way, 16.04 has Qt 5.5.1 and resvg [only support Qt >= 5.6](https://github.com/RazrFalcon/resvg/blob/master/BUILD.adoc#dependencies).

**Comment by RazrFalcon** [comment]
As expected, `QFontMetrics::width()` returns different numbers. Not sure why, but this is the source of the bug.

**Comment by RazrFalcon** [comment]
The `cairo` backend works, so it's Qt/Qt-backend bug.

**Comment by RazrFalcon** [comment]
I've build Qt 5.6.3 on Ubuntu 16.04 and it fixed rendering. So it's a Qt bug and I'm closing this as out of scope.

**Comment by RazrFalcon** [comment]
By the way, there is also a BIDI reordering bug ([QTBUG-72890](https://bugreports.qt.io/browse/QTBUG-72890)) in Qt, which will affect an Arabic text rendering too. It can't be fixed on the `resvg` side, but the next release will feature it's own text rendering engine, so it will be fixed semiautomatically.

**Comment by jonoomph** [comment]
Thanks for looking into this! I'll try rebuilding with a more recent build of Qt.
