### ISSUE TITLE
Smooth gradients / Dithering

### ISSUE THREAD

**Issue by thorwil** [RazrFalcon/resvg#118]
Rendering of gradients, especially over narrow ranges, exhibits banding. Chromium shows that dithering helps.  Please implement dithering and/or export to real 16 bit per channel.

[gradient_test_01.svg.zip](https://github.com/RazrFalcon/resvg/files/2890898/gradient_test_01.svg.zip)

rendersvg:
![gradient_test_01_resvg](https://user-images.githubusercontent.com/583291/53196619-c7295300-3618-11e9-9901-68b1319afc19.png)

Chromium (you may have to use "View Image" to get to see the real deal):
![gradient_test_01_chromium](https://user-images.githubusercontent.com/583291/53196627-cabcda00-3618-11e9-8a16-b1d0a5dca45b.png)

**Comment by RazrFalcon** [comment]
This is out of scope, since `resvg` uses cairo/Qt.

**Comment by thorwil** [comment]
Is Cairo limited to 8bit and no dithering?

**Comment by RazrFalcon** [comment]
Yes. As well as Qt.

**Comment by msand** [comment]
How about future backends? Like pure rust based ones, they won't necessarily have that restriction no?

**Comment by RazrFalcon** [comment]
@msand Yes, this is not an `resvg` restriction. So it can be "fixed" by a new backend. By there none rust-one at the moment.
