### ISSUE TITLE
dominant-baseline support

### ISSUE THREAD

**Issue by davyzhang** [RazrFalcon/resvg#119]
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline

**Comment by RazrFalcon** [comment]
Yes, this is planned. 

https://github.com/RazrFalcon/resvg/blob/master/docs/unsupported.md

**Comment by tiby312** [comment]
would love this! I use dominant-baseline support to center labels in graph/plotting related svg files. as a workaround I think people could use the dx and dy css position attributes to manually offset text vertically.

**Comment by tiby312** [comment]
@RazrFalcon I tried this out and it works great! I noticed that when used as an attribute it works, but doesn't appear to work through css style. Is that expected?

**Comment by RazrFalcon** [comment]
Yes, my bad. Will fix.

**Comment by RazrFalcon** [comment]
Fixed.

**Comment by tiby312** [comment]
Works!
