### ISSUE TITLE
A better CSS support

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#120]
The current CSS support is horrible and we should find a way to integrate [selectors](https://crates.io/crates/selectors) into the [svgdom](https://github.com/RazrFalcon/svgdom).

**Comment by dirkschulze** [comment]
@RazrFalcon Would you consider supporting CSS Variables as well? Or is the subset fixed to SVG 1.1?

**Comment by RazrFalcon** [comment]
For now, I want to support at least a decent CSS 2.

The current problem is the parser and selector itself. The only option for now is [cssparser](https://crates.io/crates/cssparser)+[selectors](https://crates.io/crates/selectors), but they are too bloated. And sort of low-level (CSS variables should be resolved manually). So I plan to write my own CSS resolver in the future.

**Comment by RazrFalcon** [comment]
A decent CSS 2 support (not complete) was added via an updated `simplecss` crate.
