### ISSUE TITLE
some rendering bugs

### ISSUE THREAD

**Issue by leeoniya** [RazrFalcon/resvg#124]
hey @RazrFalcon 

just tried `resvg-explorer-extension.exe` and it works pretty well. i'm attaching some svgs that it doesnt render properly.

i'm not sure how much of this has to do with lack of css support, but some bugs (like positioning issues) look legit.

also, huge thanks for svgcleaner and resvg!

[bad-render-resvg.zip](https://github.com/RazrFalcon/resvg/files/2973393/bad-render-resvg.zip)

**Comment by RazrFalcon** [comment]
That's was a stupid mistake. Thanks. 

I will publish a new release soon.

Fixed by https://github.com/RazrFalcon/resvg/commit/cd7f66bcb3d3ac7078adc0bec8c63c0ca15839cc

**Comment by leeoniya** [comment]
sweet, thanks!
