### ISSUE TITLE
rsvg-convert like tool

### ISSUE THREAD

**Issue by Rush** [RazrFalcon/resvg#127]
Hey y'all,
Great library! Is there a command line tool similar to `rsvg-convert` which could be used to?
a) Convert an SVG file to a PNG at a given DPI
b) Convert an SVG file to an SVG file with text converted to paths
c) Convert an SVG file to a PDF file

If yes .. please do let me know
If no ... do you think the current version of resvg would support these use cases? I would love to try playing with the code and find out. Wanted to ask first though!

**Comment by Rush** [comment]
I will reply to myself: It seems like `rendersvg` supports rendering to PNG files. 

`target/release/rendersvg --dpi 300 input.svg out.png`

**Comment by RazrFalcon** [comment]
Yes, `rendersvg` is `rsvg-convert` alternative.

**Comment by Rush** [comment]
@RazrFalcon it seems to be missing functionality to convert to PDF and to SVG (with text to path conversion). Would it be something that you would like to see in a PR?

**Comment by RazrFalcon** [comment]
Conversion to a simplified SVG with text converted to paths will be available via `usvg` in the future.

PDF is not planned, but there is [an issue](https://github.com/RazrFalcon/resvg/issues/65) to support it.

**Comment by Rush** [comment]
rendersvg could support it through Cairo / Qt.

**Comment by RazrFalcon** [comment]
It will not work, mainly because `resvg` uses it's own layers. It should be done by manually written PDF backend.

**Comment by Rush** [comment]
I know you mentioned it wouldn't work .... but it's working https://github.com/RazrFalcon/resvg/pull/128 ... mostly
