### ISSUE TITLE
How do I get output image as a Vec?

### ISSUE THREAD

**Issue by SnejUgal** [RazrFalcon/resvg#133]
I need to render an SVG on my server and send it in response to users. I would like to avoid saving the image to the drive, however, i can only find `OutputImage::save` which saves the image to the drive and no method like `to_vec`. How do I get the render result as a `Vec`?

**Comment by RazrFalcon** [comment]
Hi. It can't be done via the `Render` trait right now, but you can use backend-specific methods, e.g. `render_to_image`.

Something like:

```rust
resvg::backend_qt::render_to_image(...).unwrap().data() // &[u8]

// or

resvg::backend_cairo::render_to_image(...).unwrap().get_data().unwrap() // &[u8]
```

PS: docs.rs doesn't show up docs for optional features. I should fix this.

**Comment by SnejUgal** [comment]
This worked, thanks

Should I leave the issue open until this can be done via the `Render` trait?

**Comment by RazrFalcon** [comment]
Yes, keep it open.

**Comment by RazrFalcon** [comment]
Turns out that it's pretty hard to implement, due to lifetimes. So a backend-specific `render_to_image` should be used in this case.

**Comment by GarkGarcia** [comment]
Thanks for the help! This should be mentioned in the documentation.
