### ISSUE TITLE
Implement a raqote backend

### ISSUE THREAD

**Issue by jrmuizel** [RazrFalcon/resvg#134]
@RazrFalcon have you started on this?

**Comment by RazrFalcon** [comment]
Yeap. Nothing to show yet, since I waiting for https://github.com/jrmuizel/raqote/issues/14

I will try the latest version now.

**Comment by jrmuizel** [comment]
Great. I'm looking forward to doing some performance and correctness work on raqote and having the ability to get real content will help with that a lot.
