### ISSUE TITLE
Precompiled, Static CLI Apps for All Supported Platforms

### ISSUE THREAD

**Issue by chgibb** [RazrFalcon/resvg#139]

**Comment by RazrFalcon** [comment]
It's not possible, because `resvg` depends on external libraries (cairo, Qt, harfbuzz) and building those statically is a nightmare.

Also, there are way to many combinations only on Windows: msvc/mingw * 32/64 * cairo/qt.

It will be possible, as soon as all dependencies became Rust-only

**Comment by condemil** [comment]
Is it still not possible for linux?

**Comment by RazrFalcon** [comment]
Nope. Too much work.
