### ISSUE TITLE
BBox for the whole svg image in the c-api

### ISSUE THREAD

**Issue by moazin** [RazrFalcon/resvg#140]
Currently the *capi* has the function `resvg_get_node_bbox` which can be used to get the bounding box for any particular node. Is there a way to get the bounding box for the whole SVG image? I couldn't find any.

**Comment by RazrFalcon** [comment]
`resvg_get_image_size`?

**Comment by moazin** [comment]
Oh I tried it but it doesn't return a tight bounding box. I am looking for something that can return a tight bounding box (with x, y, width and height) of the whole SVG document, similar to how the `resvg_get_node_bbox` does for a particular node.

**Comment by RazrFalcon** [comment]
You can do this via `resvg_get_node_bbox`, if you know the `svg` node ID. Otherwise - you can't.

Why do you need this?

**Comment by moazin** [comment]
I need it for rendering SVG glyphs (supported in OpenType fonts). I want to have an SVG rendered in the tightest box possible with a knowledge of which row of pixels (in the rendered image) correspond to `y = 0` of the SVG coordinate system.

**Comment by RazrFalcon** [comment]
You can do this in Rust, but not via C-API. I will add this feature tomorrow.

**Comment by moazin** [comment]
Thank you. One way to do this could to be to modify `resvg_get_node_bbox` so that if `id` is null it returns the `bbox` of the whole SVG image. Anyways, please do it in the way that suits the library the best. :)

**Comment by moazin** [comment]
You said that `resvg_get_node_bbox` can do it if I know the SVG node's ID. I am using `resvg` version `0.6.1` and in it the function `resvg_cairo_get_node_bbox` returns a warning `No node with 'glyph179' ID is in the tree`. In the svg document that I tried the `svg` node (the root node) clearly has an ID `glyph179`.  Is this how it is supposed to behave? I had to use the last tagged version because the current master doesn't compile.

**Comment by RazrFalcon** [comment]
You right. The `svg` node id isn't preserved. My bad. `resvg_get_node_bbox` works only on `g`, `path` and `image`. I should clarify that.

>I had to use the last tagged version because the current master doesn't compile.

Can you elaborate on that?

**Comment by moazin** [comment]
Sure. I just did a `git clone` of the repo, and ran, `cargo build --features="cairo-backend"`. It gives the attached output which has errors. 
[out.txt](https://github.com/RazrFalcon/resvg/files/3285179/out.txt)

However, doing a `git checkout v0.6.1` and then building it worked just fine. That's what I meant by, `I had to use the last tagged version`.

**Comment by RazrFalcon** [comment]
You should use latest stable rust, aka 1.35. Older versions are unsupported.
