### ISSUE TITLE
Compile for Qt for Android

### ISSUE THREAD

**Issue by FalsinSoft** [RazrFalcon/resvg#151]
Hi
Is possible to compile the library for Qt but working on Android platform? Basically it mean to compile library for Qt but using the Android NDK arm7a and armv8 compilers...
Thank you

**Comment by RazrFalcon** [comment]
Probably, but you have to modify a `resvg-qt` [build script](https://github.com/RazrFalcon/resvg/blob/master/resvg-qt/build.rs) first. And probably harfbuzz [build script ](https://github.com/servo/rust-harfbuzz/blob/master/harfbuzz-sys/build.rs) too. Other than that there should be no platform specific problems.

But again, I never tried to do this and I have no plans to support android/ios.
