### ISSUE TITLE
Conflicting versions of "cairo-sys-rs" with gtk 0.7.0

### ISSUE THREAD

**Issue by CodingJonas** [RazrFalcon/resvg#152]
I try to run the example code [cairo-rs](https://github.com/RazrFalcon/resvg/tree/master/examples/cairo-rs) with the current versions of `resvg` and `gtk/gio`.

These are the dependencies in my `Cargo.toml`:

```
[dependencies]
gtk = "0.7.0"
gio = "0.7.0"
resvg = { version = "0.7.0", features = ["cairo-backend"] }
```

Building the example results in the following error:

```
error: failed to select a version for `cairo-sys-rs`.
    ... required by package `cairo-rs v0.6.0`
    ... which is depended on by `resvg v0.7.0`
    ... which is depended on by `test_svg v0.1.0 (/home/jonas/rust/test_svg)`
versions that meet the requirements `^0.8.0` are: 0.8.0

the package `cairo-sys-rs` links to the native library `cairo`, but it conflicts with a previous package which links to `cairo` as well:
package `cairo-sys-rs v0.9.0`
    ... which is depended on by `cairo-rs v0.7.0`
    ... which is depended on by `gdk v0.11.0`
    ... which is depended on by `gtk v0.7.0`
    ... which is depended on by `test_svg v0.1.0 (/home/jonas/rust/test_svg)`

failed to select a version for `cairo-sys-rs` which could resolve this conflict
```

Specifying `cario-sys-rs` to version 0.8.0 or 0.9.0 does not solve the issue.

Going back to `gtk/gio` versions 0.6.0 solves the problem, but I need the current versions for my project.
I use rustc version 1.35.0.

**Comment by RazrFalcon** [comment]
This is because resvg uses cairo-rs 0.6.0. resvg 0.7 was released before gtk-rs latest update.

I will bump cairo-rs in the master.

**Comment by RazrFalcon** [comment]
Waiting for https://github.com/gtk-rs/cairo/issues/272
