### ISSUE TITLE
Qt Image Render Aliasing / Offset

### ISSUE THREAD

**Issue by jonoomph** [RazrFalcon/resvg#153]
When rendering using Qt5, I noticed that Resvg seems to be adding an aliased border to the sides of SVG renders. I am attaching a screenshot of an example SVG file, rendered in both Inkscape and Resvg.

![Render-Aliasing1](https://user-images.githubusercontent.com/5551883/60909981-36f54e80-a245-11e9-9de3-a36e87281148.png)

Here is the SVG file I used (zipped for GitHub):
[drawing-2.svg.zip](https://github.com/RazrFalcon/resvg/files/3374146/drawing-2.svg.zip)

In OpenShot, the effect of this rendering artifact is quite noticeable, causing transparent borders around some of our masks and transitions. Here is a snippet of the code we are using to render to a QImage:

```
			ResvgRenderer renderer(QString::fromStdString(path));
			if (renderer.isValid()) {
				cached_image = std::shared_ptr<QImage>(new QImage(QSize(renderer.defaultSize().width(), renderer.defaultSize().height()), QImage::Format_RGBA8888));
				cached_image->fill(Qt::transparent);

				QPainter p(cached_image.get());
				renderer.render(&p);
				p.end();
                                ....
```

@RazrFalcon I would love to hear your thoughts on this.

**Comment by jonoomph** [comment]
Also, there are times where the border is on top and bottom also, but in the current example, the 1-pixel border is on the left and right side.

**Comment by RazrFalcon** [comment]
This is an expected backend-specific behavior:

| Qt | cairo | raqote | 
---|---|---
| ![qt](https://user-images.githubusercontent.com/725494/60916924-5d90a500-a298-11e9-9af1-5c762ff0ff3a.png) | ![cairo](https://user-images.githubusercontent.com/725494/60916930-608b9580-a298-11e9-86c8-4657527feeb1.png) | ![raqote](https://user-images.githubusercontent.com/725494/60916935-63868600-a298-11e9-91c7-ec8f70c2964f.png) |

Antialiasing is implemented differently in different applications. Usually, when I'm writing some Qt code, I'm using the +0.5 trick to make QPainter's antialiasing a bit better/sharper.

I'm not sure what can be done in this case. There are no Qt-specific "offsets" in the `resvg`.

I suggest using integer numbers. The provided SVG has floating: 622.85711, 82.85714, etc. This will fix your problem.

**Comment by leeoniya** [comment]
somewhat unrelated, but raqote's anti-aliasing looks noticeably worse, especially at the horizontal and vertical edge junctions. on the other hand, cairo and QT unnecessarily anti-alias/blend the left vertical edge. cc @jrmuizel

**Comment by jonoomph** [comment]
Thanks for the info! Let me try integers and see how that works.

**Comment by RazrFalcon** [comment]
Here is the results with integer numbers:

| Qt | cairo | raqote | 
---|---|---
| ![qt](https://user-images.githubusercontent.com/725494/60918440-ff65c100-a29b-11e9-8742-107da762aa92.png) | ![cairo](https://user-images.githubusercontent.com/725494/60918570-5370a580-a29c-11e9-9e0e-fd984ff27f49.png) | ![raqote](https://user-images.githubusercontent.com/725494/60918455-07256580-a29c-11e9-8c0e-c4f6826f0c02.png) |

**Comment by RazrFalcon** [comment]
And with a half-pixel offset:

| Qt | cairo | raqote | 
---|---|---
| ![qt](https://user-images.githubusercontent.com/725494/60918743-b5310f80-a29c-11e9-9864-d235ce3e1b15.png) | ![cairo](https://user-images.githubusercontent.com/725494/60918751-b8c49680-a29c-11e9-9bc1-eb9795db5669.png) | ![raqote](https://user-images.githubusercontent.com/725494/60918756-bb26f080-a29c-11e9-9ce9-b9509fa6dc26.png) |

So it all boils down to a specific fractional offset, that is't handled that good by a specific backend.

**Comment by jrmuizel** [comment]
raqote just uses 4x4 supersampling for it's antialaising. This quite a bit worse than what Cairo does, but is what Skia used for a long time before they switched to sometimes using analytic-aa. I'm not sure what Qt does.

**Comment by RazrFalcon** [comment]
Closing it, since it's not a resvg bug.
