### ISSUE TITLE
Compile for Qt using MinGW

### ISSUE THREAD

**Issue by omortie** [RazrFalcon/resvg#169]
I tried to compile and follow build instructions of resvg but I get the error when using cargo:

`error: linker link.exe not found | = note: The system cannot find the file specified. (os error 2)
note: the msvc targets depend on the msvc linker but `link.exe` was not found
note: please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option
error: aborting due to previous error`

using MinGW 73 64 bit with Qt5.12.1 on Windows 10

**Comment by RazrFalcon** [comment]
Can you list the commands that you used?

**Comment by omortie** [comment]
yes of course
`set PATH=C:\Qt\Qt5.12.1\5.12.1\mingw73_64\bin;C:\Qt\Qt5.12.1\Tools\mingw730_64\bin;%PATH%
set QT_DIR=C:\Qt\Qt5.12.1\5.12.1\mingw73_64
cargo.exe build --release --features "qt-backend"`

by the way my cargo is in the PATH no need to set it twice

**Comment by RazrFalcon** [comment]
Maybe you should enable the GNU toolchain first `rustup default stable-x86_64-pc-windows-gnu`?

>by the way my cargo is in the PATH no need to set it twice

The `PATH` modification is optional, so this is mentioned just in case.

**Comment by omortie** [comment]
ok it worked, thanks :)
