### ISSUE TITLE
How to decide between the supported backends ?

### ISSUE THREAD

**Issue by ngirard** [RazrFalcon/resvg#172]
I'm involved in the [IconPie](https://github.com/GarkGarcia/icon-pie) project, which aims at providing designers a state-of-the art command-line tool for generating icons and icon sets.

We are in the process of integrating `resvg` to IconPie.

We'd like to know: dependencies aside, how can we make a decision between `resvg`'s supported backends, and on which criteria ? Is there an obvious choice for our project ?

Thanks in advance !

**Comment by RazrFalcon** [comment]
All backends will produce the same results. In case of a Rust project you should prefer `raqote` backend, but it's the slowest one at the moment (technically depends on what you need).

The separation exist for an ability to use a native canvas when needed. For example, you can draw on a QWidget directly, without creating a raster image. As long as you don't need this, you can use whatever backend you want.

Sadly, all backends require `harfbuzz`, so you still have to have a C++ compiler and CMake to actually build it. Unless you don't need text rendering at all (which is not optional right now).

**Comment by ngirard** [comment]
@RazrFalcon, thanks for your quick and thorough answer.

You may want this to your own documentation, but as far as we are concerned, you can close this issue.

Cheers!

**Comment by RazrFalcon** [comment]
Glad to help.
