### ISSUE TITLE
When does resvg::backend_raqote::render_to_image fails?

### ISSUE THREAD

**Issue by GarkGarcia** [RazrFalcon/resvg#175]
I'd like to know when does `resvg::backend_raqote::render_to_image` returns `None`. As specified in the docs:

> [`resvg::Render::render_image`] Returns `None` if an image allocation failed.

However, browsing through your code, it looks like `resvg::backend_raqote::render_to_image`  only returns `None` when there's a problem with the svg input, for example, a _"0 0 0 0"_ `viewBox`. Is that so?

Can I assume it's going to return `Some(_)` if the svg data is validated previously?

**Comment by RazrFalcon** [comment]
Yes, `raqote` doesn't support failable allocations, but other backend do. 

>a "0 0 0 0" viewBox

Then `Tree::from_str` will return an error. 

`render_image` returns `None` only when it failed to allocate the root canvas. So in case of `raqote` it would never happen.

**Comment by GarkGarcia** [comment]
Great! Thanks for the help!
