### ISSUE TITLE
Rendering behavior when rendering a specific element

### ISSUE THREAD

**Issue by moazin** [RazrFalcon/resvg#182]
While using `resvg` to support OT-SVG in FreeType, I noticed a behavior that's unique to `resvg`. When rendering by id, `resvg` computes a bounding box and automatically renders the content tightly (with no redundant empty space on any side). Other libraries such as `librsvg` don't behave this way. They render whatever is in the `viewBox` as it is. For use in FreeType, I prefer the latter behavior. 
For example, rendering the following SVG image by using `resvg_cairo_render_to_canvas_by_id` gives [output-i-get](https://user-images.githubusercontent.com/23481137/66270444-4187aa00-e86d-11e9-8cac-0c5c2da6b854.png) while I actually want [expected-output](https://user-images.githubusercontent.com/23481137/66270443-3fbde680-e86d-11e9-9b03-ff09f5c578a4.png).
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 -1000 1000 1000">
  <g id="glyph1">
    <rect width="300" height="400" x="20" y="-500" fill="blue" />
  </g>
</svg>
```
I am not sure if the SVG specs say anything about which behavior is the correct one. Is there any way I can achieve the behavior I want? Can anything be done in regards to this?

**Comment by RazrFalcon** [comment]
>Other libraries such as librsvg don't behave this way.

It does. At least in the cli version. Same goes for Inkscape.

>I am not sure if the SVG specs say anything about which behavior is the correct one.

I don't think that this is defined.

Just to be clear: you want to keep the original canvas size, but render only the specified element(s) on it?

**Comment by moazin** [comment]
> It does. At least in the cli version. Same goes for Inkscape.
Yes, that's true. `rsvg-convert` has this behavior. But the function `rsvg_handle_render_cairo_sub` doesn't do this. 
> Just to be clear: you want to keep the original canvas size, but render only the specified element(s) on it?
Yes. Not only the size, but also the x and y shifts. So if the viewbox is "0 -1000 500 500" I would want the rectangle (0, -1000) to (500, -500) rendered. (Of course only stuff that matches the `ID`).

**Comment by RazrFalcon** [comment]
resvg doesn't have such method out of the box right now. You can create an empty canvas first (using `resvg_get_image_size`, `resvg_get_image_viewbox`, `resvg_get_image_bbox`), then move to the required position (using `resvg_get_node_bbox`) and then render a required element via `resvg_*_render_to_canvas_by_id` as usual.

I'm not sure that we need a dedicated method such edge case.

**Comment by moazin** [comment]
Hmm all right. Another thing that concerns me is, for use in FreeType, we need to know exactly which size attributes (`width`, `height`, `viewBox`) are present and their respective values. The current functions `resvg_get_image_viewbox` and `resvg_get_image_size` do give the sizes but no information about which attribute was used. For example, `resvg_get_image_viewbox` will return "0 0 width height" even if no viewBox was present. I essentially want a function that can give these attributes along with the information of which attributes were present and which were not. Something analogous to librsvg's `rsvg_handle_get_intrinsic_dimensions`. Do you think something like this would be a good addition to resvg's API?

**Comment by RazrFalcon** [comment]
Why do you need those attributes? They were already processed by the resvg. You don't need them anymore.

`resvg` doesn't preserve any data from the original SVG except id's.

**Comment by moazin** [comment]
To render OT-SVG glyphs, we need to know those attributes to get the size of the EM square. Then, we perform a scale transform depending on the output size that we need. There can also be a case where both `width/height` and `viewBox` have been specified and that needs to be properly handled too. Thus, we need these attributes. 

> `resvg` doesn't preserve any data from the original SVG except id's.

Hmm, I see. Well, then given the way `resvg` works, maybe such an addition won't suit `resvg`.

**Comment by RazrFalcon** [comment]
It looks like you're trying to implement something that resvg already does.

`resvg_get_image_size` doesn't return the width/height attributes values. It returns a resolved SVG canvas size ([src](https://github.com/RazrFalcon/resvg/blob/46961d20d39e64991c645924b971abcbf37374e4/usvg/src/convert/mod.rs#L104)).

If you want to fit an SVG into a specific canvas than you should use `resvg_options::fit_to`. If this is not something that you want than it will be easier for me if you explain what you want step by step.

**Comment by moazin** [comment]
It will take me some time to think about this. Maybe there's a way to get what I want with the current API. If not, I'll come back with an step by step explanation of what I really want. Feel free to close the issue for now. :+1:

**Comment by RazrFalcon** [comment]
Feel free to reopen it later.
