### ISSUE TITLE
Visibility should be inherited

### ISSUE THREAD

**Issue by harmic** [RazrFalcon/resvg#183]
Consider this svg:

```
<?xml version="1.0" standalone="no"?>
<svg height="200" width="300" xmlns="http://www.w3.org/2000/svg" version="1.1">

	<g transform="translate(50,50)" visibility="hidden">
		<g>
			<line x1="0" y1="-25" x2="0" y2="+25" style="stroke:black; stroke-width:1; stroke-opacity: 0.3"/>
			<line x1="-25" y1="0" x2="+25" y2="0" style="stroke:black; stroke-width:1; stroke-opacity: 0.3"/>
			<text x="0" y="0">Not Visible</text>
		</g>
	</g>

	<g transform="translate(150,50)" visibility="hidden">
		<line x1="0" y1="-25" x2="0" y2="+25" style="stroke:black; stroke-width:1; stroke-opacity: 0.3"/>
		<line x1="-25" y1="0" x2="+25" y2="0" style="stroke:black; stroke-width:1; stroke-opacity: 0.3"/>
		<text x="0" y="0">Not Visible</text>
	</g>

	<g transform="translate(250,50)">
		<g>
			<line x1="0" y1="-25" x2="0" y2="+25" style="stroke:black; stroke-width:1; stroke-opacity: 0.3"/>
			<line x1="-25" y1="0" x2="+25" y2="0" style="stroke:black; stroke-width:1; stroke-opacity: 0.3"/>
			<text x="0" y="0">Visible</text>
		</g>
	</g>

</svg>

```

When rendered with rendersvg, the first and third groups are visible. When rendered with other renderers (I have tried batik, Chrome, Firefox and Edge) only the third group is visible.

In the case of the first group, the 'visibility' attribute is on the grandparent of the paths & text. It seems that resvg does not allow it to inherit.

According to [SVG 1.1](https://www.w3.org/TR/SVG11/painting.html#VisibilityProperty), visibility should be an inheritable presentation attribute.

**Comment by RazrFalcon** [comment]
`visibility` is a tricky one. This is probably an SVG spec bug.

According to [11.5 Controlling visibility](https://www.w3.org/TR/SVG11/painting.html#VisibilityControl)

>Setting ‘visibility’ to hidden on a ‘g’ will make its children invisible as long as the children do not specify their own ‘visibility’ properties as visible. Note that ‘visibility’ **is not an inheritable property**.

And in the [CSS2 spec](https://www.w3.org/TR/2008/REC-CSS2-20080411/visufx.html#propdef-visibility) that SVG follows, it's not inheritable too.

This is defensively a bug, but we should use a different fix.

**Comment by harmic** [comment]
Hmm. You are correct, the SVG spec is inconsistent with itself. Later in that same section (11.5) it has:

> 'visibility'
> ...
> Inherited: yes

In regards to conflict with the CSS2 spec, a few lines below that it says:

> Except for any additional information provided in this specification, the normative definition of the ‘visibility’ property is the CSS2 definition ([CSS2], section 11.2)

Also, in [CSS 2.1](https://www.w3.org/TR/CSS2/visufx.html#propdef-visibility), visibility is listed as inherited, and in the equivalent section of [SVG2](https://www.w3.org/TR/SVG2/render.html#VisibilityControl) it also says visibility is inherited.

I know you are not aiming for SVG2 compliance - I'm only bringing that up to get a feel for which direction the standards are headed, to better understand how to handle the inconsistency in the SVG1.1 standard. I would be more inclined to think that the intent was to have visibility inherited.

Either way I am not that sure about what the practical difference between treating it as inherited vs. the description in the sentence you've quoted.

**Comment by RazrFalcon** [comment]
I'm not sure how it should be handled myself. We probably should follow other implementations.
And it looks like they changed it to inheritable after CSS 2.1

https://www.w3.org/TR/2011/REC-CSS2-20110607/changes.html#q21.89

**Comment by RazrFalcon** [comment]
Thanks for a bug report. Such small details is what makes SVG development so complicated.
