### ISSUE TITLE
Unable to render specific <use> element

### ISSUE THREAD

**Issue by jnsh** [RazrFalcon/resvg#187]
Hello

I'm having trouble rendering specific `<use>` elements in [this SVG file](https://github.com/jnsh/arc-theme/blob/master/common/xfwm4/light/assets.svg) with the `--export-id` option.

For example, there's a rectangle that has an id `menu-active`, and it is duplicated to an `<use>` element with `menu-inactive` id:
```
<rect
   style="opacity:1;fill:#e7e8eb;fill-opacity:1;stroke:none;stroke-width:1;stroke-linecap:butt;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1"
   id="menu-active"
   width="26"
   height="16"
   x="5"
   y="662.36218"
   inkscape:label="#rect4138-3" />

<use
   x="0"
   y="0"
   xlink:href="#menu-active"
   id="menu-inactive"
   transform="translate(62,-2.2617187e-5)"
   width="100%"
   height="100%"
   inkscape:label="#use5268" />
```

Trying to render the `menu-inactive` object fails with the following error:
```
$ /usr/bin/rendersvg --export-id "menu-inactive" "assets.svg" "test.png"
Error: SVG doesn't have 'menu-inactive' ID.
```

Rendering the `menu-active` object works, and the full SVG image renders correctly as well. Also, rendering the `menu-inactive` object by id works fine using inkscape, so I don't think there should be anything wrong with the SVG file.

**Comment by RazrFalcon** [comment]
Thanks. That was an interesting bug.
