### ISSUE TITLE
String / u8[] input and output

### ISSUE THREAD

**Issue by avwie** [RazrFalcon/resvg#189]
I am trying to make a web-service which renders rasterizes SVG to PNG and resvg looks promising. However, the API only provides `from_file` and `to_file`. This makes it difficult to include into a webservice.

Doesn't it make more sense to abstract it a bit to have a `from_bytes` / `from_str` and `to_bytes` / `to_str` and have the file API use that?

**Comment by RazrFalcon** [comment]
`resvg` supports `Tree::from_data`, `Tree::from_str` and `Tree::from_file`.

As for `to_bytes`, it was already discussed in #133. The only way to implement `to_vec` is via copying, which is unfortunate.

**Comment by avwie** [comment]
Ah thanks. I see now indeed

**Comment by RazrFalcon** [comment]
I will add `to_vec` later.
