### ISSUE TITLE
Canvas rendering issues under transform

### ISSUE THREAD

**Issue by therealbnut** [RazrFalcon/resvg#190]
Hey, I'm getting a rendering issue with Canvas rendering using Skia. I think it affects multiple backends though, not just Skia. The issue seems to be when a transform matrix is applied to the canvas.

https://github.com/RazrFalcon/resvg/blob/2e56929886736c0692a50b2163097f1a6c14b52f/src/backend_skia/mod.rs#L137-L139

I believe on these lines of code we need to take the matrix into account for `img_size`, although I'm not familiar enough with how these parameters are meant to work, or how the backend is implemented to diagnose and fix it myself.

This example has a scale applied.

| Output | Expected |
| - | - |
| <img width="393" alt="Screen Shot 2019-12-02 at 5 55 32 pm" src="https://user-images.githubusercontent.com/635596/69936802-f6b4a680-152c-11ea-8742-69331e914c8d.png"> | <img width="400" alt="Screen Shot 2019-12-02 at 5 55 37 pm" src="https://user-images.githubusercontent.com/635596/69936805-f87e6a00-152c-11ea-850d-32a53e359b34.png"> |

**Comment by therealbnut** [comment]
You can reproduce this issue by making this change in `examples/cairo-rs/src/main.rs`:
```diff
     drawing_area.connect_draw(move |w, cr| {
+        let scale = 0.25;
         let s = resvg::ScreenSize::new(
-            w.get_allocated_width() as u32,
-            w.get_allocated_height() as u32,
+            (scale * w.get_allocated_width() as f64) as u32,
+            (scale * w.get_allocated_height() as f64) as u32,
         ).unwrap();

+        cr.save();
+        cr.scale(1.0 / scale, 1.0 / scale);
         resvg::backend_cairo::render_to_canvas(&tree, &opt, s, cr);
+        cr.restore();

         Inhibit(false)
     });
```

So it does seem to affect all backends.

**Comment by RazrFalcon** [comment]
I'm not sure what are you trying to do. Can you provide and SVG file? Does `rendersvg` produce a correct result?

**Comment by therealbnut** [comment]
> I'm not sure what are you trying to do

Ultimately I want to be able to compose SVG content with content from other sources onto a single canvas. This worked in 0.6.1, but I'm trying to upgrade to the latest version.

I'm using revsg to render an svg into an existing canvas, I'm drawing other things to the same canvas programmatically. I want to be able to place the svg into a specific location, with a rotation, scale, and clip.

My expectation of how `render_to_canvas` should work is similar to how other canvas drawing commands work.

In this contrived example, I expect these two blocks of pseudocode should have similar results (assuming the svg has the correct content, `viewBox`, and `preserveAspectRatio`):

**Using resvg**
```rust
fn draw_circle(transform: Matrix, size: Size) {
    canvas.concat(&transform);
    let tree = load_an_svg_of_a_circle();
    render_to_canvas(&tree, &opt, size, canvas);
}
```

**Using canvas commands**
```rust
fn draw_circle(transform: Matrix, size: Size) {
    canvas.concat(transform);
    canvas.draw_oval(Rect::from_xywh(0.0, 0.0, size.width, size.height));
}
```

---

> Can you provide and SVG file?

I don't think it's specific to the SVG, but here's the one I used: [example.svg](https://github.com/RazrFalcon/resvg/files/3920809/example.svg.zip).

> Does `rendersvg` produce a correct result?

The SVG renders correctly when using `rendersvg`. Although `rendersvg` doesn't apply any transforms.

**Comment by RazrFalcon** [comment]
I think you should scale `size: Size` manually.

**Comment by therealbnut** [comment]
Yeah, I tried to solve it from the caller, by setting the size, although if you translate it then you also end up losing part of the rendered region svg proportional to the translation.

Even if I can solve the translation issue by setting the size even bigger, it seems wasteful and fragile, like it’s not how size is meant to work.

**Comment by RazrFalcon** [comment]
The API design is still an open question. I'm not sure how it should be implemented.

Regarding the `size` parameter, the problem is that SVG doesn't have a size, since shapes can be placed outside the canvas. And we have to know the size to create layers, which are raster images. That's why we need the `size` parameter.

I understand what are you trying to do, but I never tested resvg in this regard. The preferred way is to simply render to image and then render the image itself.

**Comment by therealbnut** [comment]
Okay, thanks :) If I manage to adjust the implementation so the API (or a new one) works as I thought, would it be a welcome contribution?

**Comment by RazrFalcon** [comment]
Sure.

**Comment by RazrFalcon** [comment]
After looking into it a bit, I still think that the current API is correct. You must provide a canvas size. Afaik, an affine transform cannot be reversed, so I cannot calculate the correct scale anyway.
Unless you are absolutely sure that you SVG has only one layer, you should use `resvg_*_render_to_image` and then render the raster to your canvas.

**Comment by RazrFalcon** [comment]
I've added a note to the docs that the canvas must not have a transform. Sadly, this is the limitation we cannon bypass.
