### ISSUE TITLE
"SVG data parsing failed cause the document does not have a root node." error on OpenClipArt files

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/resvg#192]
Many of the files in OpenClipArt library fail to render with resvg with the following message:

> Error: SVG data parsing failed cause the document does not have a root node.

They are rendered by librsvg and Inkscape. Tested on commit e3cfe1a6d9524b14a997b7913c44faa6d7396e59

Archive with all files failing with this error message: 
[no_root_node.tar.gz](https://github.com/RazrFalcon/resvg/files/4007391/no_root_node.tar.gz)

**Comment by RazrFalcon** [comment]
An SVG file must have a `xmlns="http://www.w3.org/2000/svg"` namespace. Without it, it is malformed. Browsers and Batik will not load such files too. I think that Inkscape and librsvg are incorrect in this regard.

For example, librsvg v2.47.1 doesn't support mixed namespaces. You can test it on [e-svg-003.svg](https://github.com/RazrFalcon/resvg-test-suite/blob/master/svg/e-svg-003.svg)

**Comment by LaurenzV** [comment]
The issue has been fixed in the newest release, anyway (as in SVGs without root xmlns are now accepted).
