### ISSUE TITLE
Can't comile successfuly？

### ISSUE THREAD

**Issue by franklydog** [RazrFalcon/resvg#194]
hi。
    when I comile resvg。it have some erros。compile on msys64，command is “QT_DIR="d:\\msys64\\mingw64\\" cargo build --verbose --release --features="qt-backend“”

error[E0599]: no method named `as_deref` found for type `std::option::Option<std::string::String>` in the current scope
   --> usvg\src\convert\mod.rs:352:63
    |
352 |     let filter_fill = resolve_filter_fill(node, state, filter.as_deref(), tree);
    |                                                               ^^^^^^^^ help: there is a method with a similar name: `as_ref`
thanks。

**Comment by RazrFalcon** [comment]
Update Rust to the latest version. `as_deref` was added in 1.40

**Comment by franklydog** [comment]
Thanks a lot。
