### ISSUE TITLE
Rendering issue when linearGradient with alpha stops is set on fill or stroke

### ISSUE THREAD

**Issue by ferdnyc** [RazrFalcon/resvg#196]
We have some Inkscape-generated SVG files that don't seem to be rendering properly in resvg — the common thread seems to be that `linearGradient`s that have `stop-opacity` set in the `<stop>` members will have their opacity ignored when used as the `fill` or `stroke` for `text` objects. All of those things are [documented](https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html) as a supported features, maybe it's the combination of all of them together that's causing issues.

Easiest thing is to provide an example. Here's our file `Bar_1.svg` as rendered by ImageMagick (which will run `inkscape` as its SVG rendering delegate), then composed over a checkerboard pattern, using the commands:
```sh
convert -background none Bar_1.svg Bar_1_magick.png
convert \( -size 1920x1080 tile:pattern:checkerboard \) Bar_1_magick.png \
  -compose over -composite Bar_1_magick2.png
```
![Bar_1_magick2](https://user-images.githubusercontent.com/538020/71977570-1eabbf80-31e7-11ea-9ed8-1f9f33db9775.png)

Now here's the output of resvg, if I construct the image the same way:
```sh
rendersvg Bar_1.svg Bar_1_resvg.png
convert \( -size 1920x1080 tile:pattern:checkerboard \) Bar_1_resvg.png \
  -compose over -composite Bar_1_resvg2.png
```
![Bar_1_resvg2](https://user-images.githubusercontent.com/538020/71977629-469b2300-31e7-11ea-91de-464ff4b6993a.png)

The issue is most visible in the (lack of) fading on the "reflected" line of text,<strike> but even the fill for the _upright_ text is less transparent in the resvg rendering, than in the Inkscape-rendered version.</strike>

The unmodified `Bar_1.svg` file used to generate both images: [Bar_1.zip](https://github.com/RazrFalcon/resvg/files/4035227/Bar_1.zip)

We originally discovered this using the Qt backend, since the surrounding code calling in to the resvg API is Qt code, but I've since reproduced it using the raqote backend as well. The image above was generated with `rendersvg` built from the latest git HEAD, using the raqote backend.

**Comment by ferdnyc** [comment]
> but even the fill for the _upright_ text is less transparent in the resvg rendering, than in the Inkscape-rendered version.

I take that part back, it may appear that way but it's a trick of perception. Using Gimp's eyedropper tool on pixel-for-pixel scaled views of both images, the fill color over the darker checkerboard squares measures the same: `#2b4aaa`.

**Comment by ferdnyc** [comment]
Here's the (cropped and inverted) result of loading both images as layers in Gimp, then applying a Difference blend mode to the top layer. At 1:1 scale, it's clear the differences are confined to the `stroke` of the upright text, and both the `fill` and `stroke` of the reflected text.

![image](https://user-images.githubusercontent.com/538020/71981561-a4803880-31f0-11ea-8292-922ff27a6b6c.png)

**Comment by RazrFalcon** [comment]
Can confirm. This is due to invalid transform processing during text-to-path conversion.

**Comment by RazrFalcon** [comment]
Done. I think that this is a good opportunity to release 0.9.0, unless you have any other issues.

**Comment by ferdnyc** [comment]
@RazrFalcon None that aren't our fault, AFAIK. Thanks for the quick response!

**Comment by jonoomph** [comment]
Thanks @RazrFalcon for the help! You Rock!
