### ISSUE TITLE
Transforms

### ISSUE THREAD

**Issue by fishrockz** [RazrFalcon/resvg#199]
I have been trying to render the plotlib produced svg's in druid with there svg widget which is based on usvg. This dose not seem to be working very well as plotlib uses a transform="translate()" in the top level group that means that they do not render properly

a typical plotlib svg looks like:
```
<svg viewBox="0 0 600 400" xmlns="http://www.w3.org/2000/svg">
<g transform="translate(48, 364)">
<g>
<rect fill="#DD3355" height="10" width="10" x="99" y="-141"/>
<rect fill="#DD3355" height="10" width="10" x="307" y="-107"/>
</g>
<g>
<circle cx="208" cy="-136" fill="#35C788" r="5"/>
<circle cx="416" cy="-204" fill="#35C788" r="5"/>
</g>
<g>
<g>
<line stroke="black" stroke-width="1" x1="0" x2="0" y1="0" y2="10"/>
<line stroke="black" stroke-width="1" x1="104" x2="104" y1="0" y2="10"/>
<line stroke="black" stroke-width="1" x1="208" x2="208" y1="0" y2="10"/>
<line stroke="black" stroke-width="1" x1="312" x2="312" y1="0" y2="10"/>
<line stroke="black" stroke-width="1" x1="416" x2="416" y1="0" y2="10"/>
<line stroke="black" stroke-width="1" x1="520" x2="520" y1="0" y2="10"/>
</g>
<line stroke="black" stroke-width="1" x1="0" x2="520" y1="0" y2="0"/>
<g>
<text font-size="12" text-anchor="middle" x="0" y="20">
0
</text>
<text font-size="12" text-anchor="middle" x="104" y="20">
1
</text>
<text font-size="12" text-anchor="middle" x="208" y="20">
2
</text>
<text font-size="12" text-anchor="middle" x="312" y="20">
3
</text>
<text font-size="12" text-anchor="middle" x="416" y="20">
4
</text>
<text font-size="12" text-anchor="middle" x="520" y="20">
5
</text>
</g>
<text font-size="12" text-anchor="middle" x="260" y="30">
Some varying variable
</text>
</g>
<g>
<g>
<line stroke="black" stroke-width="1" x1="0" x2="-10" y1="0" y2="0"/>
<line stroke="black" stroke-width="1" x1="0" x2="-10" y1="-68" y2="-68"/>
<line stroke="black" stroke-width="1" x1="0" x2="-10" y1="-136" y2="-136"/>
<line stroke="black" stroke-width="1" x1="0" x2="-10" y1="-204" y2="-204"/>
<line stroke="black" stroke-width="1" x1="0" x2="-10" y1="-272" y2="-272"/>
<line stroke="black" stroke-width="1" x1="0" x2="-10" y1="-340" y2="-340"/>
</g>
<line stroke="black" stroke-width="1" x1="0" x2="0" y1="0" y2="-340"/>
<g>
<text dominant-baseline="middle" font-size="12" text-anchor="end" x="-15" y="0">
0
</text>
<text dominant-baseline="middle" font-size="12" text-anchor="end" x="-15" y="-68">
1
</text>
<text dominant-baseline="middle" font-size="12" text-anchor="end" x="-15" y="-136">
2
</text>
<text dominant-baseline="middle" font-size="12" text-anchor="end" x="-15" y="-204">
3
</text>
<text dominant-baseline="middle" font-size="12" text-anchor="end" x="-15" y="-272">
4
</text>
<text dominant-baseline="middle" font-size="12" text-anchor="end" x="-15" y="-340">
5
</text>
</g>
<text font-size="12" text-anchor="middle" transform="rotate(-90 -30 -170)" x="-30" y="-170">
The response of something
</text>
</g>
</g>
```

I have created a test that attempts to recreate this behaviour
https://github.com/fishrockz/resvg/commit/ed51ba1c67ed9b7da9bcc85bb0ec2c1ec67434ea

The test demonstrates what i expect to happen and so currently fails, i will try to make a fix but i am new to rust and this lib so i may not do very well.

**Comment by fishrockz** [comment]
This created the svg, https://gitlab.com/pointswaves/rust-plot-gui/

**Comment by RazrFalcon** [comment]
Last time I've checked druid has no SVG support. If you are talking about a newly added SVG widget, it's not an SVG widget, it's SVG path widgets. Does not expect it work correctly.

**Comment by fishrockz** [comment]
I'm not expecting the druid widget to be perfect. But have I messed up the test cast I wrote or is exposing a real issue?

**Comment by RazrFalcon** [comment]
`resvg` doesn't apply transforms to paths. This is an expected behavior.

**Comment by fishrockz** [comment]
So should the transformation still be attached to the group? I'm just trying to work out how I would tweak the druid SVG widget so that the lines end up in the right place.

If the transformation is still attached to one of the usvg "nodes" then I should be able to track the transformations and apply in the widget?

In the test case I wrote should the transformation end up in the output file as a transform?

I am afk but will have a play this evening

**Comment by RazrFalcon** [comment]
The correct output for your file is

```xml
<svg width="1920" height="1080" viewBox="0 0 1920 1080" xmlns="http://www.w3.org/2000/svg" xmlns:usvg="https://github.com/RazrFalcon/resvg" usvg:version="0.8.0">
    <path fill="#000000" stroke="none" transform="matrix(1 0 0 1 50 50)" d="M 0 0 L 10 0 L 10 10 L 0 10 Z"/>
</svg>
```

So you have to transform the painter/context first, than render a shape, and then reset previous transform.

**Comment by fishrockz** [comment]
Brilliant
I have fixed all my lines to end up in the right place and am hoping to get it tidy enough for a patch for druid.
