### ISSUE TITLE
Unable to statically link MSVC debug runtime

### ISSUE THREAD

**Issue by olilarkin** [RazrFalcon/resvg#201]
I am trying to build RESVG debug and release static libs which link statically to the MSVC runtime.

Adding target-feature=+crt-static to rustflags in .cargo/config works for Release builds, but I cannot make it work for debug builds.

I get many linker errors due to a mismatch between skia and resvg. 

Do you have any idea why resvg is not linking to the MTd_StaticDebug when building without --release ?

here's a selection of the many errors

` skia.lib(skia.SkEmbossMaskFilter.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkEmbossMaskFilter.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkShaderMaskFilter.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkShaderMaskFilter.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkCornerPathEffect.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkCornerPathEffect.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkDiscretePathEffect.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkDiscretePathEffect.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.Sk2DPathEffect.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.Sk2DPathEffect.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkOpPathEffect.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkOpPathEffect.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.Sk1DPathEffect.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.Sk1DPathEffect.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkTrimPathEffect.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkTrimPathEffect.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkLayerDrawLooper.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkLayerDrawLooper.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkNormalSource.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkNormalSource.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkImageFilters.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(skia.SkImageFilters.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(fontmgr_win.SkFontMgr_win_dw.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(fontmgr_win.SkFontMgr_win_dw.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrDrawOpAtlas.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrDrawOpAtlas.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrAAConvexPathRenderer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrAAConvexPathRenderer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrAALinearizingConvexPathRenderer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrAALinearizingConvexPathRenderer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrSmallPathRenderer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrSmallPathRenderer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrStencilAndCoverPathRenderer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrStencilAndCoverPathRenderer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrTessellatingPathRenderer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrTessellatingPathRenderer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrDefaultPathRenderer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrDefaultPathRenderer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrDashLinePathRenderer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)
          skia.lib(gpu.GrDashLinePathRenderer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in libresvg_skia-7538b2eb333eb96e.rlib(skia_capi.o)`

**Comment by RazrFalcon** [comment]
No idea. Maybe some cargo bug.
