### ISSUE TITLE
Support lengthAdjust and textLength

### ISSUE THREAD

**Issue by keyliaran** [RazrFalcon/resvg#204]
Hello, I need to render svg with **lengthAdjust** and **textLength** attributes, but current version of library doesn't support these attributes.

**Comment by RazrFalcon** [comment]
And?

**Comment by keyliaran** [comment]
Will this attributes be supported in future releases?

**Comment by RazrFalcon** [comment]
Yes.

**Comment by ullenboom** [comment]
Is there anything we can do about it? Sadly, this problem is unsolved for almost 3 years.

**Comment by RazrFalcon** [comment]
Well, we can implement it. It would take a couple of days, which I don't have. That's about it.

**Comment by RazrFalcon** [comment]
Done. 

As always, no one really supports this feature, so I have no idea how exactly it should be implemented.
