### ISSUE TITLE
Consider listing notable users in README

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/resvg#205]
Raqote lists notable users of the library in README as an indicator of the code being complete enough to handle those workloads. It probably makes sense to do the same for resvg.

For example, I was not aware that OpenShot uses resvg.

**Comment by RazrFalcon** [comment]
Yes, this is a good idea, but I don't know who actually uses it. OpenShot is the main candidate.
Also, Wikimedia has plans on using it.

**Comment by RazrFalcon** [comment]
Should revisit this in a few years.
