### ISSUE TITLE
bboxes example only works if fill is None or has transparency < 1.0

### ISSUE THREAD

**Issue by stevensonmt** [RazrFalcon/resvg#207]
In `draw_bboxes.rs` line 45 `rtree.root().append_kind(usvg::NodeKind::Path(usvg::Path ...)` the fill is set to None because otherwise the fill overlays everything. This makes sense as it is appended as a child to the tree. I could not find documentation in usvg to "prepend" to a Tree or to append one Tree to another. Is there some other way to generate a background as the actual background without overlaying on top of all the other elements from the file?

I recognize this might be more of a usvg question, but the repository does not take issues and I'm not certain it is in active development.

**Comment by RazrFalcon** [comment]
I guess you're looking for something like this:

```rust
    /// ...

    for bbox in bboxes {
        let node = usvg::Node::new(usvg::NodeKind::Path(usvg::Path {
            id: String::new(),
            transform: usvg::Transform::default(),
            visibility: usvg::Visibility::Visible,
            fill: Some(usvg::Fill {
                paint: usvg::Paint::Color(usvg::Color::black()),
                opacity: usvg::Opacity::new(0.2),
                rule: usvg::FillRule::default(),
            }),
            stroke: stroke.clone(),
            rendering_mode: usvg::ShapeRendering::default(),
            data: Rc::new(usvg::PathData::from_rect(bbox)),
        }));

        rtree.root().prepend(node);
    }

    /// ...
```

See `rctree` [documentation](https://docs.rs/rctree/0.3.3/rctree/struct.Node.html) for details.

usvg is part of resvg. They are developed in parallel.

**Comment by stevensonmt** [comment]
Thank you so much. That is perfect. I missed the documentation that said `usvg::Node` is an "Alias for rctree::Node<NodeKind>."
