### ISSUE TITLE
how to run/use resvg

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#208]
I would like to render a svg as png, but I do not know how to start resvg. I tried `resvg` and `cargo run resvg`, but it did not work.

I already succesfully build:
```bash
sudo apt install qtbase5-dev libharfbuzz-dev libcairo2-dev
cargo build --release --features "qt-backend"
cargo build --release --features "cairo-backend"
cargo build --release --features "raqote-backend"
```

**Comment by RazrFalcon** [comment]
You should use [rendersvg](https://github.com/RazrFalcon/resvg/tree/master/tools/rendersvg), which is a CLI tool. `resvg` is just a library. 

I should note it somewhere...

**Comment by RazrFalcon** [comment]
I guess we can close this now.
