### ISSUE TITLE
Render only specified element

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#21]
- [x] Store original id's
- [x] Detect item bounding box #33
- [x] Add method to query id's
- [ ] Add option to CLI

**Comment by moazin** [comment]
Hi. I am a GSoC student working on the project "Adding OpenType SVG font support to FreeType". For this project, we are evaluating different SVG rendering libraries to ultimately seek out what works best for us. Resvg is one of the candidates. 

An important feature we need is the ability to render a `<g>` element that has an specific id. Why we need this feature and how we plan to use it is described in the section `Glyph Identifiers` of the OpenType SVG specs. You can see that [here](https://docs.microsoft.com/en-us/typography/opentype/spec/svg#glyph-identifiers). 

 I was happy to see that resvg provides a function named `resvg_cairo_render_to_canvas_by_id`. The SVG document that I tried it is attached below. However, when used, the method returns an error, "A node with `glyph8` ID was not found". So I started looking and it looks like that when `convert_doc` is called, the new simplified tree doesn't have those `Group` elements whose ID is being searched for. 

What I want to ask is, am I doing it wrong? or is it expected to behave this way? if yes, do you plan to fix this issue? I am attaching my main file and the svg document for your convenience. The program is written in C. 
[svg-file.txt](https://github.com/RazrFalcon/resvg/files/3256150/svg-file.txt)
[prog.txt](https://github.com/RazrFalcon/resvg/files/3256151/prog.txt)

**Comment by RazrFalcon** [comment]
You should enable [keep_named_groups](https://github.com/RazrFalcon/resvg/blob/master/capi/include/resvg.h#L212).

**Comment by moazin** [comment]
Oops, missed that. Thank you very much, that works. :+1:
