### ISSUE TITLE
Warning (in resvg::image:36): Failed to load an embedded image

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#210]
I try to render https://commons.wikimedia.org/wiki/File:Abkhazia_map-fr.svg, but sadly the (partly) transparent png is not rendered at all.

> rendersvg ![min.svg.txt](https://github.com/RazrFalcon/resvg/files/4231984/min.svg.txt) [rEsvg.png](https://user-images.githubusercontent.com/15687581/74959262-8a9a5e00-540a-11ea-8929-13476a432fc3.png)

| rsvg | resvg |
| ------ | ------ |
| ![rsvg](https://user-images.githubusercontent.com/15687581/74959245-84a47d00-540a-11ea-960e-073eaae37039.png)| ![rEsvg](https://user-images.githubusercontent.com/15687581/74959262-8a9a5e00-540a-11ea-8929-13476a432fc3.png)|

### Copyright

source: https://commons.wikimedia.org/wiki/File:Abkhazia_map-fr.svg

Author: https://commons.wikimedia.org/wiki/User:S%C3%A9mhur

license: CC-BY-SA 3.0 https://creativecommons.org/licenses/by-sa/3.0

**Comment by RazrFalcon** [comment]
Closed by https://github.com/RazrFalcon/resvg/commit/5527c4b6ecb354ddc66fb9f7732c0d925477ecb7
