### ISSUE TITLE
doctype after comment --> error

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#212]
I try to render https://commons.wikimedia.org/wiki/File:AntigenicShift_HiRes.svg but sadly rendersvg says `Error: SVG data parsing failed cause unknown token at 3:1.`

> rendersvg [min.svg.txt](https://github.com/RazrFalcon/resvg/files/4232125/min.svg.txt) resvg.png

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generator: Adobe Illustrator 13.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 14948)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg"/>
```

### Copyright

source: https://commons.wikimedia.org/wiki/File:AntigenicShift_HiRes.svg

Author: {{Derivative}}: {{U|Mouagip}}
*{{F|AntigenicShift_HiRes.png}}: {{W|National Institute of Allergy and Infectious Diseases}} (NIAID).

license: Public Domain

**Comment by RazrFalcon** [comment]
Fixed by https://github.com/RazrFalcon/xmlparser/commit/94638df5244b5ebfbe0ba76961399a80c4ddf4d1
