### ISSUE TITLE
does not render <clipPath containing <use refering to a <g roup containing two <path

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#213]
I am processing https://commons.wikimedia.org/wiki/File:Flag-map_of_the_world.svg

I optimized the file (using e.g. svgcleaner) to ![Flagmapc44pS54C4CCCC44_vpb0oo555InkS4CCuSCoSC.svg.txt](https://github.com/RazrFalcon/resvg/files/4237570/Flagmapc44pS54C4CCCC44_vpb0oo555InkS4CCuSCoSC.svg.txt)

I assume it is the same problem as in https://github.com/RazrFalcon/svgcleaner/issues/211

|lib|pic|
|-----|-----|
|rsvg|![Flagmapc44pS54C4CCCC44_vpb0oo555InkS4CCuSCoSC_rsvg](https://user-images.githubusercontent.com/15687581/75062559-5050bf80-54e3-11ea-931b-b030b812c6d6.png)|
|resvg|![Flagmapc44pS54C4CCCC44_vpb0oo555InkS4CCuSCoSC_resvg](https://user-images.githubusercontent.com/15687581/75062570-56df3700-54e3-11ea-8cb6-c162ae806c27.png)|

**Comment by RazrFalcon** [comment]
The problem is in the missing Argentina? It's missing in Chrome and Firefox too.

I will investigate the cause.

**Comment by RazrFalcon** [comment]
Yes. resvg, Chrome and Firefox are correct. `use` is not allowed in `clipPath`. The file is malformed.

**Comment by JoKalliauer** [comment]
@RazrFalcon : Actually it is the correct behaviour of resvg, see https://github.com/RazrFalcon/svgcleaner/issues/211#issuecomment-589796605 


Quting from https://www.w3.org/TR/SVG11/masking.html#EstablishingANewClippingPath
> A ‘clipPath’ element can contain ‘path’ elements, ‘text’ elements, basic shapes (such as ‘circle’) or a ‘use’ element. If a ‘use’ element is a child of a ‘clipPath’ element, it must directly reference ‘path’, ‘text’ or basic shape elements. Indirect references are an error (see Error processing).

**Comment by RazrFalcon** [comment]
You are right. I forgot about that. But in this file, `clipPath` contains `use` that references `g`. So the file is malformed.
