### ISSUE TITLE
Add GIF support

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#214]
Processing https://commons.wikimedia.org/wiki/File:Markakol_map-ru.svg 

[min.svg.txt](https://github.com/RazrFalcon/resvg/files/4237940/min.svg.txt)

|rsvg|resvg
|-----|-----|
|![MarkakolcCS5isoSCOSC_r](https://user-images.githubusercontent.com/15687581/75069873-6914a180-54f2-11ea-83ee-c1dd94c8ef49.png)|![MarkakolcCS5isoSCOSC_re](https://user-images.githubusercontent.com/15687581/75069882-6e71ec00-54f2-11ea-9ac6-566fcb876d15.png)|

### Copyright

source: https://commons.wikimedia.org/wiki/File:Markakol_map-ru.svg

author Mikhail2009

license: https://creativecommons.org/licenses/by-sa/3.0

**Comment by RazrFalcon** [comment]
This is kinda out of scope. The SVG requires only PNG and JPEG.
