### ISSUE TITLE
Incorrect filtering at the edge of an image

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#215]
rendering https://commons.wikimedia.org/wiki/File:Pelean_Eruption-numbers.svg
similar for https://commons.wikimedia.org/wiki/File:Mahuri.svg https://commons.wikimedia.org/wiki/File:Anime_Girl.svg

The border of
[Pelean_EruptionnumbersOCSv0_p.svg.txt](https://github.com/RazrFalcon/resvg/files/4238044/Pelean_EruptionnumbersOCSv0_p.svg.txt)

looks strange (soothed to the border) I assume it should be a sharp border (I do not how blurs should work)

|rsvg|resvg|
|----|----|
|![Pelean_EruptionnumbersOCSv0_p_r](https://user-images.githubusercontent.com/15687581/75071950-bd218500-54f6-11ea-9ab9-a3f5b5ef2f88.png)|![Pelean_EruptionnumbersOCSv0_p_re](https://user-images.githubusercontent.com/15687581/75071958-c3affc80-54f6-11ea-927a-f8b7eca6d3de.png)|

### expected 
![Screenshot from 2020-02-21 22-02-41](https://user-images.githubusercontent.com/15687581/75072023-e7734280-54f6-11ea-8fc0-fe4771d4024d.png)

### Copyright
source: https://commons.wikimedia.org/wiki/File:Pelean_Eruption-numbers.svg

author Sémhur

license: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by RazrFalcon** [comment]
You mean the top part? In the new rsvg (2.47.2) it looks the same.

I guess this is due to the edge of the image. resvg doesn't work well with filters that are outside the canvas.

**Comment by JoKalliauer** [comment]
Yes the top part, this also affects images such as https://commons.wikimedia.org/wiki/File:Mahuri.svg or https://commons.wikimedia.org/wiki/File:Anime_Girl.svg


|rsvg|resvg|
|----|----|
|![Anime Girl_r](https://user-images.githubusercontent.com/15687581/75073844-a11fe280-54fa-11ea-8514-9b9a303fa3ce.png)|![Anime Girl_re](https://user-images.githubusercontent.com/15687581/75073856-a5e49680-54fa-11ea-8ea0-8db96dfde365.png)|


|rsvg|resvg|
|----|----|
|![Mahuri_r](https://user-images.githubusercontent.com/15687581/75073870-ad0ba480-54fa-11ea-8eb1-a268b448b858.png)|![Mahuri_re](https://user-images.githubusercontent.com/15687581/75073882-b1d05880-54fa-11ea-9b6a-83afc4bf3453.png)|


### copyright

source https://commons.wikimedia.org/wiki/File:Anime_Girl.svg and  https://commons.wikimedia.org/wiki/File:Mahuri.svg

author Niabot

license https://creativecommons.org/licenses/by/3.0

**Comment by RazrFalcon** [comment]
Fixed in v0.33

**Comment by JoKalliauer** [comment]
Thanks, now librsvg has this regression: https://gitlab.gnome.org/GNOME/librsvg/-/issues/969
