### ISSUE TITLE
Invalid alpha blending in the blur filter

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#216]
Processing https://commons.wikimedia.org/wiki/File:Fishing_reel-sm.svg

[Fishing_reelsm5p5csoSC.svg.txt](https://github.com/RazrFalcon/resvg/files/4238091/Fishing_reelsm5p5csoSC.svg.txt)

|lib|pic
|----|----|
|rsvg|![Fishing_reelsm5p5csoSC_r](https://user-images.githubusercontent.com/15687581/75072788-7df43380-54f8-11ea-8b04-015bb5e7c987.png)|
|resvg|![Fishing_reelsm5p5csoSC_re](https://user-images.githubusercontent.com/15687581/75072801-82b8e780-54f8-11ea-9923-1a12386a8b31.png)|

If you look closely the shaddow behind 8 looks strage in resvg

### Copyright

source: https://commons.wikimedia.org/wiki/File:Fishing_reel-sm.svg

author: Original photo: Jan Tik. Vectorized version: Chabacano

license: https://creativecommons.org/licenses/by-sa/3.0/

**Comment by RazrFalcon** [comment]
Yes, this is some weird blur artifacts.

The minimal SVG:

```xml
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <filter id="filter1">
        <feGaussianBlur stdDeviation=".67353111"/>
    </filter>
    <rect x="20" y="20" width="160" height="160" fill="#191919" filter="url(#filter1)"/>
</svg>
```

**Comment by RazrFalcon** [comment]
Seems to be fixed now.

**Comment by JoKalliauer** [comment]
Sorry I don't even see the difference now any more (between librsvg and rendersvg), don't know what I reported. Thanks for closing.
