### ISSUE TITLE
Correct path is being removed

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#217]
Processing https://commons.wikimedia.org/wiki/File:Phreatic_Eruption-numbers.svg

[PhreaticS5O4s.svg.txt](https://github.com/RazrFalcon/resvg/files/4238112/PhreaticS5O4s.svg.txt)

|lib|pic|
|---|---|
|rsvg|![PhreaticS5O4s_r](https://user-images.githubusercontent.com/15687581/75073593-0e7f4380-54fa-11ea-8f75-4cf12b7eaeff.png)|
|resvg|![PhreaticS5O4s_re](https://user-images.githubusercontent.com/15687581/75073604-15a65180-54fa-11ea-81b6-c8f851db8ffa.png)|

I assume this behaviour is indented (error-processing) since I get following messages
```bash
Warning (in resvg::filter:169): Filter 'bo' has an invalid region.
Warning (in resvg::filter:169): Filter 'bn' has an invalid region.
Warning (in resvg::filter:169): Filter 'bk' has an invalid region.
```

### Copyright

source https://commons.wikimedia.org/wiki/File:Phreatic_Eruption-numbers.svg

author Sémhur ·✉·✍·

license https://creativecommons.org/licenses/by-sa/3.0/

**Comment by RazrFalcon** [comment]
The latest rsvg produces the same result. But Chrome and Inkscape are correct.

**Comment by RazrFalcon** [comment]
Looks like this is yet another undefined behavior.

I've clarified it the sources: https://github.com/RazrFalcon/resvg/commit/933c927fed2f2d95b93b7b8e043331f83f0d3310
