### ISSUE TITLE
colour change

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#218]
Processing https://commons.wikimedia.org/wiki/File:POL_COA_Trzaska.svg

[POLCpCpSOSC.svg.txt](https://github.com/RazrFalcon/resvg/files/4238147/POLCpCpSOSC.svg.txt)

|lib|pic|
|---|---|
|rsvg|![POLCpCpSOSC_r](https://user-images.githubusercontent.com/15687581/75074221-869a3900-54fb-11ea-9f32-57a7b6617d5e.png)|
|resvg|![POLCpCpSOSC_re](https://user-images.githubusercontent.com/15687581/75074238-8c901a00-54fb-11ea-8c7d-c0573c438c49.png)

resvg renders the green at the top a bit more bright, don't know which one is correct (save both in the same folder and change forward/backward with your png-viewer)

### Copyright

soucre: https://commons.wikimedia.org/wiki/File:POL_COA_Trzaska.svg

author:  All except interior of shield and peacock faethers Bastianow based on works of Mr. Tadeusz Gajl interior of shield and peacock feathers made by WarX

license: https://creativecommons.org/licenses/by-sa/2.5

**Comment by JoKalliauer** [comment]
same for https://commons.wikimedia.org/wiki/File:Renal_corpuscle.svg for the green part numbered with 6

|rsvg|resvg|
|---|---|
|![Renal corpuscle_r](https://user-images.githubusercontent.com/15687581/75075226-9c106280-54fd-11ea-8858-41f9bf3e24fb.png)|![Renal corpuscle_re](https://user-images.githubusercontent.com/15687581/75075230-a03c8000-54fd-11ea-8798-276183bb6a29.png)|

### Copyright

source: https://commons.wikimedia.org/wiki/File:Renal_corpuscle.svg

author: M.Komorniczak (polish Wikipedist) 

license: https://creativecommons.org/licenses/by-sa/3.0

**Comment by RazrFalcon** [comment]
>save both in the same folder and change forward/backward with your png-viewer

I'v using [vdiff](https://github.com/RazrFalcon/resvg-test-suite/tree/master/tools/vdiff) instead.

**Comment by RazrFalcon** [comment]
What resvg backend do you use? It looks like it boils down to backend's anti-aliasing implementation. All those thin lines are nightmare to smooth down.

**Comment by JoKalliauer** [comment]
I use the binary in `resvg/target/release/rendersvg` 

I think the last backend I build resvg was `cargo build --release --features "qt-backend"`

(Sorry I do not understand anything about what the different backends mean or which I am acutually using.)

I thought it is a different color, but is only a different line-thickness? I think we can close this issue

**Comment by RazrFalcon** [comment]
Yes, and I don't really have any control over it.

You can find the current backend in the help output. Next to the `--backend` option.

**Comment by JoKalliauer** [comment]
> What resvg backend do you use?

Till now with "qt".

**Comment by RazrFalcon** [comment]
cairo, qt, raqote ans skia may produce vastly different results. There are no such thing as a "correct rasterization". And I can't control the behavior from the resvg.

So shapes outlining, gradients. anti-aliasing, text hinting will always be different. So they can be ignored. The real problem is when something is hugely different or missing completely.
