### ISSUE TITLE
thiner linewidth than rsvg

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#220]
processing https://commons.wikimedia.org/wiki/File:Su25-kompo-vers2.svg

|rsvg|resvg|
|---|---|
|![Su25-kompo-vers2_r](https://user-images.githubusercontent.com/15687581/75075451-21941280-54fe-11ea-82f5-3085d695a088.png)|![Su25-kompo-vers2_re](https://user-images.githubusercontent.com/15687581/75075468-2789f380-54fe-11ea-933f-41357eeb5894.png)|

I'm not sure if this is considered as an issue?

### Copyright

source https://commons.wikimedia.org/wiki/File:Su25-kompo-vers2.svg

author Altoing

license https://creativecommons.org/licenses/by-sa/3.0

**Comment by RazrFalcon** [comment]
This is due to different anti-aliasing implementations in different 2D libraries.

Here is how much it can vary:

![Su25-kompo-vers2](https://user-images.githubusercontent.com/725494/75076962-19da6b00-550a-11ea-8bed-7adb134f0ae7.png)

(diff is relative to Chrome)
