### ISSUE TITLE
Question: Correct rendered?

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#222]
The first version in https://commons.wikimedia.org/wiki/File:D%C3%A9bit_de_Filtration_Glom%C3%A9rulaire.svg#filehistory is https://upload.wikimedia.org/wikipedia/commons/archive/e/e5/20200220180909%21D%C3%A9bit_de_Filtration_Glom%C3%A9rulaire.svg
(I already made a workaround, therefore a new version exists.)

Is rendered differently in rsvg and resvg.

|rsvg|resvg|
|---|---|
|![Débit de Filtration Glomérulaire_r](https://user-images.githubusercontent.com/15687581/75160121-cdfe1080-5719-11ea-9c9f-e4d744e3d6dd.png)|![Débit de Filtration Glomérulaire_re](https://user-images.githubusercontent.com/15687581/75160127-d2c2c480-5719-11ea-81aa-b56dbeba3049.png)|

I personally assume resvg is right, since writing-mode= is not allowed in tspan(acording to validators), but however I do not know and reporting librsvg bugs has imho a low respondance-rate.

**Comment by RazrFalcon** [comment]
`resvg` is correct.

https://www.w3.org/TR/SVG11/text.html#SettingInlineProgressionDirection

>The ‘writing-mode’ property applies only to ‘text’ elements; the property is ignored for ‘tspan’, ‘tref’, ‘altGlyph’ and ‘textPath’ sub-elements.
