### ISSUE TITLE
change dpi-settings of pt,mm

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#223]
rsvg and resvg render different sizes for   `width="000mm"   height="000mm" viewBox="0 0 000 000"` If you used rsvg for years and want to change to resvg you maybe do not care about current standards, you just want that the old versions still work.

- https://commons.wikimedia.org/wiki/File:Asterias.svg `width="216mm" height="200mm"  viewBox="0 0 216 200"`
- https://commons.wikimedia.org/wiki/File:Digestive_system_diagram_en.svg `width="163.97112mm"   height="231.70444mm" viewBox="0 0 581.00001 820.99997"`
- https://commons.wikimedia.org/wiki/File:Mature_flower_diagram.svg `viewBox="0 0 692.57628 399.92478"   height="112.86766mm"   width="195.46042mm"` 
- https://commons.wikimedia.org/wiki/File:Respiratory_system_complete_cy.svg `   width="255.9985mm"   height="272.74594mm"   viewBox="0 0 907.08131 966.42261"`
- https://commons.wikimedia.org/wiki/File:Respiratory_system_complete_en.svg `   width="255.9985mm"   height="272.74594mm"   viewBox="0 0 907.08131 966.42261"`

|rsvg|resvg|
|---|---|
|![Asterias_r](https://user-images.githubusercontent.com/15687581/75162523-fd168100-571d-11ea-8f0c-53f682dcecf1.png)|![Asterias_re](https://user-images.githubusercontent.com/15687581/75162542-043d8f00-571e-11ea-8f1c-6e3a431c7fd6.png)|
|![Digestive system diagram en_r](https://user-images.githubusercontent.com/15687581/75162580-0c95ca00-571e-11ea-9cc6-c3c6cab597ec.png)|![Digestive system diagram en_re](https://user-images.githubusercontent.com/15687581/75162600-14ee0500-571e-11ea-9365-4589412ff4e3.png)|
|![Mature flower diagram_r](https://user-images.githubusercontent.com/15687581/75162685-36e78780-571e-11ea-98f9-ced2870241b6.png)|![Mature flower diagram_re](https://user-images.githubusercontent.com/15687581/75162693-3b13a500-571e-11ea-9663-983a2f6840f5.png)|
|![Respiratory system complete cy_r](https://user-images.githubusercontent.com/15687581/75163645-dfe2b200-571f-11ea-9b88-e853bb1d4c43.png)|![Respiratory system complete cy_re](https://user-images.githubusercontent.com/15687581/75163648-e07b4880-571f-11ea-9fc2-07d37734c867.png)
|![Respiratory system complete en_r](https://user-images.githubusercontent.com/15687581/75163650-e113df00-571f-11ea-8438-25e28cb35073.png)|![Respiratory system complete en_re](https://user-images.githubusercontent.com/15687581/75163651-e113df00-571f-11ea-9c03-9295f5c64dec.png)|

rsvg and resvg render different windows: `   height="00cm"   width="000pt"`

- https://commons.wikimedia.org/wiki/File:Euro_Construction.svg `   height="16cm"   width="19.5cm"`
- https://commons.wikimedia.org/wiki/File:Fortepian_-_schemat.svg `width="2248" height="750pt"`
- https://commons.wikimedia.org/wiki/File:Heart_numlabels.svg `width="140mm" height="150mm"`
- https://commons.wikimedia.org/wiki/File:Map_at_millstaetter_see.svg `width="1050pt" height="210mm"`
- https://commons.wikimedia.org/wiki/File:Musculi_colli_stylohyoideus.svg `   width="920pt"   height="780pt"`
- https://commons.wikimedia.org/wiki/File:Pianino_-_mechanizm_angielski.svg `   width="560"   height="900pt"`
- https://commons.wikimedia.org/wiki/File:Pianino_-_mechanizm_wiede%C5%84ski.svg `   width="560"   height="900pt"` 
- https://commons.wikimedia.org/wiki/File:Snle-snle-ng-svg.svg `   width="539.00000pt"   height="517.00000pt"`

|rsvg|resvg|
|---|---|
|![Euro Construction_r](https://user-images.githubusercontent.com/15687581/75163000-c1c88200-571e-11ea-850f-42d2a5e7141d.png)|![Euro Construction_re](https://user-images.githubusercontent.com/15687581/75163015-c7be6300-571e-11ea-9d82-783dcc884d34.png)|
|![Fortepian - schemat_r](https://user-images.githubusercontent.com/15687581/75163041-d3118e80-571e-11ea-8047-0ad7d5707c0b.png)|![Fortepian - schemat_re](https://user-images.githubusercontent.com/15687581/75163064-ddcc2380-571e-11ea-86cb-08c151c50bc2.png)|
|![Heart numlabels_r](https://user-images.githubusercontent.com/15687581/75163085-ede40300-571e-11ea-8290-d83e47fc359c.png)|![Heart numlabels_re](https://user-images.githubusercontent.com/15687581/75163089-ee7c9980-571e-11ea-9ea1-0095a1d0fade.png)|
|![Map at millstaetter see_r](https://user-images.githubusercontent.com/15687581/75163146-081de100-571f-11ea-9b47-a4f5dee6e384.png)|![Map at millstaetter see_re](https://user-images.githubusercontent.com/15687581/75163147-08b67780-571f-11ea-852d-c7924fc01109.png)|
|![Musculi colli stylohyoideus_r](https://user-images.githubusercontent.com/15687581/75163196-1e2ba180-571f-11ea-9fa0-1eb77ec0356b.png)|![Musculi colli stylohyoideus_re](https://user-images.githubusercontent.com/15687581/75163199-1ec43800-571f-11ea-93b0-92bfd9782d20.png)|
|![Pianino - mechanizm angielski_r](https://user-images.githubusercontent.com/15687581/75163271-3a2f4300-571f-11ea-80c9-9b42ba718a93.png)|![Pianino - mechanizm angielski_re](https://user-images.githubusercontent.com/15687581/75163273-3ac7d980-571f-11ea-9795-f003784490af.png)|
|![Pianino - mechanizm wiedeński_r](https://user-images.githubusercontent.com/15687581/75163274-3ac7d980-571f-11ea-923f-234230ad3906.png)|![Pianino - mechanizm wiedeński_re](https://user-images.githubusercontent.com/15687581/75163277-3b607000-571f-11ea-886a-169bfa0323aa.png)|
|![Snle-snle-ng-svg_r](https://user-images.githubusercontent.com/15687581/75163727-01dc3480-5720-11ea-9cfe-d0fa3a6e3219.png)|![Snle-snle-ng-svg_re](https://user-images.githubusercontent.com/15687581/75163729-0274cb00-5720-11ea-9c01-9ef9389d0ce3.png)|

### Copyright see follow individual links above
currently, all of them are in https://commons.wikimedia.org/wiki/Category:Featured_pictures_on_Wikimedia_Commons_-_vector , mostly they can be used under CC-BY-SA

**Comment by RazrFalcon** [comment]
>you used rsvg for years and want to change to resvg you maybe do not care about current standards, you just want that the old versions still work

I will not backport old bugs.

You can play with the `--dpi` option if you like. rsvg uses (or at least used) 90, afaik, and resvg is using 96.

**Comment by JoKalliauer** [comment]
>I will not backport old bugs.

I didn't expect something different. I did neither say you should nor you shouldn't.

> You can play with the `--dpi` option if you like. rsvg uses (or at least used) 90, afaik, and resvg is using 96.

Thanks that solves the issue.

**Comment by RazrFalcon** [comment]
>I did neither say you should nor you shouldn't.

Sorry, my English is a bit rough/robotic.

By the way, the SVG spec is a bit vague about the default DPI.

According to the https://www.w3.org/TR/CSS21/syndata.html#length-units

>The reference pixel is the visual angle of one pixel on a device with a pixel density of 96dpi and a distance from the reader of an arm's length. For a nominal arm's length of 28 inches, the visual angle is therefore about 0.0213 degrees. For reading at arm's length, 1px thus corresponds to about 0.26 mm (1/96 inch).

Also, the latest rsvg version is using 96, but still exposes 90 via C interface for compatibility.
