### ISSUE TITLE
gradient precission

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#224]
processing https://commons.wikimedia.org/wiki/File:EM_Spectrum_Properties_edit.svg

|lib|pic
|---|---|
|rsvg|![EM Spectrum Properties edit_r](https://user-images.githubusercontent.com/15687581/75164592-50d69980-5721-11ea-9a1a-e3ef60f6388d.png)|
|resvg|![EM Spectrum Properties edit_re](https://user-images.githubusercontent.com/15687581/75164596-516f3000-5721-11ea-82e1-4961b54cc123.png)|

The atomic nuclei look differnent (gradinet?) and the molecules look different (anti-aliasing?)

**Comment by RazrFalcon** [comment]
This is fine. Gradient rendering is backend-dependent. I cannot control it. 

If you want to compare rsvg and resvg, you should build resvg with the cairo backend to get similar rendering results.

**Comment by JoKalliauer** [comment]
I rendered https://commons.wikimedia.org/wiki/File:Mahuri.svg with cairo-backend and still get different eye-bluring

||pic|
|--|--|
|r|![Mahuri_r](https://user-images.githubusercontent.com/15687581/75172644-e0824500-572d-11ea-8723-9b78bc5e0cd2.png)|
|re|![Mahuri_re](https://user-images.githubusercontent.com/15687581/75172676-ebd57080-572d-11ea-8334-4909277a0309.png)|

I think chrome renders it more like resvg.

### Copyright
source https://commons.wikimedia.org/wiki/File:Mahuri.svg

author Niabot

license https://creativecommons.org/licenses/by/3.0

**Comment by RazrFalcon** [comment]
Why do you think that this is because gradients and not filters?

**Comment by JoKalliauer** [comment]
> Why do you think that this is because gradients and not filters?

Sorry i think in Mahuri.svg it's filters. I'm not so precise and mix them up. (also I know the difference)
