### ISSUE TITLE
IIR blur is too strong

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#225]
Processing https://commons.wikimedia.org/wiki/File:Iowa_16_inch_Gun.svg

The blur at (5) and (9) looks different.

|lib|pic|
|--|--|
|r|![Iowa 16 inch Gun_r](https://user-images.githubusercontent.com/15687581/75166314-fc80e900-5723-11ea-9e2b-0f0b9892afef.png)|
|re|![Iowa 16 inch Gun_re](https://user-images.githubusercontent.com/15687581/75166340-030f6080-5724-11ea-9832-80f264397fbc.png)|

**Comment by RazrFalcon** [comment]
This can be "fixed" by using the box blur by default. Looks like the IIR blur simply produces a smoother result. Not sure if this can be considered a bug. 

Even Chrome and Firefox a slightly different. And Inkscape produces the same result as resvg.

I guess we can mark this as unspecified behavior.
