### ISSUE TITLE
cannot install skia-backend

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#226]
I followed the steps at https://skia.org/user/build#quick and at https://github.com/RazrFalcon/resvg/blob/master/BUILD.adoc#skia-backend

I am running `SKIA_DIR=/home/jkalliau/prgm/resvg-0.9.0/skia SKIA_LIB_DIR=/home/jkalliau/prgm/resvg-0.9.0/skia/out/Shared cargo build --release --features "skia-backend"`  in `/home/jkalliau/prgm/resvg-0.9.0`

and get the errormessage:
<pre><font color="#8AE234"><b>   Compiling</b></font> resvg-skia v0.9.0 (/home/jkalliau/prgm/resvg-0.9.0/bindings/resvg-skia)
<font color="#EF2929"><b>error</b></font><b>:</b> failed to run custom build command for `resvg-skia v0.9.0 (/home/jkalliau/prgm/resvg-0.9.0/bindings/resvg-skia)`

Caused by:
  process didn&apos;t exit successfully: `/home/jkalliau/prgm/resvg-0.9.0/target/release/build/resvg-skia-10f7874a6ef90454/build-script-build` (exit code: 1)
--- stdout
OPT_LEVEL = Some(&quot;3&quot;)
TARGET = Some(&quot;x86_64-unknown-linux-gnu&quot;)
HOST = Some(&quot;x86_64-unknown-linux-gnu&quot;)
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some(&quot;false&quot;)
CARGO_CFG_TARGET_FEATURE = Some(&quot;fxsr,sse,sse2&quot;)
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
running: &quot;c++&quot; &quot;-O3&quot; &quot;-ffunction-sections&quot; &quot;-fdata-sections&quot; &quot;-fPIC&quot; &quot;-m64&quot; &quot;-I&quot; &quot;cpp&quot; &quot;-I&quot; &quot;/home/jkalliau/prgm/resvg-0.9.0/skia&quot; &quot;-Wall&quot; &quot;-Wextra&quot; &quot;-std=c++14&quot; &quot;-o&quot; &quot;/home/jkalliau/prgm/resvg-0.9.0/target/release/build/resvg-skia-669f36be1e63f8e3/out/cpp/skia_capi.o&quot; &quot;-c&quot; &quot;cpp/skia_capi.cpp&quot;
cargo:warning=In file included from /home/jkalliau/prgm/resvg-0.9.0/skia/include/core/SkScalar.h:11,
cargo:warning=                 from /home/jkalliau/prgm/resvg-0.9.0/skia/include/private/SkFixed.h:11,
cargo:warning=                 from /home/jkalliau/prgm/resvg-0.9.0/skia/include/core/SkColorSpace.h:16,
cargo:warning=                 from /home/jkalliau/prgm/resvg-0.9.0/skia/include/core/SkImageInfo.h:11,
cargo:warning=                 from /home/jkalliau/prgm/resvg-0.9.0/skia/include/core/SkColor.h:11,
cargo:warning=                 from /home/jkalliau/prgm/resvg-0.9.0/skia/include/core/SkCanvas.h:13,
cargo:warning=                 from cpp/skia_capi.cpp:11:
cargo:warning=/home/jkalliau/prgm/resvg-0.9.0/skia/include/private/SkFloatingPoint.h:163:48: warning: ‘clang::no_sanitize’ scoped attribute directive ignored [-Wattributes]
cargo:warning= static inline float sk_double_to_float(double x) {
cargo:warning=                                                ^
cargo:warning=/home/jkalliau/prgm/resvg-0.9.0/skia/include/private/SkFloatingPoint.h:230:66: warning: ‘clang::no_sanitize’ scoped attribute directive ignored [-Wattributes]
cargo:warning= static inline float sk_ieee_float_divide(float numer, float denom) {
cargo:warning=                                                                  ^
cargo:warning=/home/jkalliau/prgm/resvg-0.9.0/skia/include/private/SkFloatingPoint.h:235:70: warning: ‘clang::no_sanitize’ scoped attribute directive ignored [-Wattributes]
cargo:warning= static inline double sk_ieee_double_divide(double numer, double denom) {
cargo:warning=                                                                      ^
cargo:warning=cpp/skia_capi.cpp: In function ‘void skiac_path_set_fill_type(skiac_path*, FillType)’:
cargo:warning=cpp/skia_capi.cpp:406:37: error: ‘FillType’ is not a member of ‘SkPath’
cargo:warning=     PATH_CAST-&gt;setFillType((SkPath::FillType)type);
cargo:warning=                                     ^~~~~~~~
cargo:warning=cpp/skia_capi.cpp:404:60: warning: unused parameter ‘type’ [-Wunused-parameter]
cargo:warning= void skiac_path_set_fill_type(skiac_path* c_path, FillType type)
cargo:warning=                                                   ~~~~~~~~~^~~~
exit code: 1

--- stderr

error occurred: Command &quot;c++&quot; &quot;-O3&quot; &quot;-ffunction-sections&quot; &quot;-fdata-sections&quot; &quot;-fPIC&quot; &quot;-m64&quot; &quot;-I&quot; &quot;cpp&quot; &quot;-I&quot; &quot;/home/jkalliau/prgm/resvg-0.9.0/skia&quot; &quot;-Wall&quot; &quot;-Wextra&quot; &quot;-std=c++14&quot; &quot;-o&quot; &quot;/home/jkalliau/prgm/resvg-0.9.0/target/release/build/resvg-skia-669f36be1e63f8e3/out/cpp/skia_capi.o&quot; &quot;-c&quot; &quot;cpp/skia_capi.cpp&quot; with args &quot;c++&quot; did not execute successfully (status code exit code: 1).

</pre>

**Comment by RazrFalcon** [comment]
You should not use Skia unless you are familiar with it. It's a pretty complex library.

The problem is that Skia doesn't have a stable API, so you must build a specific version. In our case it's m76. See [resvg-skia-ci-build](https://github.com/RazrFalcon/resvg-skia-ci-build) for details.

Anyway, look like I should update Skia bindings.
