### ISSUE TITLE
Invalid dashoffset in qt and raqote backends

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#227]
Rendering https://commons.wikimedia.org/wiki/File:Mamiya_645_Super_system.svg with two different backends leads to different dash-offset.

||pic|
|--|--|
|cairo|![Mamiya 645 Super system_cairo](https://user-images.githubusercontent.com/15687581/75174401-d1e95d00-5730-11ea-8030-136173755425.png)
|qt|![Mamiya 645 Super system_qt](https://user-images.githubusercontent.com/15687581/75174463-e7f71d80-5730-11ea-8fb4-6eda3f6738bf.png)|

see e.g. left upper corner the vertical short line

### Copyright

source: https://commons.wikimedia.org/wiki/File:Mamiya_645_Super_system.svg

author Eric Gaba

license https://creativecommons.org/licenses/by-sa/3.0

**Comment by RazrFalcon** [comment]
Hmm... interesting. Only qt and raqote backends are producing such results. All other backends and applications are correct.

**Comment by RazrFalcon** [comment]
- https://github.com/jrmuizel/raqote/issues/119
- https://bugreports.qt.io/browse/QTBUG-83048

**Comment by RazrFalcon** [comment]
There is nothing I can do from the resvg side, so I'm closing this.

**Comment by JoKalliauer** [comment]
@RazrFalcon  Since it is related to subpaths, maybe you can split path into seperate paths? (Do some pre-processing/svg-optimization)

**Comment by RazrFalcon** [comment]
Technically yes, but I will remove Qt support soon and raqote will be fixed too.
