### ISSUE TITLE
different desh-dencity

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#228]
Rendering https://commons.wikimedia.org/wiki/File:Grundriss_Burg_Hageneck.svg leads to different line-density

|r|re|
|---|---|
|![Grundriss Burg Hageneck_r](https://user-images.githubusercontent.com/15687581/75376741-d3ea2200-58d0-11ea-94f9-4a3e8c88ecd0.png)|![Grundriss Burg Hageneck_re](https://user-images.githubusercontent.com/15687581/75376748-d77da900-58d0-11ea-9937-5774b5ed9b6e.png)|

### Copyright
source: https://commons.wikimedia.org/wiki/File:Grundriss_Burg_Hageneck.svg

author: Sir Gawain

license: https://creativecommons.org/licenses/by-sa/4.0/deed.de

**Comment by RazrFalcon** [comment]
This is a bug of the old rsvg. 

Please, use the latest rsvg version in your tests and compare with chrome/firefox first.

**Comment by JoKalliauer** [comment]
> Please, use the latest rsvg version in your tests and compare with chrome/firefox first.

I have Ubtuntu 18.04 LTS so it is default is rsvg-convert version 2.40.21, installing newer ones leaded to problems (depends on cairo 1.16,...)

I think I will wait till April for Ubuntu 20.04 LTS and then update

**Comment by RazrFalcon** [comment]
>installing newer ones leaded to problems (depends on cairo 1.16,...)

Yes, I've also ran into this. Here is a workaround (edit paths and versions first):

```sh
cd cairo-src
./configure --prefix=/my_path/cairo-build-1.16
make 
make install
cd  librsvg-src
env PKG_CONFIG_PATH=/my_path/cairo-build-1.16/lib/pkgconfig ./configure --prefix=/my_path/librsvg-build-2.47 --enable-introspection=no --disable-pixbuf-loader
make 
make install
```

`my_path` can be replaced with any user path like `/home/name/` (do not use `~`).

And that's it. No need to install anything as root.
