### ISSUE TITLE
Invalid shape rendering in the Cairo backend

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#231]
[KK1.svg.txt](https://github.com/RazrFalcon/resvg/files/4263114/KK1.svg.txt)

![KK1_re](https://user-images.githubusercontent.com/15687581/75471053-f001c800-5991-11ea-9ecf-29c53a10c23a.png)

source https://commons.wikimedia.org/wiki/File:KK1.svg

author Tomasz Steifer

license https://creativecommons.org/licenses/by-sa/3.0/deed.de

**Comment by RazrFalcon** [comment]
Looks like a cairo bug. Other backends are fine.

**Comment by RazrFalcon** [comment]
cairo backend was removed.
