### ISSUE TITLE
optional PNG-file-size optimization

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#232]
The file-size of resvg is generally larger compared with inkscape or rsvg (same resolution)

let's take https://commons.wikimedia.org/wiki/File:Milky_Way_Arms_ssc2008-10.svg

|ink|rsvg|resvg|
|--|--|--|
|![Milky Way Arms ssc2008-10](https://user-images.githubusercontent.com/15687581/75471460-95b53700-5992-11ea-8495-4366c09b3220.png)|![Milky Way Arms ssc2008-10_r](https://user-images.githubusercontent.com/15687581/75471461-96e66400-5992-11ea-8498-9075dc79d023.png)|![Milky Way Arms ssc2008-10_re](https://user-images.githubusercontent.com/15687581/75471463-96e66400-5992-11ea-8c3c-a859ceb4ab1d.png)|
|1.012.430 bytes|900.220 bytes|1.215.919 bytes|

after lossless [PNG-Optimization](https://commons.wikimedia.org/wiki/User:JoKalliauer/Optimization#Lossless_Optimizing_PNG) with [optipng](http://optipng.sourceforge.net/) and [pngout](http://www.jonof.id.au/kenutils.html) 

|ink|rsvg|resvg|
|--|--|--|
|![Milky Way Arms ssc2008-10](https://user-images.githubusercontent.com/15687581/75471759-ed53a280-5992-11ea-87d4-c224f9984630.png) |![Milky Way Arms ssc2008-10_r](https://user-images.githubusercontent.com/15687581/75471761-edec3900-5992-11ea-9207-ff29849258c1.png)|![Milky Way Arms ssc2008-10_re](https://user-images.githubusercontent.com/15687581/75471763-ee84cf80-5992-11ea-8761-36c395f6d8a3.png)|
|820.135 bytes|810.734 bytes|812.131 bytes|

I know it increases processing time, but therefore it should be optional.

**Comment by RazrFalcon** [comment]
This is intentional. PNG compression is very slow. I will add an option later.

**Comment by JoKalliauer** [comment]
There are some fast PNG-optimziatiors, such as pingo which is 2 to 3 decimal Magnitudes (i.e. factor of 309 and a factor of 505 ) faster than PNGOUT or Optipng, see https://css-ig.net/png-tools-overview#compare

**Comment by RazrFalcon** [comment]
I will not use png optimizer. They are out of scope. I was talking about the default png compression.

**Comment by JoKalliauer** [comment]
> I will not use png optimizer. They are out of scope. I was talking about the default png compression.

@RazrFalcon  Imho some png-optimizers are open-source, why not allow an opt-in-feature (opt-in during install (mention that it is an external progam) and opt-in during rendering)?

**Comment by RazrFalcon** [comment]
Because this is an unnecessary bloat. This library renders SVG to PNG. That's it.
