### ISSUE TITLE
Invalid pattern offset in the Cairo backend

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#233]
[Provinzen kastilien.svg.txt](https://github.com/RazrFalcon/resvg/files/4263402/Provinzen.kastilien.svg.txt)

|ink|rsvg|resvg|
|-|-|-|
|![Provinzen kastilien](https://user-images.githubusercontent.com/15687581/75475575-5211fb80-5999-11ea-9c8c-ac8ab0d72d87.png)|![Provinzen kastilien_r](https://user-images.githubusercontent.com/15687581/75475579-52aa9200-5999-11ea-82dc-04873deb7388.png)|![Provinzen kastilien_re](https://user-images.githubusercontent.com/15687581/75475581-53432880-5999-11ea-840f-768735152839.png)|

source: https://commons.wikimedia.org/wiki/File:Provinzen_kastilien.svg

author
    Kastilien 1833.svg:
    España - División provincial y regional de 1833.svg: Miguillen
    derivative work: Marnal

license https://creativecommons.org/licenses/by/3.0/deed.de

**Comment by RazrFalcon** [comment]
Looks like a Cairo bug. Qt/Skia backend are no affected.

**Comment by RazrFalcon** [comment]
cairo backend was removed.
