### ISSUE TITLE
hairline crack rendering

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#234]
rendersvg [SilversmithBMP2SVGaccelerated-i-o.svg](https://upload.wikimedia.org/wikipedia/commons/5/52/Silversmith_BMP2SVG_accelerated-i-o.svg) [silver.png](https://user-images.githubusercontent.com/15687581/75478828-e3d03780-599e-11ea-961a-b4b02fd1ac8f.png) -w=3000

there should be any hair-line-cracks

![silver](https://user-images.githubusercontent.com/15687581/75478828-e3d03780-599e-11ea-961a-b4b02fd1ac8f.png)

source https://commons.wikimedia.org/wiki/File:Silversmith_BMP2SVG_accelerated-i-o.svg

author DancingPhilosopher

license https://creativecommons.org/licenses/by-sa/3.0/deed.de

**Comment by RazrFalcon** [comment]
Can you explain what is wrong?

**Comment by JoKalliauer** [comment]
There should not be any transparent spaces beteen pixels

![Zoom](https://user-images.githubusercontent.com/15687581/75491470-4e40a200-59b6-11ea-9dce-933a0bc6a5c0.png)

**Comment by RazrFalcon** [comment]
Why not? Other applications produce them too.

**Comment by JoKalliauer** [comment]
> Why not? Other applications produce them too.

Because there is zero space between the pixels read the file in an texteditor (4.4MB):

view-source:https://upload.wikimedia.org/wikipedia/commons/5/52/Silversmith_BMP2SVG_accelerated-i-o.svg

**Comment by RazrFalcon** [comment]
>Because there is zero space between the pixels

This is not how SVG works. Due to antialisaing, floats rounding and scaling it can produce whatever it wants.

Anyway, it's not a resvg bug, since this behavior depends on a 2D graphic library itself.

**Comment by JoKalliauer** [comment]
> Why not? Other applications produce them too.

According to https://gitlab.com/inkscape/inkscape/issues/928#note_279440484 Adobe Illustrator does not produce them.

**Comment by RazrFalcon** [comment]
Well, that's the point. The result depends on a rendering library. This out of scope of resvg.
