### ISSUE TITLE
Allow quoted FuncIRI

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#235]
[SVG Gradient.svg.txt](https://github.com/RazrFalcon/resvg/files/4263678/SVG.Gradient.svg.txt)

|ink|resvg|
|--|--|
|![SVG Gradient](https://user-images.githubusercontent.com/15687581/75479637-25151700-59a0-11ea-8492-4722660923e9.png)|![SVG Gradient_re](https://user-images.githubusercontent.com/15687581/75479641-25adad80-59a0-11ea-989c-8424dec1318e.png)|

source https://commons.wikimedia.org/wiki/File:SVG_Gradient.svg

author Glrx

license https://creativecommons.org/publicdomain/zero/1.0/deed.de

**Comment by RazrFalcon** [comment]
`fill="url('#gfuser')"` isn't allowed now. Can't find a part of the spec the specifies this.

**Comment by JoKalliauer** [comment]
> 
> 
> `fill="url('#gfuser')"` isn't allowed now. Can't find the part of the spec the specifies this.

it should be `fill="url(#gfuser)"` instead? similar to 
- https://www.w3schools.com/graphics/svg_grad_linear.asp
- https://www.w3schools.com/graphics/svg_grad_linear.asp

**Comment by RazrFalcon** [comment]
I've never seen such a format. But since other apps are supporting it, I will implement it too.

**Comment by RazrFalcon** [comment]
https://github.com/RazrFalcon/svgtypes/issues/4

**Comment by RazrFalcon** [comment]
As always, nothing is as easy as it looks: https://github.com/w3c/svgwg/issues/781

**Comment by LaurenzV** [comment]
Seems like this issue can be closed? At least the SVG renders fine for me now.

**Comment by RazrFalcon** [comment]
Yep, missed this one.

**Comment by JoKalliauer** [comment]
confirm fix
