### ISSUE TITLE
Several text rendering issues

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#236]
[SVG Test TextAlign.svg.txt](https://github.com/RazrFalcon/resvg/files/4263783/SVG.Test.TextAlign.svg.txt)

|ink|resvg|rsvg|
|--|--|--|
|![SVG Test TextAlign](https://user-images.githubusercontent.com/15687581/75481374-3e6b9280-59a3-11ea-9448-571ffdd7fbd9.png)|![SVG Test TextAlign_re](https://user-images.githubusercontent.com/15687581/75481377-3f042900-59a3-11ea-8769-c299cb302036.png)|![SVG Test TextAlign_rsvg](https://user-images.githubusercontent.com/15687581/75481379-3f042900-59a3-11ea-8a39-31baf27ed73e.png)

mistakes

- Try text on path below (right upper corner)
- text-anchor=" for left-to-right-text
- Chinese(whatsoever) verticallyc written is too high

source: https://commons.wikimedia.org/wiki/File:SVG_Test_TextAlign.svg

author Glrx

license: https://creativecommons.org/licenses/by-sa/3.0/deed.de

**Comment by RazrFalcon** [comment]
>Try text on path below (right upper corner)

What is wrong with it?

>text-anchor=" for left-to-right-text

This is an undefined behavior. We can do whatever we want.

>Chinese(whatsoever) verticallyc written is too high

`dominant-baseline` isn't supported. #119

**Comment by JoKalliauer** [comment]
>What is wrong with it?

 dominant-baseline="central" (ok thats #119 )

> Chinese(whatsoever) verticallyc written is too high

in line 95 I do not see any `dominant-baseline`

|lib|pic|
|--|--|
|resvg|![SVG Test TextAlign_re](https://user-images.githubusercontent.com/15687581/75481377-3f042900-59a3-11ea-8769-c299cb302036.png)|
|svg|![svg](https://upload.wikimedia.org/wikipedia/commons/9/9b/SVG_Test_TextAlign.svg)|

**Comment by RazrFalcon** [comment]
`alignment-baseline` isn't supported also. I've created #242
