### ISSUE TITLE
Should newlines be remove or converted into spaces?

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#237]
![SVG_test_text_tspan_ws.svg](https://gitlab.com/inkscape/inbox/uploads/44bdbc3aa9300f9cd6560a135c26d3e0/SVG_test_text_tspan_ws.svg)

|ink|resvg|rsvg|
|--|--|--|
|![SVG test text tspan ws](https://user-images.githubusercontent.com/15687581/75482023-4972f280-59a4-11ea-9244-3a8b47be8825.png)|![SVG test text tspan ws_re](https://user-images.githubusercontent.com/15687581/75482026-4a0b8900-59a4-11ea-9db3-c347d01927d5.png)|![SVG test text tspan ws_rsvg](https://user-images.githubusercontent.com/15687581/75482027-4a0b8900-59a4-11ea-9e3e-7a85c344bff0.png)|

imho nobody renders correct (not Chrome and not FF)

source https://commons.wikimedia.org/wiki/File:SVG_test_text_tspan_ws.svg

author user: Sameboat (slightly modified Perhelion)

license Public Domain

**Comment by JoKalliauer** [comment]
Sorry I think resvg renders correct

**Comment by RazrFalcon** [comment]
The latest rsvg produces the same results as resvg. Firefox and Batik too. So resvg is correct.

**Comment by JoKalliauer** [comment]
Linespaces should not lead to spaces see https://gitlab.com/inkscape/inbox/issues/1914#note_295975972

 https://www.w3.org/TR/SVG11/text.html#WhiteSpace
> First, it will remove all newline characters.

So the line with (only line-break - default) should not have any spaces

**Comment by RazrFalcon** [comment]
This is [a very hard topic](https://github.com/RazrFalcon/resvg/blob/933c927fed2f2d95b93b7b8e043331f83f0d3310/usvg/src/svgtree/parse.rs#L1078). resvg mimics Chrome's behavior intentionally.

Looks like we should definitely remove new lines, and not convert them to spaces. But I don't remember is this was done intentionally. 
It will require some testing.

PS: not sure about Inkscape 1.1, but 0.92 has an awful text support.

**Comment by JoKalliauer** [comment]
same issue with https://commons.wikimedia.org/wiki/File:Mathematical_implication_diagram-alt.svg

**Comment by RazrFalcon** [comment]
Removing newlines produces an invalid result too. Essentially, this is an undefined behavior and everyone is doing whatever they want. And since there is no correct result - it cannot be fixed. So I'm closing it.
