### ISSUE TITLE
Support CSS specificity

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#238]
[SVG Text Chunk.svg.txt](https://github.com/RazrFalcon/resvg/files/4263876/SVG.Text.Chunk.svg.txt)

|ink|rsvg|resvg|
|--|--|--|
|![SVG Text Chunk](https://user-images.githubusercontent.com/15687581/75482795-ca7eb980-59a5-11ea-82ea-e32301a0ceb3.png)|![SVG Text Chunk_r](https://user-images.githubusercontent.com/15687581/75482796-cb175000-59a5-11ea-9716-2a89906f8426.png)|![SVG Text Chunk_re](https://user-images.githubusercontent.com/15687581/75482797-cbafe680-59a5-11ea-8f4d-299d1d659997.png)|

According to FF headline should be black

source https://commons.wikimedia.org/wiki/File:SVG_Text_Chunk.svg

author Glrx and JoKalliauer

license https://creativecommons.org/licenses/by-sa/3.0/deed.de

**Comment by RazrFalcon** [comment]
Yes, `simplecss` doesn't support CSS specificity.

**Comment by RazrFalcon** [comment]
https://github.com/RazrFalcon/simplecss/issues/5
