### ISSUE TITLE
thin lines not rendered at all

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#239]
#### svg-File
![T199618.svg](https://gitlab.com/inkscape/inbox/uploads/0f3f3fe7baeb2e76d4efc7d4053a9f93/T199618.svg)

#### Rendering
![T199618_re](https://user-images.githubusercontent.com/15687581/75483762-c784c880-59a7-11ea-9b98-14950b7486d2.png)

#### Copyright

source: https://commons.wikimedia.org/wiki/File:T199618.svg

author [The Oxygen Team](https://github.com/KDE/oxygen-icons/blob/master/AUTHORS), [KDE](https://techbase.kde.org/Projects/Oxygen/Licensing);

license https://www.gnu.org/licenses/lgpl-3.0.html

**Comment by RazrFalcon** [comment]
This a backend-specific behavior. I cannon control it.
