### ISSUE TITLE
complety wrong colour

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#240]
#### SVG:
![Tradex Logo Wiki Mesa de trabajo 1.svg](https://upload.wikimedia.org/wikipedia/commons/8/86/Tradex_Logo_Wiki_Mesa_de_trabajo_1.svg)

#### png:
|ink|resvg|
|-|-|
|![Tradex Logo Wiki Mesa de trabajo 1](https://user-images.githubusercontent.com/15687581/75484127-75907280-59a8-11ea-9bc9-290fc1d8c051.png)|![Tradex Logo Wiki Mesa de trabajo 1_re](https://user-images.githubusercontent.com/15687581/75484143-7a552680-59a8-11ea-9535-4c6da66b7ceb.png)|

#### copyright

source https://commons.wikimedia.org/wiki/File:Tradex_Logo_Wiki_Mesa_de_trabajo_1.svg

author Jeshuajw

license https://creativecommons.org/licenses/by-sa/4.0/deed.de

**Comment by RazrFalcon** [comment]
The `mix-blend-mode` CSS property is not part of the SVG spec, so resvg is correct.
