### ISSUE TITLE
Support alignment-baseline

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#242]

**Comment by Joeldorne** [comment]
Looking forward to this! When do you think it will be ready?

**Comment by RazrFalcon** [comment]
No idea.

**Comment by gmeeker** [comment]
This would be really useful because Chrome supports it.  The tests just mention "hanging" but I'm trying to use other values like "central" and "text-before-edge".
I've posted a bounty:
https://app.bountysource.com/issues/89281644-support-alignment-baseline

Here's a file that renders differently in resvg compared to Chrome:
![legend](https://user-images.githubusercontent.com/6538028/202018467-bb5f6625-2a44-487b-8c2e-2cca30c63880.svg)

**Comment by RazrFalcon** [comment]
$500? Really? I'm not sure how hard it would be to implement, but that's a lot.

**Comment by gmeeker** [comment]
Oh, it's my first bounty. It's worth it to us so we don't have to find a workaround.  Happy to support resvg.  It's a great project.

**Comment by RazrFalcon** [comment]
Well, if you want to sponsor me directly, there is no need for BountySource. I'm not even sure if it works in my country.

As for the bug, it could take from 2 days up to a week. I haven't looked into it much. Half of the time will be spent on writing tests anyway. And will probably require adding `BASE` and `bsln` tables support to `ttf-parser`.

Not sure if someone else would be able to figure it all out. There is a reason why it's not implemented.
I might look into it on the weekend, but no promises. Very busy.

**Comment by RazrFalcon** [comment]
@gmeeker Added an absolute minimal support ([54489e03b73b6bc83957dfe7331](https://github.com/RazrFalcon/resvg/commit/93cc39c782c8054489e03b73b6bc83957dfe7331)).

It's very simple, but should be as good as Chrome since it does't really implement this property properly either.
You can find more in-depth overview [here](https://github.com/RazrFalcon/resvg/blob/93cc39c782c8054489e03b73b6bc83957dfe7331/usvg/src/text/fontdb_ext.rs#L196).

Currently, only a horizontal layout is supported. Vertical should be rewritten from scratch...

Technically, I should also take the current text script into account, but doesn't look like Chrome does it and it would be even more complicated.

Either way, the current implementation should be good enough for your use case and more will come later. Including `text-before-edge` and `dominant-baseline`.

**Comment by RazrFalcon** [comment]
Added `dominant-baseline` support as well.

And by "added" I mean that resvg produces the same output as Chrome. Because Chrome, Firefox and Safari all produce different output when you start mixing `dominant-baseline` and `alignment-baseline`.
Baseline support in general is pretty tragic across all SVG apps: https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html#a-dominant-baseline

**Comment by RazrFalcon** [comment]
I'm closing this in favor of #558 and #559
