### ISSUE TITLE
Unspecified feBlend behavior with in2=BackgroundImage

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#243]
|svg-------------------|ink|rsvg|resvg|
|-|-|-|-|
|![svg](https://upload.wikimedia.org/wikipedia/commons/7/79/Crystal128-contents2.svg)|![Crystal128-contents2](https://user-images.githubusercontent.com/15687581/75584215-8a840900-5a6f-11ea-8f2b-a867104044b2.png)|![Crystal128-contents2_r](https://user-images.githubusercontent.com/15687581/75584216-8b1c9f80-5a6f-11ea-9157-3bdb5313e31f.png)|![Crystal128-contents2_re](https://user-images.githubusercontent.com/15687581/75584217-8b1c9f80-5a6f-11ea-9aba-aa779520eb71.png)|

source https://commons.wikimedia.org/wiki/File:Crystal128-contents2.svg

author Everaldo Coelho (YellowIcon); All Crystal icons were posted by the author as LGPL on kde-look, the SVG version in various KDE packages;

license https://www.gnu.org/licenses/lgpl-3.0.html

**Comment by RazrFalcon** [comment]
Literally everyone is producing different results:

![Crystal128-contents2](https://user-images.githubusercontent.com/725494/75598728-bec6ec00-5aa6-11ea-8868-e731c8f3c530.png)

1. `mix-blend-mode` is not part of the SVG 1.1 spec.
1. Chrome and Firefox doesn't support `BackgroundImage`.

So it's hard to tell how it actually should be rendered. I will leave it open for now.

**Comment by RazrFalcon** [comment]
`BackgroundImage` is deprecated. Out of scope.
