### ISSUE TITLE
radialGradient

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#248]
|lib|pic|
|-|-|
|svg|![svg](https://upload.wikimedia.org/wikipedia/commons/6/6c/LibrsvgBug_T193942.svg)
|ink|![LibrsvgBug T193942](https://user-images.githubusercontent.com/15687581/75587176-33cdfd80-5a76-11ea-91b9-77ab636150aa.png)
|resvg|![LibrsvgBug T193942_resvg](https://user-images.githubusercontent.com/15687581/75587185-37fa1b00-5a76-11ea-905a-f08a07fc981a.png)
|rsvg|![LibrsvgBug T193942_rsvg](https://user-images.githubusercontent.com/15687581/75587189-3b8da200-5a76-11ea-9d7d-0ac0892797d7.png)

I assume firefox renders correct (I use firefox as default browser)

source https://commons.wikimedia.org/wiki/File:LibrsvgBug_T193942.svg

author Tomasz Steifer and JoKalliauer

license https://creativecommons.org/licenses/by-sa/3.0/deed.de

**Comment by RazrFalcon** [comment]
This is a Cairo bug.

![LibrsvgBug_T193942](https://user-images.githubusercontent.com/725494/75598143-5413b180-5aa2-11ea-8de9-85a3e0b4d0ea.png)

I plan to drop the cairo and Qt support anyway, so this will not be a problem in the future.

**Comment by JoKalliauer** [comment]
Can confirm the problem is fixed.
