### ISSUE TITLE
Invalid textPath placement

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#249]
#### What happened?
|lib|pic|
|-|-|
|svg|![svg](https://upload.wikimedia.org/wikipedia/commons/4/42/Manfeild_Autocourse_track_map_%28New_Zealand%29.svg)
|ink|![Manfeild Autocourse track map (New Zealand)](https://user-images.githubusercontent.com/15687581/75587721-662c2a80-5a77-11ea-97d0-45810e331419.png)
|resvg|![Manfeild Autocourse track map (New Zealand)_resvg](https://user-images.githubusercontent.com/15687581/75587731-6a584800-5a77-11ea-91db-5acdfe22740b.png)
|rsvg|![Manfeild Autocourse track map (New Zealand)_rsvg](https://user-images.githubusercontent.com/15687581/75587735-6d533880-5a77-11ea-8aef-4e456a8892a0.png)

#### What should have happened?
- Dunlop Corner is missplaced
- gray curve at "Chris amon Straight" looks strage

#### Copyright

source https://commons.wikimedia.org/wiki/File:Manfeild_Autocourse_track_map_(New_Zealand).svg

author Will Pittenger

license https://creativecommons.org/licenses/by-sa/3.0/deed.de

**Comment by RazrFalcon** [comment]
Can confirm.

By the way, Firefox doesn't render "Dunlop Corner" at all.

**Comment by JoKalliauer** [comment]
fixed in resvg 0.14

**Comment by RazrFalcon** [comment]
Good. Thanks.
