### ISSUE TITLE
Processing of invalid gradientTransform

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#251]
#### What happened?
|lib|pic|
|-|-|
|svg|![svg](https://upload.wikimedia.org/wikipedia/commons/9/96/SVG_edge_case_-_zero_scale_gradient.svg)
|ink|![SVG edge case - zero scale gradient](https://user-images.githubusercontent.com/15687581/75588459-fdde4880-5a78-11ea-98d7-fc2656ecd25c.png)
|resvg|![SVG edge case - zero scale gradient_resvg](https://user-images.githubusercontent.com/15687581/75588465-0171cf80-5a79-11ea-8eeb-d11f4f52fdd1.png)
|rsvg|![SVG edge case - zero scale gradient_rsvg](https://user-images.githubusercontent.com/15687581/75588467-046cc000-5a79-11ea-9f8d-8947dfc329d3.png)

#### What should have happened?
 - I assume the middle square should not be rendered at all (as firefox)

#### Copyright

source https://commons.wikimedia.org/wiki/File:SVG_edge_case_-_zero_scale_gradient.svg

author TilmannR

license Public Domain

**Comment by RazrFalcon** [comment]
An invalid `gradientTransform` is an undefined behavior. We can do whatever we want. `resvg`/`rsvg` simply skips the `gradientTransform`. Chrome and Inkscape are keeping only the last stop. Firefox ignores the element completely. And Batik crashes.

**Comment by RazrFalcon** [comment]
PS: As you may noticed, an undefined behavior is a common theme in the SVG. You can't even imagine how many things are not defined. The resvg test suite has like 50 test files with UB. I've even plan to create a list of all undefined I know.

**Comment by JoKalliauer** [comment]
is gradientTransform="scale(0)" invalid ? 

inkscape assumes something different:
https://gitlab.com/inkscape/inbox/issues/1928#note_296375486

**Comment by RazrFalcon** [comment]
>the entire shape is rendered in the color of the second stop

But why? Spec doesn't specify this. I mean, this is how it rendered by other applications:

![SVG_edge_case_-_zero_scale_gradient](https://user-images.githubusercontent.com/725494/75603457-239a3a80-5ad7-11ea-954c-cb751cde0900.png)

Given how different the results are I'm not sure we can interpreter the spec this way.

**Comment by JoKalliauer** [comment]
> But why?

Because it is the [limes](https://en.wikipedia.org/wiki/Limit_of_a_function) of x to zero in gradientTransform="scale(x)"

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="-20 -20 40 40" xmlns="http://www.w3.org/2000/svg">
	<linearGradient id="a" gradientTransform="scale(0)">
		<stop stop-color="#00f" offset="0"/>
		<stop stop-color="#ff0" offset="1"/>
	</linearGradient>
	<rect x="-29" y="-20" width="40" height="40" fill="url(#a)"/>
</svg>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="-20 -20 40 40" xmlns="http://www.w3.org/2000/svg">
	<linearGradient id="a" gradientTransform="scale(0.1)">
		<stop stop-color="#00f" offset="0"/>
		<stop stop-color="#ff0" offset="1"/>
	</linearGradient>
	<rect x="-20" y="-20" width="40" height="40" fill="url(#a)"/>
</svg>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="-20 -20 40 40" xmlns="http://www.w3.org/2000/svg">
	<linearGradient id="a" gradientTransform="scale(1)">
		<stop stop-color="#00f" offset="0"/>
		<stop stop-color="#ff0" offset="1"/>
	</linearGradient>
	<rect x="-20" y="-20" width="40" height="40" fill="url(#a)"/>
</svg>
```

**Comment by RazrFalcon** [comment]
Limit? This is an affine transform. And 0,0,0,0,0,0 considered invalid.
