### ISSUE TITLE
Invalid character spacing on a specific textPath

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#255]
#### What happened?
|lib|pic|
|-|-|
|svg|![](https://upload.wikimedia.org/wikipedia/commons/b/b5/Hidrograf%C3%ADa_Galicia_Cunca_Mari%C3%B1a_Oriental_en.svg)
|ink|![Hidrografía Galicia Cunca Mariña Oriental en](https://user-images.githubusercontent.com/15687581/75592269-2880cf00-5a82-11ea-982f-84a97200ad0c.png)
|resvg|![Hidrografía Galicia Cunca Mariña Oriental en_resvg](https://user-images.githubusercontent.com/15687581/75592280-2b7bbf80-5a82-11ea-853f-00183662ede9.png)

#### What should have happened?
 - letter distance seems to be strange at "Rio of Fox" (left edge)

#### Copyright

source https://commons.wikimedia.org/wiki/File:Hidrograf%C3%ADa_Galicia_Cunca_Mari%C3%B1a_Oriental_en.svg

author Iago Casabiell González

license https://creativecommons.org/licenses/by-sa/4.0/deed.de

#### Version and Operating System:

- Inkscape Version: 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21
- Operating System: Ubuntu 18.04

**Comment by RazrFalcon** [comment]
Yes, this is a `textPath` rendering bug.

**Comment by JoKalliauer** [comment]
same with ![](https://upload.wikimedia.org/wikipedia/commons/a/a2/GHCS_JTTtree.svg)

### INkscape
![GHCS JTTtree](https://user-images.githubusercontent.com/15687581/75813387-3723fa80-5d90-11ea-92c9-8468a9921763.png)

### resvg
![GHCS JTTtree_resvg](https://user-images.githubusercontent.com/15687581/75813394-3be8ae80-5d90-11ea-946f-18f09c6cf735.png)

### vdiff
![Screenshot from 2020-03-03 20-47-25](https://user-images.githubusercontent.com/15687581/75813459-4f941500-5d90-11ea-8df8-41df600655e4.png)

**Comment by chubei-oppen** [comment]
Hi, I'm running into this bug with a simple textPath (an ellipse). I'm trying to fix this special case temporarily. Could you kindly point out the relevant code? I read usvg and found https://github.com/RazrFalcon/resvg/blob/7b26adbcc9698dcca687214c84d216794f60a5be/usvg/src/convert/text/shaper.rs#L438 suspicious.

**Comment by chubei-oppen** [comment]
https://github.com/RazrFalcon/resvg/blob/7b26adbcc9698dcca687214c84d216794f60a5be/usvg/src/convert/text/shaper.rs#L666
For my problem, the root cause seems to be this line. Because arc length doesn't generally vary linearly with the curve parameter.

**Comment by RazrFalcon** [comment]
@chubei-oppen I haven't looked into this bug, so I don't know the reason. You're on the right path, it's somewhere in the `shaper.rs`.

**Comment by chubei-oppen** [comment]
@RazrFalcon I came up with a somewhat ugly solution in #326. Some code is copied from kurbo because that computation can be reused.

Whenver we need to map arc length to curve parameter, we subdivide the bezier curve until the start point or the end point of the subdivided curve is within accuracy of the target arc length. 
It takes `O(log(L / a))` time for a single OutlinedCluster, where `L` is the arc length, `a` is our desired accuracy.
Subdivided curves are cached in a segment tree.

It works well enough for me as my use case is not very time sensitive.

If you see this as a plausible algorithm I can add proper documentation, tests and fix code styles (may need your guide here because I'm new to Rust), otherwise I'll keep it in my fork.

**Comment by RazrFalcon** [comment]
@chubei-oppen This is a very complicated algorithm for such a trivial task. I'm not saying that it's wrong, but maybe it should be implemented on the `kurbo` side?

Also, allocating a tree is fairly expensive, so maybe `kurbo` authors will came up with a better solution.

**Comment by chubei-oppen** [comment]
@RazrFalcon `kurbo` has [inv_arclen](https://docs.rs/kurbo/0.7.0/kurbo/trait.ParamCurveArclen.html?search=#method.inv_arclen), which uses binary search. I'm not an expert on Bezier curves and don't know if its performace is acceptable. Do you want to see a what a pull request using `inv_arclen` looks like?

**Comment by RazrFalcon** [comment]
If it produces the expected result - sure.

**Comment by chubei-oppen** [comment]
@RazrFalcon `inv_arclen` has its own [bug](https://github.com/linebender/kurbo/issues/153). I guess I'll wait until that's fixed.
