### ISSUE TITLE
path with double nodes

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#256]
#### What happened?
|lib|pic|
|-|-|
|svg|![](https://upload.wikimedia.org/wikipedia/commons/7/71/LibrsvgBug_T193300.svg)
|resvg|![LibrsvgBug T193300_resvg](https://user-images.githubusercontent.com/15687581/75593235-02a8f980-5a85-11ea-96dd-db0c0a1eb256.png)

#### What should have happened?
 - Firefox renders the whole path, resvg doesn't

#### Copyright

source https://commons.wikimedia.org/wiki/File:LibrsvgBug_T193300.svg

author PerryPlanet, Johannes Kalliauer

license https://creativecommons.org/licenses/by-sa/4.0/

#### Version and Operating System:

- Inkscape Version: 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21
- Operating System: Ubuntu 18.04

**Comment by RazrFalcon** [comment]
This is a Cairo bug. I can't do anything about it.

![LibrsvgBug_T193300](https://user-images.githubusercontent.com/725494/75597556-c97d8300-5a9e-11ea-9202-8496c583566f.png)

**Comment by JoKalliauer** [comment]
This issue seems to be solved

![LibrsvgBug_T193300_rendersvg](https://user-images.githubusercontent.com/15687581/113041857-c02b8200-919a-11eb-9146-0972cf05afd4.png)
