### ISSUE TITLE
Endless loop during enable-background processing

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#257]
Rendering https://commons.wikimedia.org/wiki/File:Dojikko2.3.svg did not terminate after >2days

|lib|pic|
|-|-|
|svg|![](https://upload.wikimedia.org/wikipedia/commons/3/36/Dojikko2.3.svg)
|resvg >2days| no image |
|rsvg 13,33min|![Dojikko2 3_rsvg](https://user-images.githubusercontent.com/15687581/75699479-d4a7fd00-5cb0-11ea-9d9b-b178f3808908.png)|
|ink 9,83min|![Dojikko2 3](https://user-images.githubusercontent.com/15687581/75699534-ed181780-5cb0-11ea-8b99-a7358bddc69e.png)|

**Comment by RazrFalcon** [comment]
Yes, that's a bug.

PS: rendering this image without filters and clip-paths makes it an abstract painting :smile: 

![out](https://user-images.githubusercontent.com/725494/75741500-72341880-5d13-11ea-8581-d3b64e5c3ea4.jpg)

**Comment by RazrFalcon** [comment]
It's not even an endless loop, technically. It will finish eventually, but it will take a lot of time. For now, I'm not sure how to fix it.

**Comment by JoKalliauer** [comment]
Do you know which features causes (or might cause) the problem, I would like to make a workaround for [resvg_Issues_details](https://commons.wikimedia.org/wiki/User:JoKalliauer/SVG_test_suites/resvg_Issues_details) (embedded in [User:JoKalliauer/SVG_test_suites](https://commons.wikimedia.org/wiki/User:JoKalliauer/SVG_test_suites) )

**Comment by RazrFalcon** [comment]
This is because `in="BackgroundImage"` in filters. `BackgroundImage` doesn't supported by browsers and many other apps, so they work faster by not doing anything. But resvg has to rerender the `BackgroundImage` for each filter, which takes a lot of time. To fix it, I have to cache those images, but this a bit more complicated and will heavily increase memory usage.

In the end of the day I simply don't have enough time to fix it right now.

**Comment by JoKalliauer** [comment]
> This is because `in="BackgroundImage"` in filters. `BackgroundImage` doesn't supported by browsers and many other apps, so they work faster by not doing anything. But resvg has to rerender the `BackgroundImage` for each filter, which takes a lot of time. To fix it, I have to cache those images, but this a bit more complicated and will heavily increase memory usage.
> 
> In the end of the day I simply don't have enough time to fix it right now.

Thanks that's the answer I requested for creating https://commons.wikimedia.org/wiki/File:Dojikko2.3_simplified.svg, which renders within few minutes.

PS: I might was unclear : I wanted to make a workaround (simplification) on svg-side not on resvg (I know too less coding)

**Comment by RazrFalcon** [comment]
"Fixed" by removing `enable-background` feature altogether. It was deprecated in SVG 2 anyway.
