### ISSUE TITLE
Pattern-rendering

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#259]
#### What happened?
|lib|pic|
|-|-|
|svg|![](https://upload.wikimedia.org/wikipedia/commons/0/08/Coa_Frankfurt-H%C3%B6chst_Test.svg)
|ink|![Coa Frankfurt-Höchst Test](https://user-images.githubusercontent.com/15687581/75718078-a3402900-5cd2-11ea-8a91-ef8809beed4f.png)
|resvg|![Coa Frankfurt-Höchst Test_resvg](https://user-images.githubusercontent.com/15687581/75718086-a63b1980-5cd2-11ea-9dda-f787818a2b56.png)
|rsvg|![Coa Frankfurt-Höchst Test_rsvg](https://user-images.githubusercontent.com/15687581/75718101-a9360a00-5cd2-11ea-9a17-089d2b33b19a.png)

#### What should have happened?
 - as in chrome
![Screenshot from 2020-03-02 22-05-44](https://user-images.githubusercontent.com/15687581/75718135-b3f09f00-5cd2-11ea-94e8-92ec7cccab46.png)

#### Copyright

source https://commons.wikimedia.org/wiki/File:Coa_Frankfurt-H%C3%B6chst_Test.svg

author  T.h.

license Public Domain

#### Version and Operating System:

- Inkscape Version: 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21
- Operating System: Ubuntu 18.04

**Comment by RazrFalcon** [comment]
The problem is that the image tries to use a 1x1 px pattern, which is way too small. And because of anti-aliasing it becomes a bit transparent. Basically, this is a highly unrealistic edge-case.

Not sure how to fix this. I guess we can say that image itself is malformed.
