### ISSUE TITLE
Add some badges to README.md

### ISSUE THREAD

**Issue by suhr** [RazrFalcon/resvg#26]
See https://shields.io/ and https://docs.rs/about

Badges to crates.io and docs.rs would be very nice to have.

**Comment by RazrFalcon** [comment]
I don't see a point in that. Link to the docs - maybe, but other...

**Comment by suhr** [comment]
It is handy. Also, it clearly shows that there's indeed a crate on crates.io and some docs.

**Comment by RazrFalcon** [comment]
I will think about it.
