### ISSUE TITLE
filter containing 22 subparts not rendered on small thumbs

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#268]
#### What happened?
|lib|pic|
|-|-|
|svg|![svg](https://upload.wikimedia.org/wikipedia/commons/8/89/Sun_disc_standard_1320222-red.svg)
|ink|![Sun disc standard 1320222-red](https://user-images.githubusercontent.com/15687581/76022617-c7487800-5f27-11ea-9410-1ff81fb9dfab.png)
|resvg|![Sun disc standard 1320222-red_resvg](https://user-images.githubusercontent.com/15687581/76022632-cb749580-5f27-11ea-9907-bea30f6ef571.png)
|rsvg|![Sun disc standard 1320222-red_rsvg](https://user-images.githubusercontent.com/15687581/76022642-cf081c80-5f27-11ea-967b-439712e3fe36.png)

#### Optimized svg
[SunCSOSCOCSv0_p.svg.txt](https://github.com/RazrFalcon/resvg/files/4295023/SunCSOSCOCSv0_p.svg.txt)

![Screenshot from 2020-03-05 21-26-04](https://user-images.githubusercontent.com/15687581/76022732-ffe85180-5f27-11ea-8d10-ab394f396e5a.png)

#### What should have happened?
 - resvg should render the same in vdiff

#### Copyright

source https://commons.wikimedia.org/wiki/File:Sun_disc_standard_1320222-red.svg

#### Version and Operating System:

- Inkscape Version: 0.92.4 or 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21
- Operating System: Ubuntu 18.04

```xml
 <filter id="a" x="-.25" y="-.25" width="1.5" height="1.5" color-interpolation-filters="sRGB">
  <feGaussianBlur in="SourceAlpha" result="result91" stdDeviation=".01"/>
  <feComposite in="SourceGraphic" in2="result91" operator="in" result="fbSourceGraphic"/>
  <feColorMatrix in="fbSourceGraphic" result="fbSourceGraphicAlpha" type="saturate" values="1"/>
  <feGaussianBlur in="fbSourceGraphic" result="result1" stdDeviation=".01"/>
  <feTurbulence baseFrequency=".04" numOctaves="4" result="result0" seed="20" type="fractalNoise"/>
  <feDisplacementMap in="result1" in2="result0" result="result2" scale="30" xChannelSelector="R" yChannelSelector="G"/>
  <feColorMatrix result="result3" type="saturate" values="1"/>
  <feGaussianBlur in="fbSourceGraphic" result="result4" stdDeviation=".01"/>
  <feComposite in="result4" in2="result3" operator="atop" result="fbSourceGraphic"/>
  <feColorMatrix in="fbSourceGraphic" result="fbSourceGraphicAlpha" values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"/>
  <feGaussianBlur in="fbSourceGraphic" result="result0" stdDeviation="1.5"/>
  <feTurbulence baseFrequency=".02" numOctaves="8" result="result1" seed="20" type="fractalNoise"/>
  <feComposite in="result0" in2="result1" operator="out" result="result2"/>
  <feSpecularLighting lighting-color="#dfbc10" in="result2" result="result4" specularConstant="2" specularExponent="30" surfaceScale="2.5">
   <feDistantLight azimuth="225" elevation="62"/>
  </feSpecularLighting>
  <feComposite in="result4" in2="result2" operator="atop" result="result92"/>
  <feBlend in2="result92" mode="multiply" result="fbSourceGraphic"/>
  <feColorMatrix in="fbSourceGraphic" result="fbSourceGraphicAlpha" values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"/>
  <feGaussianBlur in="fbSourceGraphicAlpha" result="blur" stdDeviation="30"/>
  <feColorMatrix result="bluralpha" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0"/>
  <feOffset dx="20" dy="20" in="bluralpha" result="offsetBlur"/>
  <feMerge>
   <feMergeNode in="offsetBlur"/>
   <feMergeNode in="fbSourceGraphic"/>
  </feMerge>
 </filter>
```

source: https://commons.wikimedia.org/wiki/File:Sun_disc_standard_1320222-red.svg

**Comment by JoKalliauer** [comment]
The old issue seems to be solved:
![JK](https://user-images.githubusercontent.com/15687581/113041078-d1c05a00-9199-11eb-9c6b-eb8aae71fba1.png)



However this image contains another issue:

|svg|resvg|librsvg|Inkscape|batik|
|----|----|----|----|----|
|[svg](https://github.com/RazrFalcon/resvg/files/6231496/Sun_disc_standard_1320222-red.svg.txt)|![Sun_disc_standard_1320222-red_rendersvg](https://user-images.githubusercontent.com/15687581/113040533-2dd6ae80-9199-11eb-89bf-c8fb9fa11fd9.png)|![Sun_disc_standard_1320222-red_librsvg](https://user-images.githubusercontent.com/15687581/113040524-2911fa80-9199-11eb-9964-1178a795b3b2.png)|![Sun_disc_standard_1320222-red_Inkscape](https://user-images.githubusercontent.com/15687581/113040498-21525600-9199-11eb-9945-e52770040a20.png)|![Sun_disc_standard_1320222-red_batik](https://user-images.githubusercontent.com/15687581/113040488-1d263880-9199-11eb-9c9c-8bd362f2ece9.png)|

it seems that the path has on offset, compared to librsvg/batik/Inkscape. (change from one file to the next one)

**Comment by RazrFalcon** [comment]
Yes, looks like it was.

**Comment by JoKalliauer** [comment]
The orriginal isue is resolved, however there seems to be an offset of the pattern/filters/path (I assume the remaining issue is a duplicate of #392 )

|svg|librsvg|resvg|batik|
|---|---|---|---|
|![svg](https://upload.wikimedia.org/wikipedia/commons/8/89/Sun_disc_standard_1320222-red.svg)|![68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f382f38392f53756e5f646973635f7374616e646172645f313332303232322d7265642e737667_librsvg](https://user-images.githubusercontent.com/15687581/121883093-a1587880-cd11-11eb-8a1f-62e4287dd167.png)|![68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f382f38392f53756e5f646973635f7374616e646172645f313332303232322d7265642e737667_rendersvg](https://user-images.githubusercontent.com/15687581/121883122-a74e5980-cd11-11eb-96d4-1ca21b133ec2.png)|![68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f382f38392f53756e5f646973635f7374616e646172645f313332303232322d7265642e737667_batik](https://user-images.githubusercontent.com/15687581/121883138-ab7a7700-cd11-11eb-949f-f357cf528252.png)|

## detail viewBox="1940 360 400 500" (by gimp)

|librsvg|resvg|batik|
|---|---|---|
|![librsvg_detail](https://user-images.githubusercontent.com/15687581/121883832-82a6b180-cd12-11eb-81d3-5f5a32184c3e.png)|![resvg_detail](https://user-images.githubusercontent.com/15687581/121883846-86d2cf00-cd12-11eb-8b17-2b47b70597c2.png)|![Batik_detail](https://user-images.githubusercontent.com/15687581/121883864-8afeec80-cd12-11eb-90de-88f36615a112.png)|

**Comment by RazrFalcon** [comment]
No, this is filter issue. I've made #394
