### ISSUE TITLE
Clip paths are cropped at the size of the original SVG

### ISSUE THREAD

**Issue by romanzes** [RazrFalcon/resvg#275]
I'm drawing an SVG multiple times on 1080*1080 canvas using `resvg::backend_skia::render_to_canvas()` function. The result looks like this:

![yoga json](https://user-images.githubusercontent.com/5735967/77384821-7ddaa280-6dda-11ea-95ce-7d101da545fc.png)

Different offsets are achieved by applying translate transformations to the canvas.

Here is the SVG I used for testing: [MADoO6CFQhs.svg.zip](https://github.com/RazrFalcon/resvg/files/4372967/MADoO6CFQhs.svg.zip)

I suspect that the problem might be caused by the fact that the matrix is copied from the original canvas to sub_surface [here](https://github.com/RazrFalcon/resvg/blob/master/src/backend_skia/mod.rs#L281). As the subsurface is only of the size of the original SVG, it gets cropped when translated.

**Comment by RazrFalcon** [comment]
I guess this is the same as #190, basically you should not use any transformations on canvas. This method should be used to render an SVG once. We are doing it this way so all the memory/canvas management is done by the caller. It doesn't behave like drawRect/drawImage methods.

**Comment by romanzes** [comment]
@RazrFalcon thanks for your response. I'm using Skia backend, so I tried calling `render_to_image()` function and drawing the returned `Surface` on Skia canvas like this:
```rust
let mut surface = resvg::backend_skia::render_to_image(
    &tree,
    &resvg::Options::default()
).unwrap();
skia_canvas.draw_image(surface.image_snapshot(), Point::new(0.0, 0.0), None);
```
I also had to add this function into the `Surface` implementation in `resvg-skia-safe` (I'm using my local copy of resvg):
```rust
pub fn image_snapshot(&mut self) -> Image {
    self.surface.borrow_mut().image_snapshot()
}
```
It works well with raster output, however, when I use it for PDF output, SVG gets rasterised. This didn't happen when I used `render_to_canvas()`. I suspect it might be because `image_snapshot()` rasterises the SVG into a bitmap. Is there a better way to do it so it wouldn't be rasterised in PDFs? I understand that neither Skia nor PDF support are the top priorities of this project, but maybe you'd be able to give me some hints? 🙂 Thanks in advance.

**Comment by RazrFalcon** [comment]
>when I use it for PDF output

You shouldn't do this. The only solution is to wait for a proper SVG to PDF implementation. The current hack is unwelcome and will be forbidden eventually.

**Comment by romanzes** [comment]
> > when I use it for PDF output
> 
> You shouldn't do this. The only solution is to wait for a proper SVG to PDF implementation. The current hack is unwelcome and will be forbidden eventually.

Good to know. Can I help with the proper SVG to PDF implementation somehow? Is there a plan for it?

**Comment by RazrFalcon** [comment]
A popper PDF support will be available in a few years. There are nothing ready yet. We have to write a PDF writing library and fonts subsetting first.

The original task is #65 No progress since then.

**Comment by RazrFalcon** [comment]
I've added a note to the docs that the canvas must not have a transform. Sadly, this is the limitation we cannon bypass.
