### ISSUE TITLE
usvg-cli ignores fonts from $HOME/.local/share/fonts

### ISSUE THREAD

**Issue by tuxmark5** [RazrFalcon/resvg#276]
Line in src/fontdb.rs
`let path = Path::new(home).join("/.local/share/fonts"); `
should be replaced to
`let path = Path::new(home).join(".local/share/fonts");`

Otherwise it checks "/.local/share/fonts" instead of "/home/user/.local/share/fonts"

**Comment by RazrFalcon** [comment]
Thanks. This is definitely an unexpected behavior of `Path`.
