### ISSUE TITLE
Option to disable anti-aliasing?

### ISSUE THREAD

**Issue by MichalMichalak** [RazrFalcon/resvg#279]
Is there an option to disable antialiasing? Specifically for CLI tool - rendersvg.
If not, would it be difficult to add it?

**Comment by RazrFalcon** [comment]
You cannot disable anti-aliasing, but you can override the default values: 

```
rendersvg --shape-rendering optimizeSpeed --text-rendering optimizeSpeed --image-rendering optimizeSpeed in.svg out.png
```

**Comment by MichalMichalak** [comment]
Works great. Thank you!
