### ISSUE TITLE
Spell it as just “resvg”

### ISSUE THREAD

**Issue by suhr** [RazrFalcon/resvg#28]
It will avoid reading it as libre + svg. Also, it will match the crate name.

**Comment by RazrFalcon** [comment]
Yep. This was suggested [here](https://www.reddit.com/r/rust/comments/7knfnm/announcing_libresvg_an_svg_rendering_library/drftb6k/).

I will do this in v0.2.

**Comment by RazrFalcon** [comment]
Done.
