### ISSUE TITLE
'svgop': small, binary SVG optimizer

### ISSUE THREAD

**Issue by twardoch** [RazrFalcon/resvg#280]
This may be of interest: svgo is a great Node-based SVG optimizer. It works very well, but you don't want Node in all environments. Well, I just managed to compile svgo with the QuickJS package: a small new JS interpreter that can combine itself with the JS code and produce a binary. So far I made a macOS binary of svgo, and it's a <2 MB self-contained executable. It can also be made for Windows & Linux.

https://github.com/twardoch/svgop

**Comment by RazrFalcon** [comment]
What about https://github.com/RazrFalcon/svgcleaner ?
