### ISSUE TITLE
Consider adding a Blend2D backend

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/resvg#281]
[Blend2D](https://blend2d.com/) is a new vector graphics rendering library that utilizes a JIT rendering pipeline construction. Authors [claim](https://blend2d.com/performance.html) that its performance is dramatically better than Qt and Cairo on most operations even in single-threaded mode, and has optional multi-threading support.

The downside is that it's currently in beta and is not as well tested as e.g. Skia, so it's not a viable candidate for The One Non-Rust Backend. See also #195.

**Comment by RazrFalcon** [comment]
Yes, I know about this project. And as you mentioned, it still in beta. That's why I'm not adding it.

And yes, I want to remove all backends all together, because it's a bit of a burden (and mostly useless one). On the other hand, raqote is nowhere near the finish state, so it's all a bit vague.

**Comment by RazrFalcon** [comment]
Only Skia will be officially supported from now.
