### ISSUE TITLE
Support --export-area-page option like in Inkscape

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#284]
```
--export-area-page                     Exported area is the entire page
```

**Comment by daviddeutsch** [comment]
I think this feature goes back to my suggestion over here: https://github.com/RazrFalcon/svgcleaner/issues/216#issuecomment-626681710

What's the status of this? Inkscape is only getting slower for me :wink:

**Comment by RazrFalcon** [comment]
Don't really have much free time lately. Will see what can be done on the weekends.

**Comment by daviddeutsch** [comment]
No pressure whatsoever, just curious. :bow:
