### ISSUE TITLE
Implement mesh gradients

### ISSUE THREAD

**Issue by nifker** [RazrFalcon/resvg#285]
Could we see mesh gradients like described here implemented in this library? Or this is currently out of scope?
https://www.w3.org/TR/2016/CR-SVG2-20160915/pservers.html#MeshGradients

**Comment by RazrFalcon** [comment]
1. SVG2 isn't supported at all for now.
1. It must be implemented in a rendering library first, aka Qt, Skia, cairo, raqote.
