### ISSUE TITLE
Unexpected invalid size

### ISSUE THREAD

**Issue by Moxinilian** [RazrFalcon/resvg#286]
Hello! I'm currently using [pdf-rs's font module](https://github.com/pdf-rs/font) with its experimental SVG font support. To do that, I'm using [Twitter's emoji font](https://twemoji.twitter.com/) which is correctly parsed usually. However, when parsed with usvg, it triggers an unexpected `InvalidSize` error. Here is an example of one of those SVGs (they all follow the same structure).

```xml
<svg xmlns="http://www.w3.org/2000/svg" id="glyph833">
	<g transform="translate(0 -6.75) translate(0,-1638.4) scale(56.8888888889)">
		<path d="M20 21.5a1.5 1.5 0 0 1-3 0v-3a1.5 1.5 0 1 1 3 0v3z" fill="#67757F" />
		<path d="M27.138 33.817C27.183 35.022 26.206 36 25 36H12.183A2.183 2.183 0 0 1 10 33.817V21c0-1.205.115-2.183 2.183-2.183S15 23 25 21c1.091 0 2.183.978 2.138 2.183v10.634z" fill="#E1E8ED" />
		<path d="M18.687 18.538c-2.595 0-6.962-1.934-6.962-5.898 0-3.988 4.351-5.414 7.005-11.401.751-1.693.999-1.107 1.86-.076 2.06 2.463 5.058 7.483 5.058 11.574-.001 4.641-4.64 5.801-6.961 5.801z" fill="#FCAB40" />
		<path d="M18.687 17.447c-4.184 0-3.482-5.802 0-9.283 2.321 1.16 5.801 9.283 0 9.283z" fill="#FDCB58" />
		<path d="M11 29a1 1 0 1 1-2 0v-7a1 1 0 1 1 2 0v7zm4 3a1 1 0 1 1-2 0v-7a1 1 0 1 1 2 0v7zm0-11a1 1 0 1 1-2 0v-1a1 1 0 1 1 2 0v1z" fill="#CCD6DD" />
	</g>
</svg>
```

Do you know what is going on there? If it is a bug, is there a way around it?
Thanks in advance!

**Comment by s3bk** [comment]
```rust
    /// SVG doesn't have a valid size.
    ///
    /// Occurs when width and/or height are <= 0.
    ///
    /// Also occurs if width, height and viewBox are not set.
    /// This is against the SVG spec, but an automatic size detection is not supported yet.
    InvalidSize,
```

So the *solution* would be to allow missing sizes?

**Comment by s3bk** [comment]
To be clear: This is probably not an usvg issue.
This is a failure of "lets hope that feeding [this modification of SVG](https://docs.microsoft.com/de-de/typography/opentype/spec/svg#svg-documents) to usvg will work".

The proper solution is probably to parse the XML using whatever usvg uses and then proceed from there. I need to talk to @pcwalton on how to best implement the SVG import for pathfinder.

**Comment by Moxinilian** [comment]
Oh wow, I’m blind. Sorry about that.
Thank you!

**Comment by RazrFalcon** [comment]
@Moxinilian Yes, this is an expected behavior. Please follow #40

**Comment by RazrFalcon** [comment]
Also, you can't use `usvg` for OpenType SVG right now. See #135
