### ISSUE TITLE
Blend modes are very slow (infinite loop?)

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/resvg#289]
The following example file that ships with Inkscape takes a very long time to render with resvg, regardless of backend: [blend_modes.svg.gz](https://github.com/RazrFalcon/resvg/files/4704679/blend_modes.svg.gz)

rsvg-convert for comparison renders this in less than a second. Tested with rendersvg on git revision 7e32794d78dfe58887a9f30d4a90fa8fbfee03aa. I ran `cargo update` before compiling, I can attach the Cargo.lock if needed.

**Comment by RazrFalcon** [comment]
Duplicate of #257
