### ISSUE TITLE
Support latest skia

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#293]

**Comment by Brooooooklyn** [comment]
Recommand https://github.com/rust-skia/rust-skia, we will always sync with the latest skia

**Comment by RazrFalcon** [comment]
It's a very heavy dependency. It requires 100 dependencies on linux. This is no go for me.

**Comment by Brooooooklyn** [comment]
> It's a very heavy dependency. It requires 100 dependencies on linux.

Oh, that's weird, we should have no extra dependencies if our prebuild script worked fine. Shouldn't we ?  @pragmatrix

**Comment by pragmatrix** [comment]
The set of dependencies is statically determined by cargo, which means that as long we support a fallback to the full Skia build, the dependencies include all the crates that are needed for that. 

To mitigate that, we could add a feature for the full build to rust-skia, set this as the default to keep the compatilibity, and resvg could then specify the an empty feature set by default to keep the dependencies to a minimum (exluding dev-deps ~39 vs. ~100 on Windows for CPU rendering). If needed, users of resvg may re-enable the full build by patching the skia-safe dependency.

Besides of that, the API differs from the Skia backend that is used by resvg (which AFAIK is based on the C API), so we need to port the backend drawing code to skia-safe _and test it_ before even considering the integration. I could offer to do that and, also test a bit, and also keep it updated to the latest Skia milestones if needed, but in return I would need a strong commitment from the community around resvg that the rust-skia backend is kept updated in terms of resvg features in the foreseeable future.

**Comment by RazrFalcon** [comment]
@pragmatrix The current resvg skia bindings has just a single dependency - `cc`. So even 39 is too much. This is especially critical, since it will affect vendored archive, which includes all dependencies.

So the only way for me to use `skia-safe` is too have an option to select a prebuilt skia. And this variant should depend only on `cc` for linkage.

**Comment by pragmatrix** [comment]
@RazrFalcon What do you mean by "select a prebuilt skia" exactly? Does that mean that your build script or a manual process provides a suitable platform binary from https://github.com/rust-skia/skia-binaries/releases extracts them and sets up an environment variable so that - say a build.rs - can be used to inform cargo about how and what to link? This way, I think we can get the dependencies down to 3 (`bitflags`, `lazy_static`, and `skia-bindings`), and we would not need `cc`, because our prebuilt packages already include the compiled bindings.

**Comment by RazrFalcon** [comment]
Right now, resvg simply requires setting a path to a prebuilt skia. How you built it or where you get it in the first place, we don't care.

Anyway, the skia backend future is a bit vague. So for me, this more about maintaining the current setup rather than finding new solutions.

**Comment by pragmatrix** [comment]
I see, but just to be clear, given that the discussed preconditions are met, you are open to add a second skia backend as an option if someone is driving demand for that?

**Comment by RazrFalcon** [comment]
The current direction is to remove all backends altogether in favor of raqote.

**Comment by luxxxxy** [comment]
> 
> 
> The current direction is to remove all backends altogether in favor of raqote.

@RazrFalcon Well, that aged well. Skia is a pain in the ass.

**Comment by RazrFalcon** [comment]
@luxxxxy Well, raqote is basically alpha-quality. And Skia is the best 2D library in existence. So the choice was obvious.

**Comment by luxxxxy** [comment]
@RazrFalcon problem is it's impossible to compile

**Comment by RazrFalcon** [comment]
@luxxxxy Again, there are no other choice.

**Comment by luxxxxy** [comment]
@RazrFalcon at least provide semi-useful documentation on how the hell to make it compile properly. I couldn't figure it out on either Windows or Linux. Skia isn't even in the fuckin' AUR (well, skia-git is, but that just errors out) or Homebrew.

**Comment by RazrFalcon** [comment]
https://github.com/RazrFalcon/tiny-skia#build-with-embedded-skia ?

>Skia isn't even in the fuckin' AUR (well, skia-git is, but that just errors out) or Homebrew.

This is up to Google.

**Comment by luxxxxy** [comment]
@RazrFalcon Huh, this works now, even though I remember it not working earlier.

**Comment by luxxxxy** [comment]
@RazrFalcon I'm not sure that Skia works on platforms such as RISC-V, though.

**Comment by RazrFalcon** [comment]
@luxxxxy I don't care about those platforms.

**Comment by luxxxxy** [comment]
Sorry if this comes off as rude, but only caring about x86 is a very quick way to ensure your library never sees any big use.

**Comment by RazrFalcon** [comment]
Well, you can always port Skia to Rust. This would help a lot. But you won't. Because you're not Google. End of story.

Anyway, resvg is still the most cross-platform one. The next closest one feature-wise is librsvg, and it supports only Linux+Gnome. So... make your choice.

**Comment by luxxxxy** [comment]
I mean, you ditched a fully Rust-based backend...

**Comment by RazrFalcon** [comment]
Raqote? It supports like 1% of Skia features and very buggy and slow.

Again, you can spend your time making it better. I can't. That's why I'm using Skia.
