### ISSUE TITLE
no_std support?

### ISSUE THREAD

**Issue by nuxeh** [RazrFalcon/resvg#295]
I guess this crate doesn't have `no_std` support, since after a quick look there's no mention of this being the case.

**Comment by RazrFalcon** [comment]
It's not possible.

**Comment by tronical** [comment]
> It's not possible.

I'm curious, what features of std does resvg (the library) require that aren't available in `core` or `alloc`?

**Comment by RazrFalcon** [comment]
`HashMap` and floats (you have to use libm, just like `tiny-skia` does) for one. You can try implementing no_std, but I'm not interested in working on it or even maintaining, if it would require a lot of changes.

`no_std` also limits the library design, which I'm not fond of. Like we have to forget about threads and stuff.

**Comment by tronical** [comment]
Thanks for the explanation.
