### ISSUE TITLE
Smushed font rendering

### ISSUE THREAD

**Issue by dabreegster** [RazrFalcon/resvg#300]
![85369645-c155c180-b52d-11ea-9b46-38929acd973f](https://user-images.githubusercontent.com/1664407/85436522-0da8fd80-b53e-11ea-9515-16b6151add94.png)

Have you seen an issue like https://github.com/dabreegster/abstreet/issues/76 before? usvg is working fine for the .svg button (just a bunch of <path>s), but the text rendering looks way off. I think each letter might be there, but somehow without any x offset. Don't spend too much time on this; it could also be an issue in lyon or my code somewhere.

**Comment by RazrFalcon** [comment]
Can you provide the source SVG?

**Comment by dabreegster** [comment]
```
<svg width="9999" height="9999" viewBox="0 0 9999 9999" xmlns="http://www.w3.org/2000/svg"><text x="0" y="0" font-size="21" font-family="Overpass"><tspan fill="#5B5B5B">Community Proposals</tspan></text></svg>
```

This is what I'm feeding in, but viewing standalone (with ristretto or firefox), this is actually seemingly empty.

The issue is only happening for one user with an unknown platform; I can get more info from them before spending more time on this. Thanks for the fast response!

**Comment by dabreegster** [comment]
Ah, and worth mentioning that the Overpass font is definitely not missing

**Comment by RazrFalcon** [comment]
It's empty, because `y` on `text` corresponds to baseline. So the text is above the image.

**Comment by RazrFalcon** [comment]
Installed the Overpass font - everything works fine. The main culprit is harfbuzz. Or some math rounding/overflow issue.

If the user uses linux - we can check what harfbuzz produces for this font. Otherwise... 

Also, if he has access to usvg/resvg CLI, he can try to generate a preprocesses SVG, to see what `usvg` actually produces. 

And also, maybe there were some warnings in the log. `usvg` prints a warning for almost every situation.

**Comment by dabreegster** [comment]
A later pass of my code handles the y offset -- although actually I didn't realize this issue before; I think I understand why I have some hacks in place now. :)

They are on Linux; I gave instructions to see what usvg does: https://github.com/dabreegster/abstreet/issues/76#issuecomment-648331883
Thanks so much for the help debugging this!

**Comment by dabreegster** [comment]
[diff.zip](https://github.com/RazrFalcon/resvg/files/4821743/diff.zip)
Running usvg on my system vs theirs produces very different results. So is the likely explanation that harfbuzz on their system is somehow broken or configured differently?

**Comment by RazrFalcon** [comment]
The latest release uses it's own harfbuzz fork, so it should work out of the box. Unless the bug was actually in resvg.

**Comment by dabreegster** [comment]
Confirmed fixed in https://github.com/dabreegster/abstreet/issues/76, thank you for solving this!

**Comment by RazrFalcon** [comment]
Nice!
