### ISSUE TITLE
Make Tree:from_dom() public

### ISSUE THREAD

**Issue by romanzes** [RazrFalcon/resvg#305]
I'd like to be able to parse `svgdom::Document` myself, modify it programmatically (as it's easier than modifying a `usvg::Tree`, and then convert into a `Tree`.
Currently I have to do this:
```rust
let document = Document::from_str(string).unwrap();
// modify document
let opt = resvg::Options::default();
let tree = Tree::from_str(&document.to_string(), &opt.usvg).unwrap();
```
If `Tree::from_dom()` was public, I would be able to get rid of extra serialization and deserialization.

**Comment by RazrFalcon** [comment]
`svgdom` not used for many versions now.

**Comment by romanzes** [comment]
> `svgdom` not used for many versions now.

Thanks, I see now. I was using an outdated version, then checked the repo and saw that `from_dom()` is still private, but didn't notice that it was using `svgtree::Document`. Maybe because the comment still says that `svgdom::Document` is used.
Still, wouldn't it make sense to make that function public?

**Comment by RazrFalcon** [comment]
No. It's an internal implementation.
