### ISSUE TITLE
Provide method to parse an SVG from a roxmltree::Document?

### ISSUE THREAD

**Issue by fschutt** [RazrFalcon/resvg#308]
I'd like to split "parsing the XML file" and "constructing the SVG file from the XML document" into two separate steps, so that I can re-use parts of my XML API. Currently there's no easy way to create a `usvg::Tree` from a `roxmltree::Document`, even though `usvg` uses `roxmltree` / `xmlparser` for parsing. Could this be added to the API? Thanks.

**Comment by RazrFalcon** [comment]
So basically: `usvg::Tree::from_roxmltree(tree: &roxmltree::Tree)`? it shouldn't be a problem.
