### ISSUE TITLE
text-decoration crashing usvg

### ISSUE THREAD

**Issue by zimond** [RazrFalcon/resvg#310]
here's a test svg which crashes usvg because the text `Rect` building returns `None`

```xml
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1080 303" x="0px" y="0px" enable-background="new 0 0 1080 303" xml:space="preserve">
    <text  name="_8888.88" font-size="40px" fill="#9E9E9E" text-anchor="end" font-family="Oswald" text-decoration="line-through" transform="matrix(1,0,0,1,814.714,132.041)">
        <tspan x="0" y="0">8888.88</tspan>
    </text>
</svg>
```

**Comment by RazrFalcon** [comment]
Works fine for me. Can you provide additional info? resvg version, usvg options, os, etc.

![out](https://user-images.githubusercontent.com/725494/88261370-d52c4900-ccce-11ea-86d4-ac60bae8b929.png)

**Comment by zimond** [comment]
After changing the font family everything works, I believe the font file is the problem. In your preview pic the font is not oswald.

Here's the font file ( the copyright belongs to original font author)

[Oswald-Regular.ttf.zip](https://github.com/RazrFalcon/resvg/files/4964513/Oswald-Regular.ttf.zip)

**Comment by RazrFalcon** [comment]
Yes, I can reproduce with this font.

>In your preview pic the font is not oswald.

It is `Oswald-VariableFont_wght.ttf` from Google Fonts.

**Comment by zimond** [comment]
well seems I got a really weird font file from somewhere....😇

**Comment by RazrFalcon** [comment]
Yes, it has post.underline_thickness set to 0, which is not handled well by usvg.

**Comment by zimond** [comment]
Thanks! It seems I can just replace the font to get everything working again.
