### ISSUE TITLE
Unable to build with nightly-x86_64-pc-windows-gnu on version v0.8.0

### ISSUE THREAD

**Issue by sum-elier** [RazrFalcon/resvg#312]
I am using this [GUI library (Iced)](https://github.com/hecrj/iced) in my application. But I am unable to build because of the following error https://github.com/rust-lang/rust/issues/74921. Here's an excerpt of output from `cargo tree --edges all` of my project:

```
iced feature "default"
└── iced v0.1.1
    ├── iced_wgpu feature "default"
    │   └── iced_wgpu v0.2.3
    │       ├── resvg feature "default"
    │       │   └── resvg v0.8.0
    │       │       └── usvg feature "default"
    │       │           └── usvg v0.8.0
    │       │               ├── harfbuzz_rs feature "default"
    │       │               │   ├── harfbuzz_rs v1.1.2
    │       │               │   │   ├── harfbuzz-sys v0.3.4
    │       │               │   │   │   [build-dependencies]
    │       │               │   │   │   ├── cc feature "default" (*)
    │       │               │   │   │   └── pkg-config feature "default"
    │       │               │   │   │       └── pkg-config v0.3.18
    │       │               │   │   └── bitflags feature "default" (*)
    │       │               │   ├── harfbuzz_rs feature "build-native-freetype"
    │       │               │   │   ├── harfbuzz_rs v1.1.2 (*)
    │       │               │   │   └── harfbuzz-sys feature "build-native-freetype"
    │       │               │   │       └── harfbuzz-sys v0.3.4 (*)
    │       │               │   └── harfbuzz_rs feature "build-native-harfbuzz"
    │       │               │       ├── harfbuzz_rs v1.1.2 (*)
    │       │               │       └── harfbuzz-sys feature "build-native-harfbuzz"
    │       │               │           ├── harfbuzz-sys v0.3.4 (*)
    │       │               │           ├── harfbuzz-sys feature "cc"
    │       │               │           │   └── harfbuzz-sys v0.3.4 (*)
    │       │               │           └── harfbuzz-sys feature "pkg-config"
    │       │               │               └── harfbuzz-sys v0.3.4 (*)
```

Given this information I have a couple of questions:

1. Is the [fix](https://github.com/rust-lang/rust/issues/74921#issuecomment-665867877) mentioned in the linked issue relevant to this crate? Since the latest release is v0.11.0 maybe it does include it, right?
1. If not, what can I do about the problem mentioned in the issue, is there any flag I can enable?
1. Just out of curiosity: I couldn't find where this project is importing `harfbuzz_rs` that's why I am asking here. How does this crate import that dependency?

Thank you

**Comment by RazrFalcon** [comment]
windows-gnu is not supported.

>I couldn't find where this project is importing harfbuzz_rs

Via `usvg`.

**Comment by sum-elier** [comment]
The error thrown is related to a flag that has to be enabled
https://github.com/servo/rust-harfbuzz/commit/b9db0ca4046d2a15306105ac4b97525e58106a7f
Even if this isn't enabled, would there be additional compilation problems?

**Comment by RazrFalcon** [comment]
resvg uses tiny-skia, therefore you must built it with clang. So you will get an error anyway.

**Comment by RazrFalcon** [comment]
By the way, resvg doesn't use `harfbuzz_rs` anymore. It uses `rustybuzz`.
