### ISSUE TITLE
Is it possible to get bounding box of text, including leading/trailing spaces?

### ISSUE THREAD

**Issue by michaelkirk** [RazrFalcon/resvg#317]
Consider this input file:
```svg
<svg width="500" height="500" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
    <line x1="100" y1="100" x2="100" y2="400" file="yellow" />
    <text x="100" y="200" font-family="monospace" xml:space="preserve">
        <tspan fill="yellow">Line with trailing spaces.                             </tspan>
    </text>
    <text x="100" y="300" font-family="monospace" xml:space="preserve">
        <tspan fill="yellow">  A little leading spaces.</tspan>
    </text>
    <text x="100" y="400" font-family="monospace" xml:space="preserve">
        <tspan fill="yellow">This text already trimmed.</tspan>
    </text>
</svg>
```
(also available at https://gist.github.com/michaelkirk/fa3fbca0c87ec8e78eee6abf2cc96fac?short_path=efa0067)

When run through the draw_bbox example, we get something like: 
![image](https://user-images.githubusercontent.com/217057/91339256-12cb3880-e78b-11ea-9dd4-0d44d9c1b0cf.png)

To clarify what I'm looking for, compare to this output from chrome's developer tools, which bounds preserved whitespace:
<img width="867" alt="Screen Shot 2020-08-24 at 6 37 49 PM" src="https://user-images.githubusercontent.com/217057/91112808-ec958380-e638-11ea-9cfb-a09e94d35f3c.png">
![image](https://user-images.githubusercontent.com/217057/91339515-735a7580-e78b-11ea-8d12-c68cf38bf49f.png)

So, **Is it possible to get a text's computed bounding box with usvg**, like that rendered in chrome?

In my spelunking, I believe this information is last available in: [`convert::text::text_to_paths text_to_paths`](https://github.com/RazrFalcon/resvg/blob/master/usvg/src/convert/text/mod.rs#L190), where we track `last_x` and the `advance`.

But then the calling method recomputes the bbox based on rendered glyphs in [`convert::text::convert`](https://github.com/RazrFalcon/resvg/blob/master/usvg/src/convert/text/mod.rs#L64), which does not account for trailing spaces.

For more context, my application is using usvg to render text widgets. Something like this:
```rust
// space pad, left aligned to 3 chars
let text_to_display = format("Foo: {:<3}", "A");

// note trailing spaces 👀 
assert_eq!(text_to_display, "Foo: A  ");

// this method builds svg text, which it passes through `usvg::Tree::from_str`
let widget = render_my_application_widget(text_to_display);

// `bbox` is based on rendered size and location of glyphs, 
// but there is no glyph for "space", so the widget bbox only reflects the right most rendered glyph
layout(widget, widget.bbox())
```

I'm using the `xml:space="preserve"`, which seems to be sufficient to respect leading `space` (`format("Foo: {:>3}", "A")` works, `format("Foo: {:<3}", "A")` does not). I think this is because the `space`s, though not rendering glyphs, offset the position of the subsequently rendered glyphs.

/cc @dabreegster

**Comment by RazrFalcon** [comment]
Interesting. Basically, the problem is that `usvg::Node::calculate_bbox` calculates a bbox of a path, which obviously doesn't account "spaces", because there are none.

So the only solution is to store the original bbox in `usvg::Path`.

**Comment by RazrFalcon** [comment]
Otherwise, the text handling code is correct. This is how it looks with debug bboxes:

![out](https://user-images.githubusercontent.com/725494/91343945-e85a9900-e7e5-11ea-8c31-5cfe988b86ee.png)

**Comment by RazrFalcon** [comment]
Turned out that this is not only a useful feature, but actually a correct way to handle text. `objectBoundingBox` actually requires text bbox, not path bbox.
