### ISSUE TITLE
Cairo Support

### ISSUE THREAD

**Issue by mmstick** [RazrFalcon/resvg#318]
Is this ever going to be supported again? Had to switch all of my GTK applications to using librsvg since it's been dropped in 0.11

**Comment by RazrFalcon** [comment]
No. Never. 

Is there a reason to use cairo? Is this because of an ability to pass the cairo context to resvg?

Anyway, the next release will use a pure Rust port of skia: [tiny-skia](https://github.com/RazrFalcon/tiny-skia). cairo is just too troublesome and slow.

**Comment by mmstick** [comment]
GTK uses Cairo for all of its rendering, and therefore if you want to render a SVG into a GTK widget with a `gtk::DrawingArea`, you have to render to the provided Cairo context given on `connect_draw()` callbacks. I can't see any way to do this now that Cairo support has been dropped.

**Comment by RazrFalcon** [comment]
`resvg` will produce `resvg::Image`, which contains an RGBA data, which you can draw whenever you want.

[Here](https://github.com/RazrFalcon/resvg/blob/55888a5cbcd651aef810b36f9b97d368af97fda6/src/backend_cairo/image.rs#L78) is how it was previously done in resvg.

**Comment by mmstick** [comment]
I'm sure I could figure out how to do it if I had enough time, but time is something I lack at the moment. This is a lot to unpack, so I'm going to have to stick with librsvg for the time being.

**Comment by RazrFalcon** [comment]
Yeah, I guess adding a few examples would not hurt.

**Comment by CodingJonas** [comment]
I tried to reimplement the code you linked in [your answer](https://github.com/RazrFalcon/resvg/issues/318#issuecomment-684996055) in this issue, but I struggle to see how I can get the pixel color information to map onto the cairo surface from [resvg::Image](https://docs.rs/resvg/0.12.0/resvg/struct.Image.html), which is what I get from [resvg::render](https://docs.rs/resvg/0.12.0/resvg/fn.render.html).

I only see the `u8` slice from `image.data()`, do I have to process this into rgba points somehow?

Has anyone found a solution for this issue?

**Comment by RazrFalcon** [comment]
>I only see the u8 slice from image.data(), do I have to process this into rgba points somehow?

Just use `data.chunks(4)` and this is your RGBA pixel color.
