### ISSUE TITLE
No font rendering

### ISSUE THREAD

**Issue by theashguy** [RazrFalcon/resvg#321]
Hey there all, 

I've been suffering from no fonts existing in my font-db on OSX. Just a whole lot of...

```Warning: No match for 'sans-serif' font-family.```

...in my console. I've tried with different font names, variations with capitalisation, different folders (ie, focusing only on system installed fonts) to no avail.

Have attempted to run the same code with both v0.11.0 and the master branch. Other than enabling the "text" feature I'm not sure if there is anything else that I need to do to make this work? Is there some way to inspect the font-db to see what keys are actually being created without checking the source out and hacking some printlns in?

For context, I've just updated from the ~0.9 branch where I was using the Cairo renderer and that worked fine everywhere. I'm currently running OSX Catalina 10.15.2.

Cheers.
Ash.

---

Edit: Looks like this is also happening on my Ubuntu server with the 'sans-serif' font family. Is it possible that the text feature is not enabling for some reason? Although if the text feature wasn't enabling it wouldn't throw the warning presumably...

**Comment by RazrFalcon** [comment]
>Is there some way to inspect the font-db to see what keys are actually being created without checking the source out and hacking some printlns in?

You can run the [find-system-font](https://github.com/RazrFalcon/fontdb/blob/master/examples/find-system-font.rs) example. It has the same code as usvg.

You can also overwrite `sans-serif` with whatever font you like. [Here](https://github.com/RazrFalcon/resvg/blob/70350e271c67b48c50e45ebbb68c295c8d9cc344/usvg/src/lib.rs#L251) is the default fonts.
