### ISSUE TITLE
(Qt bindings) Transformed bounding boxes?

### ISSUE THREAD

**Issue by dolinenkov** [RazrFalcon/resvg#322]
I'm currently integrating the library into a commercial C++ project, and dealing with an issue when a bounding box returned by `ResvgRenderer::boundsOnElement` method seems to be transposed.
I've looked at the code inside, and seen that the bounding box is transposed after being received from the library (c-api/ResvgQt.h, lines 458 and 473):
```c++
        if (resvg_get_node_bbox(d->tree, rawId, &bbox))
            return QRectF(bbox.x, bbox.y, bbox.height, bbox.width);
```
Could please someone help me with identifying whether is it a bug or not?

**Comment by RazrFalcon** [comment]
This is definitely a bug. You can just swap those values. I will fix the master later.
