### ISSUE TITLE
Does not compile on aarch64

### ISSUE THREAD

**Issue by Gelbpunkt** [RazrFalcon/resvg#323]
When compiling for aarch64, I ran into two issues (they do not appear when building for x86_64):
```rust
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rustybuzz-0.1.1/src/common.rs:192:38
    |
192 |             std::ffi::CStr::from_ptr(char_ptr)
    |                                      ^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rustybuzz`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: skia/src/core/SkCpu.cpp:94:13: error: unknown type name 'SkFILEStream'
warning:             SkFILEStream midr_el1(path.c_str());
warning:             ^
warning: 1 error generated.

error: build failed
```
Figured I don't need text support so I dropped rustybuzz, but SkFILEStream is still unknown (it is defined in SkStream.cpp, https://github.com/google/skia/blob/master/src/core/SkCpu.cpp#L8). The files for the original source were deleted, found them in https://docs.rs/crate/tiny-skia/0.1.0/source/skia/src/core/SkCpu.cpp and the arm64 part there.

I am aware of tiny-skia 0.2.0 and really waiting for a resvg release based on that to get around all these C++ issues.

My question is, can you either release a resvg version based on tiny-skia 0.2.0 rather soon or fix the skia bug with a tiny-skia 0.1.1 release?

Many thanks!

**Comment by RazrFalcon** [comment]
If everything would go smoothly, a new release will be available in a couple of weeks.

**Comment by Gelbpunkt** [comment]
Would it be possible to release a patch version of tiny-skia 0.1.1 that bundles SkStream.cpp as well instead of removing it?

**Comment by RazrFalcon** [comment]
It would be highly problematic.

**Comment by RazrFalcon** [comment]
Should be fixed now.
