### ISSUE TITLE
Somewhat load an invalid size document

### ISSUE THREAD

**Issue by naufraghi** [RazrFalcon/resvg#325]
Would it make sense to add an option in `usvg` to make the absence of size attributes in an SVG document non-fatal?

In my use case the dimensions are absent (the document is generated by another software) but in any case they are not informative, it would be the bounding box of all the expanded paths.

I have a local branch adding a `--ignore-invalid-size` option if interested in adding that support.

**Comment by RazrFalcon** [comment]
I guess this is part of #40 

It's not trivial to implement and therefore it's not implemented yet/

**Comment by naufraghi** [comment]
I understand that producing an invalid SVG may be an unwanted feature. But the parsing and simplification of ʻusvg` can be enormous value even with the missing dimension.

In particular, finding the bounding box can be CPU-intensive (or pervasive in code), so I was wondering if a shortcut that may make sense or not. Perhaps an option accessible only if using ʻusvg` as a library? 

I am also happy with my local 10-line patch, but since it was useful to me I thought about proposing the change.

**Comment by RazrFalcon** [comment]
I think you should wait for automatic bbox detection feature, which will also allow setting custom dimensions.
