### ISSUE TITLE
resvg skips text elements even though fonts loaded

### ISSUE THREAD

**Issue by yuta0801** [RazrFalcon/resvg#331]
it happens with the example in docker.

reproduce: https://github.com/yuta0801/resvg-text

it output image like this
![image](https://user-images.githubusercontent.com/21266306/100153212-2780af00-2ee7-11eb-9cf6-9af44e743ca3.png)

**Comment by RazrFalcon** [comment]
Run `resvg` with `--list-fonts` to see what fonts were loaded, if any.

**Comment by yuta0801** [comment]
It shows me `No match for 'Arial' font-family`, and I try to install Arial font and it works. thank you

I was just wondering that would it be possible to get the warnings using resvg as a library?

**Comment by RazrFalcon** [comment]
>I was just wondering that would it be possible to get the warnings using resvg as a library?

`resvg` uses `log`, so you have to use some logging wrapper in your binary.

>I tried to use Noto instead of Arial, but this is not working...

This is because the SVG file requires the Arial font. And font fallback isn't that great right now.

**Comment by yuta0801** [comment]
I try to remove `font-family="Arial"`, and replace it with `font-family="Noto Serif CJK JP"`, but both not working.
Only text is rendered is `font-family="Noto Mono"` with `WARN - Fallback from Noto Mono to Noto Serif CJK JP.`
It seems not to select font correctly by `font-family`...

**Comment by RazrFalcon** [comment]
This is a normal behavior. The font you've selected must have the required glyphs. You can't use just a random font.

**Comment by yuta0801** [comment]
Ok, I misunderstood. The actually issue is the Japanese text does not render even specify "Noto Serif CJK JP"
I think the font has those characters and there is no warning.

I found text renders with "Noto Sans JP" font new installed while tring various things
but does not render with "Noto Serif JP" font new installed in same way

Do you have any thoughts about what the cause might be?

**Comment by RazrFalcon** [comment]
Send me the font, so I could try to reproduce it.

**Comment by RazrFalcon** [comment]
Need more info.
