### ISSUE TITLE
Could staticlib be added as crate-type for the C-API?

### ISSUE THREAD

**Issue by JanosGit** [RazrFalcon/resvg#333]
I'm currently maintaining a fork of resvg in which the `crate-type` of the C-API's `Cargo.toml` is set to `staticlib` instead of `cdylib` as I need a static library for my project. I'd love to drop my fork and stick to your original repo instead, so I wonder if you could simply add staticlib as a second crate-type to generate?

Thanks, Janos

**Comment by RazrFalcon** [comment]
Sure. I've removed `staticlib` because I've had some issues with linking, where the external project was trying to link to static library by default, and I wanted dynamic one.
