### ISSUE TITLE
bug with scaling of raster image 

### ISSUE THREAD

**Issue by konstare** [RazrFalcon/resvg#341]
Hi,
Thank you for the program. I am playing with it right now and found some bug, with rendering raster images.  As I understand, the bug happens when size of a raster image at some point is smaller than a pixel. The applied zoom works incorrectly for such images. v.0.13 and 0.12 are affected. Below i show the code for v.0.12.

So, I use a raster image with size 200x300 and put in svg with size = (1, 1.5). I expect that after the 160 zooming the size should be 160, 240 (It should fit in the path). The resulting size is something near (160, 320). In fact if width is smaller 1.5,  the resvg always gives the same result (160, 320). If width is larger 1.5 than resvg works as it should. (firefox, librsvg work correctly with such svg)

![in](https://user-images.githubusercontent.com/60809944/103443434-502b5f80-4c70-11eb-9d81-f8d8773749ef.png)

![out](https://user-images.githubusercontent.com/60809944/103443645-879b0b80-4c72-11eb-8361-fc8f12a6cce9.png)

```
use resvg::render;
use std::path::Path;
use usvg::{FitTo, Options, Tree};

fn main() {
    let svg_str = "<svg viewBox='-8 -4.5 16 9' xmlns='http://www.w3.org/2000/svg'>
<image height='1.5' href='in.png' width='1' x='0' y='0'/>
<path d='M0,0 l1,0 l0,1.5 l-1,0 z' fill='none' stroke='black' stroke-width='0.05'/>
</svg>
";
    let tree = Tree::from_str(&svg_str, &Options::default()).unwrap();
    let img = render(&tree, FitTo::Zoom(160), None).unwrap();
    img.save_png(Path::new("out.png")).unwrap();
}
```

**Comment by RazrFalcon** [comment]
Yes, this is an interesting edge-case. It's just a rounding issue. I will fix it soon.

**Comment by konstare** [comment]
Thank you. It drastically simplified my pet project.
