### ISSUE TITLE
limit dimensions in both directions

### ISSUE THREAD

**Issue by Vasilich** [RazrFalcon/resvg#343]
I need to limit rendered PNGs to be max. 500 pixels in any dimension (width or height). Now if i specify 
`-width 500 -height 500`
it wil render SVG to PNG with **width** 500 keeping aspect ratio. E.g. if SVG has dimensions 100x50, then resulting PNG will be 500x250. But if SVG has dimensions 100x200, then resulting PNG will be 500x1000.
How can i convert SVG to PNG with dimensions limited to both directions?

Thanks in advance.

**Comment by RazrFalcon** [comment]
Do you want to fit the image into a 500x500 region or stretch it out? 
Anyway, both variant are unsupported right now.

**Comment by Vasilich** [comment]
I need to keep aspect ratio, so sizes 500x150, 500x500, 100x500 are all valid - there are only limitation "not more than". 
For now i used batch script that first evaluates the SVG image size (with ImageMagick), and then calculates expected dimensions that fit into 500x500 box (in my other project the box has size 640x480). But this script also has limitations when some special chars are used in filenames,  and has dependency on ImageMagick. So you can count this (defining max size for width or /and height) as a feature request :)
Thanks.

**Comment by RazrFalcon** [comment]
Sure, I will add it in the next release.

**Comment by Vasilich** [comment]
tested it - working as expected. thanks!
