### ISSUE TITLE
fill="transparent" parsing failure

### ISSUE THREAD

**Issue by ReaktivnoePoni** [RazrFalcon/resvg#344]
[2.svg.txt](https://github.com/RazrFalcon/resvg/files/5813091/2.svg.txt)

Using c-api with resvg 0.12
Getting `Warning (in usvg::svgtree::parse:421): Failed to parse fill value: 'transparent'. Fallback to black.`

**Comment by RazrFalcon** [comment]
`transparent` is not a valid value in SVG 1.1. It became available only in SVG 2.0, which is not supported.

**Comment by mfauveau** [comment]
Is transparent background at all supported? 
I've tried with <rect fill="none" style="stroke: none; stroke-opacity: 0;" width="100%" height="100%" x="0" y="0"></rect> and other variations without success.
If there is a way kindly advise :)

**Comment by RazrFalcon** [comment]
Background is transparent by default. Or are you talking about element background?

**Comment by mfauveau** [comment]
Even without a rectangle covering the background it seems that I automatically get a black background. Changing the rectangle fill to a color does render properly. Might be an issue on my end though.

**Comment by RazrFalcon** [comment]
Can you provide a minimal example? Maybe you want to use `fill="none"`

**Comment by mfauveau** [comment]
Did use ```fill="none"```. Might be an issue on my side, I'll circle back when I can test.

**Comment by RazrFalcon** [comment]
Done.
