### ISSUE TITLE
Bug with scaling fonts

### ISSUE THREAD

**Issue by konstare** [RazrFalcon/resvg#345]
Hey,
I met the same bug as for images https://github.com/RazrFalcon/resvg/issues/341 
Namely, for small enough viewbox due to a  rounding issue a text completely disappear.
It can be reproduced with the following code:
```
use resvg::render;
use tiny_skia;
use usvg::{FitTo, Options, Tree};
fn main() {
    let svg = "<svg viewBox='-8 -4.5 16 9' xmlns='http://www.w3.org/2000/svg'> <text x='0' y='4' >A</text> </svg>";
    let tree = Tree::from_str(&svg, &Options::default()).unwrap();
    let fit_to = FitTo::Zoom(160.0);
    let pixmap_size = fit_to
        .fit_to(tree.svg_node().size.to_screen_size())
        .unwrap();
    let mut pixmap = tiny_skia::Pixmap::new(pixmap_size.width(), pixmap_size.height()).unwrap();
    render(&tree, fit_to, pixmap.as_mut()).unwrap();
    pixmap.save_png("/tmp/1.png").unwrap();
}
```
Firefox and librsvg show the letter A. resvg shows blank png.

**Comment by RazrFalcon** [comment]
This is because you forgot to load fonts. Set [examples/minimal.rs](https://github.com/RazrFalcon/resvg/blob/master/examples/minimal.rs)
