### ISSUE TITLE
C Library for Windows

### ISSUE THREAD

**Issue by Vasilich** [RazrFalcon/resvg#346]
is there any chance to get C library for windows (as *.DLL) in releases?
As i understood the only way to get it now is to compile it by myself  from sources somehow?
Thanks.

**Comment by RazrFalcon** [comment]
Yes, you have to build it manually. The main reason is that there are to many possibilities: i686/x86_64, MSVS/MinGW, SSE2/AVX.

>compile it by myself from sources somehow

If you have MSVS installed, then it simply:

1. [Install Rust](https://www.rust-lang.org/tools/install)
2. `git clone https://github.com/RazrFalcon/resvg.git`
3. `cd resvg/c-api`
4. `cargo build --release`

**Comment by Vasilich** [comment]
Thanks a lot, RazrFalcon!
In case someone else will need it: for statically linked CRT (to use in Windows DLL) use command line 
`SET "RUSTFLAGS=%RUSTFLAGS% -C target-feature=+crt-static"`
before building it with cargo
