### ISSUE TITLE
Flattening <clipPath> in usvg

### ISSUE THREAD

**Issue by Sairony** [RazrFalcon/resvg#347]
I have a use case where usvg fits like a glove, my issue however is that clipPaths are not simplified. I realize this is probably a rather large option to support but I thought I'd ask anyway if it's something which is considered or would be considered.

**Comment by RazrFalcon** [comment]
Can you provide an example of what you want?

**Comment by Sairony** [comment]
Since everything is simplified into paths, it would be possible for the clipPaths to be resolved against their targets, producing an SVG which contains no clipPaths but producing the same results as the one containing them.

**Comment by RazrFalcon** [comment]
You mean clipping actual paths and not a raster image?

**Comment by RazrFalcon** [comment]
Anyway, this is not possible. In SVG, clipPath operation on raster. Otherwise we will get tons of bugs, because clipping is only possible to paths without stroke and filled with a solid color, because it will change that path bbox.
