### ISSUE TITLE
<image> tag in <defs> not working

### ISSUE THREAD

**Issue by Flaise** [RazrFalcon/resvg#350]
Hello. I'm trying to use resvg to render a procedurally modified SVG to a raster image. I give resvg [this input](https://svgur.com/i/TXp.svg) and it gives me [this output](https://i.imgur.com/W7z4wGy.png). That's not the output I was looking for and when I open the SVG, the input image, in Firefox and Chrome, those supposedly standards-compliant browsers do actually render what I wanted to see.

I realize resvg isn't designed to support everything but from the looks of the SVG code [ view-source:https://svgur.com/i/TXp.svg ], the tags that aren't working are the `<image>` tag inside of the `<defs>` tag, both of which are documented in this repository as being supported. So the problem is either I'm actually not following the standards and the browsers are able to figure out what I want anyway or there's something not working in resvg. Do you have any insight as to what is going on here?

**Comment by RazrFalcon** [comment]
1. Nothing inside `defs` is visible. This is how SVG works.
2. You should use `xlink:href`. This is a more robust construct. `href` is SVG2 only variant, which would not works outside browsers.

**Comment by Flaise** [comment]
That second point was just enough of a hint for me to figure out what went wrong. I was giving resvg bad data because the xmltree crate clips off attribute prefixes by mistake. I wrote a workaround and everything works now. Thanks for the help!
