### ISSUE TITLE
usvg: would like option to prefix (or mangle) element IDs

### ISSUE THREAD

**Issue by ijackson** [RazrFalcon/resvg#353]
This is necessary to be able to include a usvg-cleaned SVG into some other document which uses id= attributes; or to incorporate multiple usvg-cleaned SVGs into the same document.

I found this issue https://github.com/svg/svgo/issues/674 in svgo which is a request for roughly the same thing.  Some of the comments discuss why it's needed.  Unfortunately, it's not a very edifying conversation.

Anyway I think for `usvg`, what I would like for my own application is a `--id-prefix` option to `usvg`.

**Comment by RazrFalcon** [comment]
It should be fairly trivial to implement.

**Comment by ijackson** [comment]
> It should be fairly trivial to implement.

Oh, thank you for getting around to this! :-)
