### ISSUE TITLE
Support rendering to u16/f32 per channel pixel formats

### ISSUE THREAD

**Issue by virtualritz** [RazrFalcon/resvg#355]
See subject.

Eight bit/channel are not enough for most smooth gradients etc.

**Comment by RazrFalcon** [comment]
SVG is technically 8bit only. I don't know any app that supports rendering SVG to 16/32bit bitmaps.

On the other hand, since we're using our own rendering library, it fairly easy to implement. So this basically blocked only by `tiny-skia`.

**Comment by virtualritz** [comment]
The colors are specified in 8bit.
As soon as you blend them in any meaningful way (opacity, interpolation etc), you end up aliasing if you promote the result back to 8bit. Yes, you can dither but that's not the same.

I think this would be great to have.

**Comment by RazrFalcon** [comment]
Out of scope. This should be done by tiny-skia anyway: https://github.com/RazrFalcon/tiny-skia/issues/63
