### ISSUE TITLE
usvg unit conversion errors with custom dpi settings

### ISSUE THREAD

**Issue by JonHollander** [RazrFalcon/resvg#357]
# Summary
When using a custom dpi setting with usvg/resvg, attributes with non-pixel unit values (e.g. mm units) will be converted incorrectly.

# Example
```
<svg width="100mm" height="100mm" version="1.1" xmlns = 'http://www.w3.org/2000/svg' viewBox='0 0 1000 1000'> 
    <rect x="5" y="5" width="995" height="995" stroke="green" stroke-width="5" fill="none"/>  
    <rect x="0" y="0" width="185.208mm" height="79.375mm" fill="red"/>
    <rect x="185.208mm" y="79.375mm" width="79.375mm" height="185.208mm" fill="blue"/>
</svg>
```

`usvg --dpi 96` produces: 
![09_units_mm_vb_dpi_96](https://user-images.githubusercontent.com/5515181/110142537-1f0ffe00-7d8b-11eb-86af-0635d324b142.png)

`usvg --dpi 25` produces:
![09_units_mm_vb_dpi_25](https://user-images.githubusercontent.com/5515181/110142636-39e27280-7d8b-11eb-84cc-adf82b1654ae.png)

Note the interior rectangles are scaled disproportionately.

I believe the desired output for `usvg --dpi 25` should be:
![08_units_mm_root_dpi_25](https://user-images.githubusercontent.com/5515181/110143773-75ca0780-7d8c-11eb-8a1a-b6001bec7476.png)

# Proposed Solution
This issue occurs because the `dpi` setting is used to define a unit conversion from inches to pixels AND to specify an output rendering resolution. 

I propose separating these functions and defining two arguments for usvg: 
  * dpi_units:  Sets the value of dpi units from inches to pixels [default: 96, but 72/90 are sometimes used]
  * dpi_render: Sets the output pixel resolution for converting svg to usvg [default: 96, but sometimes higher values like 300 are used]
  
I have already implemented this solution in our code. I am happy to submit a PR if you agree that this is an issue and approve this solution. If you prefer a different solution, please feel free to suggest it and I may be able to implement it.

**Comment by RazrFalcon** [comment]
The problem with DPI is that I have no idea how it should be processed. It's not specified in the spec. librsvg will produce the same result. 

I guess you want `--export-dpi` just like Inkscape instead. Which is basically a glorified `--zoom`. Am I right?

**Comment by JonHollander** [comment]
Yes, the SVG spec is very vague and frustrating, but `--export-dpi` is basically correct. We're using this to output SVG with units other than display pixels for our CNC tools (e.g. --dpi_render 25.4 to output in mm)

**Comment by RazrFalcon** [comment]
Then you can simply use `--zoom dpi/96`

**Comment by JonHollander** [comment]
Our application may be an edge case, but we're only using usvg, not resvg, so the '--zoom' option won't help us. We use the usvg data as input to a geometry processing pipeline to convert svg to cutting toolpaths.

**Comment by RazrFalcon** [comment]
Oh, I see. usvg doesn't support any resizing features. And I'm not sure it's even possible. Will think about it.

**Comment by RazrFalcon** [comment]
I don't think this is possible. To implement this, we have to modify all coordinates in an SVG, which is pretty troublesome. 

There are also some edge cases, like implicit `<image>` dimensions, which we should resolve first and then scale, I guess. Too many edge cases.
