### ISSUE TITLE
Error: the file has no valid ID's

### ISSUE THREAD

**Issue by daviddeutsch** [RazrFalcon/resvg#358]
I'm trying to - once again - replace inkscape with resvg tools but I'm already running into problems using `--query-all`. This is my test svg file:
```svg
<svg
   xmlns="http://www.w3.org/2000/svg"
   version="1.1"
   width="800"
   height="1970"
   viewbox="0 0 800 1970">
    <g id="notice">
        <g id="n-2ddbd3ff-a1c8-4775-89fe-892a8c4066fc">
            <g id="n-2026ef7e-e1b4-419b-b0d4-5d2a7a83d4a1">
            <text id="n-2026ef7e-e1b4-419b-b0d4-5d2a7a83d4a1-line-1" x="675" y="39">
                <tspan x="504" y="39" id="tspan15">Test</tspan>
            </text>
            </g>
        </g>
    </g>
</svg>

```
What am I missing here? Shouldn't `resvg` find at least 5 IDs?

This is the inkscape output:
```
svg7,504.12,30.432,22.2959,8.688
notice,504.12,30.432,22.2959,8.688
n-2ddbd3ff-a1c8-4775-89fe-892a8c4066fc,504.12,30.432,22.2959,8.688
n-2026ef7e-e1b4-419b-b0d4-5d2a7a83d4a1,504.12,30.432,22.2959,8.688
n-2026ef7e-e1b4-419b-b0d4-5d2a7a83d4a1-line-1,504.12,30.432,22.2959,8.688
tspan15,504.12,30.432,22.2959,8.688
```

**Comment by RazrFalcon** [comment]
```
> resvg --query-all test.svg
notice,504.363,31.055,19.477,8.109
n-2ddbd3ff-a1c8-4775-89fe-892a8c4066fc,504.363,31.055,19.477,8.109
n-2026ef7e-e1b4-419b-b0d4-5d2a7a83d4a1,504.363,31.055,19.477,8.109
n-2026ef7e-e1b4-419b-b0d4-5d2a7a83d4a1-line-1,504.363,31.055,19.477,8.109
```

What version are you using?

**Comment by daviddeutsch** [comment]
The latest that cargo would install for me - v0.14.0

**Comment by RazrFalcon** [comment]
No idea. What OS do have? Does file renders correctly?

**Comment by RazrFalcon** [comment]
Can you show the whole cli command?

**Comment by daviddeutsch** [comment]
This is on the latest Kubuntu 20.10. Inkscape loads the file just fine:
![image](https://user-images.githubusercontent.com/630246/110934638-8cdd9c00-832e-11eb-9e63-14d14ed30551.png)
```
$ resvg --query-all test.svg
Error: the file has no valid ID's.
```

**Comment by RazrFalcon** [comment]
Can you render it via resvg?

**Comment by daviddeutsch** [comment]
```
resvg test.svg test.png
```
produces a png file of the correct size with no content.

**Comment by RazrFalcon** [comment]
Have you used `--no-default-features` when building resvg? Because looks like you have the `text` feature disabled.

Or maybe if fails to load fonts. Try `resvg --list-fonts test.svg out.png`

**Comment by daviddeutsch** [comment]
Hmm, maybe it's trying to default to `Times New Roman`?
```
[... lots of fonts ...]
Warning (in usvg::convert::text::convert:412): No match for 'Times New Roman' font-family.
Warning (in usvg::convert::text::convert:412): No match for 'Times New Roman' font-family.
Warning (in usvg::convert::text::convert:412): No match for 'Times New Roman' font-family.
```

**Comment by RazrFalcon** [comment]
Try `resvg --font-family "Ubuntu Sans" test.svg out.png` or whatever you have on your OS. Warning are shown for a reason.

**Comment by daviddeutsch** [comment]
I installed `ttf-mscorefonts-installer` and it's working fine, now.

I only saw those warnings when using `--list-fonts`. Maybe it'd make sense to also throw them on other actions? And - this kind of dependency on a windows font file could perhaps be improved upon.

**Comment by RazrFalcon** [comment]
>Maybe it'd make sense to also throw them on other actions?

Warning are suppressed during `--query-all` to simplify the output. 

> And - this kind of dependency on a windows font file could perhaps be improved upon.

It doesn't depend on windows fonts. It uses _Times New Roman_ as a fallback. Ideally we should query it from fontconfig, but its api is a nightmare and it is horribly slow, so I'm avoiding it.

**Comment by daviddeutsch** [comment]
> Warning are suppressed during --query-all to simplify the output.

Ah ok, that does make sense. In this instance, I'd have preferred to see those warnings on stderr, though.

> It doesn't depend on windows fonts. It uses Times New Roman as a fallback.

Would it be an option to fallback to 'sans-serif'? Or would that result in the same fontconfig query?

**Comment by RazrFalcon** [comment]
>I'd have preferred to see those warnings on stderr, though

They are in stderr, but for a typical user they are the same.

>Or would that result in the same fontconfig query?

Yes. You have to specify the font you need in the SVG anyway. Relying on the _default_ one is an edge case and any SVG rendering library can whatever it wants. resvg fallbacks to _Times New Roman_.

**Comment by daviddeutsch** [comment]
Alright, that makes sense. Thanks!
