### ISSUE TITLE
How to extend/stretch text along the entire textPath?

### ISSUE THREAD

**Issue by undali** [RazrFalcon/resvg#359]
I'm sorry, maybe this question is inappropriate here.

There's a similar question on stackoverflow(https://stackoverflow.com/questions/13566042/how-to-extend-the-text-along-the-entire-textpath-in-svg). It suggested to use textLength attribute. But to calculate the perfect textlength, they used javascript. 

I've tried textPath's attribute _method_ (_stretch/align_).

Is there any plan to support this feature on resvg, or any other workaround to achieve this?

If not, I'll try to implement this on resvg myself , some direction will be appreciated.

It's such a wonderful library.
Thanks.

**Comment by RazrFalcon** [comment]
Request for `lengthAdjust` and `textLength` already exists: #204

The `method` attribute does a completely different thing, afaik. And no one supports it anyway.

I'm not sure if there is a way to achieve what you want using pure SVG (excluding `textLength` hack).
