### ISSUE TITLE
resvg test suite: which one is correct

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#362]
![https://raw.githubusercontent.com/RazrFalcon/resvg/master/.github/chart.svg](https://raw.githubusercontent.com/RazrFalcon/resvg/master/.github/chart.svg)

Do you have a table which file is rendered correclty, or how they should render correctly. I rendered them by batik, inkscape, librsvg, resvg, and I sometimes don't know which one is right.

I know the [supported features](https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html), but I want to know the correct files.

**Comment by RazrFalcon** [comment]
https://github.com/RazrFalcon/resvg-test-suite/blob/master/results.csv

This file is used by https://github.com/RazrFalcon/resvg-test-suite/tree/master/tools/vdiff

**Comment by JoKalliauer** [comment]
The legend of
https://github.com/RazrFalcon/resvg-test-suite/blob/master/results.csv
is
0...Undefined
1...Correct
2...Wrong
3...Chashes
