### ISSUE TITLE
[usvg] slow compared to librsvg, inkscape, batik for specific file

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#363]
I compared the average rendering times for 141 images at https://commons.wikimedia.org/wiki/Category:Featured_pictures_on_Wikimedia_Commons_-_vector

With https://commons.wikimedia.org/wiki/Commons:Imker_(batch_download) you can download the whole category at commons.

I know resvg supports more features (e.g: textPath)  and maybe has a better precession (e.g. gausian blur), however I wondered that it was the slowest of all rendering engines, even slower than Inkscape.

svg | librsvg 2.50.3 | resvg 0.14.0 | Inkscape 1.0.2 | batik 1.14
-- | -- | -- | -- | --
time | 8,82min | 24,58min | 18,82min | 19,2min

-I think all of the rendering-engines use singe-CPU?
-Since I did hardly use the PC during rendering, CPU,RAM,SSD should have almost no utilization. So I don't think it is because of CPU-prioritization .
-Since librsvg renders nearly all files almost correct, the time-difference should imho be neglibible.
-Since it contains 141 files I don't think it is related to a singe file

I know it is bad elaborated bug-report, but maybe you can comment on that where I should reinvestigate.

PS: Do you know how to check the CPU-times of commands in a bash-script?

**Comment by RazrFalcon** [comment]
How exactly do you build resvg?

**Comment by JoKalliauer** [comment]
## build
I just rebuild it:
```bash
sudo dnf install qt5-qtbase-devel harfbuzz-devel qt5-qtbase qt5-qtbase-devel qt5-qtsvg qt5-qtsvg-devel npm inkscape librsvg2 batik batik-rasterizer wxsvg wxsvg-devel
sudo dnf upgrade
cd ~/Dokumente/GitDesktop/
# git clone https://github.com/RazrFalcon/resvg.git #allready done
cd resvg/
git config pull.rebase false
git pull
cargo build --release
./make-vendored.sh
```


## one file more than 60 times slower than {librsvg,inkscape,batik}

svg | librsvg 2.50.3 | resvg 0.14.0 | Inkscape 1.0.2 | batik 1.14
-- | -- | -- | -- | --
real time | 0m5,691s | 11m52,413s| 0m6,774s | 0m11,335s
user time | 0m9,973s | 11m42,682s| 0m8,562s | 0m28,025s
sys time | 0m0,097s| 0m0,411s | 0m0,218s | 0m0,842s

### SVG-file
![India_roadway_map.svg](https://gitlab.com/inkscape/inbox/uploads/c05365635ce90647303faafce92238c2/India_roadway_map.svg)

source: https://commons.wikimedia.org/wiki/File:India_roadway_map.svg

author: CC-by-sa [PlaneMad](https://en.wikipedia.org/wiki/User:Planemad)/Wikimedia

license: CC BY SA 3.0

### bash script
```bash
#!/bin/bash

for file in *.svg
 do
 
 echo #Add a empty line to split the output
 echo $file

 echo resvg
 time ~/Dokumente/GitDesktop/resvg/target/release/resvg "$file" "${file%.svg}_rendersvg.png"
 
 echo librsvg
 time rsvg-convert "$file" >"${file%.svg}_librsvg.png"

 echo inkscape
 time inkscape "$file" --export-type="png"
 mv "${file%.svg}.png" "${file%.svg}_Inkscape.png"
 
 echo batik
 time java -jar ~/prgm/batik-1.14/batik-rasterizer-1.14.jar "$file" -d "${file%.svg}_batik.png"

done
```


### terminal output
```
India roadway map.svg
resvg
Warning (in usvg::svgtree::parse:66): Failed to parse d value: 'M209-152.5'.
Warning (in usvg::svgtree::parse:66): Failed to parse d value: 'M105-323'.

real	11m52,413s
user	11m42,682s
sys	0m0,411s
librsvg

real	0m5,691s
user	0m9,973s
sys	0m0,097s
inkscape
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
WARNING: unknown type: a:midPointStop
Background RRGGBBAA: ffffff00
Area 0:0:1638.55:1852.41 exported to 1639 x 1852 pixels (96 dpi)

real	0m6,774s
user	0m8,562s
sys	0m0,218s
batik
About to transcode 1 SVG file(s)

Converting India roadway map.svg to India roadway map_batik.png ... ... success

real	0m11,335s
user	0m28,025s
sys	0m0,842s
```


### PNG "natural size" (1639x1852)


svg | librsvg 2.50.3 | resvg 0.14.0 | Inkscape 1.0.2 | batik 1.14
-- | -- | -- | -- | --
real time | 0m5,691s | 11m52,413s| 0m6,774s | 0m11,335s
user time | 0m9,973s | 11m42,682s| 0m8,562s | 0m28,025s
sys time | 0m0,097s| 0m0,411s | 0m0,218s | 0m0,842s
PNG| ![India roadway map_librsvg](https://user-images.githubusercontent.com/15687581/111868395-f3d80200-8979-11eb-9edc-336a61497ee9.png) | ![India roadway map_rendersvg](https://user-images.githubusercontent.com/15687581/111868415-fdfa0080-8979-11eb-9951-4ddcc4bd13dd.png) | ![India roadway map_Inkscape](https://user-images.githubusercontent.com/15687581/111868423-07836880-897a-11eb-9d6b-d25c4158539f.png) | ![India roadway map_batik](https://user-images.githubusercontent.com/15687581/111868431-0f430d00-897a-11eb-9331-79e0e21f01f8.png)

**Comment by RazrFalcon** [comment]
This is some performance bug. resvg is pretty fast in general.
And most of the time is spent during preprocessing and not rendering. Feels like a text shaping bug. Will investigate later.

**Comment by JoKalliauer** [comment]
I optimized the file with scour, [svgcleaner](https://github.com/JoKalliauer/cleanupSVG/blob/master/SystemLanguageCleanerFull.sh#L13), svgo, "ungrouped" all groups/switches with inkscape and splitted the svg in Text-svg and a Objects-svg (without text).

The path-svg is slower than the text-svg.

## Text

svg | librsvg 2.50.3 | resvg 0.14.0 | Inkscape 1.0.2 | batik 1.14
-- | -- | -- | -- | --
real time | 0m15,682s| 0m52,114s| 0m5,331s| 0m8,176s
user time | 0m22,275s | 0m50,196s| 0m7,390s | 0m17,128s
sys time | 0m0,130s| 0m0,635s| 0m0,148s | 0m0,637s

![Text.svg](https://gitlab.com/inkscape/inbox/uploads/ce8a33ebefb6a79bf38740c629ebc443/Text.svg)



## Objects

svg | librsvg 2.50.3 | resvg 0.14.0 | Inkscape 1.0.2 | batik 1.14
-- | -- | -- | -- | --
real time | 0m9,201s| 6m31,513s| 0m3,215s | 0m8,116s
user time | 0m8,892s | 6m21,154s| 0m3,077s | 0m19,244s
sys time | 0m0,047s| 0m2,195s | 0m0,162s | 0m0,537s

![Objects.svg](https://gitlab.com/inkscape/inbox//uploads/513e45b1e6d9ddb832591c32890780e5/Objects.svg)

**Comment by JoKalliauer** [comment]
I delimited one issue the useless clipPath slow down extremely:

## micro-SVG (Text unmodified) with useless clipPaths
[both.svg.txt](https://github.com/RazrFalcon/resvg/files/6248564/both.svg.txt)

real	1m45,192s
user	1m42,838s
sys	0m0,468s

## micro-SVG (Text unmodified) without clipPaths
[both_(Kopie)CU.svg.txt](https://github.com/RazrFalcon/resvg/files/6248585/both_.Kopie.CU.svg.txt)

real	0m2,754s
user	0m2,469s
sys	0m0,230s

**Comment by RazrFalcon** [comment]
@JoKalliauer Should be way better now. On my hardware `both.svg.txt` rendering reduced from 113527ms to just 8596ms (13x faster).

Please test the latest commit if you can to make sure I haven't broke anything it the process.

**Comment by JoKalliauer** [comment]
You fixed imho half of the issue. (I tried to make a Minimal working example with a mikro-svg, which got fixed, but the original one [https://upload.wikimedia.org/wikipedia/commons/archive/7/78/20210402095817%21India_roadway_map.svg](https://upload.wikimedia.org/wikipedia/commons/archive/7/78/20210402095817%21India_roadway_map.svg) still takes about 4minutes for rendering.)

Because of the Warnings, it might be a malformed svg.

## fixed:
rendering-times of the mikro-svg `both.svg.txt`:
|resvg|librsvg|inkscape|batik|
|---|----|---|---|
|7,100s|0,638s|3,175s|7,840s|

## unfixed:
```bash
wget https://upload.wikimedia.org/wikipedia/commons/archive/7/78/20210402095817%21India_roadway_map.svg -O Input.svg
time usvg Input.svg Output.svg
```
resulted in
```bash
Warning (in usvg::svgtree::parse:66): Failed to parse d value: 'M209-152.5'.
Warning (in usvg::svgtree::parse:66): Failed to parse d value: 'M105-323'.

real	3m53,301s
user	3m52,748s
sys	0m0,149s
```

**Comment by RazrFalcon** [comment]
Yes, preprocessing is still incredibly slow on this file.

**Comment by RazrFalcon** [comment]
Fixed. I was using a very dumb/slow algorithm for checking that element id is unique.

**Comment by JoKalliauer** [comment]
Do you know how to get the latest develomentversion from git. I tried `cargo install resvg --force --git https://github.com/RazrFalcon/resvg/`, but it still slow (I assume it is the released 0.15).

**Comment by RazrFalcon** [comment]
I think it should be

```
cargo install --force --git https://github.com/RazrFalcon/resvg/
```

**Comment by JoKalliauer** [comment]
> I think it should be
> 
> ```
> cargo install --force --git https://github.com/RazrFalcon/resvg/ resvg
> ```
> 
> Works very fast for me.

I run
```
cargo install --force --git https://github.com/RazrFalcon/resvg/ resvg
cargo install --force --git https://github.com/RazrFalcon/resvg/ usvg
```
`resvg` is fast, but `usvg` is not ? I thought resvg always runs usvg first, does it use different options?

```bash
rm -f Input.svg
wget -q https://upload.wikimedia.org/wikipedia/commons/archive/7/78/20210402095817%21India_roadway_map.svg -O Input.svg
time resvg Input.svg PNG.png
time usvg Input.svg Output.svg
```

returns:
```bash
Warning (in usvg::svgtree::parse:64): Failed to parse d value: 'M209-152.5'.
Warning (in usvg::svgtree::parse:64): Failed to parse d value: 'M105-323'.

real	0m7,221s
user	0m6,853s
sys	0m0,355s
```
```bash
Warning (in usvg::svgtree::parse:66): Failed to parse d value: 'M209-152.5'.
Warning (in usvg::svgtree::parse:66): Failed to parse d value: 'M105-323'.

real	3m52,365s
user	3m51,813s
sys	0m0,146s
```

**Comment by RazrFalcon** [comment]
It seems that your are calling older usvg version somehow. Warning should be at line 64, not 66 in the latest build.

**Comment by JoKalliauer** [comment]
> It seems that your are calling older usvg version somehow. Warning should be at line 64, not 66 in the latest build.

Thanks!
`cargo install --force --git https://github.com/RazrFalcon/resvg/ usvg` creates a binary in `~/.cargo/bin/usvg`, however I had a symbolic link in `~/bin/usvg` symbolically-linking to `/home/jkalliau/Documents/GitHub/resvg/target/release/usvg`

![Screenshot from 2021-07-01 11-22-42](https://user-images.githubusercontent.com/15687581/124100600-e513e780-da5e-11eb-8869-093a483a7f90.png)
