### ISSUE TITLE
 font-family="Sans" fallback to "Serif"

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#365]
Rendering https://upload.wikimedia.org/wikipedia/commons/archive/d/d8/20210328175854%21Tugboat_diagram-en_edit.svg by resvg leas to rendering of "Sans" with a serif-font.

## SVG 
```xml
      <text
         x="635.49414"
         y="254.37999"
         style="font-size:14px;font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;text-indent:0;text-align:start;text-decoration:none;line-height:125%;letter-spacing:normal;word-spacing:normal;text-transform:none;direction:ltr;block-progression:tb;writing-mode:lr-tb;text-anchor:start;color:black;fill:black;fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;marker:none;marker-start:none;marker-mid:none;marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:inline;overflow:visible;font-family:Sans"
         id="text3658"
         xml:space="preserve"><tspan
           x="635.49414"
           y="254.37999"
           style="font-size:14px;font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;text-indent:0;text-align:start;text-decoration:none;line-height:125%;letter-spacing:normal;word-spacing:normal;text-transform:none;direction:ltr;block-progression:tb;writing-mode:lr-tb;text-anchor:start;color:black;fill:black;fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;marker:none;marker-start:none;marker-mid:none;marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:inline;overflow:visible;font-family:Sans"
           id="tspan3660">antenna</tspan></text>
```
![https://upload.wikimedia.org/wikipedia/commons/archive/d/d8/20210328175854%21Tugboat_diagram-en_edit.svg](https://upload.wikimedia.org/wikipedia/commons/archive/d/d8/20210328175854%21Tugboat_diagram-en_edit.svg)

## PNG by resvg
![Tugboat diagram-en edit_rendersvg](https://user-images.githubusercontent.com/15687581/112762577-9b030c00-9000-11eb-9881-346842a34758.png)

**Comment by RazrFalcon** [comment]
Yes, generic family names should be in a lower case. Not sure if mixed case actually allowed by CSS.

**Comment by JoKalliauer** [comment]
even ` font-family="sans"` renders as serif:
## SVG
```xml
   <text font-family="sans" font-size="14" x="635.49" y="254.38"><tspan font-family="sans" font-size="14" x="635.49" y="254.38">antenna</tspan></text>
```
[Tugboat_diagram-en_editstscC.svg.txt](https://github.com/RazrFalcon/resvg/files/6217830/Tugboat_diagram-en_editstscC.svg.txt)

## rendersvg

![Tugboat_diagram-en_editstscC_rendersvg](https://user-images.githubusercontent.com/15687581/112763140-79575400-9003-11eb-875d-bbb27b184e6f.png)

**Comment by RazrFalcon** [comment]
My bad. There is no `sans` family. Only `sans-serif`. So `Sans` will fallback to Times New Roman or whatever default family user selected.

**Comment by JoKalliauer** [comment]
> My bad. There is no `sans` family. Only `sans-serif`. So `Sans` will fallback to Times New Roman or whatever default family user selected.

Thanks, what happens if no "Times New Roman" is available (most Linux-distributions)?

**Comment by JoKalliauer** [comment]
Can the default fallback be changed?

**Comment by RazrFalcon** [comment]
Nothing good. It's a user problem now. Generic families resolving is undefined, so we can do whatever we want.

>Can the default fallback be changed?

Yes.

```
  --font-family FAMILY          Sets the default font family that will be
                                used when no 'font-family' is present
                                [default: Times New Roman]
```
