### ISSUE TITLE
There is a black edge in output png

### ISSUE THREAD

**Issue by wangrl2016** [RazrFalcon/resvg#367]
Shadow png 
![out](https://user-images.githubusercontent.com/49860767/113141837-cbdf7d00-925c-11eb-9f86-a04311cff9b7.png)

Google chrome png
![Screenshot from 2021-04-01 09-24-44](https://user-images.githubusercontent.com/49860767/113230780-57dcbd80-92cc-11eb-9a52-733158921ca7.png)

**Comment by RazrFalcon** [comment]
Please, improve the bug report.

**Comment by wangrl2016** [comment]
There is an svg (above), the svg contains a base64 png which has alpha channel.

The png original size is 87x159, the ratio of width and height is 0.55, but after tranform, the ratio is change.

When I use resvg to render the svg file, we can see there is shadow in the png edge, like the above picture.

**Comment by wangrl2016** [comment]
The svg source file
<svg width="560" height="560" viewBox="0 0 560 560" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
    <g transform="translate(0, 0)rotate(0,685,280)" opacity="1">
        <g transform="rotate(0,685,280)matrix(1,0,0,1,0,0)translate(0, 0)">
            <g>
                <rect width="560" height="560" fill="rgb(153,226,101)"/>
            </g>
        </g>
    </g>

    <svg width="128.52708402987963" height="223.84524427862706"
         viewBox="38.171190950140215 0 164.88757487350952 287.17137523707123" version="1.1"
         xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <svg width="203.05876582364974" height="371.1073996087392"
             viewBox="0 0 203.05876582364974 371.1073996087392" version="1.1"
             xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <image x="0" y="0" width="203.05876582364974" height="371.1073996087392"
                   href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFcAAACfCAYAAACMc0W1AAADxUlEQVR4Ae3BQc7dVQHA0fO9Xts4cAPCyIEbUAcOWIGSFEMdsAY04gDDBkwIQ3UV1YBp3IXGxik4a2UBdqC1vT9NdEQMoV/73i1/7jm2bdu2bdu2bdu2bdu2bdu2bdu2bdu2bfs8Vxaq/B83cRu38X18Ezd9cY/wAH/Gh/g9HntOV1dXvlQqlUqleqP6uBfr4+pHlUqlUqlUKpVKpVKpVCpfOs2pOTXnjeZ8vzlrzpqz5qw5a86as+asOWvOmrPmrDlrzpqz5qw5a86as+asOWvOmrPmfL85bzSn5tScmlNzak7NqTk1p+bUnJpTc2pO1zG8HH6Jd53Xu/7rFy7kykLN6T/exF2Xcwe/9YyuTifP6spCPX16E3/Fqy7nIb6Fx57B1Y0bntXJWnfwqst6BT92ASdr3bbGbRcwrFTfs8Z3XcCVhXry5B+45fIe45ZncDWGZzWsVLescdMFnGxnM6xUjuxkO5thpXJkJ9vZDCuVIzvZzmZYqRzZyXY2w0rlyIaVcmjDUjmyYaUc2rBUjmxYqRzZsFIObVgqRzasVI5sWCmHNiyVIxtWKkc2rJRDG5bKkQ0rlSMbVsqhDUvlyIaVypENK+XQhqVyZMNK5ciGlXJow0rlyIalcmTDSjm0YaVyZMNK5ciGpXJkw0o5tGGlcmTDUjmyYaUc2rBSObJhpXJkJ9vZDCuVIztZqSiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKSqVSqVQqlUqlnqifuoZh+zyP8BbuuYZhpfIS+xt+gPuuaVipvKTu43U88BxOts/6A17DA89pWKm8ZH6Nn+GpF2BYqbwknuId/MoLNGyP8BbuecGGlcpiD/FD3HcGw0ploft4HQ+cyfDV9RoeOaNhpbLQI2c2rFSO7GQ7m2GlcmQn29kMK5UjG1bKoQ1L5ciGlcqRnWxnM6xUjuxkO5thpXJkJ9vZDCuVIztZ6+/WeOwChpXyKb7h8j51AcNS/QXfdnl/dAEnK+UjIYQQQgghhBBCCCGEEEIIIYQQ8pEQQgghhBBCruVkqe7SA0IIIYQQQgghhBBCCCGEEEIIPaS7hBBCCCGEEHIdJ2s9xs9d1jv4pws4WSnkrnwghBBCCCGEEEIIIYQQQggh5AO5K4QQQgghhBByLcNS+Z/38HW87Xx+g/dc0MnL4Sl+gjfxiRfrE9zB23jqgoaV8lm/wz3cwRv4Dl7B13xx/8JD/Akf4i4e27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27btK+vfsoq+JRdGUNsAAAAASUVORK5CYII="/>
        </svg>
    </svg>

</svg>

**Comment by wangrl2016** [comment]
The svg source file
<svg width="500" height="500"
         viewBox="0 0 500 500" version="1.1"
         xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
         
         <rect width="500" height="500" fill="rgb(153,226,101)"/>
         
        <svg width="203.05876582364974" height="371.1073996087392"
             viewBox="0 0 203.05876582364974 371.1073996087392" version="1.1"
             xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <image x="0" y="0" width="203.05876582364974" height="371.1073996087392"
                   href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFcAAACfCAYAAACMc0W1AAADxUlEQVR4Ae3BQc7dVQHA0fO9Xts4cAPCyIEbUAcOWIGSFEMdsAY04gDDBkwIQ3UV1YBp3IXGxik4a2UBdqC1vT9NdEQMoV/73i1/7jm2bdu2bdu2bdu2bdu2bdu2bdu2bdu2bfs8Vxaq/B83cRu38X18Ezd9cY/wAH/Gh/g9HntOV1dXvlQqlUqleqP6uBfr4+pHlUqlUqlUKpVKpVKpVCpfOs2pOTXnjeZ8vzlrzpqz5qw5a86as+asOWvOmrPmrDlrzpqz5qw5a86as+asOWvOmrPmfL85bzSn5tScmlNzak7NqTk1p+bUnJpTc2pO1zG8HH6Jd53Xu/7rFy7kykLN6T/exF2Xcwe/9YyuTifP6spCPX16E3/Fqy7nIb6Fx57B1Y0bntXJWnfwqst6BT92ASdr3bbGbRcwrFTfs8Z3XcCVhXry5B+45fIe45ZncDWGZzWsVLescdMFnGxnM6xUjuxkO5thpXJkJ9vZDCuVIzvZzmZYqRzZyXY2w0rlyIaVcmjDUjmyYaUc2rBUjmxYqRzZsFIObVgqRzasVI5sWCmHNiyVIxtWKkc2rJRDG5bKkQ0rlSMbVsqhDUvlyIaVypENK+XQhqVyZMNK5ciGlXJow0rlyIalcmTDSjm0YaVyZMNK5ciGpXJkw0o5tGGlcmTDUjmyYaUc2rBSObJhpXJkJ9vZDCuVIztZqSiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKSqVSqVQqlUqlnqifuoZh+zyP8BbuuYZhpfIS+xt+gPuuaVipvKTu43U88BxOts/6A17DA89pWKm8ZH6Nn+GpF2BYqbwknuId/MoLNGyP8BbuecGGlcpiD/FD3HcGw0ploft4HQ+cyfDV9RoeOaNhpbLQI2c2rFSO7GQ7m2GlcmQn29kMK5UjG1bKoQ1L5ciGlcqRnWxnM6xUjuxkO5thpXJkJ9vZDCuVIztZ6+/WeOwChpXyKb7h8j51AcNS/QXfdnl/dAEnK+UjIYQQQgghhBBCCCGEEEIIIYQQ8pEQQgghhBBCruVkqe7SA0IIIYQQQgghhBBCCCGEEEIIPaS7hBBCCCGEEHIdJ2s9xs9d1jv4pws4WSnkrnwghBBCCCGEEEIIIYQQQggh5AO5K4QQQgghhBByLcNS+Z/38HW87Xx+g/dc0MnL4Sl+gjfxiRfrE9zB23jqgoaV8lm/wz3cwRv4Dl7B13xx/8JD/Akf4i4e27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27btK+vfsoq+JRdGUNsAAAAASUVORK5CYII="/>
        </svg>
</svg>

**Comment by wangrl2016** [comment]
<svg width="500" height="500"
         viewBox="0 0 500 500">
         <rect width="500" height="500" fill="rgb(153,226,101)"/>
        <svg width="203.05876582364974" height="371.1073996087392"
             viewBox="0 0 203.05876582364974 371.1073996087392" >
            <image x="0" y="0" width="203.05876582364974" height="371.1073996087392"
                   href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFcAAACfCAYAAACMc0W1AAADxUlEQVR4Ae3BQc7dVQHA0fO9Xts4cAPCyIEbUAcOWIGSFEMdsAY04gDDBkwIQ3UV1YBp3IXGxik4a2UBdqC1vT9NdEQMoV/73i1/7jm2bdu2bdu2bdu2bdu2bdu2bdu2bdu2bfs8Vxaq/B83cRu38X18Ezd9cY/wAH/Gh/g9HntOV1dXvlQqlUqleqP6uBfr4+pHlUqlUqlUKpVKpVKpVCpfOs2pOTXnjeZ8vzlrzpqz5qw5a86as+asOWvOmrPmrDlrzpqz5qw5a86as+asOWvOmrPmfL85bzSn5tScmlNzak7NqTk1p+bUnJpTc2pO1zG8HH6Jd53Xu/7rFy7kykLN6T/exF2Xcwe/9YyuTifP6spCPX16E3/Fqy7nIb6Fx57B1Y0bntXJWnfwqst6BT92ASdr3bbGbRcwrFTfs8Z3XcCVhXry5B+45fIe45ZncDWGZzWsVLescdMFnGxnM6xUjuxkO5thpXJkJ9vZDCuVIzvZzmZYqRzZyXY2w0rlyIaVcmjDUjmyYaUc2rBUjmxYqRzZsFIObVgqRzasVI5sWCmHNiyVIxtWKkc2rJRDG5bKkQ0rlSMbVsqhDUvlyIaVypENK+XQhqVyZMNK5ciGlXJow0rlyIalcmTDSjm0YaVyZMNK5ciGpXJkw0o5tGGlcmTDUjmyYaUc2rBSObJhpXJkJ9vZDCuVIztZqSiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKSqVSqVQqlUqlnqifuoZh+zyP8BbuuYZhpfIS+xt+gPuuaVipvKTu43U88BxOts/6A17DA89pWKm8ZH6Nn+GpF2BYqbwknuId/MoLNGyP8BbuecGGlcpiD/FD3HcGw0ploft4HQ+cyfDV9RoeOaNhpbLQI2c2rFSO7GQ7m2GlcmQn29kMK5UjG1bKoQ1L5ciGlcqRnWxnM6xUjuxkO5thpXJkJ9vZDCuVIztZ6+/WeOwChpXyKb7h8j51AcNS/QXfdnl/dAEnK+UjIYQQQgghhBBCCCGEEEIIIYQQ8pEQQgghhBBCruVkqe7SA0IIIYQQQgghhBBCCCGEEEIIPaS7hBBCCCGEEHIdJ2s9xs9d1jv4pws4WSnkrnwghBBCCCGEEEIIIYQQQggh5AO5K4QQQgghhBByLcNS+Z/38HW87Xx+g/dc0MnL4Sl+gjfxiRfrE9zB23jqgoaV8lm/wz3cwRv4Dl7B13xx/8JD/Akf4i4e27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27Zt27btK+vfsoq+JRdGUNsAAAAASUVORK5CYII="/>
        </svg>
</svg>

**Comment by wangrl2016** [comment]
The svg file
[next.zip](https://github.com/RazrFalcon/resvg/files/6240418/next.zip)

**Comment by wangrl2016** [comment]
There is an svg, the svg contains a base64 png which has alpha channel.

The png original size is 87x159, but we change the width and height to 174x318.

When I use resvg to render the svg file, we can see there is shadow in the png edge, like the above picture.

**Comment by wangrl2016** [comment]
<image x="0" y="0" width="174" height="318" href="" />

**Comment by wangrl2016** [comment]
Have res
