### ISSUE TITLE
reword error-message: Memory allocation failed

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#368]
It is the Micro-SVG-file of https://github.com/RazrFalcon/resvg/issues/257 and I cet several warnings of 
```bash
Warning (in resvg::filter:264): Memory allocation failed while processing the 'aE' filter. Skipped.
Warning (in resvg::filter:264): Memory allocation failed while processing the 'aE' filter. Skipped.
Warning (in resvg::filter:264): Memory allocation failed while processing the 'aE' filter. Skipped.
```

However it only uses ~100MB RAM, so I think might not be an endless loop (as #257) , it might be memory-problem?

### SVG
[in.svg.txt](https://github.com/RazrFalcon/resvg/files/6246226/in.svg.txt)

### Copyright

source:  https://commons.wikimedia.org/wiki/File:Dojikko2.3.svg

author: User:Niabot

license: https://creativecommons.org/licenses/by-sa/3.0/

**Comment by RazrFalcon** [comment]
This is actually just a wrong error. This simply means that it tries to allocate a 0x0 image. I will have to reword it.

But the reason it takes so long is the same as for #257
