### ISSUE TITLE
Incorrect clipPath when processing svg containing symbols

### ISSUE THREAD

**Issue by alec-deason** [RazrFalcon/resvg#369]
When processing an input svg which contains symbols usvg creates clipPaths which appear to be incorrect and also dramatically slow down rendering.

This gist contains an example of the problem: https://gist.github.com/alec-deason/3ca9d1a5d721ef0c2571246303dad57e

The raw_input.svg is a file created by the Verovio music engraving tool which includes <symbol>s.

The usvg_output.svg file is the result of running raw_input.svg through usvg which shows the incorrect clipPaths cutting the note heads in half.

If I manually remove those paths from usvg_ouput.svg then the rendered image appears correct, no more clipped notes, and rendering in resvg is approximately 100 times faster.

This may be related to #363 since the reporter on that issue mentions performance problems related to unnecessary clipPaths

**Comment by RazrFalcon** [comment]
The fix is trivial. 

The reason why `clipPath` is slow is because your image is pretty large and resvg does clipping for the whole image.
