### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#370]
I'm going to republish/reshare [the resvg-test-suite](https://github.com/RazrFalcon/resvg/tree/master/tests/svg) on [Wikimedia Commons](https://commons.wikimedia.org/wiki/User:JoKalliauer/SVG_test_suites#ReSVG-Test-suite) , using this [Template](https://commons.wikimedia.org/wiki/User:JoKalliauer/SVG_test_suites/resvg_Info) .
The svgs are published under the MIT-License (not [MPL2.0](https://www.mozilla.org/en-US/MPL/2.0/)).

With [MIT](https://github.com/RazrFalcon/resvg/tree/master/tests#license) you mean the [Expat License not the X11-License](https://en.wikipedia.org/wiki/MIT_License#License_terms), which differ imho just the additional last sentence
>Except as contained in this notice, the name of RazrFalcon shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Software without prior written authorization from RazrFalcon.

GitHub uses the [Expat-MIT-license](https://choosealicense.com/licenses/mit/), without that last sentence.

**Comment by RazrFalcon** [comment]
Yes, the test suite is under MIT. Not sure about the variant thought. Expat I guess.

Note that PNGs in `resvg/tests/png` and `resvg-test-suite/png` are different. resvg contains pngs generated by resvg itself. This is used for regression testing. resvg-test-suite, on the other hand, contains carefully selected pngs that show the expected rendering results.

**Comment by RazrFalcon** [comment]
`resvg/tests/svg` and `resvg-test-suite/svg` are exactly the same. PNGs are different, as described above. And you don't need anything else. Just those two dirs.

**Comment by JoKalliauer** [comment]
> resvg-test-suite, on the other hand, contains carefully selected pngs that show the expected rendering results.

**Is https://github.com/RazrFalcon/resvg-test-suite/blob/master/png/a-alignment-baseline-001.png correct?**
Chrome, which is [correct](https://github.com/RazrFalcon/resvg-test-suite/blob/master/results.csv), renders it differently.

The first file in https://commons.wikimedia.org/wiki/User:JoKalliauer/SVG_test_suites/all_Images is somehow representative to understand the table and the "Expected PNG" should imho be correct.

PS: Wikimedia does not allow uploading exact duplicates. I used a md5sum-hash to identify, remove duplicates and then link duplicates to the uploaded file.

**Comment by RazrFalcon** [comment]
No idea. Welcome to the SVG world, where nothing is certain. Seriously though, I have no idea how it should actually be rendered and I haven't looked into it much. Chrome is the only app that renders text under the baseline, so I'm not sure we can use this as a proof of some sort.

**Comment by RazrFalcon** [comment]
I finally understood the issue about `a-alignment-baseline-001`. Yes, PNG is wrong. I still not sure how exactly it should be rendered, but I assume that Chrome is correct.
