### ISSUE TITLE
slow on large dimensions

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#371]
resvg is extremly fast for simple files and small dimensions (compared to others), however it has more extremely slow renderings compared to others, which ruins the average time of renderings.

Inkscape has a bad performance for small files (e.g. resvg-test-suite), however for large files it is often the fastest.

Batik seems to use ~2CPUs, resvg is in my experience limited to one CPU, librsvg/Inkscape has i guess some, but hardly parallel-processing

## slow-file for 2.636 × 4.235
![](https://upload.wikimedia.org/wikipedia/commons/archive/9/91/20210406204111%21AntigenicShift_HiRes.svg)

| |resvg|librsvg|inkscape|batik (uses ~2CPUs)|
|---|---|---|---|---|
|real time|2m6,226s|0m11,346s|0m4,546s|0m8,992s

## 373 × 600
![](https://upload.wikimedia.org/wikipedia/commons/9/91/AntigenicShift_HiRes.svg)

| |resvg|librsvg|inkscape|batik (uses ~2CPUs)|
|---|---|---|---|---|
|real time|0m1,727s|0m0,385s|0m1,463s|0m1,463s

## Copyright

source: https://commons.wikimedia.org/wiki/File:AntigenicShift_HiRes.svg

author: https://commons.wikimedia.org/wiki/User:Mouagip

license: Public Domain

**Comment by RazrFalcon** [comment]
resvg indeed has an inefficient large images handling, because of the way layers are handled (clipping is the most common one). But the provided image doesn't have layers, so this is a different issue. Will investigate.

**Comment by JoKalliauer** [comment]
PS: The 373x600 image was optimized, so it is not only a scaled down svg of the other.

**Comment by RazrFalcon** [comment]
Thanks to 4db63614ae06c1d9598ceeafad7e967c04929d57 resvg is only 2x slower on my machine now.

**Comment by JoKalliauer** [comment]
> Thanks to [4db6361](https://github.com/RazrFalcon/resvg/commit/4db63614ae06c1d9598ceeafad7e967c04929d57) resvg is only 2x slower on my machine now.

Thanks Much faster now:

https://upload.wikimedia.org/wikipedia/commons/archive/9/91/20210406204111%21AntigenicShift_HiRes.svg limited to one cpu: (tested on different computer)

|resvg|librsvg|inkscape|batik|
|---|---|---|---|
|18,392s|6,317s|2,654s|6,387s|
