### ISSUE TITLE
Chained feImage do not work

### ISSUE THREAD

**Issue by afdw** [RazrFalcon/resvg#372]
The following works as I expect (renders a green square):
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="512" height="512" viewBox="0 0 512 512">
    <defs>
        <g id="compositing-group-0">
            <rect x="0%" y="0%" width="100%" height="100%" fill="green"/>
        </g>
        <filter id="filter-0">
            <feImage xlink:href="#compositing-group-0"/>
        </filter>
    </defs>
    <g filter="url(#filter-0)">
        <rect x="0%" y="0%" width="100%" height="100%"/>
    </g>
</svg>
```

But the following does not work in resvg (I get transparent output), where as Chrome and r-svg give the same result as the first example:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="512" height="512" viewBox="0 0 512 512">
    <defs>
        <g id="compositing-group-0">
            <rect x="0%" y="0%" width="100%" height="100%" fill="green"/>
        </g>
        <filter id="filter-0">
            <feImage xlink:href="#compositing-group-0"/>
        </filter>
        <g id="compositing-group-1" filter="url(#filter-0)">
            <rect x="0%" y="0%" width="100%" height="100%"/>
        </g>
        <filter id="filter-1">
            <feImage xlink:href="#compositing-group-1"/>
        </filter>
    </defs>
    <g filter="url(#filter-1)">
        <rect x="0%" y="0%" width="100%" height="100%"/>
    </g>
</svg>
```

Is it ought to work? Or I am doing something wrong?

**Comment by RazrFalcon** [comment]
Yes, `compositing-group-0` is removed for some reason.

**Comment by RazrFalcon** [comment]
Turns out this is a pretty serious, fundamental bug. It will take some time to fix it. 
Thanks for reporting.

**Comment by afdw** [comment]
If you are interested, this was discovered during work on the [Work on the SVG backend](https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/152) in Cairo.

My implementation of [the Cairo operators](https://cairographics.org/operators/) generates lots or masks and filters, because I did not found a better solution. Example of a generated file (far from the worst one): [operator-www.svg11.argb32.out.svg.zip](https://github.com/RazrFalcon/resvg/files/6292917/operator-www.svg11.argb32.out.svg.zip).

In r-svg they seem to take exponentially long to render. For example, I did not manage to wait for this one: 
[record1414x-select-font-face.svg11.argb32.out.svg.zip](https://github.com/RazrFalcon/resvg/files/6292919/record1414x-select-font-face.svg11.argb32.out.svg.zip). Works "fine" in Chrome though.

So this is just a remark of what is possible while you are implementing this.

Thanks for you work, by the way. [You test page](https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html) was especially useful as an implementation-(implemented features) matrix.

**Comment by RazrFalcon** [comment]
Nice.

`feImage` is a weird one. We have to have a completely custom logic just for it, which produces a lot of bugs. And `feImage` support in general is pretty bad across all implementations.

>You test page was especially useful

Thanks! It was intentionally made as a separate project to simply future SVG libs development.
