### ISSUE TITLE
SVG has an invalid size

### ISSUE THREAD

**Issue by mothsART** [RazrFalcon/resvg#373]
Hi,

Firstable, thanks for this awesome lib!

I used it on different kind of svg files and some doesn't been parse.

This svg example:
```xml
<? xml version = "1.0" encoding = "UTF-8" standalone = "no"?>
<svg>
     <circle cx = "100" cy = "100" r = "100" />
</svg>
```

will interprated by some other svg engine like this:
```xml
<? xml version = "1.0" encoding = "UTF-8" standalone = "no"?>
<svg
    xmlns = "http://www.w3.org/2000/svg"
    viewBox = "0 0 200 200">
    <circle cx = "100" cy = "100" r = "100" />
</svg>
```
In other word, several engine add a default xmlns if it's empty and define a viewbox adjust on the content if the viewbox isn't explicilty defined.

I'm ok that svg is malformed like you say here https://github.com/RazrFalcon/resvg/issues/192, but can you consider an ** ugly ** option for integrate it (or converting)?

If this engine is integrated on an app design for "non dev", malformed svg is a difficult speech especially if svg was produce by an application.

**Comment by RazrFalcon** [comment]
1. `<? xml` is malformed. The space there is not allowed.
2. `xmlns` is mandatory. Try opening you file in the browser. It will not be rendered.
3. `resvg` doesn't support size autodetection, so an SVG without `viewBox` or `width`/`height` is still malformed.

Yes, some apps can ignore `xmlns`, but this against the standard.

**Comment by mothsART** [comment]
Ok, tks for the quick reply.

1. a mistake, ignore it
2. ok, i will find a solution for my usage and understand your choise
3. is it a possible development ? (Sure, seems a very complex algo)

**Comment by RazrFalcon** [comment]
Yes, it would be done eventually: #40
