### ISSUE TITLE
<use/> elements fail to render

### ISSUE THREAD

**Issue by Aerdan** [RazrFalcon/resvg#377]
I have an [SVG document](https://freki.aerdan.org/pride3.svg) which renders my `<use/>` elements in Firefox, but [does not in `resvg`](https://freki.aerdan.org/resvg.png). The [w3c validator](https://validator.w3.org/check?uri=https%3A%2F%2Ffreki.aerdan.org%2Fpride3.svg&charset=%28detect+automatically%29&doctype=Inline&group=0) claims it to be SVG 1.1.

**Comment by RazrFalcon** [comment]
This is technically SVG 2, because `href` and not `xlink:href` is not allowed in SVG 1.1.

I guess I have to add this to exceptions, because people are asking about this too often.

**Comment by RazrFalcon** [comment]
https://www.w3.org/TR/SVG2/changes.html#linking 

>Deprecated the ‘xlink:href’ attribute in favor of using ‘href’ without a namespace.
