### ISSUE TITLE
Specifying opacity on a <use> leads to a fully opaque element

### ISSUE THREAD

**Issue by romanzes** [RazrFalcon/resvg#384]
Here is the SVG that is rendered incorrectly: [use_with_opacity.svg.zip](https://github.com/RazrFalcon/resvg/files/6477477/use_with_opacity.svg.zip)

This is what it looks like in Google Chrome and other browsers:
<img width="300" alt="Screen Shot 2021-05-14 at 6 07 14 pm" src="https://user-images.githubusercontent.com/5735967/118242837-14878880-b4e1-11eb-905b-1fc63b33dffc.png">

This is how resvg renders it:
<img width="300" alt="Screen Shot 2021-05-14 at 6 10 32 pm" src="https://user-images.githubusercontent.com/5735967/118242822-118c9800-b4e1-11eb-94e6-cea7441ffd8e.png">

The SVG consists of `<use>` elements referencing `<symbol>` elements. Symbols don't have opacity specified on them, but uses do. If I move the `opacity` attribute from `<use>` to `<symbol>`, it's rendered correctly.

Old versions of resvg didn't have this issue, it first appeared in this commit: https://github.com/RazrFalcon/resvg/commit/0408fb3cc9907bfbc3d5f4e61c669dcf7ce5d9a9

**Comment by RazrFalcon** [comment]
Yes, any style attributes set on `use` which references `symbol` are ignored.

**Comment by romanzes** [comment]
Thank you for fixing it so quickly!

**Comment by romanzes** [comment]
However, after checking I found that the original SVG I attached to the issue is still rendered the same way. This is because the function returns earlier in this line: https://github.com/RazrFalcon/resvg/blob/59b39affa6c5588a984bb6508ddfe8438c77c29d/usvg/src/convert/use_node.rs#L46

**Comment by RazrFalcon** [comment]
Yes, this is a more complicated case. Not sure how to fix it yet. It will take some time.
