### ISSUE TITLE
part of the image with <pattern> not rendered

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#385]
Reported in
- https://phabricator.wikimedia.org/T20463
- https://commons.wikimedia.org/wiki/Librsvg_bugs#Pattern
- https://gitlab.gnome.org/GNOME/librsvg/-/issues/733

### svg

![20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp.svg](https://gitlab.gnome.org/GNOME/librsvg/uploads/8b0d3c302315d09f6b3b38708f59c1ec/20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp.svg)

### png

|librsvg 2.40|librsvg 2.50|librsvg 2.51|resvg|inkscape|batik|
|---|---|---|---|---|---|
|![20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_librsvg240](https://gitlab.gnome.org/GNOME/librsvg//uploads/9fb50bc32a7541e3021338c52f9ce19c/20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_librsvg240.png)|![20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_librsvg](https://gitlab.gnome.org/GNOME/librsvg//uploads/d735ab18b6238c49a7999743461afcd4/20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_librsvg.png)|![20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_librsvg251](https://gitlab.gnome.org/GNOME/librsvg//uploads/f9c574cd885bd52aab2e4ebebaa84591/20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_librsvg251.png)|![20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_rendersvg](https://gitlab.gnome.org/GNOME/librsvg//uploads/24c63625ce64cd143ae1b084bb02ce9c/20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_rendersvg.png)|![20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_Inkscape](https://gitlab.gnome.org/GNOME/librsvg//uploads/d2bd4b934386e2919fc5e3ecf45ea250/20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_Inkscape.png)|![20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_batik](https://gitlab.gnome.org/GNOME/librsvg//uploads/68d8c20103ec866dd2726736d4d3ed61/20150613092109Grundriss_Burg_HageneckCSOUOCC_SinkUOSCp_batik.png)|

### copyright

source https://commons.wikimedia.org/wiki/File:Grundriss_Burg_Hageneck.svg

author https://commons.wikimedia.org/wiki/User:Sir_Gawain

license https://creativecommons.org/licenses/by-sa/4.0

**Comment by RazrFalcon** [comment]
For this particular image and at this particular scale (viewbox) the physical pattern size is 1x1 px, which is obviously too tiny for any kind of meaningful results. So all you will get is a shade of gray. In my case, it's white.

I would say this is an implementation details and not a bug. Not sure what the spec has to say about it.
