### ISSUE TITLE
CLI piping

### ISSUE THREAD

**Issue by mfauveau** [RazrFalcon/resvg#387]
Any plans to allow piping?

With rsvg-convert I can do:
```
echo 'data' | rsvg-convert
```

With resvg I have to do:
```
echo 'data' > /tmp/input.svg | resvg /tmp/input.svg
```

That would be a useful addition.

Thanks for your hard work.

**Comment by RazrFalcon** [comment]
Yes, it can be implemented fairly easily.

**Comment by RazrFalcon** [comment]
Done.

Note that in this case you have to set `--resources-dir DIR` so `resvg` where to look for referenced files (list fonts, images and stuff).
