### ISSUE TITLE
Image element without width and height

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#388]
I just tested a pretty useless SVG (embedding a completely white png)

### svg
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="0 0 515 512" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <image xlink:href="data:image/png;base64,  
iVBORw0KGgoAAAANSUhEUgAAAQAAAAEAAQMAAABmvDolAAAAA1BMVEX///+nxBvI AAAAH0lEQVR4Xu3AAQkAAADCMPunNsdhWxwAAAAAAAAAwAEhAAABg2UP5AAAAABJ RU5ErkJggg==
"/>
</svg>
```
[svg](https://gitlab.com/inkscape/inbox/uploads/847e2fe6a09a1eb99f2d72d2065b0a0d/2021-05-12S4OcsxCcOscs.svg)

![svg](https://gitlab.com/inkscape/inbox/uploads/847e2fe6a09a1eb99f2d72d2065b0a0d/2021-05-12S4OcsxCcOscs.svg)

### png
|resvg|librsvg 2.48.9|Inkscape|batik
|---|---|---|---|
|wrong (fully transparent)|wrong (fully transparent)|correct (left upper corner white)|chrashes|
|![2021-05-12S4OcsxCcOscs_rendersvg](https://user-images.githubusercontent.com/15687581/119154412-6d5f9f80-ba52-11eb-8442-76a76d8f2ef0.png)|![2021-05-12S4OcsxCcOscs_librsvg](https://user-images.githubusercontent.com/15687581/119154430-72245380-ba52-11eb-8649-b602925ebe5f.png)|![2021-05-12S4OcsxCcOscs_Inkscape](https://user-images.githubusercontent.com/15687581/119154446-77819e00-ba52-11eb-8a15-23610946dda3.png)|--|

## System
Fedora 32

**Comment by RazrFalcon** [comment]
This is because you haven't set `width` and `height`.

My svg test suite already has this case: `e-image-026`. This is an undefined behaviour. I have no idea how it should be handled.

![e-image-026](https://user-images.githubusercontent.com/725494/119156435-e82db800-ba5c-11eb-8128-e78cb932c787.png)

**Comment by RazrFalcon** [comment]
Looks like this is allowed in SVG2: https://www.w3.org/TR/SVG2/geometry.html#Sizing

**Comment by JoKalliauer** [comment]
Sorry I thought the PNG-compression is not supported.

**Comment by RazrFalcon** [comment]
PNG and JPEG are supported, to some extent.

I leave this issue as part of SVG2 effort.
