### ISSUE TITLE
[feature request] Is there a way to specify currentColor

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#390]
Some Wikimedians like [Colorable SVG](https://phabricator.wikimedia.org/T106240), so that you create one SVG and it can be rendered in several colours. librsvg2.48 implemented `--stylesheet=custom.css` see https://gitlab.gnome.org/GNOME/librsvg/-/issues/736#note_1119478 , does resvg has a similar functionality?

**Comment by RazrFalcon** [comment]
No, it always fallbacks to black.

As for stylesheet injection: #277

**Comment by bjorn** [comment]
> No, it always fallbacks to black.

I see this is implemented in the SVG parser:

https://github.com/RazrFalcon/resvg/blob/b8938f406eb0a008e7403451a8dbcade63b02361/crates/usvg-parser/src/style.rs#L147-L150

After reading the comments at #467 I understand that #277 would provide a more complete solution, but maybe it's alright to add support for only setting a current color?

**Comment by RazrFalcon** [comment]
Adding custom currentColor or CSS injection would probably take the same amount of time. Therefore just wait for #277

**Comment by jaydevelopsstuff** [comment]
```rust
svg_data = svg_data.replace("currentColor", color);
```

Just a simple replace after reading the SVG data to a string is working well for me. It's a pretty rudimentary solution and I'm sure there are edge cases but it works alright until a proper injection system is implemented.
