### ISSUE TITLE
writing-mode with pseudo-multiline

### ISSUE THREAD

**Issue by IlyaBizyaev** [RazrFalcon/resvg#391]
Hello! :)

Trying to render two lines of vertical text, I came up with this markup:
```svg
    <text fill="#E7B2AA" x="312" y="281" style="font-size:34px;font-family:Zilla Slab" writing-mode="tb">
        <tspan y="281" dx="0">
            Chaël
        </tspan>
        <tspan y="281" dx="-1.2em">
            Hello
        </tspan>
    </text>
```
In Inkscape, it is rendered like this:
![inkscape](https://user-images.githubusercontent.com/11175213/119840469-b2317d80-bf0d-11eb-8c69-733a5d08a689.png)

With `resvg`:
![writing-mode-tspan](https://user-images.githubusercontent.com/11175213/119839623-f96b3e80-bf0c-11eb-97be-ce2ea1cfca7c.png)

Am I doing things wrong? :)

**Comment by RazrFalcon** [comment]
Yep, this is a bug.

**Comment by JoKalliauer** [comment]
confirm fixed
|svg|ink|resvg|librsvg|batik|
|---|---|---|---|---|
|![svg](https://gitlab.com/inkscape/inbox/uploads/be454d480003c7ec2c6d60eb6a3face3/bugtextrs.svg)|![bugtextrs_Inkscape](https://user-images.githubusercontent.com/15687581/121881424-90a70300-cd0f-11eb-8a24-3cb57e96b4a4.png)|![bugtextrs_rendersvg](https://user-images.githubusercontent.com/15687581/121881440-956bb700-cd0f-11eb-9408-ae7b6ee74fa9.png)|![bugtextrs_librsvg](https://user-images.githubusercontent.com/15687581/121881521-afa59500-cd0f-11eb-8d62-e3067ead07a9.png)|![bugtextrs_batik](https://user-images.githubusercontent.com/15687581/121881537-b3391c00-cd0f-11eb-969e-75160a3abdf9.png)|
