### ISSUE TITLE
Why usvg::Tree doesn't implement Send?

### ISSUE THREAD

**Issue by changhe3** [RazrFalcon/resvg#400]
This makes it impossible to move parsed svgs between threads, and to cache them globally.

**Comment by RazrFalcon** [comment]
Probably because `Tree` is based on `rctree`, aka `std::rc::Rc`, so it's not thread save by design.

**Comment by changhe3** [comment]
I see, so there is no way to make it `Send` without someone writing an `arctree`.

**Comment by RazrFalcon** [comment]
No idea. `Tree` is single-threaded by desing.

**Comment by changhe3** [comment]
I suppose the simplest workaround is to just serialize it to String and deserialize again on another thread.
