### ISSUE TITLE
Let Options take font database by value?

### ISSUE THREAD

**Issue by dhardy** [RazrFalcon/resvg#402]
The `Options` struct takes a `fontdb::Database` by value. This isn't ideal for repeated usage; could it take a reference instead? (I see that the whole `Options` struct is only used by reference, but this still doesn't really work for me — I would like to create `Options` on demand referring to an existing fontdb `Database`.)

https://github.com/RazrFalcon/resvg/blob/8a838f776aa0f1642a61d8becd802efffeb55b19/usvg/src/options.rs#L130

**Comment by RazrFalcon** [comment]
I guess it's possible. Will try to implement this.

**Comment by RazrFalcon** [comment]
Added. A bit ugly, but should work.
