### ISSUE TITLE
[feature request] provide a portable AppImage

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#403]
To be independent on the packed version by the OS, or to use it without sudo-rights, an [AppImage](https://en.wikipedia.org/wiki/AppImage) would be great. I know [Inkscape provides appimages](https://inkscape.org/release/inkscape-1.1/gnulinux/appimage/) (for every [development-version](https://inkscape.org/release/inkscape-dev/gnulinux/appimage/dl/)).

**Comment by RazrFalcon** [comment]
AppImage of what? resvg/usvg? They are statically linked and portable by default.
