### ISSUE TITLE
render_patch 

### ISSUE THREAD

**Issue by janakg** [RazrFalcon/resvg#404]
Hi, thanks for this amazing library @RazrFalcon 

I am just wondering is there an easier way to implement a patch update to the pixmap instead of rerendering all nodes for updates. The use case is partial updates to the pixmap as we do in virtual dom. I'd like to get your ideas to implement the same by extending render_node function.

Similar to virtual_dom_rs

Thanks in advance.

**Comment by RazrFalcon** [comment]
resvg isn't designed for a live updates. It has to be rewritten from scratch do so. You don't have to rewrite usvg though.

**Comment by janakg** [comment]
Sure, it helps. Thanks.
