### ISSUE TITLE
Support `mix-blend-mode`

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#421]
https://www.w3.org/TR/compositing-1/#mix-blend-mode

**Comment by yisibl** [comment]
librsvg 2.49.0
https://gitlab.gnome.org/GNOME/librsvg/-/issues/607

**Comment by yisibl** [comment]
Here's a use case for using `mix-blend-mode`: http://shan-shui-inf.lingdong.works/

**Comment by yisibl** [comment]
Thanks!
