### ISSUE TITLE
Question: vc_redist.x64.exe

### ISSUE THREAD

**Issue by paulushub** [RazrFalcon/resvg#424]
How does the `viewsvg-win.zip` distribution handles the included `vc_redist.x64.exe`? There is no readme or information on this.
Any plan to release `resvg.exe` only package, for console applications?

**Comment by RazrFalcon** [comment]
It should be executed manually. Will add a readme.

Yes, I plan to have an automated releases.

**Comment by paulushub** [comment]
Thanks, maybe you can also label the `viewsvg-win.zip` with `x64` to indicate it requires 64-bits windows.
