### ISSUE TITLE
Return name of font 

### ISSUE THREAD

**Issue by Dimon-II** [RazrFalcon/resvg#425]
There is no standard function in Windows that returns the name of a font from a ttf or otf file.
Is it possible to make a wrapper for the **resvg_options_load_font_file** function that will return the string name or names separated by commas?

**Comment by RazrFalcon** [comment]
I think this is way to specific feature for resvg.

Maybe you could use: https://docs.microsoft.com/en-us/windows/win32/api/gdiplusheaders/nf-gdiplusheaders-fontfamily-getfamilyname
