### ISSUE TITLE
Disabling resources-dir when using the CLI

### ISSUE THREAD

**Issue by mwilliamson-foodsteps** [RazrFalcon/resvg#428]
Hello! I'm using using stdin to pass an SVG into the resvg CLI, but that results in the warning `Warning: Make sure to set --resources-dir when reading SVG from stdin.` The SVG shouldn't contain any references to external data, so setting `--resources-dir` is unnecessary. I could set it to an arbitrary directory to make the warning go away, but if possible it'd be better if resvg just produced an error if any external resources are referenced, or at least didn't try to load external resources. Is that possible? I had a look through the CLI arguments, and couldn't see anything that would seem to do that.

In any case, thanks for the tool!

**Comment by RazrFalcon** [comment]
You're expected to set `--resources-dir`. Even to just a random path. 

>if possible it'd be better if resvg just produced an error if any external resources are referenced

`resvg` can't produce errors, only warnings. So this is not an option. If I remove `--resources-dir` warning, you will get random `invalid href` warnings instead, which is even more confusing.

**Comment by mwilliamson-foodsteps** [comment]
Ah, fair enough. I suppose the the ideal thing for my use case would be to have a flag along the lines of "--no-resources-dir", and to have resvg produce a warning only when references to external resources are found in the SVG, but I appreciate that might be a niche use case.

**Comment by RazrFalcon** [comment]
Well, one way or another you would still have to specify a flag...
