### ISSUE TITLE
The export-area-drawing needs to follow the width flag

### ISSUE THREAD

**Issue by yisibl** [RazrFalcon/resvg#432]
```shell
resvg foo.svg foo-out.png --width=900 --export-area-drawing
```
The size of the currently(resvg 0.16.0) generated png is not 900px. I hope that it can always follow the width or height flag, then internally crop the transparent pixels and scale to fill to the specified size.

**Comment by RazrFalcon** [comment]
Yes, it scales first and then crops. It cannot be done backward.

**Comment by yisibl** [comment]
Usually, it is quite common to generate screenshots of a specified size through resvg. Is there a way to achieve it?

**Comment by RazrFalcon** [comment]
Just don't use `--export-area-drawing`. It simply removes the transparency. And I don't know the real image size before rendering. For example, blur effect will expand the image size, but I don't know how much. It is hard to calculate and it is not implemented.

**Comment by yisibl** [comment]
We have initially achieved post-cropping zooming here, but there are more special cases that need to be dealt with.
https://github.com/zimond/rusty-svg/blob/16815de84cb4b38bbc36b80a0ad6e0020543c068/src/lib.rs#L237
