### ISSUE TITLE
Add function to get SVG BBox

### ISSUE THREAD

**Issue by yisibl** [RazrFalcon/resvg#433]
I found that there is a `resvg_get_image_bbox` function, which seems to only be used in the c-api? 

I hope that the bbox of SVG can also be obtained in the resvg API. This is similar to [SVGGraphicsElement.getBBox](https://developer.mozilla.org/zh-CN/docs/Web/API/SVGGraphicsElement/getBBox?language=en-US)(svg root) in the DOM API

Thanks.

**Comment by RazrFalcon** [comment]
`tree.root().calculate_bbox()`

**Comment by yisibl** [comment]
The calculation of calculate_bbox() seems to have some problems

https://github.com/zimond/rusty-svg/pull/15/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R482-R483

Test svg:

```svg
<svg viewBox="-40 0 150 100" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- example from https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform -->
  <g fill="grey"
     transform="rotate(-10 50 100)
                translate(-36 45.5)
                skewX(40)
                scale(1 0.5)">
    <path id="heart" d="M 10,30 A 20,20 0,0,1 50,30 A 20,20 0,0,1 90,30 Q 90,60 50,90 Q 10,60 10,30 z" />
  </g>
  <use xlink:href="#heart" fill="none" stroke="red"/>
</svg>
```

**Comment by yisibl** [comment]
This issue appears to have been fixed via https://github.com/RazrFalcon/resvg/pull/482
