### ISSUE TITLE
Viewsvg is recognized as trojan by Windows Defender

### ISSUE THREAD

**Issue by reknih** [RazrFalcon/resvg#445]
Windows Defender does not allow the user to open the precompiled `viewsvg.exe` because it claims to have found the `Win32/Sabsik.TE.A!ml` trojan within it. The archive with the executable has been obtained from the GitHub releases page.
![Screenshot of the Defender warning](https://user-images.githubusercontent.com/3874949/131824789-4fa9e693-adc9-4828-861e-512366ac7acc.png)

**Comment by RazrFalcon** [comment]
Either Github inserts malware (unlikely) or Defender is simply wrong. Either way there is not much I can do about it.

**Comment by JoKalliauer** [comment]
@reknih 1 out of 66 malware-checkes on https://www.virustotal.com claimed malware: https://www.virustotal.com/gui/file/14d69d2abb34ca57b85703e5060c4906336e518c03288f5822c1dc0f2d7e76cd/detection

@RazrFalcon It is often possible to submit wrong positives to malware-checkers.

**Comment by reknih** [comment]
I have submitted the file to Microsoft Security for false positive analysis.

**Comment by reknih** [comment]
Microsoft has processed the ticket and adjusted Defender security definitions.
