### ISSUE TITLE
Units of font size?

### ISSUE THREAD

**Issue by dhardy** [RazrFalcon/resvg#446]
`Options::font_size` apparently defaults to 12. Units are not specified.  When rendering SVG using this default I get text around 7px tall (though possibly image scaling is involved here).

**Comment by RazrFalcon** [comment]
Should be pixels.

**Comment by dhardy** [comment]
Pixels per EM or pixels (height)? I presume the former, but the latter is what `ab_glyph` uses.

**Comment by RazrFalcon** [comment]
Yes, looks like browsers use 16px by default.
Anyway, SVG without the default font family and size is an UB. I can do whatever I want.
