### ISSUE TITLE
DPI arg seems to be ignored by cargo run

### ISSUE THREAD

**Issue by DavidBJaffe** [RazrFalcon/resvg#451]
I tried `cargo run --release -- --dpi 300 --background white ~/plot.svg ~/plot.png`.  Inspection with Preview on my Mac shows `72` DPI, and indeed that's what I get, regardless of the value given for DPI.  What am I doing wrong?   Thank you!

**Comment by RazrFalcon** [comment]
`--dpi` affect only relative units conversion, like mm. You're probably looking for `--zoom`.

**Comment by DavidBJaffe** [comment]
Just tried it.  `--zoom` does not change the reported DPI (for me).  I believe (but have not verified) that the DPI reported by preview reflects the values shown in the `pHYs` chunk of the PNG file, see https://www.w3.org/TR/2003/REC-PNG-20031110/#11pHYs.  If it seems like the right thing to do, I can directly read that chunk from the file and see what values appear there.  I am also imagining that those values could be modified as a post-processing step, but don't know if that makes sense.

**Comment by RazrFalcon** [comment]
Oh, you are talking about DPI in PNG? No, it always "default". I never modify it. Not even sure if there is a point in doing so.

**Comment by DavidBJaffe** [comment]
Ah, let me explain my motivation.  I believe that if one raises the DPI value, then viewers (like Preview on Mac) show a physically smaller image that is better resolved.  Does that make sense?

**Comment by RazrFalcon** [comment]
I don't think this is how it works. Preview will show the image in the same way, independently from DPI. At least this is how it works for me.

In theory, we could write this property, but I'm not sure any app actually cares about it.

Right now, the `--dpi` value affects only relative length units resolving. That's it.

**Comment by DavidBJaffe** [comment]
OK I may be totally confused.  I'll do an experiment!

**Comment by DavidBJaffe** [comment]
I have done the experiment.  It's complicated.  First, if you make a screenshot on a Mac, then the resulting PNG has an iDOT chunk, and that appears to affect rendering.  The iDOT chunk is an undocumented apple-ism.  Some people have reverse engineered and sort of understand it.

However, this is irrelevant for making _new_ PNG files.  More specifically, if one takes a PNG file generated by resvg, and adds a pHYs chunk after iHDR with pixels per meter = 5669, then opening in Preview will yield an image that is at half the physical size of the original.  This enables higher resolution display of PNGs on a Mac, when the PNGs are opened in Preview.   However, I can't claim that I fully understand the pros/cons of adding such a pHYs chunk, and if I decide to do it, it can be done by modifying the PNG generated by resvg.

**Comment by RazrFalcon** [comment]
Yes, I think this is something that should be done separately. I'm not sure any SVG rendering app does this.

I'm not even sure that the library I use to write PNG supports this.
