### ISSUE TITLE
calculate_bbox sometimes returns f64 max for width and height

### ISSUE THREAD

**Issue by bunnegirl** [RazrFalcon/resvg#455]
i'm not able to provide a minimal example at this time, but i have an svg with several 326x326 sized groups, and i'm fetching them by id for rendering with resvg, for some of these groups (always the same groups) instead of calculating 326x326, it returns the following:

```
ScreenRect(1749 1049 4294967295 4294967295)
```

other groups work as expected:

```
ScreenRect(700 1049 326 326)
```

i suspect that this is a structural problem within my own program somehow, because i have almost identical code in another project doing exactly the same thing just fine on the same svg file.

i've attached the svg file that i'm working on in a zip: [emojiset.zip](https://github.com/RazrFalcon/resvg/files/7147346/emojiset.zip)

**Comment by bunnegirl** [comment]
i have narrowed it down to the following group on line 1201:

```xml
    <g
       id="idle-eyes"
       class="eyes-stroke"
       style="stroke-width:2.11665612;stroke-miterlimit:4;stroke-dasharray:none;stroke-linecap:round;stroke-linejoin:round">
      <path
         d="m 9.099,49.796 h 7.1732"
         fill="none"
         stroke-linecap="round"
         stroke-width="0.560041"
         id="path6112"
         style="stroke-width:2.11665612;stroke-miterlimit:4;stroke-dasharray:none;stroke-linecap:round;stroke-linejoin:round" />
      <path
         d="m 24.606,49.796 h 7.1732"
         fill="none"
         stroke-linecap="round"
         stroke-width="0.560041"
         id="path6114"
         style="stroke-width:2.11665612;stroke-miterlimit:4;stroke-dasharray:none;stroke-linecap:round;stroke-linejoin:round" />
    </g>
```

both of these paths are horizontal lines, which after reading #450 i guess means they don't have a bbox, however they do have a stroke, and that should have usable dimensions. this doesn't really matter in my case, as these are not critical for calculating the bbox as they are firmly inside it.

however there is a validation issue in `calc_node_bbox`, it shouldn't be returning a bbox with f64::MAX as width and height if it's not able to calculate a bbox.

i've rather unintelligently solved the issue locally by comparing the resulting bbox with a new bbox, if they're the same then return `None` and if they're not then the bbox is valid and can be returned.

```rust
            if bbox == Rect::new_bbox() {
                None
            } else {
                Some(bbox)
            }
```

this might cause issues elsewhere however as i'm not really familiar with the code.

**Comment by RazrFalcon** [comment]
Yeah... Looks like I would have to rework bbox calculation logic. The current one is too restrictive.

The problem is that in some cases zero sized (width or height) bboxes are not allowed, but looks like in some cases they do.
