### ISSUE TITLE
Slow for a specific file

### ISSUE THREAD

**Issue by akindle** [RazrFalcon/resvg#457]
This svg file: [FUJI.svg.txt](https://github.com/RazrFalcon/resvg/files/7171749/FUJI.svg.txt) renders anomalously slowly (~261 seconds on my laptop vs 5-15 seconds in various browsers) with resvg.
Building on windows with stable-i686-pc-windows-msvc, rustc 1.53.0, release configuration.
I'm not experienced with profiling rust code, but I think it's related to the feTurbulence filter?
![image](https://user-images.githubusercontent.com/2405627/133471261-4b20c40d-45ee-4fa2-b4cd-93c21d823e4a.png)
![image](https://user-images.githubusercontent.com/2405627/133471315-233a26e1-6a5f-46e3-bbb9-cf27a16f454b.png)
It's not clear to me why `t.fract()` would be a particularly expensive operation

Browser performance isn't great either, so maybe its just a badly designed svg

**Comment by RazrFalcon** [comment]
Yes, `feTurbulence` is a very expensive filter. The original C code uses `rx0 = t - (int)t;`. You could try using it and check if there is a difference.

It should be `let rx0 = t - t as i32 as f32;`

**Comment by akindle** [comment]
changing it to `let rx0 = t - t as i32 as f64;` and `let ry0 = t - t as i32 as f64;` cut the time in half and produced a binary-identical output, interesting!

**Comment by RazrFalcon** [comment]
Looks like a Rust bug to me. Anyway, you can send a pull request if you want.

Dumb question, but are you testing the release build? 261 seems too slow.

**Comment by RazrFalcon** [comment]
Also, you should use i64 there.

**Comment by RazrFalcon** [comment]
Strangely, `fract()` indeed produces a different assembly here: https://godbolt.org/z/M7jvYWv9a

But building using `-C target-cpu=haswell` improves the situation quite a lot.

**Comment by akindle** [comment]
> 
> 
> Looks like a Rust bug to me. Anyway, you can send a pull request if you want.
> 
> Dumb question, but are you testing the release build? 261 seems too slow.

Yeah, should be - `cargo build --release` and then running it from the targets\release\ directory anyway
