### ISSUE TITLE
update kurbo dependency

### ISSUE THREAD

**Issue by james-lawrence** [RazrFalcon/resvg#459]
druid seems locked on version 0.14.x of usvg and resvg pings kurbo to vs 0.8.0. unfortunately druid uses 0.8.1 which caused a [perceived regression](https://github.com/linebender/kurbo/issues/176) in resvg. unfortunately this state of affairs has prevent upgrading usvg in druid and as a result I can't investigate if the newer versions of usvg make it possible to resolve the majority of the issues with svg rendering.

**Comment by james-lawrence** [comment]
@RazrFalcon do you have a test case for the issue caused by the kurbo regression? only place I could find in here that seems related is this [line](https://github.com/RazrFalcon/resvg/blob/7c89269337d0fb4ff673d2a196cffe8926399d81/usvg/src/text/shaper.rs#L671) should be a simple adjust of the value to something like ~0.0041 to fix the value change between 0.8 and 0.8.1. but I don't have any samples handy that trigger that code path.

**Comment by RazrFalcon** [comment]
Just update kurbo and run tests. Some text-on-paths will fail.

The "regression" should be fixed by inverting precession based on the current scale.
