### ISSUE TITLE
Can usvg::Svg size be in percents like 100% when converting to string?

### ISSUE THREAD

**Issue by pashinin** [RazrFalcon/resvg#461]
I want to insert SVG into a web page.
But when I render it to string using 

```
rtree.to_string(&usvg::XmlOptions::default())
```
I get

```
<svg width="200" height="200" viewBox="0 0 200 200" ...
```

Can I somehow change width to be `100%` instead of just exactly `200`?

**Comment by RazrFalcon** [comment]
Currently, no. But I guess it can be added.

On the other hand, I'm not sure what is your uses case is. `usvg` output is designed strictly for parsers. You should not use it on web pages or else.

**Comment by pashinin** [comment]
> `usvg` output is designed strictly for parsers. You should not use it on web pages or else.

Then how can I dynamically create SVG to insert into a web page? I looked [here](https://github.com/RazrFalcon/resvg/blob/master/examples/custom_rtree.rs)

**Comment by pashinin** [comment]
Well, ok, I think I can just write plain SVG as I need)

**Comment by RazrFalcon** [comment]
I guess you are looking for something like: https://crates.io/crates/svg

resvg is a SVG renderer, not SVG generator.
