### ISSUE TITLE
C-API - crop the mastered image

### ISSUE THREAD

**Issue by zcream** [RazrFalcon/resvg#463]
These are the data structures that control the size of the raster image.
Lets say, I wish to fit the image to 1000x1000 but only wish to render a window of 100x100. 
Would that be possible ? 
```
typedef enum resvg_fit_to_type {
    RESVG_FIT_TO_ORIGINAL, /**< Use an original image size. */
    RESVG_FIT_TO_WIDTH, /**< Fit an image to a specified width. */
    RESVG_FIT_TO_HEIGHT, /**< Fit an image to a specified height. */
    RESVG_FIT_TO_ZOOM, /**< Zoom an image using scaling factor */
} resvg_fit_to_type;

typedef struct resvg_fit_to {
    resvg_fit_to_type type; /**< Fit type. */

    /**
     * @brief Fit to value
     *
     * Not used by RESVG_FIT_TO_ORIGINAL.
     * Must be >= 1 for RESVG_FIT_TO_WIDTH and RESVG_FIT_TO_HEIGHT.
     * Must be > 0 for RESVG_FIT_TO_ZOOM.
     */
    float value;
} resvg_fit_to;
```

**Comment by RazrFalcon** [comment]
Do you want to crop the final image or do you want to skip rendering of the other tiles altogether?

**Comment by zcream** [comment]
If the final image has to be cropped, its more efficient to skip rendering of the other tiles. At the current moment, I can crop the final image, I'm curious if a more efficient way can be used.

**Comment by RazrFalcon** [comment]
I guess you are looking for #354

**Comment by zcream** [comment]
OK. So, no support ATM. I am not versed with rust so I cannot work on render.rs - thanks.
