### ISSUE TITLE
usvg slow

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#468]
file: https://gitlab.gnome.org/GNOME/librsvg/uploads/028b1646a203b470ac46c3281c9b12f7/case.svg

## time

|usvg|resvg|librsvg2.50|inkscape|batik|
|---|---|---|---|---|
|86,875s|100,089s|0,331s|1,605s|20,416s|

## Copyright

license:
-no permission
-maybe below Treshhold of orginality

author: https://gitlab.gnome.org/oleksandr.khylobokyi

source: https://gitlab.gnome.org/GNOME/librsvg/-/issues/683

**Comment by Shnatsel** [comment]
I expected it to be slow due to some filter, but that is - surprisingly - not the case.

38% of the time is spent in `usvg::converter::is_id_used`. And another 63% in `rctree::NodeEdge::next_item`, mostly on incrementing reference counts.

Profile: https://share.firefox.dev/3pDAEK2

**Comment by RazrFalcon** [comment]
A weird edge-case. Too many very heavy patterns.
