### ISSUE TITLE
Return errors instead of crashing

### ISSUE THREAD

**Issue by HappySeaFox** [RazrFalcon/resvg#469]
Hi! Thanks for the great library! :)

I use the `c-api` binding in resvg-0.19. I noticed that my `C++` application crashes if I provide `NULL` as options to `resvg_parse_tree_from_data()`. Maybe there are more cases to reproduce the issue unknown to me.

The request is to return an error and print a warning in such cases, but not to crash the whole application.

Thanks in advance.

**Comment by RazrFalcon** [comment]
This is intentional. There is an assert inside that checks for NULLs. You have to check it beforehand. I will update the docs.

**Comment by RazrFalcon** [comment]
Well, this way `options` will still we be allocated internally, so it doesn't matter. It will only make API more complicated.
