### ISSUE TITLE
[Question] about license

### ISSUE THREAD

**Issue by ssssota** [RazrFalcon/resvg#470]
I created a library called [svg2png-wasm](https://github.com/ssssota/svg2png-wasm).
I am using this library internally. (It is very easy to use and I appreciate it).

I apologize for not being familiar with OSS licensing.
Is it possible to distribute svg2png-wasm under the MIT license?
(I'm currently applying MPL-2.0 on a temporary basis).

https://www.mozilla.org/en-US/MPL/2.0/FAQ/#distribute-my-binaries
I think svg2png-wasm falls into this section.
I am aware that resvg is compiled to WebAssembly, so it is not a redistribution of the source code.

Please forgive me if this is not a direct problem with resvg.

**Comment by RazrFalcon** [comment]
Good question. I don't know actually. I think MPL allows you to include "binaries" to your own project, no matter what license do you use. Everything should be just fine as long as you're not modifying resvg in any way and mention that your app uses it.
