### ISSUE TITLE
[μsvg] convert SVG 2.0 to micro SVG 1.1

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#477]
My library/framework/language/software doesn't have a good SVG library, and only supports the current SVG 1.1-Standard.

I would like to convert SVG 2.0 to micro SVG 1.1 (as much as possible) to be compatible with my library/framework/language/software.

I would like to have a option to output a micro SVG 1.1 (I don't mind if it is buggy/slow, but the most common features should be implemented).

**Comment by RazrFalcon** [comment]
>I don't mind if it is buggy/slow

I do. 

I will try to flatten alpha. Will see if it would work.

**Comment by JoKalliauer** [comment]
> > I don't mind if it is buggy/slow
> 
> I do.

Sorry for writing unclear: I meant the default output (SVG 2.0) should be fast and almost bug-free (especially for resvg), but I prefer buggy&slow SVG 1.1-convertion than having nothing (So Conversion to SVG 1.1 could be a post-process.)

**Comment by JoKalliauer** [comment]
confirm fix, using `cargo install usvg resvg --force --git https://github.com/RazrFalcon/resvg/`
