### ISSUE TITLE
Drop shadow filter is extremely slow

### ISSUE THREAD

**Issue by Fancyflame** [RazrFalcon/resvg#478]
![image](https://user-images.githubusercontent.com/31250625/140936929-f69433b7-d047-4de9-a38f-49e5f3efef84.png)
![image](https://user-images.githubusercontent.com/31250625/140936564-2a68655b-edbb-4927-9aa7-7d5a9fed853c.png)
![image](https://user-images.githubusercontent.com/31250625/140936414-eeab0471-b4fe-44d4-a2a9-34e8b8661e36.png)
![image](https://user-images.githubusercontent.com/31250625/140936304-53a47901-8816-44d7-8db8-ad1dea39b473.png)
Rendering such a picture, it unexpectedly costs 800+ms per frame. Why is this so slow, and how to fasten it?

**Comment by RazrFalcon** [comment]
This is actually pretty fast for a CPU blur.

>Why is this so slow

Because it's a CPU-based, non-SIMD blur.

>how to fasten it

Rewrite [blur](https://github.com/RazrFalcon/resvg/blob/master/svgfilters/src/box_blur.rs) using SIMD.

**Comment by RazrFalcon** [comment]
Also, for GUI stuff, a typical use case for resvg will be to render SVG into a bitmap first and then render a bitmap on screen. No need to render SVG each time/frame.

**Comment by Fancyflame** [comment]
> Also, for GUI stuff, a typical use case for resvg will be to render SVG into a bitmap first and then render a bitmap on screen. No need to render SVG each time/frame.
Yeah, I'm trying to make a GUI library myself. I am using resvg to render all of the stuff. When I was about to implement `box-shadow` effects like CSS does, I encountered this problem. You're right if I just have one fixed scale svg picture, but in my case, when the window is resized, all of the things need to be redraw. Thus, I think only using CPU to render GUI does not sound though.
By the way, what about supporting multi-thread renderer to fasten the speed?

**Comment by RazrFalcon** [comment]
>Thus, I think only using CPU to render GUI does not sound though.

Using CPU to render UI is no go in 2021. In the end of the day, you would have to blend multiple layers on a 4k canvas. Doing this at least 60 times per second is possible only on GPU.

>By the way, what about supporting multi-thread renderer to fasten the speed?

It would improve performance only in a very specific cases. `resvg` is not designed for realtime rendering. What you need is `usvg` + some GPU canvas library. And the only choice you have, afaik, is Skia (not tiny-skia that resvg uses, the original one). They even added an SVG support recently.

**Comment by Fancyflame** [comment]
Thanks, I'll try other renderers.
