### ISSUE TITLE
Release v0.2.0 on crates.io

### ISSUE THREAD

**Issue by stphan-arch** [RazrFalcon/resvg#48]
Hi,

I saw that a new version [v0.2.0](https://github.com/RazrFalcon/resvg/releases/tag/v0.2.0) was released yesterday.
It would be nice to have this version also available on [crates.io](https://crates.io) in the near future.
Thanks for your effort!

Best regards.

**Comment by RazrFalcon** [comment]
As soon as I fix [#50196](https://github.com/rust-lang/rust/issues/50196).

**Comment by RazrFalcon** [comment]
Done.
