### ISSUE TITLE
[μsvg] Warning (in usvg::svgtree::parse:66): Failed to parse stop-color value: 'rgba(255,255,255,255)'.

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#490]
## command
`cargo install usvg resvg --force --git https://github.com/RazrFalcon/resvg/`

`usvg --version`
0.14.1

## Input
`stop-color="rgba(189,198,201,255)"`
![Input.svg](https://gitlab.com/inkscape/inbox/uploads/ec50dfd0e1ce57601030da8b37942736/Input.svg)

## Output
` stop-color="#000000"`
![Output.svg](https://gitlab.com/inkscape/inbox/uploads/84efd1a11868b06eb250e4e60679650b/Output.svg)

## Diff
![Screenshot from 2021-12-09 09-16-40](https://user-images.githubusercontent.com/15687581/145359620-6956feb0-261f-41e6-8699-1109ceaf2fca.png)

**Comment by RazrFalcon** [comment]
>0.14.1

This is some very old version. The latest one is 0.19

**Comment by JoKalliauer** [comment]
> This is some very old version. The latest one is 0.19

Thanks, I somehow had an old symbolic link in ~/bin/usvg. (I use 3 different OS.)

Solved, sorry for the noise
