### ISSUE TITLE
Ghostscript_Tiger.svg is rendered bottom-right quarter only

### ISSUE THREAD

**Issue by mhfan** [RazrFalcon/resvg#492]
Original svg file:

https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg

resvg rendered:

![tiger-resvg](https://user-images.githubusercontent.com/1171428/146346408-b076fb91-b363-46de-a211-1b24c645131f.png)

Correct should be:

![tiger](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Ghostscript_Tiger.svg/512px-Ghostscript_Tiger.svg.png)

**Comment by RazrFalcon** [comment]
Works fine for me. How exactly are you "rendering" it.

**Comment by mhfan** [comment]
yes, it seems I made mistakes, used a wrong svg file, sorry!
