### ISSUE TITLE
Negative scaling and coordinates lead to misposition

### ISSUE THREAD

**Issue by antmelnyk** [RazrFalcon/resvg#494]
Hey there, I hope you're having a good new year @RazrFalcon! 🍾 

There is a difference in behavior between `resvg` and Chrome rendering when negative scaling and coordinates are involved.
See this cryptic SVG with world Hello being mirrored on the sides of the image. Chrome renders it correctly on the top image (almost what I need), `resvg` is completely off on the bottom image.

SVG code (apologies for very long base64 image line):
Check out links inside `<g clip-path="url(#area)">` that refer the image. You can see that I just change `x, y` coordinates and `transform(scale())` values.

I'm trying to wrap my head around what is wrong with either my understanding or `resvg` rendering and/or transform property, but it's hard to think in this 4D chess format. Would you kindly clarify what could cause the difference? Thank you.

```
<?xml version="1.0" encoding="UTF-8"?>
<svg:svg xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="3300" id="canvas" preserveAspectRatio="xMidYMid meet" viewBox="0 0 3900 3300" width="3900">

	<svg:defs>
		<clipPath id="area">
			<rect width="14740.1574803149" height="12472.4409448819" />
		</clipPath>

		<svg:image overflow="visible" width="118.110236220472in" height="94.4881889763782in" id="template_image" xlink:href="data:image/png;........." />
		"
	</svg:defs>
	<svg:g fill="#6ea748" id="color_background">
		<svg:svg height="100%" id="artboard" viewBox="0 0 14740.1574803149 12472.4409448819" width="100%" x="0" y="0">
			<g clip-path="url(#area)">
				<svg preserveAspectRatio="xMidYMid slice" x="17.7165354330709in" y="17.7165354330709in" width="118.110236220472in" height="94.4881889763782in">
					<use xlink:href="#template_image" />
				</svg>
				<svg x="-100.393700787401in" y="17.7165354330709in" width="118.110236220472in" height="94.4881889763782in">
					<use xlink:href="#template_image" x="-100%" transform="scale(-1,1)" />
				</svg>
				<svg x="-100.393700787401in" y="-76.7716535433073in" width="118.110236220472in" height="94.4881889763782in">
					<use xlink:href="#template_image" x="-100%" y="-100%" transform="scale(-1,-1)" />
				</svg>
				<svg x="17.7165354330709in" y="-76.7716535433073in" width="118.110236220472in" height="94.4881889763782in">
					<use xlink:href="#template_image" y="-100%" transform="scale(1,-1)" />
				</svg>
				<svg x="135.826771653543in" y="-76.7716535433073in" width="118.110236220472in" height="94.4881889763782in">
					<use xlink:href="#template_image" x="-100%" y="-100%" transform="scale(-1,-1)" />
				</svg>
				<svg x="135.826771653543in" y="17.7165354330709in" width="118.110236220472in" height="94.4881889763782in">
					<use xlink:href="#template_image" x="-100%" transform="scale(-1,1)" />
				</svg>
				<svg x="135.826771653543in" y="112.204724409449in" width="118.110236220472in" height="94.4881889763782in">
					<use xlink:href="#template_image" x="-100%" y="-100%" transform="scale(-1,-1)" />
				</svg>
				<svg x="17.7165354330709in" y="112.204724409449in" width="118.110236220472in" height="94.4881889763782in">
					<use xlink:href="#template_image" y="-100%" transform="scale(1,-1)" />
				</svg>
				<svg x="-100.393700787401in" y="112.204724409449in" width="118.110236220472in" height="94.4881889763782in">
					<use xlink:href="#template_image" x="-100%" y="-100%" transform="scale(-1,-1)" />
				</svg>
			</g>
			<svg:path d="M 0 0 L 14740.1574803149 0 L 14740.1574803149 12472.4409448819 L 0 12472.4409448819 z M 283.464566929134 283.464566929134 L 14456.6929133858 283.464566929134 L 14456.6929133858 12188.9763779528 L 283.464566929134 12188.9763779528 z" fill="#ffffff" fill-rule="evenodd" id="bleed" opacity="0.8" />
		</svg:svg>
	</svg:g>
</svg:svg>
```

<img width="975" alt="Screenshot 2022-01-05 at 20 10 24" src="https://user-images.githubusercontent.com/17108334/148267426-5bc2e5d8-1115-4692-8a8e-ef0e3544f79e.png">
<img width="786" alt="Screenshot 2022-01-05 at 20 04 50" src="https://user-images.githubusercontent.com/17108334/148267433-02be4e9d-b98a-4bcf-9792-16fd59d48681.png">

**Comment by RazrFalcon** [comment]
Can you send me the whole file?

**Comment by antmelnyk** [comment]
Here you go:
[external_image.svg.zip](https://github.com/RazrFalcon/resvg/files/7817632/external_image.svg.zip)

**Comment by RazrFalcon** [comment]
Some weird nested SVG placement issue is happening. No idea why. Probably some transformations order bug.
Inkscape and librsvg are also broken in the same way. Browsers are fine.

**Comment by antmelnyk** [comment]
Makes sense. Will try to find way around...

The problem is, I *have* correct result rendered with`librsvg` (at least with `rsvg-convert`), it doesn't fail when `image` is wrapped in another SVG like this:

```xml
<svg id="placeholder_front">
  <svg preserveAspectRatio="xMinYMin meet" viewBox="0 0 1 1" width="123.01059890567664%" height="4200%" x="50.0%" y="50.0%" id="560e62174272ec52c33fa4e13bdc98f51" overflow="visible" class="artwork">
    <g transform="rotate(37.000000)">
      <image xlink:href="560e62174272ec52c33fa4e13bdc98f5.png" width="100%" height="100%" x="-50%" y="-50%" />
    </g>
  </svg>
</svg>
```
Also, see I raised that [in this issue](https://github.com/RazrFalcon/resvg/issues/6).

[2.40.16_working.zip](https://github.com/RazrFalcon/resvg/files/7821356/2.40.16_working.zip)
It works on `rsvg-convert` version 2.40.16, but fails on `rsvg-convert` version 2.50.7 😵 
Obviously, the problem here is more in abusing SVG format than implementation failure, but still it's a bummer.

I guess will try to find a way around using `resvg`. I can change SVG to some extent (e.g., I stripped SVG wrapper to reference only `<image>` using `<use>`, but nevertheless have to achieve the same visuals.

**Comment by RazrFalcon** [comment]
I'm not sure what results are you trying to achieve, but you're using a very obscure methods. For example, `preserveAspectRatio` on `image` with SVG content would not work in Chrome and Safari.

A general rule of thumb when it comes to SVG - never write SVG by hand. It would 100% fail in some app or another. Even in resvg test suite, browsers are barely reaching 90% coverage.

I will take a look into when I will have time. Hopefully it would be an easy fix.
