### ISSUE TITLE
explorer-thumbnailer not work on my file explorer

### ISSUE THREAD

**Issue by lili2012** [RazrFalcon/resvg#495]
`regsvr32.exe  server.dll `worked for for a few time and may be because I install/uninstall again and again now regsvr32.exe  server.dll won't show any message and after clean thunbnail cache on my disk file explorer won't show svg thumbnail. 

While [thumpsvg](https://github.com/putara/thumpsvg) is another thumbnail opensource project which depend on resvg. [thumpsvg](https://github.com/putara/thumpsvg) could work properly.  Even though `regsvr32.exe  server.dll `wont work right on my windows file explorer,  I could still get thumbnail through program code even after cleaning disk thumbnail cache, I've tried several times.
```
IThumbnailCache* thumbnailCache;
thumbnailCache->GetThumbnail(psi, MDLThumbnailSide, WTS_FLAGS::WTS_EXTRACT, &sharedBitmap, nullptr, nullptr);
```
I think the different between thumpsvg and explorer-thumbnailer is how they modify registry. I don't know.

**Comment by RazrFalcon** [comment]
Sorry, but I'm not sure what are you trying to do. Are you trying to access Explorer's icons cache?

`explorer-thumbnailer` should work just like [svg-explorer-extension](https://github.com/tibold/svg-explorer-extension). I'm sure it works fine in the Explorer itself. No idea about the winapi.

I'm not a Windows developer, therefore I can't help you much.

**Comment by lili2012** [comment]
I could access Explorer's icons cache, this is totally ok. But file explorer wont show svg thumbnail now.

**Comment by RazrFalcon** [comment]
Are you sure you have a single SVG provider? Maybe there are still some leftovers from other apps?

**Comment by lili2012** [comment]
I found the problem: `HKEY_CLASSES_ROOT\CLSID\{4432C229-DFD0-4B18-8C4D-F58932AF6105}\InprocServer32` 's value is:

C:\Windows\system32\regsvr32.exe

not the right one: 

D:\openSource\resvg\tools\explorer-thumbnailer\target\release\server.dll.  

in `com::registration::get_dll_file_path() ` 
```
GetModuleFileNameA(
        hmodule,
        path.as_mut_ptr() as *mut _,
        MAX_FILE_PATH_LENGTH as _,
    );
```
GetModuleFileNameA will return regsvr32.exe if hmodule is NULL.
I am not familiar rust so I can't fix it. Hope you could help me. Thanks!

**Comment by RazrFalcon** [comment]
@gentoo90 Hi! Any suggestions?

**Comment by gentoo90** [comment]
Yeah, `regsvr32` doesn't work very well with `com` crate. That was one of the reasons why I've [added proper registry values to the installer](https://github.com/RazrFalcon/resvg/pull/315/commits/37aefc1d370c724332cf8c349537f2a2cfb755ed). @lili2012, try uninstalling the thing and reinstalling it with the installer instead of `regsvr32`.

**Comment by lili2012** [comment]
I see. 

Could change  `HKEY_CLASSES_ROOT\CLSID\{4432C229-DFD0-4B18-8C4D-F58932AF6105}\InprocServer32` 's value from

`C:\Windows\system32\regsvr32.exe`
to
`D:\openSource\resvg\tools\explorer-thumbnailer\target\release\server.dll`

**Comment by RazrFalcon** [comment]
@lili2012 

1. You need Inno Setup which will compile this file into an executable. Here is how it works on CI: https://github.com/RazrFalcon/resvg/blob/5c1641631c04de4df3af4dea84ab710aa1914bbb/.github/workflows/tagged-release.yml#L88
