### ISSUE TITLE
feDiffuseLight surfaceScale doesn't scale

### ISSUE THREAD

**Issue by Omnikron13** [RazrFalcon/resvg#500]
When applying the feDiffuseLight filter primitive the value of the surfaceScale attribute has to be manually scaled when changing the output dimensions to produce visually similar output.
This is inconsistent with the behaviour when rendering with e.g. inkscape or imagemagick, and seems to be incorrect.

**Comment by RazrFalcon** [comment]
Can you provide a minimal example SVG?

**Comment by Omnikron13** [comment]
Minimal version of the SVG I noticed this in:

![example](https://user-images.githubusercontent.com/2133262/152290740-6e052642-23fd-4205-8ba2-86bfbba2ecfa.svg)

Rendering this out at, say, 1000x1000 and 4000x4000 yields notably different results.

**Comment by RazrFalcon** [comment]
By the way, this is how it looks in other apps:

![feDiffuseLighting](https://user-images.githubusercontent.com/725494/153717753-168b0b56-4696-4568-80c3-daf0bde64b9c.png)

You're trying to use very advances SVG features and this is always a bad idea.

**Comment by RazrFalcon** [comment]
After some experiments, I think it's just an Inkscape bug. resvg produces almost identical output to Chrome and Firefox and this the only thing that matters.

**Comment by Omnikron13** [comment]
Ohh... My bad, I removed the `kernelUnitLength` attribute from the `feDiffuseLighting` tag and accidentally oversimplified the example image I posted. That is required for the primitive to scale properly as the image is scaled.
Interestingly though if I add that in to the filter of the SVG you linked it scales as I would expect in Firefox, but not in Chrome as far as I can see.

**Comment by RazrFalcon** [comment]
If you're willing to solve this I would suggest creating an issue on https://github.com/w3c/svgwg 
So far, I don't see any clarification in the spec about how this should be handled. if this behaviour is undefined, I can do whatever I want in resvg.
