### ISSUE TITLE
Applying options in C API

### ISSUE THREAD

**Issue by keto33** [RazrFalcon/resvg#505]
I am trying to use the C API, but I have a problem with applying the common options. For example, if applying zoom 2

```
    resvg_fit_to fit_to = { RESVG_FIT_TO_TYPE_ZOOM, 2 };
    resvg_render(tree, fit_to, resvg_transform_identity(), width, height, (char*)surface_data);

    /* RGBA -> BGRA */
    for (int i = 0; i < width * height * 4; i += 4)
    {
        unsigned char r = surface_data[i + 0];
        surface_data[i + 0] = surface_data[i + 2];
        surface_data[i + 2] = r;
    }
```

it does not work. Evidently, the `i` range for the pixels is not right, as `width * height * 4` is for the number of pixels of the original size.

I know it is a stupid question, but how should we apply the options given in `resvg.h` in C?

**Comment by RazrFalcon** [comment]
Your code is correct. `fit_to` scales the SVG, no the `surface_data`.

**Comment by keto33** [comment]
> Your code is correct. `fit_to` scales the SVG, no the `surface_data`.

What is the point of scaling the SVG without scaling the `surface`? We have to increase the dimensions of the `surface` as well to create the PNG pixels.

In the case of zoom 2, it generates the first quarter of the image only. The other three quarters are outside the PNG canvas.

**Comment by RazrFalcon** [comment]
Because resvg cannot "resize"/reallocate `surface_data`. `fit_to` indicates how SVG should be scaled/fit into the provided surface.

If you what to scale SVG by two, you also have to scale the surface by two, by yourself.

**Comment by RazrFalcon** [comment]
The idea behind it is that people already have a surface/pixmap and they want to draw an SVG on top of it. resvg simply access surface's pixels.

**Comment by keto33** [comment]
The idea is that we have the array of pixels `surface_data`. If having the SVG paths, we can further manipulate the output pixels before writing the PNG without altering the core code.

**Comment by RazrFalcon** [comment]
No problem!

Sadly, there is no access to internal SVG data. You have to use Rust for that. Or you can write your own C binding to resvg/usvg. Or just extend resvg's C API to your needs.

It would be externally hard to map resvg tree to C even in read-only way.

**Comment by RazrFalcon** [comment]
Yeah, I should add this example to CI.
