### ISSUE TITLE
pattern not rendered on small thumbnails

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#507]
## Input SVG
![instant insanity nets](https://user-images.githubusercontent.com/15687581/158151833-7c9c6fad-aad3-446e-a139-af65f299ba36.svg)

## Rendering PNG with resvg 0.22.0
![instant insanity nets_rendersvg](https://user-images.githubusercontent.com/15687581/158151919-0534f728-d431-465a-8394-d1932031b06e.png)

## Copyright

author [cmglee](https://commons.wikimedia.org/wiki/User:Cmglee)

license [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0)

source https://commons.wikimedia.org/wiki/File:Instant_insanity_nets.svg

## Similar issues

#259
#385 
#366

**Comment by yisibl** [comment]
The rendering results in resvg 0.22.0 look correct.

![image](https://user-images.githubusercontent.com/2784308/158164060-0feb6153-d11a-4a13-9c15-57c51034a829.png)

**Comment by JoKalliauer** [comment]
@yisibl : If you are using the Commons-Version please use the old version: https://upload.wikimedia.org/wikipedia/commons/archive/1/12/20220314111059%21Instant_insanity_nets.svg

and render it in 96px x 96px, the issue does only occur on small thumbnails

**Comment by RazrFalcon** [comment]
At the original scale the pattern tile is just 2x2 px. No wonder the output is a mess.
I consider this file to be malformed. Out of scope.
