### ISSUE TITLE
C++ API

### ISSUE THREAD

**Issue by N3WWN** [RazrFalcon/resvg#51]
Thank you for resvg!  😃 

I'm liking it very much and it renders SVG files so much better than QtSVG!

I'm opening this issue as a request for a C++ API.

I'd like to be able to use resvg in C++ applications without converting `QString` variables to `char *` for use with `resvg_parse_rtree_from_file()` and `resvg_qt_render_to_image()`.

The reason for this is that filenames and paths in some languages and on some platforms do not behave well when converted to `char *`.

My immediate need is for use with a Qt backend, if that is easier to implement than a complete C++ API.

Thanks for your consideration in adding a C++ API.  If I were more familiar with doing this work, I would do it myself and contribute a PR.

**Comment by RazrFalcon** [comment]
Even with a C++ API you still have to convert QString to std::string. Or do you want a Qt API?

>The reason for this is that filenames and paths in some languages and on some platforms do not behave well when converted to char *.

It's a known issue. resvg C-API requires that `char *` is a valid UTF-8 string, which is still not idea on Windows.

I will add a C++ and Qt-like API.

**Comment by N3WWN** [comment]
Sorry, I suppose you're right 😁   A Qt API would be awesome!

Thanks!

**Comment by RazrFalcon** [comment]
[Added.](https://github.com/RazrFalcon/resvg/tree/master/capi/qt-wrapper) It mimics [QSvgRenderer](http://doc.qt.io/qt-5/qsvgrenderer.html) and has the same behavior. You can check it via [examples/resvg-vs-qtsvg](https://github.com/RazrFalcon/resvg/tree/master/examples/resvg-vs-qtsvg).

It still an alpha and you have to use git version of the resvg.

Hope it what you wanted.
