### ISSUE TITLE
Can resvg support pdf file export?

### ISSUE THREAD

**Issue by origel** [RazrFalcon/resvg#510]
In my work, the function svg convert to png and pdf is required. In the past, I used `rsvg-convert` to finished my work. Recently, I find `rsvg-convert` has some problems in convert svg to png and pdf, resvg can do this work very well. I plan use resvg replace rsvg-convert. But I find resvg can't convert to pdf directly. So,Can resvg support pdf file export?

I also has a propose: 
resvg command args worked such as: "resvg in.svg out.png", In my case, I call resvg command use Java Process Object. When I use resvg tool, I must create two temp files 'in.svg out.png' for resvg, and delete when process end. can resvg support in/out stream for calling. Thanks!

**Comment by RazrFalcon** [comment]
>So,Can resvg support pdf file export?

Not possible and not planned. Really hard.

>can resvg support in/out stream for calling. Thanks!

It does support in steam, but not out. It's easy to implement. I didn't thought it would have any use case. Please open a separate issue for that.

**Comment by origel** [comment]
> It does support in steam, but not out. It's easy to implement. I didn't thought it would have any use case. Please open a separate issue for that.

I try implement it by myself first.
