### ISSUE TITLE
Documentation on using usvg

### ISSUE THREAD

**Issue by cryslith** [RazrFalcon/resvg#511]
I would like to take an SVG file and turn it into essentially just a collection of colored lines that I can process.  Is it possible to do this using usvg?  I couldn't find any example of how to correctly use it and it wasn't clear to me from the API documentation.  Would it be possible to show such an example?

**Comment by RazrFalcon** [comment]
usvg produces SVG paths (albeit simplified), but not "lines". If by lines you mean path flattening then you will have to use a separate crate, like lyon or kurbo.

Can you clarify your task and provide an SVG file example and an expected output?

**Comment by cryslith** [comment]
Sorry for being unclear - path specs would be fine.  When I said "lines" I meant that the SVG files I intend to process consist only of polygons and straight lines, and won't contain any arcs or curves, so path flattening shouldn't be necessary.  For instance from this SVG
![drawing](https://user-images.githubusercontent.com/1123944/162558162-65b80f9e-f775-400b-8bbd-eb2b5a168efb.svg)

I would hope to extract stroke colors and paths like
```
vec![
  ("#000000", "M 10 10 L 40 10 L 40 50 L 10 50 Z"),
  ("#ff0000", "M 10 10 L 20 20 L 10 50"),
]
```

(Sorry, all the coordinates got scaled when I made it in inkscape, but it doesn't matter exactly what the coordinates are as long as they are given in an absolute coordinate system and I don't have to process the transformations myself.)

My understanding is usvg can do this task well but I just couldn't figure out what the right way to call into it would be.

**Comment by RazrFalcon** [comment]
How about this:

```rust
fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() != 2 {
        println!("Usage:\n\tcollect-paths <in-svg>");
        return;
    }

    let mut opt = usvg::Options::default();
    // This line required if your files reference other file.
    opt.resources_dir = std::fs::canonicalize(&args[1]).ok().and_then(|p| p.parent().map(|p| p.to_path_buf()));
    // This line is required if you want to convert text to paths.
    opt.fontdb.load_system_fonts();

    let svg_data = std::fs::read(&args[1]).unwrap();
    let tree = usvg::Tree::from_data(&svg_data, &opt.to_ref()).unwrap();

    for node in tree.root().descendants() {
        if let usvg::NodeKind::Path(ref path) = *node.borrow() {
            if let Some(usvg::Paint::Color(stroke)) = path.stroke.as_ref().map(|s| &s.paint) {
                println!("{:?}: {:?}", stroke, path.data);
            } else {
                println!("no stroke: {:?}", path.data);
            }
        }
    }
}
```

PS: I know that usvg API is complex, but this is because SVG is complex. All those "borrows" required because we have a tree of nodes.

**Comment by cryslith** [comment]
Thank you, this is exactly what I was hoping for.
