### ISSUE TITLE
measureText functionality

### ISSUE THREAD

**Issue by jonmmease** [RazrFalcon/resvg#513]
Firstly, thanks for building and releasing this amazingly impressive library.  Secondly, apologies that this is more of a question than an issue.

The background is that I'm exploring using resvg to render the SVG images produced by the [Vega](https://vega.github.io/vega/) JavaScript data visualization library.  The actual svg rendering seems to work very well. The wrinkle is that in order for Vega to position text accurately while generating an SVG document, it relies on the [`measureText()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText) function of an html canvas. I'd like to work out a way to remove this dependency on the canvas API.

So, I was wondering if it's possible to get this kind of text metric information using something in the resvg technology stack.  Thanks for any guidance you may be able to offer!

**Comment by RazrFalcon** [comment]
Currently, your best bet is https://docs.rs/usvg/0.22.0/usvg/struct.Path.html#structfield.text_bbox We do not preserve that much text layout information right now.
