### ISSUE TITLE
Support CSS 4 color() function

### ISSUE THREAD

**Issue by brian6932** [RazrFalcon/resvg#514]
I'm not particularly knowledgeable on this, just reporting what I saw
```pwsh
❯ resvg -w 128 -h 128 '.\GraphQL Logo (Rhodamine).svg' out.png
Warning (in usvg::svgtree::parse:435): Failed to parse fill value: 'color(display-p3 0.8824 0 0.5961)'. Fallback to black.
```
pretty printed SVG:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="#e10098">
  <style>
    svg{fill:color(display-p3 0.8824 0 0.5961);}
  </style>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M50 6.90308L87.323 28.4515V71.5484L50 93.0968L12.677 71.5484V28.4515L50 6.90308ZM16.8647 30.8693V62.5251L44.2795 15.0414L16.8647 30.8693ZM50 13.5086L18.3975 68.2457H81.6025L50 13.5086ZM77.4148 72.4334H22.5852L50 88.2613L77.4148 72.4334ZM83.1353 62.5251L55.7205 15.0414L83.1353 30.8693V62.5251Z"/>
  <circle cx="50" cy="9.3209" r="8.82"/>
  <circle cx="85.2292" cy="29.6605" r="8.82"/>
  <circle cx="85.2292" cy="70.3396" r="8.82"/>
  <circle cx="50" cy="90.6791" r="8.82"/>
  <circle cx="14.7659" cy="70.3396" r="8.82"/>
  <circle cx="14.7659" cy="29.6605" r="8.82"/>
</svg>
```
![GraphQL Logo (Rhodamine)](https://user-images.githubusercontent.com/18603393/166098893-935f9434-11b4-4d2f-958f-46db31af76c5.svg)

**Comment by RazrFalcon** [comment]
>color(display-p3 0.8824 0 0.5961)

This color is from the CSS Color 4 spec which is still a draft. Out of scope.

**Comment by brian6932** [comment]
@RazrFalcon https://caniuse.com/css-color-function This is the reason?
```svg
  <style>
    svg{fill:color(display-p3 0.8824 0 0.5961);}
  </style>
```
If it is not even supported in basically any browser, why not just ignore this part of the svg instead of falling back to black fill?
Or is that not something possible?

**Comment by RazrFalcon** [comment]
Yes, this feature is part of an unfinilized spec.

By the SVG spec, invalid attribute is just a warning. SVG rendering must not return an error. In the worst case scenario it should simply produce an empty image, but not an error.

**Comment by RazrFalcon** [comment]
Out of scope for the next couple of years.
