### ISSUE TITLE
Proposal for a Resvg github org

### ISSUE THREAD

**Issue by zimond** [RazrFalcon/resvg#516]
Hi Reizner! First of all thank you for years of dedicated work on resvg/usvg. We have been using this library in many products and it works really nice. You may have already noticed, me and @yisibl has been porting resvg to the frontend world via [resvg-js](https://github.com/yisibl/resvg-js), which uses `wasm-bindgen` for wasm32 target, and `napi-rs` for Node.js's NAPI. It turns out that this wrapper library works quite well and is quite recognized and used by the industry. We had a discussion and think that we are not supposed to take the credits. So I'm proposing that maybe we could form a `resvg` github organization and move `resvg`, `resvg-js` and some other related libs (namely some of the building blocks of resvg) to the new organization. I think this is better for branding and letting people know the structure of the whole idea of resvg (especially how it's ported to javascript land). Is this something you like? Or what's your thoughts on all these going on? Thanks again for what you did and your awesome work.

**Comment by RazrFalcon** [comment]
Thanks. I will think about it.

**Comment by RazrFalcon** [comment]
I think it would be too problematic to update all the links and stuff. It's fine as is.
