### ISSUE TITLE
Support RGB hex color notation for length 4 and 8

### ISSUE THREAD

**Issue by demurgos** [RazrFalcon/resvg#518]
I am trying to read some SVG files, however their colors use hex color notation such as `#00FF00FF`. This variant is not supported by `resvg` yet and causes a fallback to black:

```
Warning (in usvg::svgtree::parse:435): Failed to parse fill value: '#00FF00FF'. Fallback to black.
```

The notation is specified in the [CSS spec](https://drafts.csswg.org/css-color/#hex-notation). The 4 digit string should be interpreted as `#rgba`, and the 8-digit version as `#rrggbbaa`.

**Comment by RazrFalcon** [comment]
Yes, this feature is part of SVG 2 support, which is very rudimentary at the moment.
