### ISSUE TITLE
Colored fonts rendering as black

### ISSUE THREAD

**Issue by svk014** [RazrFalcon/resvg#524]
I am trying to render SVG text to PNG with a custom font. The font in question is a colored SVG font. Problem is, the rendered output is always black in color. How do I fix this?

**Comment by RazrFalcon** [comment]
I'm not sure what exactly do you mean by "colored SVG font", but this is probably not supported.
resvg doesn't support TrueType SVG fonts and TrueType bitmap fonts. Only "classic" glyphs.

**Comment by svk014** [comment]
can you recommend a library that supports TrueType SVG fonts?

**Comment by RazrFalcon** [comment]
SVG library? I'm not aware of any. Try librsvg.

**Comment by svk014** [comment]
Thanks a lot @RazrFalcon. I will check it out.
