### ISSUE TITLE
usvg inaccuracy in bounding box calculation

### ISSUE THREAD

**Issue by adri326** [RazrFalcon/resvg#528]
I am using `usvg` (version 0.23.0) to calculate the bounding of an SVG to automatically adjust its `viewBox`; however, the image keeps being cut off:

![image](https://user-images.githubusercontent.com/18118053/181480858-33a7dd40-d682-44ff-ab48-5d9c018d0eaa.png)

I have boiled down the issue to a [simple example](https://github.com/adri326/usvg-bb-bug), which compares the calculation made by `usvg` and by `inkscape` (a bit of conversion had to be done for them to represent the same thing). Running it with a single, complex bézier curve, we get:

## Expected

```
$ bash inkscape.sh
0.490724
0.691381
79.6328
69.0568
```

## Actual

```
$ cargo run
1.4747938305408186
0.8304907860603332
77.5923882709055
66.70245296302193
```

**Comment by RazrFalcon** [comment]
Thanks! See https://github.com/linebender/kurbo/issues/223

**Comment by adri326** [comment]
Oh, grand! Yeah, these are the hardest issues to spot and fix, I'm glad you figured it out.

Can a patch version be published so I just need to bump my Cargo.toml?

**Comment by RazrFalcon** [comment]
Yes, this code is not really used by resvg, so I wan't able to catch it using rendering tests.

I thinks I will bump a version on weekends.
