### ISSUE TITLE
Try to bake transforms when possible

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#534]
We can bake/apply transforms to paths filled/stroked with solid colors.

This is not really a performance optimization, but rather a way to simplify input files even more.

**Comment by yisibl** [comment]
Is it similar to the operation here? https://github.com/zimond/rusty-svg/blob/beb29915d792c153f918b5d00832f44778482e9e/src/lib.rs#L256

**Comment by RazrFalcon** [comment]
Yes, very similar. But without allocations and way more strict. Your code is technically incorrect, since you can apply transforms only to paths filled/stroked with a solid color. You cannot apply a skew transform to a gradient and filter. Patterns, clips and mask are also tricky.

**Comment by yisibl** [comment]
Yes, there is an experimental API.

This is very useful for converting SVG to OpenType fonts. Currently, I've found that only Python tools([picosvg](https://github.com/googlefonts/picosvg#picosvg)) can do it, so I'm very much looking forward to resvg being implemented.

**Comment by RazrFalcon** [comment]
Yes, I'm aware of picosvg as well and the fact is depends on tons of extremely complicated Bezier code/math from Skia.

**Comment by yisibl** [comment]
There is a quandary with `skia-pathops` that [has never been solved](https://github.com/googlefonts/picosvg/issues/274) very well. If you plan to implement it in rust and don't rely on `skia-pathops`, that would be great.

**Comment by RazrFalcon** [comment]
Luckily, I do _not_ plan implementing anything like this. This is far beyond my level of expertise.

**Comment by RazrFalcon** [comment]
Closing, since it's impossible to do.
