### ISSUE TITLE
Cannot create square png image from non square svg file

### ISSUE THREAD

**Issue by qarmin** [RazrFalcon/resvg#535]
[1528971912.svg.zip](https://github.com/RazrFalcon/resvg/files/9508222/1528971912.svg.zip)
```
resvg 1528971912.svg 1528971912.png -w 500 -h 500
```
will produce image with size 280x500.
Both rsvg and thorvg support such thing

**Comment by RazrFalcon** [comment]
Do you expected a centered or scaled/skewed content? Anyway, resvg indeed doesn't support this. It always preserves the aspect.

**Comment by qarmin** [comment]
If user want to get image with proper aspect ratio, then it should use proper height and weight values. For now in resvg, there is now way to resize image with different aspect ratio.

**Comment by RazrFalcon** [comment]
So your goal is to skew the image? This is not supported. Mainly because I'm not sure why anyone would want that. Can you at least explain your use case?

**Comment by RazrFalcon** [comment]
Out of scope.
