### ISSUE TITLE
Image tag not working properly for base64 png file

### ISSUE THREAD

**Issue by gggrunt** [RazrFalcon/resvg#537]
Have a dummy png file inside svg, https://codesandbox.io/s/damp-bird-x0czsi?file=/index.html, but it will load forever in viewsvg for some reason.

**Comment by RazrFalcon** [comment]
Will check what's wrong with `viewsvg`, but `resvg` works as expected: 
```
Warning (in usvg::image:195): Image has an invalid size. Skipped.
```

The `image` element without explicit width/height attributes is an SVG 2 feature, which is not yet implemented. 

Duplicate of #388
