### ISSUE TITLE
Breakout usvg?

### ISSUE THREAD

**Issue by Kenttleton** [RazrFalcon/resvg#542]
Currently, usvg is a library within resvg. With the Micro SVG spec and usvg lib I think it would be easier to maintain as a separate codebase. I noticed that the issues also seemed to be mixed along with some confusion on which part handles what in the processing steps. Separating them might clean that up on both accounts.

**Comment by RazrFalcon** [comment]
Hi! usvg and resvg indeed were separate repos, but they are tied together so much, that it's way easier to have a monorepo.
In most cases, a change to usvg requires a change to resvg as well.
