### ISSUE TITLE
Add version function for c-api

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [RazrFalcon/resvg#545]
Please consider adding a version function to the c library.

e.g. add for header:

`const char* resvg_versionstring();
`

and implementation as easy as this:

```
const char* resvg_versionstring()
{
	return RESVG_VERSION;
}

```

This way we could have the app display what version it uses.

**Comment by RazrFalcon** [comment]
But you can use `RESVG_VERSION` define directly.

**Comment by MonkeybreadSoftware** [comment]
Sorry, but when you ship DLL, dylib or so file, you can't really depend on the value in the header.
e.g. build app with header from 1.0 and later have DLL from 1.0.1, so user can replace library and the application can know the version.

**Comment by RazrFalcon** [comment]
Well, same goes for all definitions in the header. You just have to trust it.

You must update the library and the header in unison. Heaving a dedicated function would not change anything. Sorry.

**Comment by MonkeybreadSoftware** [comment]
We would really like to ship DLL and app separate and allow the user to update the DLL on their own.
So it would be nice if the application could query the library version to show the user what DLL is in use.

**Comment by RazrFalcon** [comment]
You cannot update the DLL without recompiling your app. resvg doesn't have a stable API and ABI.

**Comment by MonkeybreadSoftware** [comment]
Of course you can replace the DLL with a newer one. And there C API didn't change from 0.23 to 0.25.
Eventually you will have a stable API/ABI and a version function could help to distinguish various versions.

**Comment by RazrFalcon** [comment]
>Eventually you will have a stable API/ABI and a version function could help to distinguish various versions.

This would not happen in the next 5-10 years for sure.
