### ISSUE TITLE
Support stdout output

### ISSUE THREAD

**Issue by vbezhenar** [RazrFalcon/resvg#546]
Resvg supports reading input file from stdin but there's no support to write output to stdout which might be useful to avoid intermediate file storage.

I tried to use `/dev/stdout` as output file argument, it seems to work but produces broken output.

**Comment by RazrFalcon** [comment]
Why would you want PNG in stdout? What is the use case?

**Comment by vbezhenar** [comment]
> Why would you want PNG in stdout? What is the use case?

My use-case is web service which generates SVG in memory and returns PNG as a response to the caller. Right now I'm using random file name on tmpfs filesystem which is supplied as output filename to resvg, then I read that file in memory, delete it from tmpfs and return response to the client. Using stdout would allow to simplify that workflow. I could imagine that I'm not the only one using resvg in that manner.

**Comment by RazrFalcon** [comment]
Ok, makes sense.

**Comment by PlkMarudny** [comment]
That's exactly my workflow as well.
