### ISSUE TITLE
Library is cutting the corners of SVG

### ISSUE THREAD

**Issue by andirsun** [RazrFalcon/resvg#548]
This is my original SVG:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-0.125 -0.125 24.25 24.25" stroke-width="1.75" height="400" width="400"><defs></defs><title>desktop-monitor-approve</title><path d="M23.25,6.75a6,6,0,1,1-6-6" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></path><path d="M23.25,2.25,17.78,7.719a.749.749,0,0,1-1.06,0L15,6" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></path><polygon points="15.75 23.25 8.25 23.25 9 20.25 15 20.25 15.75 23.25" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></polygon><line x1="6" y1="23.25" x2="18" y2="23.25" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></line><line x1="0.75" y1="17.25" x2="23.25" y2="17.25" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></line><path d="M23.25,14.25v3a3,3,0,0,1-3,3H3.75a3,3,0,0,1-3-3V6.75a3,3,0,0,1,3-3h4.5" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></path></svg>
```
- Preview: 
<img width="742" alt="Screenshot 2022-10-19 at 12 51 16 PM" src="https://user-images.githubusercontent.com/22928302/196767735-16053643-5cf2-4ddc-9d8a-c94c29fe11de.png">

After render SVG as PNG the library is cutting one of the corners
#### Result ->
<img width="671" alt="Screenshot 2022-10-19 at 12 56 43 PM" src="https://user-images.githubusercontent.com/22928302/196768908-d97077b9-10ec-4249-9873-b5ccddccdee7.png">

You can check the base64 version of the image here 
[image.txt](https://github.com/yisibl/resvg-js/files/9823069/image.txt)

I tested changing render values but nothing works.

**Comment by andirsun** [comment]
https://github.com/yisibl/resvg-js/issues/155

**Comment by RazrFalcon** [comment]
Interesting. Something is wrong with line caps. They should be round (half circle) and not boxy.
