### ISSUE TITLE
Reversing a `usvg::PathData`

### ISSUE THREAD

**Issue by antonok-edm** [RazrFalcon/resvg#551]
I'm considering using `usvg` to process SVG paths to be used for 3D CAD/CAM applications. In this context, the _direction_ of the path is actually fairly useful (either for signifying the "inside" of a shape, or controlling the direction of a tool path, etc.).

I imagine reversing a path might be a common enough operation that others could be interested in having it easily accessible as well. If there's interest in having this as part of `usvg`, I'm happy to work on a PR to add it.

**Comment by RazrFalcon** [comment]
`usvg` is strictly a "storage". It doesn't provide any operations not needed for rendering. So this feature is out of scope.

They idea is to copy `usvg::PathData` to your own path type and then post-process it. Yes, this is not an ideal solution, but this is the best we can offer. A universal/generic path type (like `CGPath`) would be nice, but it's absent in the Rust ecosystem.
