### ISSUE TITLE
render result is different from chrome and rsvg-convert

### ISSUE THREAD

**Issue by origel** [RazrFalcon/resvg#557]
test svg file:
![sample](https://user-images.githubusercontent.com/11866496/202711317-c6bd6e50-ea9c-4aff-98a6-0ef5e7fc376c.svg)

chrome result:
<img width="821" alt="chrome" src="https://user-images.githubusercontent.com/11866496/202711345-4f82c078-227c-4f0f-a655-f11566bbcbb0.png">

rsvg-convert result, and the result is same to chrome:
![rsvg](https://user-images.githubusercontent.com/11866496/202711420-0e56f9a2-90d6-4087-b1ab-8c0e027b581b.png)

resvg render result:
![resvg](https://user-images.githubusercontent.com/11866496/202711495-6fc93e19-ec7c-41f7-9dda-b8fec38b1627.png)

**Comment by RazrFalcon** [comment]
Can confirm. 

This is a pretty monstrosous SVG though. Seems like either a nested SVG or a mask resolving have failed.

**Comment by RazrFalcon** [comment]
This image also broken in Firefox and crashes Batik.

**Comment by origel** [comment]
embedy svg file:
`<svg viewBox="0 0 220 248">`
change to:
`<svg viewBox="0 0 235 265">`

resvg and firefox render result is ok. Maybe viewBox proc is different by render engine.

**Comment by origel** [comment]
embedy svg file add 
`style="overflow: visible;"`
is option too.
