### ISSUE TITLE
Allow percentage `opacity` values

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#560]
Since CSS Color 4.

**Comment by prompteus** [comment]
Hi,
I've noticed an issue with percentage opacity value in rgba function. Here is a minimal example:

```svg
<svg height="200" width="200" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
  <rect x="50" y="50" width="100" height="100" fill="rgba(0, 0, 0, 50%)"/>
</svg>
```

resvg (0.44.0, installed via conda from conda-forge channel) renders this rectangle with `background="white"` as pure black. Same with no-comma syntax `fill="rgba(0 0 0 / 50%)"`

Browsers (Chrome and Firefox on Ubuntu) render the the opacity correctly with either syntax.

However, docs mark this as completed, am I missing something?

**Comment by LaurenzV** [comment]
The issue is that the `rgba` syntax is not supported, it works with the following SVG:

```svg

**Comment by prompteus** [comment]
Actually, this appears as two separate issues.

1. Percentage in rgba function is ignored
2.  "Modern" rgba syntax without commas and with slash is not supported.

Source for rgba syntax: https://www.w3.org/TR/css-color-4/#rgb-functions

**Comment by waywardmonkeys** [comment]
We're going to be switching `svgtypes` over to using the `color` crate and then updating `usvg` and `resvg` appropriately. This will improve the range of color syntaxes that are supported.

**Comment by prompteus** [comment]
Great, thanks.

What is the expected timeline for this?

**Comment by RazrFalcon** [comment]
CSS Color Module Level 4 is largely unsupported. And our SVG 2 changelog covers only CSS 3.
