### ISSUE TITLE
Not getting the correct font using family name

### ISSUE THREAD

**Issue by DSalman** [RazrFalcon/resvg#565]
I have many different variants of the same font, e.g. "Light","Bold","Medium", "Regular". I can't find a way to specify the font that ensures that the correct one is used. Also, using the proper family name (as reported by Java Font class and confirmed by fontdrop) often doesn't work at all, resulting in no text. I am not loading system fonts. Here's an example:
ApercuMonoPro-Light - returns a fontFamily of "Apercu Mono Pro Light", but this doesn't work unless I shorten it to "Apercu Mono Pro".
ApercuMonoPro-Bold - returns family name "Apercu Mono Pro". This works.
Luckily, I can differentiate between the two by setting the weight to "bold". However, that is not the case for medium & regular. 
ApercuMonoPro-Regular - returns "Apercu Mono Pro", which works, but no way to differentiate it.
ApercuMonoPro-Medium - returns "Apercu Mono Pro Medium" family; has to be shortened to work.
So, the question is how do I specify the family, if the info I get from the OS doesn't create a match in resvg?
And, is there a full proof way to differentiate between these more subtle style differences?
I can supply font files or whatever else.

**Comment by RazrFalcon** [comment]
resvg will probably not be able to handle "Apercu Mono Pro Light". Depends on a font. Please include the whole family so I could test it.

In general, you should prefer something like this: `font-family="Apercu Mono Pro" font-weight="200"`

**Comment by DSalman** [comment]
Not sure this is the entire family but its what we use.

[ApercuMonoPro.zip](https://github.com/RazrFalcon/resvg/files/10251732/ApercuMonoPro.zip)

**Comment by RazrFalcon** [comment]
`font-family="Apercu Mono Pro" font-weight="300"` works just fine for matching "Apercu Mono Pro Light". This is the correct behaviour. 

Do you want an ability to match `font-family="Apercu Mono Pro Light"` as well? I not sure if this is against the spec or not.

**Comment by RazrFalcon** [comment]
The weight value stored in the [OS/2 table](https://learn.microsoft.com/en-us/typography/opentype/spec/os2#usweightclass) of the font.

ApercuMonoPro-Light.otf - 300
ApercuMonoPro-Regular.otf - 400
ApercuMonoPro-Medium.otf - 500
ApercuMonoPro-Bold.otf - 700

**Comment by RazrFalcon** [comment]
"Full font name" generations is... quite complicated: https://learn.microsoft.com/en-us/typography/opentype/spec/namesmp

Also, I've just checked and only Safari and Inkscape have been able to match `Apercu Mono Pro Light`. Chrome and Firefox ignored it. So this is not a bug.

**Comment by DSalman** [comment]
OK, it looks like I found the major source of confusion. I used iOS native code to check the font attributes. The Apercu 'light' font returns a familyName "Apercu Mono Pro" but using Java Font class the family is "Apercu Mono Pro Light". So I guess I can't trust the name they give. What's still confusing is that fontdrop shows the same info; "familyName:  Apercu Mono Pro Light". However, they also show an entry for "preferredFamily: Apercu Mono Pro". Looks like I'll have to find a way to get the "preferred" family string in Java. Thanks for looking into this.

**Comment by RazrFalcon** [comment]
No problem. I'm well aware that a "font name" is a pretty vague term. SVG operates on [font family](https://learn.microsoft.com/en-us/typography/opentype/spec/name#name-ids) (ID 1) which is not always the same as "font name".
There are also _typographic family name_ and localized family names. The later one is allowed by SVG, but not yet supported by resvg.
