### ISSUE TITLE
usvg cannot write an SVG anymore. Is there an alternative?

### ISSUE THREAD

**Issue by Gei0r** [RazrFalcon/resvg#568]
Since writing SVG [has been removed](https://github.com/RazrFalcon/resvg/blob/master/CHANGELOG.md#removed), is there an alternative for this functionality? Maybe an external crate?

If not, are there any plans to bring it back?

**Comment by RazrFalcon** [comment]
It will be back as a separate project in the future. No timeline for now.

**Comment by Gei0r** [comment]
Alright. I might be able to contribute, if it helps.

**Comment by RazrFalcon** [comment]
@jaseg @Legonaftik @JoKalliauer @flxzt Due to popular demand `usvg` CLI and ability to write SVG is back now. 
It required a serious `usvg` crate restructurization, but I think it was worth it.
Still no text writing. It must be converted to paths (which is way CLI will do automatically).

**Comment by jaseg** [comment]
That's wonderful news! As far as gerbolyze is concerned, we want usvg to convert the text to paths anyway.
