### ISSUE TITLE
resvg produces a seemingly empty png when using --width larger than 9000px

### ISSUE THREAD

**Issue by gustofarbi** [RazrFalcon/resvg#570]
I am trying to convert the attached svg to png, however resvg produces a fully transparent image. I have tested this on MacOS as well as on debian buster with similar results. Using rsvg-convert the image gets rendered as expected.
![flora-flaeache-14](https://user-images.githubusercontent.com/28761790/212325895-acc3685e-9714-4e18-9cf3-afc0530e8b00.svg)

**Comment by RazrFalcon** [comment]
Looks like a clipping bug in `tiny-skia`. Not good. For now, you can limit the image size by 8000x8000, which is the maximum "tile" size in `tiny-skia`.
