### ISSUE TITLE
error when converting file that includes text

### ISSUE THREAD

**Issue by isaacfink** [RazrFalcon/resvg#572]
Hi guys I am having an issue when converting an svg to png specifically if the file includes text, I am using resvg-js and I opened an issue there as well but it seems like an issue with the core library

[here is a link to the issue](https://github.com/yisibl/resvg-js/issues/192)

This is the svg I am converting, it's generated by satori but It's simple enough, there is just an image and a path, the path is generated from text and it's what's causing the issue, when I run the script without text it doesn't happen, I don't know enough rust to debug more then that

![thumbnail](https://user-images.githubusercontent.com/46644190/214849764-ca9ca1b7-a79c-4732-9ca7-e41a193a610a.svg)

This is the error I am getting, it's from satori-js so it might not be helpful at all, sorry in advance

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParsingFailed(ParserError(InvalidElement(InvalidName, TextPos { row: 1, col: 119 })))', /Users/runner/.cargo/git/checkouts/resvg-4b7e4ee32ad6d954/7c98ad6/src/image.rs:24:102
```

It also fails to panic which in my limited understanding of rust means it doesn't exit properly this is the error

```
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

the svg doesn't display properly in the browser (github probably does something to it) but it works perfectly when I am opening it directly

**Comment by RazrFalcon** [comment]
No surprise. Here is the embedded SVG:

```xml
<svg  version="1.1" xmlns="http://www.w3.org/2000/svg" width="NaN" height="NaN" viewBox="0 0 1000 1294.1176470588236"><(block) => {
  const anchor = block.textAlign === "center" ? "middle" : block.textAlign === "left" ? "start" : "end";
  const x = block.textAlign === "center" ? block.width / 2 + block.left : block.textAlign === "left" ? block.left : block.width + block.left;
  return /* @__PURE__ */ __vite_ssr_import_0__.default.createElement(
    "text",
    {
      x,
      y: block.top,
      "font-family": block.fontFamily,
      "font-size": block.fontSize,
      fill: block.fill,
      "dominant-baseline": "start",
      "alignment-baseline": "hanging",
      "text-anchor": anchor,
      id: block.id
    },
    block.textLines.map((line, i) => {
      return /* @__PURE__ */ __vite_ssr_import_0__.default.createElement(
        "tspan",
        {
          dy: i === 0 ? "0" : `${block.lineHeight}em`,
          x,
          "text-anchor": anchor,
          "letter-spacing": "{block.charSpacing}em",
          "alignment-baseline": "hanging"
        },
        line
      );
    })
  );
} text="text" textLines="text" font-family="" font-size="16" font-weight="normal" font-style="normal" charSpacing="0.2" lineHeight="1.6" textAlign="center" fill="#000" left="294" top="9" width="250" height="25.6" direction="ltr" opacity="1" hiddenField="false" id="cag8bgcws" maxLines="1"></(block) => {
  const anchor = block.textAlign === "center" ? "middle" : block.textAlign === "left" ? "start" : "end";
  const x = block.textAlign === "center" ? block.width / 2 + block.left : block.textAlign === "left" ? block.left : block.width + block.left;
  return /* @__PURE__ */ __vite_ssr_import_0__.default.createElement(
    "text",
    {
      x,
      y: block.top,
      "font-family": block.fontFamily,
      "font-size": block.fontSize,
      fill: block.fill,
      "dominant-baseline": "start",
      "alignment-baseline": "hanging",
      "text-anchor": anchor,
      id: block.id
    },
    block.textLines.map((line, i) => {
      return /* @__PURE__ */ __vite_ssr_import_0__.default.createElement(
        "tspan",
        {
          dy: i === 0 ? "0" : `${block.lineHeight}em`,
          x,
          "text-anchor": anchor,
          "letter-spacing": "{block.charSpacing}em",
          "alignment-baseline": "hanging"
        },
        line
      );
    })
  );
}></svg>
```

No only the width/height is set to `NaN`, which is not allowed. But the whole SVG is just a JS script. resvg doesn't run JS to begin with.

**Comment by isaacfink** [comment]
@RazrFalcon thanks I checked my code and it turns out something was wrong with the jsx and it wasn't rendered properly, I am not using react so it's a pain

I will close this issue now but I have one more question, how can I know which elements are supported? And is any css supported at all?

**Comment by RazrFalcon** [comment]
To know what is supported the best source is: https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html

In short, almost everything is supported. CSS is supported on CSS 2.1 level.
SVG 2 features a so-so, but this is pretty universal.
