### ISSUE TITLE
Crisp upscale of custom links

### ISSUE THREAD

**Issue by randomairborne** [RazrFalcon/resvg#574]
I use some bitmap PNGs in my svgs, and they load properly, but they have fuzzy edges. Is there a way to have them scaled crisply?

**Comment by RazrFalcon** [comment]
Can you provide an example?

**Comment by randomairborne** [comment]
A code example, or an example of what i want to do?

**Comment by randomairborne** [comment]
Something like image-rendering: crisp-edges; in CSS

**Comment by RazrFalcon** [comment]
An SVG sample. I'm trying to understand what is the issue exactly.

Afaik, resvg always draws images on pixel boundaries, so there shouldn't be a problem. Which is technically an issue on it's own.

**Comment by randomairborne** [comment]
https://github.com/randomairborne/experienced/blob/main/slash/src/resources/card.svg This is my example SVG. Running cargo test (which renders the card with random data) on this repository works as intended, unless you disable OptimizeSpeed, in which case the 8x8 pixelart images are horribly blurred

**Comment by RazrFalcon** [comment]
`crisp-edges` is `optimizeSpeed`. They should produce identical output. Just add `image-rendering="optimizeSpeed"` to your `image`.

**Comment by RazrFalcon** [comment]
For pixelart you probably want `pixelated`, which is afaik not part of the SVG spec.

**Comment by randomairborne** [comment]
Okay, so they are one and the same, and that’s all it does. Thanks!
