### ISSUE TITLE
webp support?

### ISSUE THREAD

**Issue by randomairborne** [RazrFalcon/resvg#575]
is it possible to support webP along with jpeg and png?

**Comment by RazrFalcon** [comment]
Technically yes, but it would require a pure-Rust library, which is not available, afaik, at the moment.

**Comment by randomairborne** [comment]
Hmm.. is it possible to add an optional feature flag to turn it on anyway?

**Comment by RazrFalcon** [comment]
Nope. `resvg` is pure-Rust library.

**Comment by randomairborne** [comment]
That's a shame. Is work being done on a pure rust WebP library?

**Comment by RazrFalcon** [comment]
No idea. 

WebP isn't part of SVG spec anyway.

**Comment by randomairborne** [comment]
This is decidedly "not planned", not "completed"

**Comment by sorairolake** [comment]
Can convert to WebP by the following:

```
resvg input.svg -c | magick -define webp:lossless=true - output.webp
```

**Comment by randomairborne** [comment]
I wasn't clear about it, but I was asking about WebP input, not output.

**Comment by sorairolake** [comment]
@randomairborne This is a SVG rendering library. So, I think the input format is always only SVG.

**Comment by randomairborne** [comment]
...
I am aware. I was asking if this library would be able to support it in addition. The answer was no.

**Comment by Luna-devv** [comment]
Would love to see WebP support as well, what a shame

**Comment by LaurenzV** [comment]
Looks like the [image crate](https://crates.io/crates/image) does support WebP decoding without C dependencies, although I haven't tried it. But not sure if RazrFalcon would be willing to add an additional dependency for a feature that's not required by the SVG specification. But I guess it wouldn't be an issue if it's behind a feature flag?

**Comment by Luna-devv** [comment]
I personally don’t really see where a problem with it would be if it works without issues. And I think that we aren’t the only ones wanting WebP support

**Comment by LaurenzV** [comment]
Sure, but it's up to the maintainer in the end.^^ If he is fine with it I might look into implementing it.

**Comment by Luna-devv** [comment]
Looking forward, would like to have smaller file sizes from WebP

**Comment by RazrFalcon** [comment]
It seems like we have to wait for https://github.com/image-rs/image-webp to be published.
