### ISSUE TITLE
Conversion to png results with wrong color when using deg units in hsl

### ISSUE THREAD

**Issue by Arctomachine** [RazrFalcon/resvg#579]
This problem was found out when using https://github.com/vercel/satori. Since it is built-in solution there, I am not sure about other details and specifics of its usage.

When defining color like this `hsl(200, 50%, 50%)`, resulting color looks correct (look at second word on picture). But when defining it like this `hsl(200deg, 50%, 50%)`, resulting color is black (look at first word on picture)
![image](https://user-images.githubusercontent.com/29041820/218262488-c0ca329b-4a46-48f4-beb9-34faf3d68fc2.png)

You can see replication of it at vercel's playground (switch tabs above image output between svg and png):
https://og-playground.vercel.app/?share=hZNva9swEMa_yiEoScAsTtigiCQwunbbm73Z3gz8RrHOtjJZMpK81Av-7jvZ_Ze2bs8gpOP3HPLdoxPLrUTG2XIJN0Lrvcj_QGFN8CCMhOvaHhQIhyA7I2qVE9KBtkKizAxpCmdr-GptqRFuHmRXX354UAZCpTxIrO2HzAz4b9tCLgwI7S04DK2jPRStyYOyBnJbN9agCaMYodGiK51tjaQK8wVsd3DKDBBofKBVW7eCLcwqr-frNJVYJvApvRiWxewZuX5CnmMRvLvNPO4fYyPV3_NMDB86jdvTcJWXEdv3U_1DDqv1ZfI6E_s8_hiH2bFSAWcT5FHJUBG0StOLKaZCVVbhHUgqH9tJVKHxdooKeBs-a1Ua4nKaBLopUkTqe8Dav4seWh9U0V1RY4h7E-_789yOphPGb0xsfEMGup_AMFh-54S-331DrW2yWUaIpOe1p6Vrkh6t0_JV5WZJLniSW2SmB8gMS5htonE94yc2DIrxSzIXGwfC-Md4kLhvS8YLMj0mjF7DQf3qmvjownE4UZ3omet6j5Lx4Frs-_8

**Comment by RazrFalcon** [comment]
From my understanding, this is part of CSS 4 Color, which is still a draft, and resvg support only CSS 3. 
This would not be supported any time soon. Prefer CSS 3 features.

**Comment by yisibl** [comment]
The conversion of various color formats can be handled in `satori`. In my opinion, this is a very low priority for resvg.

**Comment by Arctomachine** [comment]
> part of CSS 4
It is part of level 3. Are you perhaps mistaking it for new okhsl color definition?

**Comment by RazrFalcon** [comment]
I don't see it mentioned anywhere here: https://www.w3.org/TR/css-color-3/
