### ISSUE TITLE
Support mask-type property

### ISSUE THREAD

**Issue by yisibl** [RazrFalcon/resvg#582]
This is already [svg2-changelog.md](https://github.com/RazrFalcon/resvg/blob/master/docs/svg2-changelog.md) in the documentation. I'm adding a separate issue in case anyone wants to implement it.

See also: https://github.com/vercel/satori/issues/397

**Comment by RazrFalcon** [comment]
Yes, everything from our SVG 2 changelog in the TODO. I simply have no time working on it.

**Comment by yisibl** [comment]
Amazing!
