### ISSUE TITLE
Provide pkg-config file with the C library

### ISSUE THREAD

**Issue by sdroege** [RazrFalcon/resvg#592]
Providing a [pkg-config file](https://en.wikipedia.org/wiki/Pkg-config) makes it easier for users of the library to actually find it, check its version and get the correct compiler and linker flags.

[cargo-c](https://github.com/lu-zero/cargo-c) could be helpful here for generating the pkg-config file and also to provide a mechanism for installing it, the library itself and the header. It also ensures that the library has a valid and correct soname set, which cargo doesn't set at all when building a `cdylib`.

`cargo-c` also allows running cbindgen automatically but AFAIU you're manually editing the output of it so that's maybe not very useful here.

**Comment by sdroege** [comment]
It will also make static linking easier as all the required linker flags would be part of the pkg-config file

**Comment by RazrFalcon** [comment]
I'm not familiar with `pkg-config` or `cargo-c`, so unless someone wants to make a PR it would take a while for me to figure it all out.

**Comment by RazrFalcon** [comment]
Out of scope unless someone would send a path.

**Comment by RazrFalcon** [comment]
>without a proper soname

Afaik this is a cargo bug, not resvg one. It's up to distro maintainers to decide what to do. Out of scope.

**Comment by sdroege** [comment]
Fine with me, next time someone complains about stuff being broken I'll just point them to this issue :)

> Linux-only one

On macOS you don't get proper dylib versioning either.

> Afaik this is a cargo bug

More a missing feature than a bug, but until then cargo alone is unsuitable for this purpose.

https://github.com/rust-lang/cargo/issues/5045 and https://github.com/rust-lang/cargo/issues/2273 FWIW
