### ISSUE TITLE
Allow for rendering of elements outside of the viewbox

### ISSUE THREAD

**Issue by nielsbosma** [RazrFalcon/resvg#593]
Let's say I have a simple svg document like this where one element is outside of the viewbox. 

![image](https://user-images.githubusercontent.com/4034492/223972617-3cbbd1ce-81f0-4638-8e03-750663a8113c.png)

Rendered with Resvg I get a black png:

![image](https://user-images.githubusercontent.com/4034492/223972834-7ccef067-0268-4f08-a795-8a88da11c033.png)

And I guess that's the correct behaviour.

I can fix this by wrapping all nodes in a g element with a random id and then:

resvg.exe --export-id layer-a0cea710-169d-4538-b959-88528135f896 .\foo.svg foo.png

The issue with this is that the resulting image is smaller than expected. 

I want to achieve similar to this feature in Inkscape:

![image](https://user-images.githubusercontent.com/4034492/224051229-3051098f-9139-438f-b62b-5b0ea05a0acb.png)

**Comment by RazrFalcon** [comment]
It's technically possible to ignore SVG's viewbox, but automatic size calculation in SVG doesn't work as you would expect. It doesn't care about stroke, filter regions and so on. It relies only on object bboxes.

Right now, you can simply remove the `width`, `height` and `viewBox` attributes from the root `svg` element and you will get what you want.

**Comment by RazrFalcon** [comment]
Out of scope.
