### ISSUE TITLE
Error: XML with DTD detected.

### ISSUE THREAD

**Issue by nielsbosma** [RazrFalcon/resvg#596]
![Pen-broadedge](https://user-images.githubusercontent.com/4034492/224651298-b9104a81-3c25-4336-84ff-585bc357a8fa.svg)

[Uploading Pen-broadedge.zip…]()

Converting this ^ file to png yields the error: "XML with DTD detected."

If I remove the DOCTYPE line it works: 

![image](https://user-images.githubusercontent.com/4034492/224651542-b6bc46c2-3427-4b10-b418-e24fb557a4a1.png)

Tested with 0.29

**Comment by nielsbosma** [comment]
Sorry this wan't a Resvg issue.

**Comment by RazrFalcon** [comment]
Yes, but it's also was broken recently in CLI...
