### ISSUE TITLE
Using glibc 2.6 instead of 2.7 on release binaries

### ISSUE THREAD

**Issue by frantufro** [RazrFalcon/resvg#597]
This is just a comment for consideration:

The current binary for Linux is built against glibc 2.7. 

When trying to use it on an Amazon Lambda function it complained about it. I recompiled it using a Docker image with Amazon Linux 2 which uses glibc 2.6 and it worked flawlessly.

I’m wondering it it wouldn’t make sense to link against glibc 2.6 for better compatibility on the prebuilt binary.

**Comment by generalmimon** [comment]
> When trying to use it on an Amazon Lambda function it complained about it. I recompiled it using a Docker image with Amazon Linux 2 which uses _glibc 2.6_ and it worked flawlessly.

@frantufro BTW, didn't you mean glibc 2.<ins>**2**</ins>6? (https://aws.amazon.com/amazon-linux-2/faqs/)

> Q. What are the core components of Amazon Linux 2?
> 
> The core components of Amazon Linux 2 are:
> 
> 1. A Linux kernel tuned for performance on Amazon EC2.
> 2. A set of core packages including systemd, GCC 7.3, **Glibc 2.26**, Binutils 2.29.1 that receive Long Term Support (LTS) from AWS.

Glibc 2.6 or 2.7 are more than 15 years old (https://sourceware.org/glibc/wiki/Glibc%20Timeline), so hopefully you don't mean these.

**Comment by RazrFalcon** [comment]
I think you should compile resvg by yourself all the time. The prebuilt one are just a demo. You're not suppose to use them in production (obviosly). 
And you should definitely use `RUSTFLAGS="-Ctarget-cpu=haswell"` to enable AVX2, at least on x86. 
Someday I will write build instructions...

As for your specific issue - I'm using GitHub actions. So unless there is an easy way to use an older glibc - this is out of scope.
