### ISSUE TITLE
Is there anyway way to get defs?

### ISSUE THREAD

**Issue by clouds56** [RazrFalcon/resvg#604]
I'd like to get all `LinearGradient` and `RadialGradient` before traverse the tree (to [register functions](https://github.com/typst/svg2pdf/blob/9749896ed8882eac2c26959093720ef66f575d37/src/lib.rs#L452-L464) in pdf).
In previous version, we could check children in `defs`, now is there anyway fallback?

I'm working on updating usvg version in https://github.com/typst/svg2pdf,

**Comment by RazrFalcon** [comment]
You have to loop over all nodes and check fill/stroke properties for gradients. I can write a sample code if you need. We could probably add such method to `usvg::Tree` as well.

I know it's not as nice as before, but having a separate `defs` storage makes tree modification harder.

**Comment by RazrFalcon** [comment]
Here is a code sample: https://github.com/RazrFalcon/resvg/blob/bfc98778d79dc5a299bf979d33c98f0668c3498d/usvg/src/writer.rs#L119...L143

**Comment by RazrFalcon** [comment]
Turns out the code above was wrong. As the usvg writer in general.

Instead, you can use `usvg::Tree::paint_servers` method now.
