### ISSUE TITLE
performance resvg is slower than inkscape on specific image

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#607]
I wanted to render https://commons.wikimedia.org/wiki/File:Coat_of_arms_of_Venezuela.svg

resvg-time: 5.7sec
inkscape-time: 1.2sec
usvg-time: 0.2 sec

## SVG
![Escudo](https://user-images.githubusercontent.com/15687581/229848942-fceb67a2-62d4-40cf-8930-b996fe6c7ee5.svg)

## license: Public Domain

source https://commons.wikimedia.org/wiki/File:Coat_of_arms_of_Venezuela.svg

**Comment by JoKalliauer** [comment]
I wanted to render https://commons.wikimedia.org/wiki/File:Coat_of_arms_of_Honduras.svg

resvg-time: 1.0 sec
inkscape-time: 0.5 sec
usvg-time: 0.1 sec

## SVG
![HondurasNew](https://user-images.githubusercontent.com/15687581/229850824-8398f309-abe2-4e09-92eb-f3f5de68ad6c.svg)


## license: Public Domain

source https://commons.wikimedia.org/wiki/File:Coat_of_arms_of_Honduras.svg

**Comment by RazrFalcon** [comment]
Performance issues are not bugs. resvg doesn't really claim to be fast. It's all about correctness.
Those files have thousands of layers + blur filters. 5s is a pretty damn good result for that.

The main issue here is the way resvg handles layers with opacity (spoiler: badly). This would be addressed in the future, but requires a significant renderer rewrite.

**Comment by RazrFalcon** [comment]
I have rewrote the renderer, which I planned to do for a very long time.
`Coat_of_arms_of_Venezuela.svg` should be rendered 35 times faster. Yes, you're reading this right - 35x faster.
`Coat_of_arms_of_Honduras.svg` should be 8x faster.

It's still not ready for a release. It was a nearly a complete rewrite, and even despite the fact we have thousands of tests, there are still some minor bugs I'm finding on real world file.

If you would have time, I would appreciate if you test it on some of your SVGs. Just `git clone` + `cargo build --release`. Thanks.
