### ISSUE TITLE
Continuous memory growth when using very large `--width` values

### ISSUE THREAD

**Issue by yisibl** [RazrFalcon/resvg#613]
```bash
cargo run --release -- --width 80009 tests/svg/e-path-053.svg tests/png/e-path-053.png
```

This causes the Node.js process to be killed in [resvg-js](https://github.com/yisibl/resvg-js).

Although, I can limit the maximum size of the input at the JS level, I think it would be better to solve it from `resvg`.

Memory Usage:
![image](https://user-images.githubusercontent.com/2784308/231812943-d96ee510-1951-4a6e-82bd-340b5b5e4744.png)

CPU Usage:
![image](https://user-images.githubusercontent.com/2784308/231812919-c3f2cd8a-0852-456f-af05-89496cff7d45.png)

**Comment by RazrFalcon** [comment]
I'm not sure what behavior do you expect. resvg has no memory limit. If you want to render 100k x 100k image - go ahead. Nothing stops you.

If you need a limit, then it should be set on your side.

**Comment by RazrFalcon** [comment]
Out of scope.
