### ISSUE TITLE
Documentation unclear for TextSpan::{start,end}

### ISSUE THREAD

**Issue by ennis** [RazrFalcon/resvg#618]
The documentation says this for `usvg::TextSpan::start` and `end`

> A span start in UTF-8 codepoints.

But if I'm not mistaken these seem to be byte offsets into the string, not lengths in unicode code points. Maybe the wording should be simply "A span start in bytes", or "Byte offset to the start of the span, relative to the parent text chunk"?

**Comment by RazrFalcon** [comment]
In case of UTF-8, byte offset == UTF-8 codepoint. By I guess using bytes would be more obvious. Will update the docs.
