### ISSUE TITLE
Fonts don't work/html parsed incorrectly with `&quot;`

### ISSUE THREAD

**Issue by theofficialgman** [RazrFalcon/resvg#619]
I am testing with the latest https://github.com/RazrFalcon/resvg/releases/download/v0.32.0/viewsvg-win64.zip for evaluation before using this library in a project.

I am unable to get system fonts to load with this program. I have verified that the required font is installed to `C:\Windows\Fonts` and the SVG contains no `@font-face` which I know is not supported by resvg (https://github.com/RazrFalcon/resvg/issues/541). With the system font installed, the SVG renders correctly in chromium. With the system font installed, it renders in resvgviewer with the default font and not the specified font.

With the system font removed, both chromium and resvg use the default font as expected.

**Comment by theofficialgman** [comment]
[test_svg_and_font.zip](https://github.com/RazrFalcon/resvg/files/11480196/test_svg_and_font.zip)
here is the svg in question and font to install on the system for you to test

**Comment by theofficialgman** [comment]
figured out the bug
your parser is unable to interpret the quoted font text
```
<text style="font-family: &quot;Product Sans Black&quot;; font-size: 299.1px; white-space: pre; filter: url(#drop-shadow-filter-5);"
```

this `&quot;` is valid html syntax so you should definitly correct that

**Comment by theofficialgman** [comment]
Is the format of my svg file incorrect? I currently have about a dozen SVGs with the same issue that were created in https://boxy-svg.com/ by @botspot . If it is incorrect formatting according to SVG spec we can ask for it to be fixed in boxy-svg software

**Comment by theofficialgman** [comment]
It has already been reported in boxy-svg. apparently the issue comes from chromium's xmlserializer
https://boxy-svg.com/bugs/152/quotation-marks-handling-with-font-names

**Comment by RazrFalcon** [comment]
When it comes to "web standards", there are no such thing as _correct_. Most apps do support this, so we have to as well.

As for the SVG itself, it's very browser-oriented. If you care only about Chrome (aka 99%) then you will be fine. Batik and Inkscape fail to rasterize the effects on text.
The only weird part here is that it relies on SVG 2 features, but still uses SVG 1 emulation of drop shadows, which are native in SVG 2.

**Comment by Botspot** [comment]
Pinging @jarek-foksa

**Comment by theofficialgman** [comment]
also incase @jarek-foksa , you wouldn't happen to be willing to share what method you are using for exporting the image from boxy-svg? From what I can gather, you aren't having the browser render the image at the output resolution and then creating the png, it seems like you must be rasterizing the svg into something larger and then downscaling to the output resolution. Either that or there is some sort of anti-aliasing method or post-processor being used.

**Comment by jarek-foksa** [comment]
As far as I know SVG documents containing `&quot;` are valid, but these escape codes look just plain ugly. I will try to make Boxy SVG replace them with more elegant single quotes in the next update.

> The only weird part here is that it relies on SVG 2 features, but still uses SVG 1 emulation of drop shadows, which are native in SVG 2.

Boxy SVG supports both the old and the new syntax for drop shadows (you can toggle them with the ["Set as SVG 2 filter function" checkbox](https://boxy-svg.com/blog/19/svg-2-filters) in the filter settings). The old syntax is used by default though.

> also incase @jarek-foksa answers, you wouldn't happen to be willing to share what method you are using for exporting the image from boxy-svg? From what I can gather, you aren't having the browser render the image at the output resolution and then creating the png, it seems like you must be rasterizing the svg into something larger and then downscaling to the output resolution. Either that or there is some sort of anti-aliasing method or post-processor being used.

I'm rasterizing the SVG image at the output resolution, you can read the rasterization code [here](https://gist.github.com/jarek-foksa/aaad250720a961e518de1eb4c9ce9352). Note that it uses the [UPNG library](https://github.com/photopea/UPNG.js/) to perform quantization/encoding.

**Comment by jarek-foksa** [comment]
Also, I'm injecting the following style into the SVG document to disable anti-aliasing during rasterization, I guess this might be the reason why the output looks differently:

```html
<style>* {shape-rendering: crispEdges !important;}</style>
```

**Comment by RazrFalcon** [comment]
@theofficialgman If you use resvg CLI tool, you can pass `--shape-rendering crispEdges` to disable shapes antialiasing. There is no CSS injection in resvg yet (#277). It's surprisingly hard to implement.

**Comment by RazrFalcon** [comment]
Also, I think you should adjust your expectations a bit. resvg is pretty good, but it's not a browser. SVG spec is endlessly complicated. Same with CSS, XML and so on.
CSS support in particular is very basic.

**Comment by theofficialgman** [comment]
@RazrFalcon I'm not expecting perfection. I'm honestly just impressed that for me you have already exceeded all other software out there (not including browsers) for svg rendering.

**Comment by RazrFalcon** [comment]
If you exclude browsers, specifically Chrome, then yes - resvg is probably the best. But there are still an endless amount of work left.
