### ISSUE TITLE
Missing attribute "auto" for ShapeRendering

### ISSUE THREAD

**Issue by LaurenzV** [RazrFalcon/resvg#621]
Currently, when rendering a svg with the attribute `shape-rendering` and value `auto`, it prints a warning that it failed to parse that value. The reason seems to be that this value isn't part of the `ShapeRendering` enum even though, [according to the specification](https://svgwg.org/svg2-draft/painting.html#ShapeRendering), that is a valid value (the same applies to `text-rendering` and `image-rendering`):

https://github.com/RazrFalcon/resvg/blob/f79f081fd2083d306b7fe8bce4b418191f0f7d6d/crates/usvg-tree/src/lib.rs#L96-L100

Is there a reason for this? Or am I missing something here?

**Comment by RazrFalcon** [comment]
Just a bogus warning. Will fix. Thanks.
