### ISSUE TITLE
c-api builds the shared library w/out SONAME

### ISSUE THREAD

**Issue by yurivict** [RazrFalcon/resvg#623]
This patch used to solve this problem:
```
--- build.rs.orig       1970-01-01 00:00:00 UTC
+++ build.rs
@@ -0,0 +1,3 @@
+fn main() {
+       println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libresvg.so");
+}
```
but now build.rs isn't in the root of the project any more.

**Comment by RazrFalcon** [comment]
resvg never had `build.rs`. I'm not sure what are you doing and why.

**Comment by RazrFalcon** [comment]
I assume you talk about https://github.com/rust-lang/cargo/issues/5045, if so, there is nothing I can do from my side. 
Just put your `build.rs` to `crates/c-api` and you should be fine.

**Comment by yurivict** [comment]
Ok.
