### ISSUE TITLE
Feature request: render Tree as Mask

### ISSUE THREAD

**Issue by Pr0methean** [RazrFalcon/resvg#624]
For an app of mine, I often need only the opacity mask of a rasterized SVG file and not the colors. Being able to render the Tree directly into a Mask would probably be faster than rendering to a Pixmap and passing it to `Mask::from_pixmap`, because the color channels wouldn't need to be calculated and discarded.

**Comment by RazrFalcon** [comment]
You cannot render SVG to a mask. It's a fundamentally a RGBA format. We would have to disable filters and raster images.
Also, tiny-skia is RGBA-only as well. It doesn't have a grayscale mode.

This feature would require significant changes with close to zero benefits. Out of scope.

**Comment by Pr0methean** [comment]
Is there any format you can suggest using instead for paths that contain diagonals and curves, but from which only the opacity needs to be rasterized? My app works mostly by using SVGs to define layers, then using DSL code to define which layers are stacked to create which texture and what color each layer is painted. I have a few SVGs that contain colors (and usually gradients) and are rendered out without being repainted, but they're the exception rather than the rule. The app is at https://github.com/Pr0methean/OcHd-RustBuild.

**Comment by RazrFalcon** [comment]
There are only two open-ish vector formats out there: SVG and PDF. And both are a nightmare to use. PDF does support grayscale mode, but I don't think there are any good PDF rendering libraries for rust. So you would need to use C/C++ one.

I would suggest parsing SVG manually, using something like `roxmltree` or even `usvg` if you have no control over input SVG. Then writing your own renderer, which should take like 20 LOC to render lines for `tiny-skia::Mask` (remember that `tiny-skia::Mask` is still using the RGBA pipeline as of now).

You need a very niche solution and the Rust ecosystem is too young for that.
