### ISSUE TITLE
Customize antialiasing

### ISSUE THREAD

**Issue by agg23** [RazrFalcon/resvg#626]
I realize this is a long shot, but I'll ask anyway.

Is there any reasonable way to customize how antialiasing works without reaching deep into the library and routing a bunch of stuff around. I'm not even sure if it's possible to accomplish what I want, but it would be nice if I could figure out how:

I need to extract information along multiple paths in the SVG (something that could be encoded into a `u16`), and correlate pixel by pixel in the raster with that information. My naive approach was to modify the fill color on the path, so it would basically write this ID for every pixel, but it turns out the antialiasing can change the color of a pixel, not just the alpha.

I realize you can disable antialiasing with `path.rendering_mode = ShapeRendering::CrispEdges`, but that doesn't work very well for my paths (and low resolution), and produces an ugly result.

**Comment by RazrFalcon** [comment]
The only control you have is _on_ and _off_. That's it. There are nothing else and never will be.

I'm not sure what you're trying to do. Can you illustrate it somehow?

>but it turns out the antialiasing can change the color of a pixel, not just the alpha

Are you sure? This should not happen. You can get small differences due to rounding, but that's it.

>I realize you can disable antialiasing, but that doesn't work very well for my paths (and **low resolution**), and **produces an ugly result**.

Well, that's the whole point of antialiasing.

**Comment by agg23** [comment]
My paths have a `title` attribute which contains an ID. I parse the SVG with a separate library than `usvg` to extract the titles and mark each path with that ID. I then convert the ID to a number and set the color of the path (in `resvg`) to that ID. Produces output kind of like this:

![gnw_dkjr2](https://github.com/RazrFalcon/resvg/assets/238679/fb9be18f-1473-4cb1-9aac-27db2c9d1b31)

The point of doing this is so I have a many to one mapping of pixel to ID. These IDs are for LCD segments in a matrix, and I know which pixels to turn on/off based on that ID.

----

Like I said, it was a shot in the dark. If I can't customize AA, then I'll have to come up with a more creative way to exfill this info. Thank you for your response.

**Comment by RazrFalcon** [comment]
I see. But again, I guess there is nothing you can do from the `resvg` side.
