### ISSUE TITLE
Document color space of rendered output

### ISSUE THREAD

**Issue by e00E** [RazrFalcon/resvg#629]
The resvg documentation does not mention the color space of the rendered output. The type that `render` works with is `PixMap`, which is documented like this:
> A container that owns premultiplied RGBA pixels.

This doesn't tell me what the color space is. SVG works in sRGB color space. A manual test shows that resvg stays in sRGB. This wasn't obvious to me. Could it be documented explicitly?

**Comment by RazrFalcon** [comment]
Technically there are no color space. But we assume it is sRGB.

**Comment by e00E** [comment]
This might be obvious to people who are more familiar with SVGs. I was confused when I double checked my code for color space correctness. Maybe one sentence somewhere in the resvg docs would help clear it up. The way I understand it now is that tiny-skia has no concept of color spaces and resvg follows whatever SVG does, which is always sRGB.

**Comment by e00E** [comment]
You could imagine a different svg library where the final output is presented to the user in a Pixmap equivalent that is in a different color space. For example, it could be linear RGB instead of sRGB with gamma. This is why I was unsure.
