### ISSUE TITLE
Are `data-*` attributes supported?

### ISSUE THREAD

**Issue by tgbrooks** [RazrFalcon/resvg#630]
My understanding is that the SVG standard allows for arbitrary attributes that start with `data-` as a prefix. I have some in an SVG file but they do not appear in the `attributes()` of the nodes and it looks like `AttributeId` has a fixed list of supported attributes. Is there any way to get the `data-*` attributes or is there any interest in supporting this feature?

**Comment by RazrFalcon** [comment]
I never heard about `data-` prefixes and never saw them in the spec. Therefore they are not supported.

`resvg`/`usvg` doesn't preserve any data it doesn't use, so no.

**Comment by tgbrooks** [comment]
Thanks for clarifying the situation. Just as an FYI they do appear to actually be [part of the standard](https://svgwg.org/svg2-draft/struct.html#DataAttributes), though I understand that doesn't mean they're in-scope for `usvg`.

**Comment by RazrFalcon** [comment]
I guess it was added in SVG 2. Never heard of them and never saw them.

But yes, since they do not affect rendering they are out of scope.
