### ISSUE TITLE
rosvgtree resolve_href cost too long when parse complex svg

### ISSUE THREAD

**Issue by wjian23** [RazrFalcon/resvg#634]
parse svg glyph in NotoColorEmoji font block more than 10 min and still no complete.
it's a O(n^2) algorithm, will probably become a problem when deal with too many nodes and many href node。
Saw from the comment, It's the choice for the less caret dependency, maybe can supply a more effected implement with a feature?
<img width="759" alt="image" src="https://github.com/RazrFalcon/resvg/assets/6829874/be0d3df3-b8bd-4caf-b52f-e01ea7a1e087">

**Comment by wjian23** [comment]
[noto_emoji.svg.zip](https://github.com/RazrFalcon/resvg/files/11631441/noto_emoji.svg.zip)

**Comment by wjian23** [comment]
> Can you provide a sample SVG?

[noto_emoji.svg.zip](https://github.com/RazrFalcon/resvg/files/11631445/noto_emoji.svg.zip)

**Comment by antmelnyk** [comment]
I've been working with Noto Color Emoji recently, and it's something. They basically packed most of the emojis into a single SVG document. I found there is no point in resolving the whole file (not surprised that a straightforward approach would hang the parsing).

In my case, it was better to repackage a single emoji and resolve its `<defs>`. Then you can use/cache result SVGs or rendered emojis themselves, depending on your needs.

Here's my code. I know it's a bit crazy, but that approach worked for me just fine for this specific use case, so I'll leave it here.

Base code (you should obviously handle errors and unwraps properly for your needs):
```rust
    // Get SVG document from the font
    let doc = Document::parse(svg_document)?;

    // ...

    // Output SVG that we construct using emoji glyph SVG elements.
    let mut output = String::new();

    output.push_str(
        "<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>",
    );

    let defs_node = doc
        .descendants()
        .find(|node| node.tag_name().name() == "defs");

    let glyph_node = doc
        .descendants()
        .find(|node| node.attribute("id") == Some(&glyph_id))
        .unwrap();

    // Find all references used inside the glyph among the <defs> of the SVG document
    if let Some(defs) = defs_node {
        let ids = find_dependencies_ids(glyph_node);
        let defs = find_dependencies_by_ids(defs, ids);

        output.push_str("<defs>\n");
        for def in defs {
            output.push_str(&node_to_string(def));
        }
        output.push_str("</defs>\n");
    }

    // Push the glyph itself to the output SVG
    output.push_str(&node_to_string(glyph_node));
    output.push_str("</svg>");
```

Lookup functions that recursively resolve defs:
```rust
fn find_dependencies_ids<'a>(node: Node<'a, '_>) -> Vec<&'a str> {
    let mut defs_ids = Vec::new();

    for child in node.descendants() {
        // Handle <use>
        if child.has_tag_name("use") {
            let href_id = child
                .attribute(("http://www.w3.org/1999/xlink", "href"))
                .map(|href| href.trim_start_matches('#'));

            if let Some(href_id) = href_id {
                defs_ids.push(href_id);
            }
        }

        // Handle url in fills, strokes, etc.
        // I haven't seen anything but fill used in emojis though.
        let attributes = [
            "fill",
            "stroke",
            "clip-path",
            "mask",
            "filter",
            "marker",
            "marker-start",
            "marker-mid",
            "marker-end",
        ];

        for attribute in &attributes {
            if let Some(id) = get_id_from_url_attribute(child, attribute) {
                defs_ids.push(id);
            }
        }
    }

    defs_ids
}

fn find_dependencies_by_ids<'a, 'input>(
    defs: Node<'a, 'input>,
    mut defs_ids: Vec<&'a str>,
) -> HashSet<Node<'a, 'input>> {
    let mut output_defs = HashSet::new();

    let id_to_node: HashMap<_, _> = defs
        .children()
        .filter_map(|child| child.attribute("id").map(|id| (id, child)))
        .collect();

    let mut i = 0;

    while i < defs_ids.len() {
        if let Some(def) = id_to_node.get(defs_ids[i]) {
            if !output_defs.contains(def) {
                output_defs.insert(*def);

                let new_defs_ids = find_dependencies_ids(*def);
                defs_ids.extend(new_defs_ids);
            }
        }

        i += 1;
    }

    output_defs
}
```

Manual repacking of the Node to string:
```rust
fn node_to_string(node: usvg::roxmltree::Node) -> String {
    let mut result = String::new();

    let tag_name = node.tag_name().name();

    result.push('<');
    result.push_str(tag_name);

    for attr in node.attributes() {
        result.push(' ');
        result.push_str(attr.name());
        result.push_str("=\"");
        result.push_str(attr.value());
        result.push('"');
    }

    if node.children().count() > 0 {
        result.push('>');

        for child in node.children() {
            if child.node_type() == NodeType::Element {
                result.push_str(&node_to_string(child));
            }
        }

        result.push_str("</");
        result.push_str(tag_name);
        result.push('>');
    } else {
        result.push_str("/>");
    }

    result
}
```

**Comment by wez** [comment]
I'm hitting this while trying to hook up svg rendering to freetype in wezterm.

I can take a crack at adding in a cache using the hashlink crate that is mentioned in the comments; I don't know anything useful about svg so I'm not sure I understand the comment about order preservation.

Can I safely assume that an `id` is actually unique in the document?  Is it important that resolve_href is scoped to the current node, or can we safely use a map for the whole document?

**Comment by RazrFalcon** [comment]
>A simple contains_key check satisfies the structure_use_duplicated_IDs test case

Can you guarantee that `HashMap` would not shuffle entires at some point? If not, then we should use `hashlink`.

>I'm hitting this while trying to hook up svg rendering to freetype in wezterm.

`resvg` isn't capable of rendering "svg fonts" because they use an SVG superset. Specifically CSS 4 variables that can reference the CPAL table and the fact that a single "SVG glyph" [can contain multiple glyphs](https://learn.microsoft.com/en-us/typography/opentype/spec/svg#glyph-identifiers). `resvg` would not be able to handle any of this.

**Comment by wez** [comment]
> Can you guarantee that `HashMap` would not shuffle entires at some point? If not, then we should use `hashlink`.

I don't understand this requirement; can you help me understand it?

In the PR the `id_map` is `HashMap<&str, roxmltree::Node<'_, 'input>>` and is *scoped to the entire document*.

Lookups are done using the id string, which doesn't seem to be sensitive to ordering beyond only tracking the first instance of any given id.

That map is only used during parsing of the Document, and is discarded before the `parse` method returns.

So based on my understanding, I don't see why ordering matters, and the stability of the address of the values in the hashmap is seemingly guaranteed by the type system.

What am I missing? :)

> `resvg` isn't capable of rendering "svg fonts" because they use an SVG superset. Specifically CSS 4 variables that can reference the CPAL table

Ah, bummer.

> and the fact that a single "SVG glyph" [can contain multiple glyphs](https://learn.microsoft.com/en-us/typography/opentype/spec/svg#glyph-identifiers). `resvg` would not be able to handle any of this.

I have this bit seemingly working using https://docs.rs/usvg/latest/usvg/struct.Tree.html#method.node_by_id and https://docs.rs/resvg/latest/resvg/struct.Tree.html#method.from_usvg_node

FWIW, aside from my horizontal bearing not being correct, I have this basically working with the Noto Color Emoji font.
I suppose that the glyphs I've tried so far don't use any of the superset that is missing!

**Comment by wez** [comment]
Yeah, there are definitely edge cases I need to run down; the top of this image is using the older bitmap font, while the bottom is the new svg-only(?) font file:

![image](https://github.com/RazrFalcon/resvg/assets/117777/a01707da-fb17-4967-8570-3bed99d84cd2)

other glyphs, like the ghost glyph work fine.

Seems like a headache!  There's discussion in https://gitlab.freedesktop.org/freetype/freetype/-/issues/1229 about precedence of SVG vs COLR 1.0 and it seems like COLR 1.0 might be easier to implement.

For those that might be interested in this, https://github.com/wez/wezterm/commit/edbf4ac1e4634670b23f60807d1c1e4f4cbd72b1#diff-51356399ae6d6119d06caebe451f2d833f2cdb8ee8d37645024480ac0db3eac7 is the relevant part of the commit to get that far.

**Comment by RazrFalcon** [comment]
> it seems like COLR 1.0 might be easier to implement

I wouldn't be that optimistic. TrueType is a nightmare. 

As for tables precedence, afaik it's not documented.

PS:  aren't `freetype` using `librsvg` already?

**Comment by wez** [comment]
> PS: aren't `freetype` using `librsvg` already?

AFAICT, there's a demo program that uses rsvg (that's what I based my attempt on, but ported to resvg), but there isn't an integrated compilation option to provide svg support with freetype.

In wezterm, depending on rsvg and cairo is a bit of burden, especially for !linux, which is why resvg is appealing!

**Comment by RazrFalcon** [comment]
Oh, I thought it was built-in. `resvg` being pure-Rust helps, but it's still a pretty heavy dependency. Well, unless you disable text, which you do not need.

As for the patch, you can just switch to `hashlink` and I will accept it. std HashMap doesn't guarantee order, and while your hack works, it can break any time.

**Comment by wez** [comment]
I can add in `hashlink`, but I don't think it makes any difference; the `contains_key` check is still necessary for the tests to pass. I feel like I'm still missing a piece of the puzzle to understand why ordering within the data structure matters more than only inserting the first instance of an id.

**Comment by RazrFalcon** [comment]
omg, I finally understood your point. My tiny brain... Yes, if we're inserting only the first occurrence then we're fine.
