### ISSUE TITLE
Crash when elements are translated offscreen

### ISSUE THREAD

**Issue by gmeeker** [RazrFalcon/resvg#638]
This seems to have been introduced by 0.34.0. I realize this is not a normal use case (I only discovered it accidentally) but it's still causing resvg to crash where it didn't before. I believe this SVG is still valid.
This is macOS 13. I haven't checked elsewhere.

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/resvg/src/geom.rs:27:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

![crash](https://github.com/RazrFalcon/resvg/assets/6538028/12b4bec4-5de0-453a-8709-16e0ed093aa3)

**Comment by jonmmease** [comment]
I opened a PR in https://github.com/RazrFalcon/resvg/pull/639 with this proposed fix

**Comment by jonmmease** [comment]
Thanks for the quick fix @RazrFalcon! 

One question, I saw that the fix was published in 0.35.0 as a GitHub Release, but I don't see it on [crates.io](https://crates.io/crates/resvg) yet (It still shows 0.34.1 as the latest). Do you know when that will happen? Thanks again!

**Comment by RazrFalcon** [comment]
Should be up now.

**Comment by jonmmease** [comment]
perfect, thanks!
