### ISSUE TITLE
Thanks this great project. It helped me generating images that are larger than a modern browser can hold!

### ISSUE THREAD

**Issue by thekingofcity** [RazrFalcon/resvg#640]
This is not a feature nor a bug report. Just want to support this project with some feedback.

One of my website user want to know how to export images that are [too big](https://github.com/jhildenbiddle/canvas-size#test-results) to be `canvas.toBlob`.
[railmapgen/rmp](https://github.com/railmapgen/rmp) 
![in](https://github.com/RazrFalcon/resvg/assets/3353040/fef6f854-b106-4b72-9788-8a386dd2b55a)

`resvg` helps me solve this, that's really awesome and great job!

**Comment by RazrFalcon** [comment]
Thanks! Glad to hear.
