### ISSUE TITLE
(question) Safety of untrusted SVG input

### ISSUE THREAD

**Issue by randomairborne** [RazrFalcon/resvg#641]
Hey! This is definitely a question, but discussions are not enabled here- is it generally "safe" to pass untrusted SVG to resvg, or does some sort of sanitization need to happen? what do I need to know if I plan to do this?

**Comment by RazrFalcon** [comment]
Depends on your definition of safety. Rendering a huge SVG can take time, which can be abused to cause a DDOS of sorts. 
But other than that... Idk. It can read any image on your file system, but cannot read your password, etc.

**Comment by randomairborne** [comment]
hmm- wouldn't i need a custom href resolver mapped to the fs to allow custom SVGs to read images? I'm mostly worried about things like "use a billion gigabytes of memory" or otherwise completely crash the program- but reading files from disk is something I didn't expect to be an issue? Is there a way this can be disabled?

**Comment by randomairborne** [comment]
(okay turns out one does not simply set a timeout for a synchronous function, not sure what would need to be done for this)

**Comment by RazrFalcon** [comment]
Honestly, this is not something that can be done from resvg side. If you plan to use it on a server/Linux, you should rely on OS capabilities to limit IO access, RAM usage and execution time.

**Comment by randomairborne** [comment]
Relying on OS capabilities in rust code is not good practice in my book- then i have to implement them three times over, and it might break in production but not on my dev machine. In any case, that would require me to build a seperate binary, which isn’t really feasible? i guess the answer to “is this safe to use on untrusted input” is “no”, which is a bit unfortunate.

**Comment by RazrFalcon** [comment]
>i guess the answer to “is this safe to use on untrusted input” is “no”, which is a bit unfortunate.

I would say that parsing and rendering SVG "safely" is impossible by design. There is nothing `resvg`-specific about it.
It's fairy trivial to crash most SVG libraries. Browsers are more resilient, but not you have to sandbox a browser as well.

**Comment by randomairborne** [comment]
alright, thank you then. I'll figure out something else rather then doing something that will probably be janky and unreliable to support custom SVG.
