### ISSUE TITLE
test failure on Arch Linux: paint_servers_radialGradient_focal_point_correction

### ISSUE THREAD

**Issue by flying-sheep** [RazrFalcon/resvg#644]
IDK how to make this reproducible.

I build resvg like this, and this one test fails: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=resvg

```
thread 'render::paint_servers_radialGradient_focal_point_correction' panicked at 'assertion failed: `(left == right)`
  left: `23404`,
 right: `0`', crates/resvg/tests/integration/render.rs:564:68
...
test result: FAILED. 1627 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 17.22s
```

**Comment by RazrFalcon** [comment]
Very strange. 

Can you render this SVG manually and sent it to me?

**Comment by flying-sheep** [comment]
They sure look identical …

mine | reference
--- | ---
![focal-point-correction-fail](https://github.com/RazrFalcon/resvg/assets/291575/48adf8bf-a23c-4591-a184-14f5c3099ad7) | ![focal-point-correction](https://github.com/RazrFalcon/resvg/assets/291575/f315fca2-ef3e-48a3-960f-f9885bcc3dfe)

**Comment by RazrFalcon** [comment]
What CPU do you have? Looks like a rounding bug.

**Comment by flying-sheep** [comment]
AMD Ryzen 7 3700X, microcode 0x8701013

**Comment by RazrFalcon** [comment]
Very strange. I had the same CPU and it was fine. Not sure about microcode version. But I was testing on Windows.

Either way, you can ignore this test for now. Will see what can be done here.

**Comment by msrd0** [comment]
I just encountered the same problem. My laptop was able to run the tests fine (i5-8250U). However, on my desktop (Ryzen 3900X) this test fails.

I have installed this version of the amd microcode:

```
local/amd-ucode 20230804.7be2766d-2
    Microcode update image for AMD CPUs
```
