### ISSUE TITLE
rgba fill with non-round numbers results in black background

### ISSUE THREAD

**Issue by mrmianbao** [RazrFalcon/resvg#645]
The following fill just results in a black background

<rect x={0} y={0} width={1430} height={1147} fill="rgba(248.62500607967377, 215.47500729560852, 215.47500729560852, 1)" />

I can round the numbers to fix the issue but seems like a bug as non-round numbers work fine in css.

Example with error [vercel satori playgound](https://og-playground.vercel.app/?share=vZPdToMwGIZvpfk80YRBYfxsZPPAxDvwkMTAWqBa6ALdykK4d9uyHWimJibzBL6ft8_b3xF2glBIYdMfq6xFaGh4228zqKXcp56nlHLV0hVd5QUYY8-owOgUI7Lejn64xJPJa8qqWuqCHya2cGRUPYlBozDCyOiQ6ZnRj6a_afL-HTGiBX0uRcdeRbNgJAPb1f2O7iQatiOe0Ml-z5Y6upjpsGSca8RdWZYZIG9Ge4b9k8sC_-5jl_Z5XX92u5WfYc1YC5xDS53Dr6d05ZzQxaSrivw-CFduHEQYxzhZx8kySRwU-JEbJrqWBOsoxqsouF7zH-arcZ7m93vx_7t_I8-NeQ_6Dw6IvWSi7SEdwdIgNTQHZprONM0BQotDBWmZ8546QBvxxl5Oe_P-pLKZJpWilc9NQQmksjvQyQGZF1pRU86FEh0nMH0A)

Example without error [vercel satori playgound](https://og-playground.vercel.app/?share=vZPLToQwFIZfpTluNGGGDkQXDbgw8Q1ckhiYFqgWStrOlAnh3T0FjXGhRpOZRS8n_-n39_QywV5zAQwye2yKnpCxU73NC2idG1gce--3Pt1q08QJpTQOWRDyvOSuzafkLp1D2ArZtC6f0t3tEh-l8A96RBAllGAWQSWsvA9q1pX2lUiOsi2dNvJZdxvJC1hU1I3YOzLmE53Jaenf7XD24YTTWiqFiKu6rgsg8YqOA_snlw393SeU9aWmf3udx-3PJNNU5fUuSSK8h7Xtbj7J32_-0od1FscsPFscIQI9OKl7C2yChQUMWRGsLGDIioCL6tAAq0tlRQSi0y_y6TSET-L8EiGn1r177CrBgTlzEHMErqwwoxVKaa-N4jC_AQ)

**Comment by yisibl** [comment]
https://drafts.csswg.org/css-color-4/#rgb-functions
I'll try to fix this.

**Comment by RazrFalcon** [comment]
Yes, resvg doesn't support CSS 4 Color draft.

**Comment by RazrFalcon** [comment]
Fixed in 0.36
