### ISSUE TITLE
RFC: Replace tiny-skia with native CoreGraphics support on Apple platforms

### ISSUE THREAD

**Issue by schwa** [RazrFalcon/resvg#650]
This is more a request for comment than a bug report.

I'm wondering about the feasibility of replacing tiny-skia with native Apple CoreGraphics/Quartz rendering support. Using native CoreGraphics rendering can/could would have several potential benefits on Apple platforms - naming optimisation, use of native fonts and colorspace handling, rendering directly to a context (i.e. a UI view or something else) instead of a intermediate pixel buffer etc.

Is resvg heavily tied to tiny-skia or is there some form of abstraction layer? If tied to tiny-skia would a "tiny-skia-cg" replacement library be a viable option perhaps?

Any thoughts on this topic appreciated. Thanks in advance.

**Comment by notgull** [comment]
`resvg` is just a renderer built on top of `usvg`, you can write another renderer on top of it.

I was planning on doing that but with `piet` instead of `tiny-skia`, that way anything that implements `piet` can be used as a backend. In your case you would be able to use `piet-coregraphics`.
