### ISSUE TITLE
Extract x/y coordinates from use xlink:href tag?

### ISSUE THREAD

**Issue by debuuu** [RazrFalcon/resvg#656]
Hi,

I have some SVG exported from Affinity Designer, a snip of which looks like this:

```
    <g id="Background" transform="matrix(1,0,0,1,-1,-3)">
        <use xlink:href="#_Image1" x="0" y="0" width="256px" height="242px"/>
    </g>
    <g id="Table" transform="matrix(1,0,0,1,-1,-3)">
        <use xlink:href="#_Image2" x="290" y="45" width="108px" height="162px"/>
    </g>
```

Is it possible to get the x and y position after parsing this SVG with resvg? I found usvg::ImageHrefResolver and added a simple one that prints the name of the href tag, but I only see image/png printed out, so I guess I'm going in the wrong direction.

Thanks :)

**Comment by RazrFalcon** [comment]
So you want `x="290" y="45"` without the parent transform? You can try calling `usvg` CLI tool to see what tree the `usvg` library would produce. It would look something like:

```xml
<g id="Table" transform="matrix(1 0 0 1 -1 -3)">
    <g transform="matrix(1 0 0 1 290 45)">
        <image ...
```

Meaning you want to get the transform of the first child of the element you want.

Note that `usvg` is a very complicated element and can produce different output. It will not always look the same.

**Comment by debuuu** [comment]
Thanks a lot for the reply, I'll investigate that angle!
