### ISSUE TITLE
Rotated text results in wrong Boundingbox

### ISSUE THREAD

**Issue by eqv** [RazrFalcon/resvg#66]
When individual characters are rotated, the boundingbox is calculated as if no rotation took place, yet the render is working correctly (see the png file which is generated from the attached svg (renamed to test.txt since github doesn't allow svg uploads)

The png was generated use the tool from the examples folder and resvg version 0.3.0.

![bb](https://user-images.githubusercontent.com/3338793/41509489-ddb75c08-7254-11e8-8d8d-66412a5fa4e8.png)

[test.txt](https://github.com/RazrFalcon/resvg/files/2109125/test.txt)

**Comment by RazrFalcon** [comment]
Interesting. It's definitely a bug. The bbox detection is a separate code, sadly. So it may work differently.

**Comment by RazrFalcon** [comment]
Done.

I don't plan to release a new version any time soon, so you have to use the master branch.

Note that text-decoration (underline, etc.) will also be ignored. I still don't know should it impact the bbox or not.
