### ISSUE TITLE
viewsvg: Segmentation fault

### ISSUE THREAD

**Issue by flosse** [RazrFalcon/resvg#660]
Looking for a viewer that can display medium complex SVG files under linux, I thought that `resvg/viewsvg` should be fast.
At a first try I directly encountered a `Segmentation fault`.
I suspect that this is more at the C/C++ level, but I don't know how to find out for sure.
Is it worth to look for the cause more exactly? or is `viewsg` more like a toy?
If not, how can I better isolate the error?

**Comment by flosse** [comment]
... and one more addition:
I just tried (with `resvg --dpi 4000 file.svg out.png`) to create a PNG file, but there it seems the same problem :disappointed:

**Comment by RazrFalcon** [comment]
Can you send me the SVG you're trying to render?

> or is viewsg more like a toy?

It's more like a demo.

**Comment by flosse** [comment]
> Can you send me the SVG you're trying to render?

well, it's 45 MB large, so probably that's the problem:

```
memory allocation of 49563723456 bytes failed
```

**Comment by RazrFalcon** [comment]
45MB is not that much. Can you compress this SVG and send it to me? You can use email if you prefer.

**Comment by RazrFalcon** [comment]
I should definitely limit layers size. This file uses up to 30GB of RAM. I guess your OS simply kills the process. macos handle it just fine even with 16GB of physical RAM.

Right now, the only limit is available memory and you're trying to render 132444x93556  image...

**Comment by flosse** [comment]
I see! Thank you! :pray:
