### ISSUE TITLE
Retrieving class of each element?

### ISSUE THREAD

**Issue by paxbun** [RazrFalcon/resvg#669]
I'm using [Verovio](https://github.com/rism-digital/verovio), a sheet music rendering library. Verovio includes information about graphical structure in class names, as in the screenshot below.

![image](https://github.com/RazrFalcon/resvg/assets/17005454/0fc48990-2870-48b7-b01c-4cc33b5e4164)

I want to retrieve this information, but it seems like resvg discards it.

https://github.com/RazrFalcon/resvg/blob/348b2cceac3b88f0f9df31a1789cc81dcd50ccaa/crates/usvg-parser/src/svgtree/parse.rs#L316-L343

I'm using resvg's other features, like converting texts into paths or getting absolute transform, so I don't want to use an alternative library. I think modifying resvg is inevitable, but would there be a better way to retrieve class names without modifying resvg?

**Comment by RazrFalcon** [comment]
It's not possible by design. resvg doesn't work like a browser and never will be. Your only choice it to fork it. Out of scope.

Also, resvg doesn't discard CSS classes, but rather flattens them.

**Comment by paxbun** [comment]
Anybody have the same problem, we have a modified version for you: https://github.com/clebrain/resvg
Use the `feat/class-support` branch.
