### ISSUE TITLE
Compile without KIO

### ISSUE THREAD

**Issue by meerfrau** [RazrFalcon/resvg#670]
I am currently building from source. Since I don't use Dolphin I don't need the thumbnailer and would like to compile without KIO. But:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF5 (missing: KIO Config) (found version "5.111.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:14 (find_package)
```
Is there a config option to disable it?

**Comment by RazrFalcon** [comment]
The Dolphin thumbnailer is completely optional and should not produce any errors unless you're building it directly.
You do not need cmake for resvg to begin with.

**Comment by meerfrau** [comment]
I've just deleted the line. Sorry for bothering you!
