### ISSUE TITLE
When `feImage` contains `x` or `y`, the rendering is incorrect.

### ISSUE THREAD

**Issue by ZhouXiaolin** [RazrFalcon/resvg#685]
```xml
<svg width="200" height="200" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <rect width="200" height="200" fill="#ffdd88"/>

  <defs>
    <rect fill="#ff0000" opacity="1" id="rect" width="100" height="100"/>
    <filter id="colorful-image" >
      <feImage xlink:href="#rect" href="#rect" x="30" y="50" 
        result="feImageResultnode" />
      <feMerge>
        <feMergeNode in="feImageResultnode" />
      </feMerge>
    </filter>
  </defs>
  <rect x="30" y="50" width="100" height="100" fill="#1e1705" filter="url(#colorful-image)"/>
  <rect x="30" y="50" width="100" height="100" stroke="#00f" fill="none"/>
</svg>
```
![](https://pichuang.oss-cn-beijing.aliyuncs.com/img/202311221843954.png)
i get left

**Comment by ZhouXiaolin** [comment]
In `filter/mod/apply_inner`, content on the left and top was mistakenly cropped first. After that, the `sub_pixmap` wasn't drawn correctly to its respective position. Using `<feImage xlink:href="#rect" href="#rect" x="40" y="60"` will make the issue more apparent.

**Comment by RazrFalcon** [comment]
Will take a look. `feImage` in general is a minefield and essentially unsupported. Mainly because it's completely undocumented and each library does [whatever it wants](https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html#filters-feImage).
