### ISSUE TITLE
Building rendersvg with cairo backend results in "built without any backends"

### ISSUE THREAD

**Issue by mythmon** [RazrFalcon/resvg#69]
I cloned the repo and ran, in the base of the repository:

```
$ cargo build --release --features="cairo-backend" -p rendersvg
$ ./target/release/rendersvg
```

This resulted in the error

```
Error: rendersvg has been built without any backends.
```

I have not tried the qt backend.

**Comment by RazrFalcon** [comment]
Looks like a cargo bug. You should not use the `-p, --package` flag. Run `cargo build` directly in the `tools/rendersvg`.
