### ISSUE TITLE
Cannot compile examples/minimal.rs

### ISSUE THREAD

**Issue by TobiasGrothmann** [RazrFalcon/resvg#691]
Hi there,

I am trying to rasterize a `.svg` file and save as `.png` following [crates/resvg/examples/minimal.rs](https://github.com/RazrFalcon/resvg/blob/cb52988ae36efa3c5b82f2f5db6200d75b84db9d/crates/resvg/examples/minimal.rs).

I am getting two errors, and am unsure what to do about them:
* no method named `calculate_bounding_boxes` found for struct `resvg::usvg::Tree` ([here](https://github.com/RazrFalcon/resvg/blob/cb52988ae36efa3c5b82f2f5db6200d75b84db9d/crates/resvg/examples/minimal.rs#L26C1-L26C1)). Maybe I am missing a use statement?
* `resvg::render` is a private module, not a function ([here](https://github.com/RazrFalcon/resvg/blob/cb52988ae36efa3c5b82f2f5db6200d75b84db9d/crates/resvg/examples/minimal.rs#L32))

thanks in advance

**Comment by RazrFalcon** [comment]
Examples are for the current master branch. [Here](https://github.com/RazrFalcon/resvg/blob/1dfe9e506c2f90b55e662b1803d27f0b4e4ace77/crates/resvg/examples/minimal.rs) is an old API.

This is because `resvg` is still rapidly evolving and doesn't have a stable API.

**Comment by TobiasGrothmann** [comment]
thanks, that solved it 👍
