### ISSUE TITLE
usvg ignores `style="mask-type:alpha"` produced by figma

### ISSUE THREAD

**Issue by aebrahim** [RazrFalcon/resvg#692]
It looks like `usvg` correctly passes through the `mask-type="alpha"` attribute, but strips the equivalent `style="mask-type:alpha"` from `mask` tags. Unfortunately, figma svg exports use `style="mask-type:alpha"`, so usvg ends up mangling them.

Ideal behavior: `usvg` converts from `style="mask-type:alpha"` to `mask-type="alpha"`

Samples (these are svg's):

### Before usvg
![alpha_mask_handled_correctly](https://github.com/RazrFalcon/resvg/assets/1380168/5343177f-7d54-40b4-b480-6a2c88ddf8c4)
### After usvg
![alpha_mask_handled_correctly usvg](https://github.com/RazrFalcon/resvg/assets/1380168/519a89a5-c6a7-4f40-9f0b-ac7008135d11)
### Before usvg
![alpha_mask_handled_incorrectly](https://github.com/RazrFalcon/resvg/assets/1380168/8d4e2def-ad17-4a78-9969-3cf3cdcba704)
### After usvg
![alpha_mask_handled_incorrectly usvg](https://github.com/RazrFalcon/resvg/assets/1380168/874cab2b-8f6c-4b25-9132-c3e1f569e8b0)

**Comment by LaurenzV** [comment]
Yes, this is known to not be supported yet, see also https://github.com/docs/svg2-changelog.md

**Comment by RazrFalcon** [comment]
Thanks! Easy fix. The SVG2 spec is a complete mess and I didn't noticed that `mask-type` is a presentation attribute.

**Comment by aebrahim** [comment]
Thanks for the quick fix!
