### ISSUE TITLE
Add Copyright Notice

### ISSUE THREAD

**Issue by golsby** [RazrFalcon/resvg#697]
The Volkswagen Group is using resvg as a component of Rhino (https://www.rhino3d.com). As part of their open source validation process, Volkswagen Group requests that a copyright notice be added to the license file. For example:

"Copyright 2017-2024 Yevhenii Reizner. All Rights Reserved."

An acceptable example of copyright + license is here:
https://github.com/Stykka/glTF-Bin/blob/master/LICENSE.txt

Thank you.

**Comment by RazrFalcon** [comment]
Done.
