### ISSUE TITLE
Try replacing `objectBoundingBox` with `userSpaceOnUse` during postprocessing.

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#700]
Since we know all bounding boxes already we can resolve object units as well. At least when possible.

**Comment by LaurenzV** [comment]
Do you think there are cases where this might not be possible at all? Because it would allow to simplify a lot of things, for example, when resolving a pattern, we might be able to remove the `viewBox`, `contentUnits` and `units` attributes and instead resolve the transform necessary for rendering those at parse time, unless I'm missing something? Having those removed might make implementing context fill a lot easier as well.

**Comment by RazrFalcon** [comment]
>Do you think there are cases where this might not be possible at all?

It's hard to be certain when it comes to SVG. In theory, it should be lossless. Will try soon.

**Comment by LaurenzV** [comment]
Nice, looking forward to that! Feel free to let me know if you need someone testing the changes (I'll try them out in `svg2pdf`).

**Comment by RazrFalcon** [comment]
I was able to implement `objectBoundingBox` resolving for clipPaths, masks and filters. Went relatively smooth. 
The only non-lossless part is [this](https://github.com/RazrFalcon/resvg/blob/196156424947e8777e5001da5c8c2da2d306a292/crates/usvg/src/parser/filter.rs#L394-L450), because I have no idea what to do with it. Previously, it was located in `resvg`, which was fine, but now we have to keep in `usvg`.

As for gradients and patterns - I have no idea what to do. Because of text, as usual. 
The problem is that I have to know node's object bbox before parsing its styles (fill/stroke). It's fine for paths, but basically impossible for text.
I have to parse text first, with dummy styles, calculate the bbox and then parse it again with actual styles. Which is absurd, because text parsing is one of the most complex and expensive parts in `usvg`.

Editing gradients and patterns afterward is no go either, because they are inside `Arc`, which is immutable.
Yes, you can mutate it when it has a single owner, but we don't, because text clones it a billion times.

The only option left is too simply replace/recreate all gradients and patterns with objects units afterwards, which might work.
We would still have to store `units` internally, but they would not be visible in the public API.

**Comment by RazrFalcon** [comment]
Thanks, but I will try to finish it myself. This change is a low-level as it gets. Even I struggle with it.

The issue with mutli-pass parsing is that our "defs" are shared. But right now everything is read-only shared, because working with mutable shared state in Rust is pain (aka `Rc<RefCell<T>>` and `Arc<Mutex<T>>`).
And by having mutably shared defs we would  not be able to return just `&T`. Making the public API worse. 
It's one issue after another...

We either have to drop shared state completely, which is fine by `resvg`, but will bloat `usvg` output and potentially increase memory usage a bit. 
Or recreate objects entirely when needed, aka copy-on-write. 

I haven't looked into `contextFill` yet, but the current goal is too make `usvg` more like a streaming parser, which is very hard with SVG.

**Comment by LaurenzV** [comment]
Okay! No worries, even if it doesn't end up working, it's already a lot simpler now.

**Comment by RazrFalcon** [comment]
Done. 🎉 

It took a while, but it seems to be working just fine. At least from the rendering perspective. Writing is questionable. Will have to add a bunch of rendering and svg writing tests before releasing. 
And it made everything way easier. Specifically `text_bbox` is gone from the renderer, which was very confusing. It's handled automatically now.

This is one the biggest changes to usvg in a while, so a lot of testing is still required.

**Comment by LaurenzV** [comment]
Ob wow, I will test it in a second! :D

**Comment by LaurenzV** [comment]
Yup, my test cases seem to be passing as well!

I'm wondering, could we go even further and remove the `viewBox` attribute of patterns as well and merge it with the pattern transform? Afaik the only thing we need `viewBox` for is to then merge it with the transform, right?:

```rs
let mut transform = tiny_skia::Transform::from_scale(sx, sy);
if let Some(vbox) = pattern.view_box() {
    let ts = usvg::utils::view_box_to_transform(vbox.rect, vbox.aspect, rect.size());
    transform = transform.pre_concat(ts);
}
```

**Comment by RazrFalcon** [comment]
Yes, patterns rendering is absurdly complicated in SVG. I will take a look if `viewBox` could be avoided.

**Comment by LaurenzV** [comment]
Don't worry though, I think what you've managed so far is already very incredible, thanks a lot again!
