### ISSUE TITLE
Children is empty after load svg, why?

### ISSUE THREAD

**Issue by CGQAQ** [RazrFalcon/resvg#704]
<img width="824" alt="image" src="https://github.com/RazrFalcon/resvg/assets/15936231/461f0ec8-2696-4f98-b5d8-9a9ba9fb25dc">

**Comment by CGQAQ** [comment]
> Remote links are not resolved.

Should have a chance to manually resolve it before you remove it

**Comment by RazrFalcon** [comment]
You can: https://github.com/RazrFalcon/resvg/blob/master/crates/resvg/examples/custom_href_resolver.rs
