### ISSUE TITLE
Implementing `PatialEq` for `usvg::Node`

### ISSUE THREAD

**Issue by Ultraxime** [RazrFalcon/resvg#705]
Hello,

I'm currently using the lib as a dependency in one of my project.

I was trying to add as many unitary tests as possible to my own lib, and I stumbled on the fact the `usvg::Node` does not implement `PartialEq`.
I understand, given the structure of the node, the equality of two nodes is an operation with high cost, and not really useful.
But, a structural equality would be useful for unitary test.

So I was wondering if any workarounds are known, or if it was planned to be added in the future.

Sincerely

**Comment by RazrFalcon** [comment]
Yes, it is too expensive and pointless. You should implement it on your side.

**Comment by Ultraxime** [comment]
Wouldn't be easier if you already implemented structural equality using the derive PartialEq ?
Especially because many structs in your lib does not provide it ?

**Comment by RazrFalcon** [comment]
`PartialEq` isn't implemented for a reason. `Node` isn't designed to be compared.
