### ISSUE TITLE
Unexpected empty image rendered

### ISSUE THREAD

**Issue by sorairolake** [RazrFalcon/resvg#711]
Since `resvg` v0.38.0 or later, an unexpected empty image is rendered when inputting the following SVG image.

SVG image to input:

![Input](https://github.com/RazrFalcon/resvg/assets/48999343/5c36688e-5607-494c-946f-34170b6fbc0a)

Expected output PNG image:

![Expected](https://github.com/RazrFalcon/resvg/assets/48999343/97abc946-5455-4b7e-868a-ab76b4886e57)

Actual output PNG image:

![Actual](https://github.com/RazrFalcon/resvg/assets/48999343/58a68275-2ad4-42d2-afcf-4a45a8565a36)

Code:

```rs
use std::io::Write;

fn main() {
    let args: Vec<_> = std::env::args().collect();

    let opt = resvg::usvg::Options::default();

    let data = std::fs::read(&args[1]).unwrap();
    let tree = resvg::usvg::Tree::from_data(&data, &opt).unwrap();

    let pixmap_size = tree.size.to_int_size();
    let mut pixmap =
        resvg::tiny_skia::Pixmap::new(pixmap_size.width(), pixmap_size.height()).unwrap();
    resvg::render(
        &tree,
        resvg::tiny_skia::Transform::default(),
        &mut pixmap.as_mut(),
    );
    let image = pixmap.encode_png().unwrap();
    std::io::stdout().write_all(&image).unwrap();
}
```

Cargo.toml:

```toml
[dependencies]
resvg = { version = "0.39.0", default-features = false }
```

**Comment by LaurenzV** [comment]
The API has changed, you need to call `tree.calculate_bounding_boxes()` or `tree.postprocess()` before rendering it.

**Comment by RazrFalcon** [comment]
Here is how resvg should be used: https://github.com/RazrFalcon/resvg/blob/master/crates/resvg/examples/minimal.rs
