### ISSUE TITLE
Create your own usvg::Tree 

### ISSUE THREAD

**Issue by biojet1** [RazrFalcon/resvg#713]
In the new build #712  
You cant crate your own _usvg::Tree_ now.
Everything is private.
You have to use _usvg::Tree::from_xmltree_.
Is there a way to create your own _usvg::Tree_ ?

**Comment by LaurenzV** [comment]
See here: https://github.com/RazrFalcon/resvg/issues/710

**Comment by RazrFalcon** [comment]
Nope. That's by design.
