### ISSUE TITLE
Only width/height on image

### ISSUE THREAD

**Issue by LaurenzV** [RazrFalcon/resvg#714]
Hello,

I was investigating https://github.com/typst/svg2pdf/issues/58 and found out that the issue is that we don't consider the case where only one of width/height is set. After fixing it, I realized that this does seem to be intentional though? Because two test cases fail now, one of which being:

```svg
<svg id="svg1" viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>No `width` (SVG 2)</title>
    <desc>Nothing should be rendered in a SVG 1 conforming renderer.</desc>

    <image id="image1" x="8" y="8" height="64" xlink:href="../../../resources/image.jpg"/>

    <rect id="frame" x="1" y="1" width="78" height="78" fill="none" stroke="black"/>
</svg>
```

Does this mean we don't plan to support this at all? Or is this just a remnant from when we didn't support SVG2 yet? If so, I can open a PR that fixes this.

**Comment by RazrFalcon** [comment]
I'm not sure I understand the issue. The current implementation works as expected.

**Comment by LaurenzV** [comment]
Consider the following SVG (the image is a 100x100 pixel blue image):

```svg
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">

    <rect id="frame" x="0" y="0" width="200" height="500" fill="red"/>

    <image id="image1" height="200" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAAXNSR0IArs4c6QAAAXBJREFUeF7t1VEJACAUxVDtj1XsZQoFU5yPvQRj4/Lm2ueOjjEwC8K0+CAFsXoUBOtRkIJoBjCefkhBMAMYTgspCGYAw2khBcEMYDgtpCCYAQynhRQEM4DhtJCCYAYwnBZSEMwAhtNCCoIZwHBaSEEwAxhOCykIZgDDaSEFwQxgOC2kIJgBDKeFFAQzgOG0kIJgBjCcFlIQzACG00IKghnAcFpIQTADGE4LKQhmAMNpIQXBDGA4LaQgmAEMp4UUBDOA4bSQgmAGMJwWUhDMAIbTQgqCGcBwWkhBMAMYTgspCGYAw2khBcEMYDgtpCCYAQynhRQEM4DhtJCCYAYwnBZSEMwAhtNCCoIZwHBaSEEwAxhOCykIZgDDaSEFwQxgOC2kIJgBDKeFFAQzgOG0kIJgBjCcFlIQzACG00IKghnAcFpIQTADGE4LKQhmAMNpIQXBDGA4LaQgmAEMp4UUBDOA4bSQgmAGMJwWUhDMAIbzAGCeOiB4QsvLAAAAAElFTkSuQmCC"/>
</svg>
```

Here's how it's rendered by different viewers:

<img width="1508" alt="image" src="https://github.com/RazrFalcon/resvg/assets/47084093/e5764feb-ede8-4406-a787-ed2211a33581">

Do you consider Chrome/Firefox/Safari to be incorrect here?

According to the [spec](https://www.w3.org/TR/SVG2/geometry.html#Sizing):
> New in SVG 2. Images embedded in SVG can now be auto-sized to the intrinsic size, or scaled to a fixed height or width according to the intrinsic aspect ratio. This matches the behavior of embedded images in HTML.

And since we are aiming to implement SVG2, we should allow this behaviour as well, right?

**Comment by LaurenzV** [comment]
Consider the following SVG (the image is a 100x100 pixel blue image):

```svg
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">

    <rect id="frame" x="0" y="0" width="200" height="500" fill="red"/>

    <image id="image1" height="200" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAAXNSR0IArs4c6QAAAXBJREFUeF7t1VEJACAUxVDtj1XsZQoFU5yPvQRj4/Lm2ueOjjEwC8K0+CAFsXoUBOtRkIJoBjCefkhBMAMYTgspCGYAw2khBcEMYDgtpCCYAQynhRQEM4DhtJCCYAYwnBZSEMwAhtNCCoIZwHBaSEEwAxhOCykIZgDDaSEFwQxgOC2kIJgBDKeFFAQzgOG0kIJgBjCcFlIQzACG00IKghnAcFpIQTADGE4LKQhmAMNpIQXBDGA4LaQgmAEMp4UUBDOA4bSQgmAGMJwWUhDMAIbTQgqCGcBwWkhBMAMYTgspCGYAw2khBcEMYDgtpCCYAQynhRQEM4DhtJCCYAYwnBZSEMwAhtNCCoIZwHBaSEEwAxhOCykIZgDDaSEFwQxgOC2kIJgBDKeFFAQzgOG0kIJgBjCcFlIQzACG00IKghnAcFpIQTADGE4LKQhmAMNpIQXBDGA4LaQgmAEMp4UUBDOA4bSQgmAGMJwWUhDMAIbzAGCeOiB4QsvLAAAAAElFTkSuQmCC"/>
</svg>
```

Here's how it's rendered by different viewers:

<img width="1508" alt="image" src="https://github.com/RazrFalcon/resvg/assets/47084093/e5764feb-ede8-4406-a787-ed2211a33581">

Do you consider Chrome/Firefox/Safari to be incorrect here?

According to the [spec](https://www.w3.org/TR/SVG2/geometry.html#Sizing):
> New in SVG 2. Images embedded in SVG can now be auto-sized to the intrinsic size, or scaled to a fixed height or width according to the intrinsic aspect ratio. This matches the behavior of embedded images in HTML.

And since we are aiming to implement SVG2, we should allow this behaviour as well, right?

**Comment by RazrFalcon** [comment]
Interesting. Yes, this one isn't implemented. Right now, the actual image size is used only as a fallback and we do not account for aspect.

We would have to add new tests for that as well.

**Comment by LaurenzV** [comment]
Will do so.
