### ISSUE TITLE
Extracting densely sampled straight line segments from curves

### ISSUE THREAD

**Issue by arcadeperfect** [RazrFalcon/resvg#718]
Hello, 

I am trying to extract a pre-sampled path of straight line segments, or something that allows me to sample a given path at arbitrary point t, that can represent a curve at reasonable resolution, for passing to physical plotter. Can this be achieved with the library or will I have to implement my own cubic / quad interpolation according to the verbs in the Path struct?

**Comment by RazrFalcon** [comment]
This is not supported, but you can use [kurbo](https://github.com/linebender/kurbo) for that. [Example.](https://github.com/RazrFalcon/resvg/blob/20c8dcc0d9b1c006f3964a995bbcf68c3f3da41d/crates/usvg/src/text_to_paths.rs#L1447) 
`resvg`/`usvg` are just for parsing and rendering.

**Comment by arcadeperfect** [comment]
Thanks for the reply, I will look at kurbo
