### ISSUE TITLE
Cannot mutate/alter usvg::Tree

### ISSUE THREAD

**Issue by tylers-epilog** [RazrFalcon/resvg#719]
There are several ways in which it seems that I can no longer mutate `usvg::Tree` objects.

1. Cannot insert children into nodes anymore.
2. Cannot change path `stroke`/`fill`.

There may be others, but I can't enumerate them all at the moment.

My question/concern is this: What is the new way to do this now that everything in `usvg` seems to be read-only? Am I supposed to build an entirely new tree if I want to modify an attribute or a node's children? Or perhaps are there new methods to do this that I'm not seeing?

Thanks!

**Comment by LaurenzV** [comment]
See here: https://github.com/RazrFalcon/resvg/issues/710

**Comment by tylers-epilog** [comment]
Thanks @LaurenzV! I'll take a look at that. It's a lot to digest.

**Comment by RazrFalcon** [comment]
Duplicate of #710
