### ISSUE TITLE
Add Qt 6.7 to SVG support chart

### ISSUE THREAD

**Issue by woodroof** [RazrFalcon/resvg#721]
Qt [extended](https://www.qt.io/blog/qt-svg-not-so-1.2-tiny-any-more) their SVG support. It'll be good to have comparison with a fresh Qt version.

**Comment by RazrFalcon** [comment]
Interesting. They might get +10% coverage increase. Will test someday.

**Comment by RazrFalcon** [comment]
10% jump. Not bad.
