### ISSUE TITLE
context-fill inconsistent with browser rendering

### ISSUE THREAD

**Issue by yisibl** [RazrFalcon/resvg#741]
## Test SVG

```svg
<svg width="100mm" height="100mm" viewBox="0 0 100 100" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" >
   <defs>
      <pattern patternUnits="userSpaceOnUse" width="2" height="2" viewBox="0 0 2 2" id="circular-pattern">
         <circle fill="#117611" stroke="none" id="circle-in-pattern" cx="1" cy="1" r="1" />
      </pattern>
      <marker orient="auto" id="test-marker" refX="0" refY="1" markerWidth="10"
         markerHeight="10" viewBox="0 0 2 2" preserveAspectRatio="xMidYMid">
         <rect x="0" y="0" width="2" height="2" fill="context-fill" fill-rule="evenodd" stroke="none" />
      </marker>
   </defs>
   <path fill="url(#circular-pattern)" stroke="#ff0000" stroke-width="1" marker-end="url(#test-marker)" d="M 25,50 H 75" id="test-path" />
</svg>
```

## Output

I'm not sure which rendering is correct.

![context-fill](https://github.com/RazrFalcon/resvg/assets/2784308/9ed09893-2877-418c-87fa-dcd3a26a8b0c)

Please test with Chrome 126.0.6425.0 or above, they just fixed an [issue](https://chromiumdash.appspot.com/commit/9cf8ac20f215f9a9b29089729e9d302ec8fcf930).

**Comment by yisibl** [comment]
This SVG also renders differently in the three engines, so it could be a similar issue.

![marker-hatch](https://github.com/RazrFalcon/resvg/assets/2784308/6bfa1c52-1ac9-4b6d-b228-321cb84b02bf)

**Comment by LaurenzV** [comment]
Will take a look.

**Comment by LaurenzV** [comment]
Oh yeah, looks like we don't reverse the viewbox transform of the marker...

**Comment by RazrFalcon** [comment]
Classic SVG. No one was able to figure out what the spec suppose to mean.

librsvg for the reference:
![marker-context-fill-pattern](https://github.com/RazrFalcon/resvg/assets/725494/93eae27e-d5bc-4fbb-aaef-179e60f20e18)

Safari, Inkscape and Batik do not support `context-fill` with pattern at all.

**Comment by yisibl** [comment]
@LaurenzV Which rendering do you think is correct regarding the first test case?

**Comment by LaurenzV** [comment]
The Chrome one is correct.
