### ISSUE TITLE
Dynamically create own SVG tree.

### ISSUE THREAD

**Issue by spirali** [RazrFalcon/resvg#746]
Hi,

I am using usvg as an intermediate representation of an image data. In version 0.39, I was able to dynamically create a tree and then render it. Is it still possible to do this with the current API? It seems that now I cannot now create own of tree nodes outside of usvg crate.

**Comment by LaurenzV** [comment]
It's not possible anymore. See #710.

**Comment by spirali** [comment]
Thank you.

**Comment by RazrFalcon** [comment]
You're suppose to use `tiny-skia` directly. Creating `usvg::Tree` by hand and passing it to `resvg` would be way slower.

**Comment by spirali** [comment]
I actually used this mainly for creating PDF; I built a usvg tree and then render it via svg2pdf. Therefore, the correct way for me is to probably directly use pdf-writer. Now I will need two renderers, one via tiny skia and one trough pdf-writer, but I understand your decision.

**Comment by LaurenzV** [comment]
Writing a renderer from scratch with `pdf-writer` will be a pain... You will probably have an easier time if you instead construct an SVG string and convert that. This is still more inconvenient than constructing the tree directly, but definitely less inconvenient then maintaining two rendering backends.
