### ISSUE TITLE
SVG fails to parse

### ISSUE THREAD

**Issue by LaurenzV** [RazrFalcon/resvg#749]
Attempting to render the following SVG:

![test](https://github.com/RazrFalcon/resvg/assets/47084093/0e815f0d-b0a1-4eb6-9e56-753e8b72fc78)

results in the following message:
`Error: an unknown namespace prefix 'kvg' at 39:19.`

Not sure if it's a malformed SVG, but at least it opens fine in Chrome, Safari and Firefox.

**Comment by LaurenzV** [comment]
Adding `xmlns:kvg="http://kanjivg.tagaini.net"` to the root SVG seems to fix it. But not sure if it's really not supposed to render without it? I'm not really sure what `ATTLIST` is. But in any case, since it opens fine on all other browsers maybe we should allow this too (in case this SVG really is malformed).

**Comment by RazrFalcon** [comment]
I cannot download the file for some reason. Can you re-upload it?

**Comment by LaurenzV** [comment]
You can find it here: https://github.com/KanjiVG/kanjivg/blob/master/kanji/06c34.svg

**Comment by RazrFalcon** [comment]
Yep, that's some XML DTD magic. We do not support it and would probably never will be.
Sadly, but out of scope.
