### ISSUE TITLE
Tab indentation affects rendering styles

### ISSUE THREAD

**Issue by ahaoboy** [RazrFalcon/resvg#751]
The number of tspan tag indentations causes the rendered character positions to change

```svg
<svg width="2080px" height="608px"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve">

  <style>
tspan {
    font-variant-ligatures: none;
    dominant-baseline: central;
    font-variant-ligatures: none;
    white-space: pre;
    font-family: Courier, monospace;
    font-size: 32px;
}

  </style>
  <text x="20px" y="256px" font-weight="bold" width="20px" height="32px" fill='rgb(13, 188, 121)'>
                      <tspan>✓</tspan>
  </text>
  <text x="40px" y="256px" font-weight="bold" width="20px" height="32px" fill='white'>
    <tspan></tspan>
  </text>
  <text x="60px" y="256px" font-weight="bold" width="20px" height="32px" fill='white'>
    <tspan>b</tspan>
  </text>
  <text x="80px" y="256px" font-weight="bold" width="20px" height="32px" fill='white'>
    <tspan>e</tspan>
  </text>
  <text x="100px" y="256px" font-weight="bold" width="20px" height="32px" fill='white'>
    <tspan>n</tspan>
  </text>
  <text x="120px" y="256px" font-weight="bold" width="20px" height="32px" fill='white'>
    <tspan>c</tspan>
  </text>
  <text x="140px" y="256px" font-weight="bold" width="20px" height="32px" fill='white'>
    <tspan>h</tspan>
  </text>
</svg>
```

```diff 
+ <tspan>✓</tspan>
-                       <tspan>✓</tspan>

```

### chrome/edge
![image](https://github.com/RazrFalcon/resvg/assets/19884146/29cdbdfa-acdc-41dc-8622-816a7ec9642c)

### resvg
```bash
 cat ./test.svg | resvg - -c > test.png
``` 
![d](https://github.com/RazrFalcon/resvg/assets/19884146/4f78358c-c964-49e2-80c6-5d0412b8d1a3)
![d](https://github.com/RazrFalcon/resvg/assets/19884146/25b75cd8-7e8c-4f26-8305-48b64fc943b3)

**Comment by LaurenzV** [comment]
For me it also shifts when I open it in Chrome... And the reason it does that is because you have `xml:space="preserve"` in your SVG.

**Comment by RazrFalcon** [comment]
This is the expected behaviour because you have `xml:space="preserve"`
![tspan-pad](https://github.com/RazrFalcon/resvg/assets/725494/18940859-da05-44bb-b00e-a62a390d627c)

Yes, for some reason Chrome and Safari ignore it in this case, but that's SVG for you - no one know how to render it.

Not a bug unless someone would be able to figure out what part of the spec defines such behaviour.

**Comment by ahaoboy** [comment]
Thanks for the explanation.
