### ISSUE TITLE
Strange bug with pyo3 on macos

### ISSUE THREAD

**Issue by baseplate-admin** [RazrFalcon/resvg#753]
Hi i have this following code

rust:
```rust
    let svg_string: String;

    if std::path::Path::new(&svg).exists() {
        let mut svg_data = std::fs::read(svg)
            .map_err(|_| "failed to open the provided file")
            .unwrap();
        if svg_data.starts_with(&[0x1f, 0x8b]) {
            svg_data = resvg::usvg::decompress_svgz(&svg_data)
                .map_err(|e| e.to_string())
                .unwrap();
        };
        svg_string = std::str::from_utf8(&svg_data).unwrap().to_owned();
    } else {
        svg_string = svg;
    }

```

python:

```python
def test_path():
    path = os.path.join(BASE_DIR, "acid.svg")
    base = resvg_py.svg_to_base64()
    print(path)
    assert base == svg_output


def test_gzip_path():
    path = os.path.join(BASE_DIR, "acid.svg.gz")
    base = resvg_py.svg_to_base64()
    print(path)

    assert base == svg_output
```

This fails in `macos` but runs in all other OS.

Here is the  log : https://github.com/baseplate-admin/resvg-py/actions/runs/8889901090/job/24409004312
Relevant Source :
* Rust : https://github.com/baseplate-admin/resvg-py/blob/4a89a841138d3297986892e6418c777fb068c140/src/rust/lib.rs#L164-L178 
* Python : https://github.com/baseplate-admin/resvg-py/blob/e981e211fccd43cf0581d870e0fdfb3187667023/tests/test_path.py#L1-L22

* Discussion on pyo3: https://github.com/PyO3/pyo3/discussions/4137#discussion-6584195
* Discussion on reddit : https://www.reddit.com/r/learnrust/comments/1cgpe9d/stdpathpathnewexists_with_python_pathlibpath

**Comment by LaurenzV** [comment]
I don't really get it, can you provide a simple Rust code snippet and an SVG that when run allows us to reproduce it on the Rust side?

If that issue only happens with Python then there isn't much we can do here, I think, since `resvg-py` is an unaffiliated project.

**Comment by RazrFalcon** [comment]
Can you provide/print that `acid.svg`. It seems like the string you're trying to parse is messed up somewhere on your side.

**Comment by RazrFalcon** [comment]
I do use macos, so if you can tell me how to run it locally - I will try.

**Comment by baseplate-admin** [comment]
> I do use macos, so if you can tell me how to run it locally - I will try.

First install python

1. `pip install pipx`
2. `pipx install maturin poetry`
3. `git clone https://github.com/baseplate-admin/resvg-py`
4. `poetry install`
5. `poetry shell`
6. `maturin develop`
7. `pytest .`

**Comment by baseplate-admin** [comment]
Hi @RazrFalcon,

Sorry for bothering you with this issue. 

Turns out this is a bug with python on macos..

**Comment by LaurenzV** [comment]
What's the bug? Out of curiosity.

**Comment by baseplate-admin** [comment]
The problem is with pip preferring PYPI over local package in macos. So essentially what i wrote in current package, even if i bumped the version would not be used.

Initial findings by this comment:
* https://github.com/PyO3/pyo3/issues/4161#issuecomment-2095351784

Which led me to this issue with `pip`:
* https://github.com/pypa/pip/issues/12110


References :

* https://github.com/PyO3/maturin-action/issues/263
* https://github.com/PyO3/maturin/issues/1971

**Comment by RazrFalcon** [comment]
Good. No problem.
