### ISSUE TITLE
Gradient issue

### ISSUE THREAD

**Issue by IskandarAlex2** [RazrFalcon/resvg#756]
I am making a media server with an SVG to PNG on-the-fly renderer. The issue is that it doesn't work right when the SVG contains a gradient. The images explain the problem.

<img src="https://github.com/RazrFalcon/resvg/assets/65650645/92678312-89dc-4ed0-9bc5-902151d461b2" alt="what it should have been" width="256">

<img src="https://github.com/RazrFalcon/resvg/assets/65650645/52549b75-9219-4361-b86e-d65261b4eecb" alt="what it rendered" width="256">

As additional information, the SVG was exported from Penpot with a linear gradient as the canvas background color. I should also note that the Rust server runs inside a Docker Container. I do this because resvg fail to run inside my Windows machine and let's just say I want to make sure it works inside the environment it is supposed to run in.

**Comment by LaurenzV** [comment]
Can you provide the original SVG as well? Otherwise it's hard to debug...

**Comment by IskandarAlex2** [comment]
Here, the font is [Audiowide](https://fonts.google.com/specimen/Audiowide) which you may have to download and install into your system font so that resvg recognize it

![Somethings3](https://github.com/RazrFalcon/resvg/assets/65650645/d904796e-ab00-4fd6-8897-181400c4cac0)

**Comment by IskandarAlex2** [comment]
okay for some reason the svg broke after uploading to GitHub so here a zip file
[Somethings3.zip](https://github.com/RazrFalcon/resvg/files/15238507/Somethings3.zip)

**Comment by RazrFalcon** [comment]
Can confirm:
```
Warning (in usvg::parser::style:141): Failed to parse fill value: 'url("#fill-color-gradient-render-1-0")'. Fallback to black.
```

This is because of quoted urls. That's a relatively new feature and we do not support it well.

**Comment by RazrFalcon** [comment]
We allow only single quotes in `svgtypes`...
