### ISSUE TITLE
rendering adjacent squares in SVG

### ISSUE THREAD

**Issue by hfmanson** [RazrFalcon/resvg#759]
Since resvg aims to follow the SVG spec I would like to present this corner case.
I have thin lines appearing in Chrome and resvg, not in Firefox when nine white  squares are adjacent.
![thinlines](https://github.com/RazrFalcon/resvg/assets/1826892/dfceee12-7cce-4346-9b8f-38de8cb9b0f2)

Is this inherent to SVG or a bug?

**Comment by hfmanson** [comment]
See https://stackoverflow.com/questions/78467283/thin-lines-appear-when-rendering-adjacent-squares-in-svg/78467428#78467428

**Comment by RazrFalcon** [comment]
This is by design. SVG doesn't support pixel-perfect rendering.
