### ISSUE TITLE
SVG 2 CMYK colors and CMYK JPEG output?

### ISSUE THREAD

**Issue by eremin** [RazrFalcon/resvg#766]
Hello,

is there some way now to render a SVG file with CMYK color values (device-cmyk(...) or icc-color(acmecmyk, ...) - is a part of SVG 2 draft) to JPEG with CMYK colorspace or some plans to implement this?

**Comment by RazrFalcon** [comment]
It's not possible and probably will not be possible in the next 3-5 years, if ever.
