### ISSUE TITLE
viewsvg should have ability to resize itself

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [RazrFalcon/resvg#774]
If you set Size -> Original in viewsvg, once you drag a SVG image in it, the interface should be able to resize itself but if the image is larger than screen, the interface should just resize to its maximum size on screen. This should depends on `view`, `height`, and/or `viewBox` properties.

**Comment by RazrFalcon** [comment]
viewsvg is just a demo, not an SVG viewer.
