### ISSUE TITLE
High memory usage when use image href data uri base64

### ISSUE THREAD

**Issue by ducan-ne** [RazrFalcon/resvg#780]
As mentioned by title, my process memory usage come from 100mb to 450mb after rendering the svg.
![CleanShot 2024-06-16 at 05 27 46@2x](https://github.com/RazrFalcon/resvg/assets/16853175/7fff0041-ae82-4529-978e-da8f42515222)

I'm not sure this issue is from the binding (wasm) site ore the resvg itself. But it is likely to from resvg because as I tried two js bindings (resvg-js + svg2png-wasm) have the same issue.

I couldn't myself verify if it running well in rust or not because I don't know any about Rust 🥲
My reproducible script if nodejs is fine to you: https://gist.github.com/ducan-ne/88c1f4ce047b6cf2883f3b7c0138818f

**Comment by RazrFalcon** [comment]
I can confirm that `resvg` allocates up to 268MB rendering this file.
But your JPEG embedded into SVG is 7362x3679. That's a lot. Downscale it a bit an the problem will go away.

**Comment by ducan-ne** [comment]
@RazrFalcon I'm curious the resolution is the root cause here? The file is 7362x3679 but only 432kb. I also passed w/h to image tag like this `<image x="0" y="0" width="1200" height="630"`, I though it should behave like resizing the image 👀
This is because the image comes from a editor and they resize them to fit the container (use a big image), currently it I don't figure out any way to validate this have to fit the container..

Hmm but let me try to downscale the image to fit the container, at least it seems to be a solution.

**Comment by RazrFalcon** [comment]
>The file is 7362x3679 but only 432kb. 

Compressed is 432kb, but decompressed is 7362x3679x4 (RGBA8888), which is 100MB already. And we need two of them: one for raw JPEG data and one for `tiny_skia::Pixmap`. This is because JPEG is RGB888 and we need RGBA8888.

We could potentially try decoding an already downscaled JPEG image, but for now the only solution is to have a smaller image.

> I also passed w/h to image tag, assuming it should behave like resizing the image.

Sure, but we still have to decode the original image.

**Comment by ducan-ne** [comment]
I see, thanks for clarifying that. I will try to solve from my side now.
Since it now seems appropriate after your explanation. Should I close the issue?

**Comment by RazrFalcon** [comment]
I have added #782 to address this issue in the future.
