### ISSUE TITLE
Specific SVG has greyed out colours

### ISSUE THREAD

**Issue by Stoppedpuma** [RazrFalcon/resvg#783]
The colours in this SVG appear greyed out for some reason, colours are represented properly in software without resvg.

You can download this for testing [here](https://puma.s-ul.eu/E0pK6CNG)

Appearance in oculante (uses resvg):

![image](https://github.com/RazrFalcon/resvg/assets/58333920/4d0f5f85-861a-4813-b1fb-0ace2471b63c)

Appearance in imv:

![image](https://github.com/RazrFalcon/resvg/assets/58333920/9da6fd02-92b0-4ec6-b8be-c39d7ef51a05)

**Comment by Stoppedpuma** [comment]
This is also reproducible at https://resvg-js.vercel.app/ so I'm not sure it's viewer specific?

**Comment by LaurenzV** [comment]
Okay, I see now, it seems to be an issue with resvg 0.33, which is what `oculante` uses. But it doesn't seem to be reproducible on main anymore.

**Comment by Stoppedpuma** [comment]
Got it, thanks! I'll reopen if this issue presists.

**Comment by LaurenzV** [comment]
Yep, just bisected it, this was fixed in https://github.com/RazrFalcon/resvg/commit/67ca118f47fba6b65550c40635e56207a159ca4d. Your SVG contains `mask-type: alpha` as a presentation attribute
