### ISSUE TITLE
Interested in fixing clippy lints?

### ISSUE THREAD

**Issue by mattfbacon** [RazrFalcon/resvg#788]
Would you be interested in a PR to fix the existing clippy lints?
I wanted to ask before doing the work because sometimes people don't want it.
As it is it makes it difficult to work on the project because there are over a hundred diagnostics including some deny-by-default lints that would seem to indicate serious issues.

For example:

![Some of the diagnostics](https://github.com/RazrFalcon/resvg/assets/58113890/5cd6b745-ce4b-405c-a646-91c0fc757ac1)

**Comment by LaurenzV** [comment]
Afaik he doesn't like such PRs.

**Comment by RazrFalcon** [comment]
Nope: https://github.com/RazrFalcon/resvg/blob/master/.github/pull_request_template.md

I run clippy before a release anyway.
