### ISSUE TITLE
Test cases don't pass with newest tiny-skia-path

### ISSUE THREAD

**Issue by LaurenzV** [RazrFalcon/resvg#795]
Add the following line to `Cargo.toml`:
```
[patch.crates-io]
tiny-skia-path = {git = "https://github.com/RazrFalcon/tiny-skia", rev="9b673e6"}
```

And you will see that a lot of test cases start to fail. Seems like this commit is the main fault: https://github.com/RazrFalcon/tiny-skia/commit/9b673e6c14e5e0c3f98413f8fa7e3a6cb315183b

**Comment by RazrFalcon** [comment]
This should have been fixed in master. https://github.com/RazrFalcon/tiny-skia/commit/eec0a4701a8413759a3dd51b443b8851ce4c546a ?

**Comment by LaurenzV** [comment]
Indeed, sorry for the noise, I hadn't pulled the newest branch!

**Comment by RazrFalcon** [comment]
No worries.
