### ISSUE TITLE
Inkscape clip groups are excluded

### ISSUE THREAD

**Issue by Stoppedpuma** [RazrFalcon/resvg#796]
Appearance in Inkscape:

![image](https://github.com/user-attachments/assets/d09cb281-646e-452b-a3af-dff679494bc6)

Rendered from CLI on [`v0.42.0`](https://github.com/RazrFalcon/resvg/releases/tag/v0.42.0):

![image](https://github.com/user-attachments/assets/59e0a19c-842a-4887-9609-67479879c514)

This file can be downloaded [here](https://puma.s-ul.eu/CvyLfia7) for testing.

**Comment by RazrFalcon** [comment]
It's an Inkscape bug. It doesn't follow the SVG spec. ClipPaths are not allowed to have groups.
