### ISSUE TITLE
Request: update rustybuzz dependancy in next release

### ISSUE THREAD

**Issue by sww1235** [RazrFalcon/resvg#798]
usvg depends on rustbybuzz 0.14.1 while the newest version of rustybuzz is 0.17.0.

This causes clippy to complain about duplicate crate versions. Not a huge deal and i could silence the warning, but figured I would try and get the issue fixed upstream.

Feel free to close this if this breaks things.

thank you

**Comment by sww1235** [comment]
If this is acceptable, I can submit a patch for this.

**Comment by LaurenzV** [comment]
RazrFalcon usually updates all dependencies before a new release.

**Comment by RazrFalcon** [comment]
https://github.com/RazrFalcon/resvg/blob/master/.github/pull_request_template.md

It will be done when it will be done.
