### ISSUE TITLE
Incorrect s command simplification

### ISSUE THREAD

**Issue by woodroof** [RazrFalcon/resvg#807]
Specifications says "If there is no previous command or if the previous command was not an C, c, S or s, assume the first control point is coincident with the current point."
Example:
`<path d="M 1 5 A 5.389 5.389 0 0 1 3 1 s 2.5 2 8 2 Z">`
usvg first changes `A` command to `C` and then uses this C command to calculate `s` first control point, but that is incorrect.
Current result:
`M 1 5 C 1.0558429 3.4399235 1.7854446 1.9807202 3 1 C 4.2145553 0.01927989 5.5 3 11 3 Z`
Correct result:
`M 1 5 C 1.0558429 3.4399235 1.7854446 1.9807202 3 1 C 3 1 5.5 3 11 3`.

Test svg:
![test](https://github.com/user-attachments/assets/ab182426-c865-433e-921a-3520bde449d9)
Actual result:
![actual](https://github.com/user-attachments/assets/ee20874d-ce4e-4b2c-873e-2dcdb280414d)
Expected result:
![expected](https://github.com/user-attachments/assets/5b9b516e-7d9e-49f8-9f58-036cdb303e9e)

**Comment by RazrFalcon** [comment]
Yep. Broke it a year ago trying to simplify path parsing. Lack of testing...
SVG paths are truly insane.
