### ISSUE TITLE
Deduplicate fontdb types

### ISSUE THREAD

**Issue by dhardy** [RazrFalcon/resvg#808]
`resvg` optionally depends on `fontdb`. Meanwhile,

- `usvg::FontStyle` is identical to `fontdb::Style`
- `usvg::FontStretch` is identical to `fontdb::Stretch`

Worse, there isn't even a conversion method between the two. This is a pain when implementing a `usvg::FontResolver`.

**Comment by RazrFalcon** [comment]
Erm... what exactly is your solution?

Also, there are like 2 people who would need to implement `usvg::FontResolver` themselves. It's a super niche case.

**Comment by dhardy** [comment]
The simplest I can think of is to make this feature dependent:

- when `usvg` uses `fontdb`, those types are just re-exports of the `fontdb` types
- otherwise, they are distinct types

**Comment by RazrFalcon** [comment]
This will only complicate things.

**Comment by dhardy** [comment]
No, it will simplify things for anyone downstream happening to need to use both types.

An alternative would be to implement `From` conversions. Probably more robust (to unforeseen changes in `fontdb` definitions of the types), but slightly more complicated.

**Comment by RazrFalcon** [comment]
`From` is fine.
