### ISSUE TITLE
Is there any plan to support svg compression such as svgo?

### ISSUE THREAD

**Issue by ahaoboy** [RazrFalcon/resvg#817]
https://github.com/svg/svgo

It seems that rust currently has no similar tools? resvg is the most comprehensive library currently. It would be very useful if a tool similar to svgo could be implemented based on resvg's AST.

**Comment by RazrFalcon** [comment]
`resvg`/`usvg` cannot be used for SVG minification. It should be a separate implementation. Like [svgcleaner](https://github.com/RazrFalcon/svgcleaner) once was.
