### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by lobneroO** [RazrFalcon/resvg#827]
I was just about to use this seemingly really good library, but I cannot find any documentation whatsoever. #618 leads me to believe there must be documentation though, but I could not find anything even when going back a few versions on [docs.rs](https://docs.rs/resvg/latest/resvg/#reexports). There is no Wiki in the repository either.
Is there no documentation? If there is, can it be linked somewhere?

**Comment by LaurenzV** [comment]
Well, there isn't much to document for `resvg`, because all it does is render an SVG onto a pixmap.

Maybe you arr looking for the documentation of [`usvg`](https://docs.rs/usvg/0.44.0/usvg/index.html)?

**Comment by lobneroO** [comment]
Hmm does this library not also enable creating new images programmatically? I was under the impression it did that (though maybe that was just me, since I was looking to do so). usvg as a parser is the wrong way round, so to say.

**Comment by LaurenzV** [comment]
I'm not sure I'm following... You mean creating an image from an existing SVG, or creating an image from scratch?

What part are you missing documentation from exactly?

**Comment by RazrFalcon** [comment]
>Is there no documentation?

Documentation of what? Everything you have to know about it can be found [here](https://github.com/RazrFalcon/resvg/blob/master/crates/resvg/examples/minimal.rs).

>Hmm does this library not also enable creating new images programmatically?

Nope. It's a parser/renderer.

**Comment by lobneroO** [comment]
> You mean creating an image from an existing SVG, or creating an image from scratch?
Creating an image from scratch. 

> Nope. It's a parser/renderer.
Then I was mistaken about what this does, sorry.

> Everything you have to know about it can be found [here](https://github.com/RazrFalcon/resvg/blob/master/crates/resvg/examples/minimal.rs).
No offense, but an example file that is neither linked to nor contains any comments / explanation is not documentation. I don't know why this is so prevalent nowadays.

Thanks for your quick responses

**Comment by RazrFalcon** [comment]
>I don't know why this is so prevalent nowadays.

Because writing documentation takes time and I'm already low on it.
