### ISSUE TITLE
Not compiling when installing oomox, which pulls resvg in as dependency.

### ISSUE THREAD

**Issue by stevensonmt** [RazrFalcon/resvg#99]
Getting the error message below:

> error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
>   --> usvg/src/convert/marker.rs:74:67
>    |
> 74 |                 svgdom::AngleUnit::Radians => angle.num * 180.0 / std::f64::consts::PI,
>    |                                                                   ^^^
> 
> error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
>    --> usvg/src/tree/mod.rs:251:23
>     |
> 251 |     let mut decoder = libflate::gzip::Decoder::new(inner).map_err(|_| Error::MalformedGZip)?;
>     |                       ^^^^^^^^
> 
> error: aborting due to 2 previous errors
> 
> For more information about this error, try `rustc --explain E0658`.
> error: Could not compile `usvg`.

**Comment by RazrFalcon** [comment]
- resvg version?
- Rust version?

**Comment by stevensonmt** [comment]
Rust version 1.29.2
resvg is brought in by the AUR package resvg-git using version 0.4.0.r14.gc48545f according to the pkgbuild.

**Comment by stevensonmt** [comment]
Thanks for the prompt response.
